<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Node.js 0.10がリリース</h3><p><a target="_blank" href="http://www.infoq.com/news/2013/03/node.js-0.10-released;jsessionid=DCA39AC587F77DCE3D7BA4546A18909C"><em>原文(投稿日：2013/03/13)へのリンク</em></a></p> 
<div class="clearer-space">
 &nbsp;
</div> 
<div id="newsContent"> 
 <p>Node.js開発チームは、<a target="_blank" href="http://blog.nodejs.org/2013/03/11/node-v0-10-0-stable/">node.jsのバージョン0.10をリリースした</a>が、これは高パフォーマンスな非同期サーバーを構築するためのJavaScriptベースのプラットフォームである。このリリースのフィーチャとして、ストリーム処理するためのモジュールがより使いやすくなったこと、ドメインのエラーハンドリングの改善、パフォーマンス改善がある。チームは、また0.10の後、1.0リリース前にもう１つ安定バージョンのリリース(0.12)があることを発表した。</p> 
 <p><a target="_blank" href="http://nodejs.org/api/stream.html">ストリーム</a>はnode.jsの中核部分であり、0.10で著しく変更された。ストリームは、あらゆる型の読み出し、あるいは書き込み可能なデータストリームに対する共通のインターフェースを提供し、ストリームの裏にあるのがファイル、走っているプロセス、あるいはソケットであっても抽象化する。バージョン0.10以前では、データパケットは、ストリームがオープンされた時、直ちに到着し始める<tt>data</tt>イベントとして放出された。共通の問題は、データパッケージがなくなることだった。なぜならプログラムが<tt>data</tt>イベントを聴き始めるチャンスを得る前に、それらが到着するからである。0.10には同じ動きをする後方互換性モードがあるので、推奨の方法は、<tt>readable</tt>イベントを聞き、到着したら明示的に<tt>.read()</tt>を呼んで、バッファされたデータを取得することである。その結果、データパケットを落とす可能性がずっと減る。</p> 
 <p>node.jsのバージョン0.8以前では、未処理の例外の既定動作は、サーバープロセス全体がクラッシュすることでした。この問題を回避し、未処理の例外の動作をもっと細かくコントロールするために、node.jsのバージョン0.8は<em>domains</em>（ドメイン）の実験的バージョンを導入した。ドメインは、クラッシュを限定化するメカニズムである。例えば、入ってくるHTTPリクエストのそれぞれに対してドメインを作ることが可能である。もしHTTPリクエストのドメインに付加したどのコードがクラッシュしても、そのドメインだけが死に、サーバープロセス全体がダウンすることはない。それによって、単一のHTTPリクエストにクラッシュを限定することになる。0.10では、ドメインのステータスは、「実験的」から「不安定」に格上げされ、様々なエッジケースを修正し、より良いデバッグ情報を提供する。</p> 
 <p>Node.jsコミュニティは、この数年間非常に大きくなり、企業からの関心も高まっている。呼応して、<a target="_blank" href="http://thenodefirm.com/">The Node Firm</a> や <a target="_blank" href="http://strongloop.com">StrongLoop</a>のような会社が有償のnode.jsサポート、トレーニング、コンサルティングの提供を始めた。StrongLoopは<a target="_blank" href="http://blog.strongloop.com/announcing-strongloop-node/">StrongLoop Nodeのベータ版</a>をリリースした。これは、Scalaコミュニティにおける<a target="_blank" href="http://typesafe.com">Typesafe</a> に似たモデルに従って、様々な人気のあるモジュールを含んだnode.jsの完全にサポートされたディストリビューションである。</p> 
 <p>公式なnode.js 0.10リリースのビルド済バイナリは、Windows, Mac, Linux、Solarisを含んだ、<a target="_blank" href="http://nodejs.org/download/">人気のあるOS全てに対してダウンロード出来る</a>。もちろん、node.jsはオープンソースプロジェクトなので、<a target="_blank" href="https://github.com/joyent/node/tree/v0.10.0">そのソースコードも入手可能</a>である。</p> 
 <p id="lastElm">&nbsp;</p> 
</div> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>