<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>コンテキスト境界を使って大きなドメインモデルを小さくする</h3><p><a target="_blank" href="http://www.infoq.com/news/2013/02/ddd-bounded-context-large-domain;jsessionid=D8AA061F46B5B1F45736599A185F7935"><em>原文(投稿日：2013/02/26)へのリンク</em></a></p> 
<div class="clearer-space">
 &nbsp;
</div> 
<div id="newsContent"> 
 <p>開発者は<a target="_blank" href="http://en.wikipedia.org/wiki/Domain-driven_design">ドメイン駆動設計</a>(DDD)のコンテキスト境界という概念を使って、巨大なモデルを複数の小さなモデルに分割できる。MSDN Magazineの<a target="_blank" href="http://thedatafarm.com/blog/">Julie Lerman氏</a>の記事によれば、このときに<a target="_blank" href="http://msdn.microsoft.com/en-us/data/aa937723">Entity Framework</a>のデータベースコンテキスト(DbContextクラス)が利用できる。</p> 
 <p>ひとつのコンテキスト内で多くのクラスから構成される単一のモデルを使うのではなく、複数のモデルに分割するのは役に立つ、と氏は言う。氏は2003年より<a target="_blank" href="http://mvp.microsoft.com/profiles/Lerman">Microsoft MVP</a>を受賞しており、.NETプラットフォームのコンサルタント、メンターとして活躍している。コンテキスト境界の概念を導入すれば、より小さくて凝集度の高いモデルが作成できる。氏の記事はこの考えに基づいているが、DDDのコンテキスト境界はDbContextクラスを使うことよりも広範囲の概念であることも指摘している。それゆえ、氏は自身の実装がDbContextに“はまっている”、や“特化している”と表現している。<br /> &nbsp;<br /> 顧客サポートのクラスを注文や発送のクラスと分離し、別々のDbContextクラスに置くことで、氏はアプリケーションのすべてのクラスを含む大きなコンテキストを小さくよりフォーカスが絞り込まれたコンテキストに分割する。基底にある大規模なデータモデルとデータベーステーブルは元のままだ。<br /> &nbsp;<br /> クラスにコンテキストに必要ない属性がある場合、元のクラスの一部分と一部のデータベーステーブルをカバーする小さくてより絞り込まれたクラスを作れる。これはデータベースのビューを使って実現できる。これらのクラスの制約は、クラスが制御していない、nullを許容しない列がある場合、インサートできないことだ。DbContextは例外を発生させる。<br /> &nbsp;<br /> テーブルの自動作成を使ったデータベースのセットアップ、“コードファースト”には、“上部モデル”とすべてのクラスを含むDbContextに追加の作業が必要だ。出来上がったコンテキストはデータベースを初期化するのに使う。<br /> &nbsp;<br /> <a target="_blank" href="http://domaindrivendesign.org/books/evans_2003">DDD</a>本の著者である<a target="_blank" href="http://www.infoq.com/author/Eric-Evans;jsessionid=D64F8B86FE019DC950853A676960DB4A;jsessionid=D8AA061F46B5B1F45736599A185F7935">Eric Evans氏</a>氏はこの記事に積極的に<a target="_blank" href="https://twitter.com/ericevans0/status/259096298198794240">ツイート</a>したが、このような方法でコンテキスト境界を適用することに<a target="_blank" href="http://stackoverflow.com/questions/13067650/bounded-dbcontexts-in-entity-framework-architecture">懸念</a>を示す人もおり、他の方法を提案している。DDDコミュニティの<a target="_blank" href="http://dddcommunity.org/uncategorized/bounded-context/">定義</a>から外れた使い方だという指摘がされた。</p> 
 <p>“明示的にコンテキストを定義しモデルに適用する。チームやアプリケーションの特定の部分の使い方、コードベースやデータベーススキーマなどの物理的な条件を考慮して明確に境界を設定する。モデルがこの境界内で厳密な一貫性を持つようにし、外部の問題で混乱しないようにする。”<br /> &nbsp;<br /> Entity FrameworkはMicrosoftの.NETプラットフォーム向けの<a target="_blank" href="http://en.wikipedia.org/wiki/Object-relational_mapping">オブジェクトリレーショナルマッパー</a>だ。</p> 
 <p id="lastElm">&nbsp;</p> 
</div> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>