<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Microsoftは、モバイルプッシュの一環としてクラウドIDサービスを提供する</h3><p><a target="_blank" href="http://www.infoq.com/news/2014/03/azure-ad-premium"><em>原文(投稿日：2014/03/31)へのリンク</em></a></p>
<div class="article_page_left news_container text_content_container"> 
 <div class="text_info"> 
  <p>Enterprise Mobility Suiteの立ち上げの一部として、MicrosoftはAzure Active Directory Premiumの一般提供を発表した。Microsoft Azure Active Directory Premiumは、無料のID管理と追加のグループ管理機能でシングル サインオン、ブランディングオプション、セキュリティ分析などを拡張する。</p> 
  <p>Microsoft Enterprise Mobility Suite (EMS)– 既存サービスに対抗する完全に新しい製品–は、先週のイベントで、新しいMicrosoft CEO Satya Nadella氏によって<a href="http://blogs.technet.com/b/microsoft_blog/archive/2014/03/27/a-cloud-for-everyone-on-every-device.aspx">紹介され</a>、Microsoft VP Brad Anderson氏によって、ブログに詳しい説明が投稿された。<a href="http://blogs.technet.com/b/in_the_cloud/archive/2014/03/27/enterprise-mobility-for-every-business-and-every-device.aspx?WT.mc_id=Blog_Intune_Launch_PCIT">Anderson氏は</a>EMSが対応している3つの主要な分野を示した: Microsoft Intuneによって配信されるモバイルデバイス管理、Microsoft Azure Active Directory Rights Management Servicesによるデータ保護、Microsoft Azure Active Directory (AD) PremiumによるID管理の提供。</p> 
  <p>現在、Microsoft Azure ADは、オンプレミスのディレクトリーとSaaSアプリケーションにシングルサインオンを提供するクラウドにホストされたユーザーリポジトリを提供している。対応するアプリケーションはカスタムで構築するか、Wordpress, Box, Salesforce.com, Marketo, そしてもちろんOffice 365が含まれる成長中のギャラリーから選択することができる。 4月からAzure AD Premiumは一般提供され、基本サービスに<a href="http://blogs.technet.com/b/ad/archive/2014/03/25/identity-and-access-management-for-every-user-in-every-organization-using-any-service-on-any-device.aspx">機能のホスト</a>を追加する。AD Premiumには、セルフサービスのパスワードリセット(後方でオンプレミスのディレクトリーと同期)、セルフサービスのグループ管理、ユーザーごとの多要素認証の設定、ブランディングのカスタマイズ、9つの新しいセキュリティレポートが追加されている。購入者は、Microsoft Enterprise Agreementを通じて、現在無料のプレビューが進行中のAD Premiumをアクティブ化することができる。</p> 
  <p>ForbesのBen Kepes氏は、この発表を<a href="http://www.forbes.com/sites/benkepes/2014/03/30/microsofts-enterprise-mobility-suite-covering-all-the-bases-flexibly/">見て</a>、Intune, Right Management, Azure AD Premiumの組み合わせ方法の完全なストーリーを説明した。</p> 
  <blockquote> 
   <p>これら3つのソリューションすべてを使うことで、組織はシングルサインオンをセットアップすることができるため、ユーザーはシームレスに使いたいアプリケーションすべてをシームレスに使うことができる。企業のITは従業員が使用する様々なデバイスを管理することができ、それらデバイスをまたいだデータアクセスをコントロールすることができる。大規模企業では、従業員にエンドユーザー向けアプリケーションを提供する企業の<a href="http://www.apple.com/iphone/from-the-app-store/">App Store</a>を構築することができる。そしてデーターは暗号化して安全にデバイス間で転送することができる。</p> 
  </blockquote> 
  <p>Kepes氏はMicrosoftのBrad Anderson氏と話すことで、(デバイスではなく)シングルユーザーの価格を提供し、世界で最も人気のあるID管理プラットフォームActive Directoryと密接に統合されているため、単一ベンダーのEMSは魅力的であることがわかった。Kepes氏は、組織はシンプルなセルフサービスを提供したく「使いやすさとコントロールのバランス」を望んでいるが、データ保護とガバナンスを必要としていると見ている。Anderson氏は、Microsoftが顧客に様々なシチュエーションで柔軟性を提供し、Azure AD Premiumのようなツールは、このようなソリューションを提供すると考えている。</p> 
 </div> 
</div><br><br><br><br><br><br></body></html>