<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Lean Startup: Atitudes para equipes sustentáveis</h3><p>Ramli John deu uma palestra sobre as <a href="http://ramlijohn.com/minimum-viable-attitudes-for-a-lean-startup-team/">atitudes m&iacute;nimas vi&aacute;veis para equipes lean startup</a> na confer&ecirc;ncia Lean Atartup em 2013. De acordo com Ramli existem tr&ecirc;s atitudes que ajudam equipes Lean se manterem sustent&aacute;veis ao longo do tempo: humildade, vontade de aprender e felicidade.</p>
<p>A InfoQ americana entrevistou Ramli sobre atitudes em lean startup, a import&acirc;ncia da felicidade e como lidar com o fracasso em lean startup.</p>
<p><strong>InfoQ.com: Em sua palestra sobre lean startup foi mencionado as</strong> <strong>m&iacute;nimas atitudes vi&aacute;veis</strong> <strong>que os membros das equipes de lean startup devem ter. Por que essas atitudes s&atilde;o t&atilde;o importante em lean startup (e talvez tamb&eacute;m na vida)?</strong></p>
<blockquote> 
 <p><strong>Ramli:</strong> O processo de Lean Startup n&atilde;o &eacute; f&aacute;cil. Eu acho que olhando de longe (os MVPs, as experi&ecirc;ncias e jarg&otilde;es) podemos dizer que isto &eacute; sexy. Mas ap&oacute;s executar v&aacute;rias experi&ecirc;ncias com pouco ou nenhum sucesso, possuir as atitudes certas pode ajudar as equipes a se levantarem e tentarem novamente. Sem as atitudes corretas, a maioria desistiria ap&oacute;s algumas experi&ecirc;ncias fracassadas.</p> 
</blockquote>
<p><strong>InfoQ.com: As tr&ecirc;s atitudes m&iacute;nimas vi&aacute;veis s&atilde;o humildade, vontade de aprender e felicidade. Por que escolheu estas tr&ecirc;s?</strong></p>
<blockquote> 
 <p><strong>Ramli:</strong> Um CEO de uma companhia compartilhou isso comigo como as 3 coisas que ele procura nos funcion&aacute;rios. E peguei emprestado dele :). Mas ent&atilde;o percebi que estas tr&ecirc;s atitudes n&atilde;o s&atilde;o apenas grandes para a contrata&ccedil;&atilde;o de novos funcion&aacute;rios, mas tamb&eacute;m para manter uma equipe altamente efetiva, orientada por hip&oacute;tese.</p> 
</blockquote>
<p><strong>InfoQ.com: Uma equipe de lean startup deve ser forte, apaixonada e estar atr&aacute;s das coisas que eles fazem, como mencionado. Como eles podem ao mesmo tempo ser humildes?</strong></p>
<blockquote> 
 <p><strong>Ramli:</strong> Humildade &eacute; admitir que est&aacute; errado quando se est&aacute; errado. Isto &eacute;, admitir que n&atilde;o sabe tudo e que precisa da ajuda de pessoas mais espertas. Isso n&atilde;o significa que n&atilde;o pode se gabar de vez em quando. Acho que esta &eacute; a chave. Cerque-se de pessoas mais espertas e definitivamente ser&aacute; humilde. E grandes empreendedores se cercam de pessoas melhores, mais inteligentes e mais efetivas do que eles.</p> 
</blockquote>
<p><strong>InfoQ.com: Foi mencionado que os membros da equipe devem ter apetite e ter um forte desejo de ir al&eacute;m e falar com seus clientes para descobrir o que eles realmente necessitam. &Eacute; poss&iacute;vel dar alguns exemplos de pessoas que tenham feito isto e explicar como isso os ajudou?</strong></p>
<blockquote> 
 <p><strong>Ramli:</strong> Comecei um novo projeto, o Extreme Lean TV (<a href="http://www.extremelean.tv/">http://www.extremelean.tv</a>), que mostra exemplos de empreendedores que est&atilde;o com vontade de aprender. Um exemplo &eacute; o Clay Hebert que <a href="http://www.extremelean.tv/save-100k-by-talking-to-customers/">economizou mais de US $ 100K em desenvolvimento conversando com seus clientes</a>. Outro &eacute; Jonathan Goldberg que passou da <a href="http://www.extremelean.tv/from-idea-to-money-in-14-days/">ideia para clientes pagantes em 14 dias</a>.</p> 
</blockquote>
<p><strong>InfoQ.com: Como uma lean startup, tamb&eacute;m &eacute; preciso ser capaz de lidar com falhas, por exemplo, quando suas ideias de produtos acabaram por dar errado. Como a felicidade pode lhe ajudar com isso?</strong></p>
<blockquote> 
 <p><strong>Ramli:</strong> Felicidade n&atilde;o significa ter um sorriso falso. Significa ter uma atitude positiva. Concordo que embora quando os produtos falham, &eacute; dif&iacute;cil manter o pensamento positivo. Acredito que um forte suporte pode vir quer seja da sua fam&iacute;lia, amigos pr&oacute;ximos ou mesmo da equipe. Acho que sua equipe precisa ser uma grande parte da sua rede de suporte. Se n&atilde;o estiver feliz, eles n&atilde;o estar&atilde;o. Cerque-se de pessoas positivas.</p> 
</blockquote>
<p><strong>InfoQ.com: Lean startups podem ser guiadas por 1 ou 2 pessoas ou pela equipe como mencionado em sua conversa. &Eacute; poss&iacute;vel nomear alguns dos benef&iacute;cios de ter uma equipe guiando isto?</strong></p>
<blockquote> 
 <p><strong>Ramli:</strong> Para mim uma equipe de ao menos dois &eacute; ideal para executar o processo de lean startup. O problema em fazer isso por si mesmo &eacute; que pode se estar bebendo seu pr&oacute;prio veneno. &Eacute; por isso a necessidade de encontrar pessoas que complementem suas habilidades e perspectivas. Escrevi em meu blog antes que as <a href="http://ramlijohn.com/why-startup-teams-need-to-fight/">equipes precisam ter debates saud&aacute;veis</a> ou correr o risco do perigo do pensamento em grupo.</p> 
</blockquote><br><br><br><br><br><br></body></html>