<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Akka e DDD: Combinando Programação Reativa e Domain-Driven Design</h3><p>Em sua recente palestra sobre DDD Reativo com <a href="http://www.scala-lang.org/">Scala</a> e <a href="http://akka.io/">Akka</a> (uma implementa&ccedil;&atilde;o de Modelo de Atores), <a href="http://vaughnvernon.co/">Vaughn Vernon</a>, autor do livro <a href="http://dddcommunity.org/book/implementing-domain-driven-design-by-vaughn-vernon/">Implementing Domain-Driven Design</a>, <a href="http://skillsmatter.com/podcast/design-architecture/reactive-ddd-with-scala-and-akka">explora</a> o uso de <a href="http://en.wikipedia.org/wiki/Actor_model">Modelo de Atores</a> combinado com <a href="http://en.wikipedia.org/wiki/Domain-driven_design">Desenvolvimento Guiado por Dom&iacute;nio</a>, DDD, na redu&ccedil;&atilde;o da sobrecarga arquitetural encontrada frequentemente em arquiteturas orientadas &agrave; eventos ou hexagonais.</p>
<p>O termo &quot;Reativo&quot; empregado ultimamente n&atilde;o se refere &agrave; um conceito totalmente novo devido a familiaridade com o tratamento de eventos ou mensagens, mesmo assim Vaughn define algumas caracter&iacute;sticas b&aacute;sicas do modelo de atores:</p>
<ul class="c11 lst-kix_pkdo9vb6ym7k-0 start"> 
 <li>Mensageria Ass&iacute;ncrona Direta: um ator transmite uma mensagem para outro ator diretamente e de forma ass&iacute;ncrona;</li> 
 <li>Concorr&ecirc;ncia Livre de Travas: os bloqueios n&atilde;o s&atilde;o manipulados pelos atores, somente pela infraestrutura;</li> 
 <li>Nenhum compartilhamento: os atores n&atilde;o devem saber sobre o estado interno de outros atores.</li> 
</ul>
<p>Uma das principais motiva&ccedil;&otilde;es de Vaughn em aplicar o DDD &eacute; modelar os aspectos centrais do neg&oacute;cio de maneira mais explicita. Por&eacute;m em uma arquitetura t&iacute;pica orientada &agrave; eventos, na qual o modelo de dom&iacute;nio &eacute; expl&iacute;cito e os eventos de dom&iacute;nio contribuem com alguma expressividade para o modelo, quando um evento &eacute; publicado, ainda pode ser dif&iacute;cil localizar no c&oacute;digo os lugares nos quais ocorrem rea&ccedil;&otilde;es decorrentes do evento, ocasionando impacto no modelo.</p>
<p>Em contraste, Vaughn acha o modelo de atores bastante expl&iacute;cito, ficando evidente no c&oacute;digo quando um ator envia uma mensagem &agrave; outro ator.</p>
<p>Uma pergunta para Vaughn &eacute;: quanto podemos nos beneficiar do uso do modelo de atores com DDD? Talvez seja somente uma quest&atilde;o de enviar as mensagens entre Aggregates usando a mesma arquitetura que antes? A resposta de Vaughn &eacute; n&atilde;o, porque &eacute; poss&iacute;vel se livrar da sobrecarga arquitetural encontrada frequentemente em arquiteturas orientada &agrave; eventos e hexagonais. Com o framework correto podemos reduzir a arquitetura &agrave; somente Controllers e Aggregates nos quais os Controllers podem ser atores que sabem como enviar mensagens a fim de interagir com Aggregates no modelo.</p>
<p>Vaughn n&atilde;o reconhece quaisquer limita&ccedil;&otilde;es reais para o uso do modelo de atores e DDD, em vez disso ambos podem ser aplicados quando houver necessidade de alta escalabilidade, alto desempenho e baixa lat&ecirc;ncia.</p>
<p>O Akka &eacute; constru&iacute;do para a M&aacute;quina Virtual Java, JVM, por&eacute;m Vaughn est&aacute; trabalhando em uma implementa&ccedil;&atilde;o Akka.NET, um esfor&ccedil;o a fim de portar o Akka para C# e F#.</p>
<p>No in&iacute;cio deste ano, Vaughn <a href="http://www.infoq.com/news/2013/06/actor-model-ddd">falou sobre</a> a base do modelo de atores com DDD.</p>
<p>O <a href="http://www.reactivemanifesto.org/">Manifesto Reativo</a> foi publicado em Setembro de 2013 e descreve as ideias principais por tr&aacute;s do conceito.</p><br><br><br><br><br><br></body></html>