<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Pebble opens up the first appstore for wearable devices</h3><p>Pebble, maker of the <a href="http://techland.time.com/2012/05/10/pebble-smartwatch-pre-orders-sold-out/">successful</a> Pebble and Pebble Steel smartwatches, opened up its appstore earlier this month. Pebble appstore aims at offering both customers and developers a centralised app distribution channel, thus becoming &quot;the first place where Pebble users look for Pebble apps.&quot;</p>
<p>Pebble proudly announced its appstore as the first such endeavour &quot;in the history of wearable computing,&quot; allowing users to directly browse and download third party apps. For developers, Pebble appstore promises to be <a href="https://developer.getpebble.com/blog/2013/12/18/All-Aboard-the-Pebble-app-store/">&quot;the best way to promote and distribute Pebble applications to users.&quot;</a></p>
<p>Previous to Pebble appstore, users had to rely on apps recommended by Pebble or on websites like <a href="http://www.mypebblefaces.com/">My Pebble Faces</a>. Third party services and stores will continue to be legitimate means for app discovery and installation, said Pebble.</p>
<p>Pebble smartwatch is meant to work alongside a smartphone, not to replace it, and among the commonest use cases for watchapps <a href="https://developer.getpebble.com/2/guides/app-phone-communication.html">Pebble lists</a>:</p>
<ul> 
 <li>A watchapp that is a mini-dashboard of a phone app;</li> 
 <li>A phone app that fetches data from the web, and displays that data on a watchapp;</li> 
 <li>A watchapp that serves as a remote control for a phone app, utilizing Pebble’s buttons to trigger actions on the phone.</li> 
</ul>
<p>In the new Pebble appstore, apps are divided in six categories: Daily, Tools &amp; Utilities, Notifications, Remotes, Fitness, and Games. The appstore also includes watchfaces and companion apps for iOS and Android designed to work with Pebble.</p>
<p>Pebble offers developers a C-based SDK to develop watchapps, and <a href="https://developer.getpebble.com/2/ios-reference/index.html">Objective-C</a> and <a href="https://developer.getpebble.com/2/android-reference/index.html">Java</a> frameworks, known as PebbleKit, to integrate a native iOS/Android app with a Pebble watch. Furthermore, a <a href="https://developer.getpebble.com/2/guides/javascript-guide.html">PebbleKit JavaScript Framework</a> is also available to allow developers to integrate their watchapps with an iOS or Android device without requiring native programming. Due to iOS Developers Agreement forbidding download of any executable code in a iOS app, though, all JavaScript watchapps are packed within the <a href="https://itunes.apple.com/app/pebble-smartwatch/id592012721">iOS Pebble app</a>. This implies that new JavaScript watchapps cannot be made immediately available, since their release is only possible through a new release of the iOS Pebble app.</p>
<p>Submission to Pebble appstore is open to everyone and is free, subject only to abiding Pebble <a href="https://dev-portal.getpebble.com/terms_of_use">Terms of Use</a> and <a href="https://dev-portal.getpebble.com/developer/agreement">Developer Agreement</a>.</p>
<p>According to Pebble, <a href="http://developer.getpebble.com/2/distribute/publish-to-pebble-appstore.html">apps will not be reviewed or approved individually</a>, although Pebble reserve the right to remove apps that do not comply with their terms and conditions. Pebble appstore does not support paid apps at the moment and any monetization options for developers are dependent on releasing an iOS or Android companion app.</p>
<p>Pebble appstore is <a href="https://developer.getpebble.com/blog/2014/02/03/Pebble-appstore-is-live/">integrated within the main Pebble app for iOS</a> and should be soon available also on <a href="https://developer.getpebble.com/blog/2014/02/03/Android-appstore-beta/">Android, being currently in beta</a>.</p>
<p>Pebble met a huge success in its <a href="https://www.kickstarter.com/projects/597507018/pebble-e-paper-watch-for-iphone-and-android/">crowdfunding campaign on Kickstarter</a> raising more than $10 million although they <a href="http://en.wikipedia.org/wiki/Pebble_(watch)">only sought $100,000 originally</a>. <a href="http://techland.time.com/2012/04/18/how-pebble-became-a-smartwatch-phenomenon-overnight/">According to Time</a>, Pebble success is due to a combination of factors like low price, iPhone support, and smart timing.</p>
<p>At launch, Pebble appstore featured about 1,000 apps and watch faces, but <a href="http://www.theverge.com/2014/2/3/5373910/pebble-app-store-now-available-ios">Chris Welch on The Verge</a> pointed out that &quot;convenience is more important than any one number; by introducing the app store, Pebble is giving its customers a central destination to find and try out new software.&quot;</p>
<p>According to <a href="http://www.wired.com/gadgetlab/2014/02/best-new-apps-pebble/">Christina Bonnington, writing for The Verge</a>, the long-awaited Pebble App Store offers &quot;a thriving ecosystem of third party developers and a single consolidated marketplace behind it&quot; and will allow to &quot;see what a smartwatch can really do&quot;.</p><br><br><br><br><br><br></body></html>