<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Two More DevOps Tool Vendors Acquired</h3><p>The excitement over DevOps is continuing to increase in major corporations. Today it was announced that two DevOps tool vendors were acquired. UrbanCode was picked up by IBM while Nolio went to CA Technologies.</p> 
<p><b>UrbanCode</b></p> 
<p><a href="http://www.urbancode.com/html/products/devops/default.html">UrbanCode</a> was originally known for Anthill, its continuous integration server. But these days they are more focused on their uXxx products.</p> 
<p>The continuous integration server uDeploy builds upon their work with Anthill Pro. It boasts an support for “enterprise-wide continuous integration” with a heavy emphasis on automated testing and dependency management. It uses template configuration which is supposed to make it easier to ensure that new projects adhere to the standards used elsewhere in the company.</p> 
<p>uBuild supports a wide variety of source control systems, build tools, testing frameworks, and issue trackers. The <a href="http://www.urbancode.com/html/products/build/integrations/">full list</a> is available on their website.</p> 
<p>The companion to uBuild is <a href="http://www.urbancode.com/html/products/release/">uRelease</a>. This tool is essentially an issue tracker or dashboard for the release process. It tracks environments, what’s installed in them, and the release plans. The last bit is essential, as uRelease can be used both to reduce the chance that steps are not skipped and to provide visible to other teams as the rollout progresses.</p> 
<p><a href="http://www.urbancode.com/html/products/terraform/">Terraform</a> is an open source provisioning tool that supports Amazon EC2 and VMWare vSphere. And overlapping product, <a href="http://www.urbancode.com/html/products/provision/">uProvision</a>, is in development and is intended to support a wider range of server provisioning activities.</p> 
<p><b>Nolio</b></p> 
<p>Nolio claims to be a “Zero Touch Deployment Company”. There newest product is called <a href="http://www.noliosoft.com/product">Application Release Operations Suite</a>. This uses a visual designer plan releases. On the execution side, Nolio is able to <a href="http://www.noliosoft.com/product/features">track the progress of deployments and enforce rules</a> such as,</p> 
<blockquote> 
 <p>Only start with the application server upgrade once both a backup has been completed successfully and the databases have been successfully upgraded</p> 
 <p>Remove a third of the application servers from the load balancer, stop the applications on the offline servers, upgrade the DB instances connected to those servers, upgrade the application servers, reconnect the upgraded application servers - loop for two more times on the remaining.</p> 
</blockquote> 
<p>Releases can be tagged in order to make rollbacks easier when an update is found to be faulty.</p> 
<p>On the security and compliance side, deployments can be configured that that certain steps require management approval. This is especially important for <a href="http://www.soxlaw.com/">SOX compliance</a> where an audit trail of who authorized production changes is essential.</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>