<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>EclipseがJCPに参加</h3><p><a target="_blank" href="http://www.infoq.com/news/2013/11/eclipse-joins-jcp"><em>原文(投稿日：2013/11/07)へのリンク</em></a></p>
<div class="article_page_left news_container text_content_container"> 
 <div class="text_info"> 
  <p>JCP(Java Community Process) EC(Executive Committee / 執行委員会)に新たに選出されたメンバが来週就任し，Javaプログラム言語の方向性に対して影響力を行使し始める。その中のひとつである<a href="http://www.eclipse.org" target="_blank">Eclipse財団</a>は，今後２年間にわたってこの決議機関に席を持つことになる。</p> 
  <p>Eclipse財団の同委員会への参加には，全体の14%の支持率に当たる221の同意票が投じられた。これは公開選挙された議席候補の中では最高の得票数だ。今回の投票では，もっとも得票の多い8候補がECに選出される。得票上位４候補の任期は２年，それ以外は１年だ。Eclipse財団に2年の任期が与えられたことは，フリーのオープンソースJava IDEで知られる同組織が，今後数年間にわたるJSRへの投票権と，Javaプログラム言語の仕様承認権を手に入れたことを意味している。</p> 
  <p>再任された候補の中には，Eclipse財団に次ぐ13%の支持を得た<a href="http://twitter.com" target="_blank">Twitter</a>と，同じく2011年に選任されていた<a href="http://www.azulsystems.com/" target="_blank">Azul Systems</a>が含まれている。Azul Systemsと同社CTOのGil Tiene氏は，今年サンフランシスコで開催された<a href="http://www.infoq.com/news/2013/10/azul-jcp-member-of-the-year">Java OneカンファレンスでJCP Member of the Yearにも選ばれている</a>。同賞はその年において，Javaコミュニティにもっとも大きな影響を与えた人物あるいは企業を認定するものだ。Azul Systemsは投票の10%に当たる166票を獲得し，１年間の任期でECメンバの座に着くことになる。</p> 
  <p>JCPは今年，承認議席3と選出議席2を廃止して，ECメンバの合計数を25に削減した。その内の１議席はOracleが確保し，残る議席を，委員会メンバによる投票プロセスを通じて選ぶように定められている。1,088の投票権所有者中，今回投票を行ったのは24.77%に過ぎなかったが，2012年に確認された投票率は23.70%であったので，それに比較すれば向上している。</p> 
  <p>昨年の投票後に<a href="http://www.infoq.com/jp/news/2012/11/jcpec2012">InfoQが伝えた</a>ように，今年はJCP改革の節目となる年でもあった。2012年の選挙以前，JCPは２つの業務執行委員会で構成されていた。JavaのStandardおよびEnterprise(SE/EE)エディションを扱う委員会と，Micro Edition(ME)を担当する委員会だ。いずれの委員会も，承認10議席と選出5議席，合わせて15議席から構成されていた。投票されるメンバはいずれも３年間の任期を持ち，承認/選出数が毎年5名になるように期間をずらして設定されていた。今年は選出議席の任期が変更されて，上位当選者の任期を2年，下位を1年のみとするようになっている。</p> 
  <p>選挙結果に関する全報告が <a href="http://www.jcp.org/en/whatsnew/elections">JCPのWebサイトに紹介</a>されている。JCPとECに関しては<a href="http://www.jcp.org/en/procedures/jcp2_9">JCP 2.0 Process Document</a>として，同じく上記のWebサイトで確認できる。</p> 
 </div> 
</div><br><br><br><br><br><br></body></html>