<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>GoogleがMotorolaをLenovoに売却</h3><p><a target="_blank" href="http://www.infoq.com/jp/news/2014/02/presto-aws-qubole"><em>原文(投稿日：2014/01/30)へのリンク</em></a></p>
<div class="article_page_left news_container text_content_container"> 
 <div class="text_info"> 
  <p>GoogleはMotorola Mobilityを29.1億ドルでLenovoに売却する。Lenovoが2,000件の特許を獲得する一方で，同社ポートフォリオの特許の大部分はGoogleが保持する。Googleにとってこの取引は損失かも知れないが，Androidエコシステムにはメリットがある。</p> 
  <p><a href="http://www.infoq.com/jp/news/2011/08/Whats-Next-for-Android">2011年にMotorola Mobilityを125億ドルで買収した</a>時に指摘されたのが，Googleが強い関心を持っているのは買収を通じて取得する17,000件の特許と，同じく承認待ちの7,500件の特許である，ということだ。その時点で，GoogleがAndroid開発とハードウェア製造を兼ねるようになることから，<a href="http://gigaom.com/2011/08/15/will-hardware-makers-trust-google-after-motorola-buy/">この動きをAndroidエコシステムへの脅威とする意見が一部にはあった</a>。Googleはすべてのパートナを同じように扱うことを宣言した。<a href="http://googleblog.blogspot.ro/2011/08/supercharging-android-google-to-acquire.html">Motorolaはライセンス取得者のひとつに過ぎないのだ</a>と，CEOのLarry Page氏は説明している。</p> 
  <p>それから2年半後，Androidエコシステムは大きく成長した。IDCの調査によれば，2013年第3四半期に世界中で出荷された<a href="http://www.idc.com/getdoc.jsp?containerId=prUS24442013">スマートフォンの81%に，Googleのオペレーティングシステムが搭載されている</a>という。Googleはすべてのハードウェア製造者をフェアに扱っているようだ。そして同社には今，そうしなければならない理由がさらにある。29.1億ドルで<a href="http://googleblog.blogspot.com/2014/01/lenovo-to-acquire-motorola-mobility.html">Motorola MobilityをLenovoに売却すると昨日，発表したからだ</a>。特許の大部分はGoogleに残り，Lenovoが獲得するのは2,000件に過ぎない。さらに，<a href="http://www.theverge.com/2014/1/29/5359068/google-keeping-motorola-advanced-technology-group-project-ara-phone">Advanced Technology and Projectsグループとその特許は，今回の取引には含まれず</a>，Androidチームへの統合が予定されている。</p> 
  <p>一部のアナリストは，セットトップボックス部門を23.5億ドルで売却済であることを考慮しても，Googleは &quot;<a href="http://arstechnica.com/gadgets/2014/01/reports-google-will-sell-motorola-mobility-to-lenovo-for-3-billion/">70億ドルの損害</a>&quot;を被ることになる，と指摘する。その一方で，<a href="http://mobile.nytimes.com/blogs/dealbook/2014/01/29/did-google-really-lose-on-its-original-motorola-deal/">Googleはよい取引をした</a>と考える意見もある。当初の損失を32億ドルと想定し，<a href="http://www.sec.gov/Archives/edgar/data/1288776/000119312512440217/d400524d10q.htm">2012年時点で特許を55億ドルと評価していた</a>のだから，計算上の損失はないというのだ。ただしこれが成り立つのは，特許にGoogleが当初考えていた程度の価値がある場合に限られる。そして，特許訴訟のプロセスは今のところ，Motorolaに十分なキャッシュをもたらしてはいないのだ。現時点でMicrosoftに支払い義務があるのは，&quot;Motorolaが当初要求していた40億ドルではなく，同社の販売されるXbox 360とWindows 7 PCすべてにおいて，Motorolaの標準関連Wi-Fiとビデオエンコーディング特許を使用するための，<a href="http://www.theverge.com/2013/4/26/4271432/does-anyone-know-why-google-bought-motorola">年間ロイヤリティとしての17億ドル&quot;のみである</a>。それでもPage氏は，&quot;Androidエコシステム全体を守る&quot;ために特許を使用し続ける，と約束している。どの程度の成功を収められるかは，今後を見なければならない。</p> 
  <p>Androidエコシステムはおそらく，この取引から恩恵を受けられるだろうし，2013年第3四半期のAndroid出荷全体の<a href="http://www.idc.com/getdoc.jsp?containerId=prUS24442013">39.9%を占めるSamsung</a>との競争の中で，Lenovoの立場を強固なものにするだろう。ひとつのメーカが市場を独占するというのは，技術革新のペースが遅くなり，価格が上昇する可能性があるという意味で，望ましいことではない。Lenovoは現在，PC市場のリーダであり，最近では23億ドルで<a href="http://www.forbes.com/sites/maggiemcgrath/2014/01/23/lenovo-buying-ibm-server-business-for-2-3-billion/">IBMのサーバビジネス</a>を買収している。</p> 
 </div> 
</div><br><br><br><br><br><br></body></html>