<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>A flexibilidade do Agile: ponto forte ou calcanhar de Aquiles?</h3><p>O princ&iacute;pio de &quot;responder a mudan&ccedil;as mais do que seguir um plano&quot; em geral &eacute; visto como um ponto forte do Agile, mas alguns consideram essa flexibilidade invi&aacute;vel na pr&aacute;tica, por terem visto alguns projetos &aacute;geis com dificuldades para gerenciar mudan&ccedil;as com clientes que esperam flexibilidade muito al&eacute;m do normal. Os efeitos s&atilde;o atrasos no projeto, problemas com qualidade e equipes com dificuldades para entregar valor. Ser&aacute; que o Agile n&atilde;o est&aacute; a altura de suas promessas ou ser&aacute; que &eacute; a forma como as equipes e organiza&ccedil;&otilde;es t&ecirc;m adotado o Agile que est&aacute; causando os problemas?</p>
<p>No artigo &quot;<a href="http://www.cio.com/article/734338/Why_Agile_Isn_t_Working_Bringing_Common_Sense_to_Agile_Principles">Por que o Agile n&atilde;o est&aacute; funcionando</a>&quot;, publicado na CIO.com, <a href="http://www.theconsultantcto.com/about">Lajos Moczar</a> apresenta raz&otilde;es pelas quais acredita que a metodologia &aacute;gil &eacute; falha:</p>
<blockquote> 
 <p>As promessas do Agile s&atilde;o muitas, mas na pr&aacute;tica a realidade &eacute; outra - muito distante das expectativas. Parece que o Agile falhou como outros modismos antes dele, e que tem tornado as coisas ainda piores no mercado de TI.</p> 
</blockquote>
<p>Uma das falhas apontadas &eacute; a prioridade do desenvolvimento sobre o planejamento:</p>
<blockquote> 
 <p>Na teoria, os desenvolvedores codificam ao mesmo tempo em que colaboram com as partes interessadas, para definir, refinar e mudar os requisitos durante o andamento do projeto. Mas o Agile n&atilde;o diferencia as mudan&ccedil;as pequenas das grandes; cada mudan&ccedil;a tem seu custo, e o Agile n&atilde;o leva isso em conta. O resultado &eacute; que frequentemente s&atilde;o feitas mudan&ccedil;as grandes no final do projeto. (afinal trata-se de um projeto &aacute;gil que pode lidar bem com isso).</p> 
 <p>A &uacute;nica forma que um projeto pode lidar com essa situa&ccedil;&atilde;o, por&eacute;m, &eacute; adicionando itera&ccedil;&otilde;es. Conforme isso acontece, os defeitos que antes seriam f&aacute;ceis de resolver tornam-se cada vez mais dif&iacute;ceis de tratar, uma vez que a base de c&oacute;digo n&atilde;o para de ser alterada.</p> 
</blockquote>
<blockquote> 
 <p>Trata-se de uma abordagem bastante diferente das pr&aacute;ticas tradicionais - em que o projeto &eacute; constru&iacute;do sobre requisitos bem definidos, e as mudan&ccedil;as s&atilde;o tratadas por meio do processo de Gest&atilde;o de Mudan&ccedil;as. Apesar dos problemas, essa estrat&eacute;gia pelo menos leva em conta o tempo e os custos financeiros mais claramente.</p> 
</blockquote>
<p><a href="https://twitter.com/shanehastie">Shane Hastie</a> apresentou sua rea&ccedil;&atilde;o ao referido artigo em seu post &quot;<a href="http://blog.softed.com/2013/06/14/please-don%E2%80%99t-equate-tragile-with-agile/">Por favor, n&atilde;o confunda Agilidade com Fragilidade</a>&quot;, iniciando dessa maneira:</p>
<blockquote> 
 <p>O autor interpreta de forma completamente equivocada o manifesto &aacute;gil e trata algumas pr&aacute;ticas inteiramente fora de contexto, utilizando declara&ccedil;&otilde;es sem fundamento para justificar suas conclus&otilde;es.</p> 
</blockquote>
<p>O primeiro ponto abordado &eacute; sobre a falha mencionada por Moczar a respeito da prioridade do desenvolvimento sobre o planejamento. Hastie explica o problema de fazer a defini&ccedil;&atilde;o antecipada dos requisitos e as dificuldades encontradas com a gest&atilde;o de mudan&ccedil;as:</p>
<blockquote> 
 <p>A realidade &eacute; que as necessidade do neg&oacute;cio s&atilde;o vol&aacute;teis. A expectativa de vida de uma demanda de neg&oacute;cio hoje &eacute; de aproximadamente seis meses, de forma que se a entrega acontecer s&oacute; um ano mais tarde, o simples passar do tempo tornar&aacute; 75% do que foi pedido simplesmente errado.</p> 
</blockquote>
<p>Hastie explica que o Agile trata as necessidades dos clientes de forma disciplinada e cuidadosa, e que ele de nenhuma forma se op&otilde;e ao planejamento:</p>
<blockquote> 
 <p>O Agile n&atilde;o &eacute; desculpa para ignorar boas pr&aacute;ticas de design, nem para permitir mudan&ccedil;as enormes sem an&aacute;lise de impacto. O Agile prop&otilde;e a adapta&ccedil;&atilde;o dentro de alguns limites e reconhece que, quando uma mudan&ccedil;a &eacute; grande o suficiente a ponto de impactar o valor do projeto, ela precisa ser avaliada, mas n&atilde;o resistida.</p> 
 <p>N&atilde;o h&aacute; nada no Manifesto &Aacute;gil sobre n&atilde;o planejar a estrutura geral do produto desde o come&ccedil;o, e certamente nenhum dos autores &aacute;geis de respeito e l&iacute;deres na &aacute;rea recomendam come&ccedil;ar escrevendo c&oacute;digo &quot;como poesia de versos livres&quot;. Qualquer projeto precisa de algum design pr&eacute;vio, e nos projetos &aacute;geis o que se evita &eacute; o design antecipado de grande porte, pois sabemos que o mundo certamente mudar&aacute; ao nosso redor.</p> 
</blockquote>
<p><a href="https://twitter.com/estherschindler">Esther Schindler</a> escreveu em seu artigo &quot;<a href="http://www.itworld.com/software/359398/why-your-users-hate-agile-development-and-what-you-can-do-about-it">Por que seus usu&aacute;rios odeiam o desenvolvimento &aacute;gil (e o que fazer a respeito)</a>&quot;, no <a href="http://www.itworld.com/">ITworld</a>, sobre as diferentes vis&otilde;es que os desenvolvedores e usu&aacute;rios podem ter do Agile. Uma das diferen&ccedil;as apontadas &eacute; que os desenvolvedores entendem o Agile como um processo iterativo; os usu&aacute;rios como desorganizado e sem fim.</p>
<blockquote> 
 <p>Logo no come&ccedil;o da hist&oacute;ria do Agile [...] muitos grupos e empresas viram o Agile como desculpa para que as equipes de desenvolvimento deixassem de estimar, documentar e planejar. As coisas melhoraram muito desde aquela &eacute;poca, mas a m&aacute; impress&atilde;o ainda circula por a&iacute;, mesmo na pr&oacute;pria comunidade de desenvolvimento.</p> 
</blockquote>
<p>As equipes &aacute;geis procuram ser o mais flex&iacute;veis quanto poss&iacute;vel para atender &agrave;s necessidades dos usu&aacute;rios, mas os pr&oacute;prios usu&aacute;rios (Hastie defende) podem acabar tendo expectativas acima do normal sobre essa flexibilidade, tornando dif&iacute;cil para as equipes continuarem a entregar valor:</p>
<blockquote> 
 <p>&Agrave;s vezes a mentalidade de que &quot;o Agile significa desorganiza&ccedil;&atilde;o&quot; leva os usu&aacute;rios e os clientes a interpretar o Agile como um processo que admite que eles pr&oacute;prios sejam inconstantes. Os m&eacute;todos &aacute;geis permitem sim aos usu&aacute;rios alterarem as prioridades, mesmo que no final de um projeto grande.</p> 
 <p>O desenvolvedor <a href="http://www.linkedin.com/in/scostea">Sorin Costea</a>, contudo, observa um problema quando as coisas funcionam bem: &quot;Os usu&aacute;rios n&atilde;o conseguem acreditar que existem limites no poder de entrega. N&atilde;o conseguem entender ideias como Velocidade ou Timeboxes, mas t&ecirc;m expectativa de pedir hist&oacute;rias de usu&aacute;rio a qualquer momento e t&ecirc;-las entregues no prazo&quot;. O argumento seria &quot;afinal, somos &aacute;geis, certo?&quot;</p> 
</blockquote>
<p><a href="http://www.linkedin.com/in/corbinnorman">Corbin Norman</a> postou em seu blog <a href="http://thegeniusway.me/2013/06/10/acknowledging-the-common-good-of-agile-praising-the-good-of-agile-and-abrogating-the-minuscule-negativity-it-brings/">reconhecendo</a> o bem geral trazido pelo Agile: Louvando seu lado positivo e afastando seu &quot;min&uacute;sculo&quot; lado negativo. Norman fala tamb&eacute;m de como as pessoas &agrave;s vezes t&ecirc;m uma vis&atilde;o negativa do Agile:</p>
<blockquote> 
 <p>Os cr&iacute;ticos do Agile argumentam que essa metodologia de desenvolvimento est&aacute; tornando as coisas piores para quem trabalha com software, pois traria promessas que n&atilde;o pode cumprir, induzindo ao h&aacute;bito de promover um levantamento mal acabado de requisitos, de esconder os custos reais do desenvolvimento e dificultar a gest&atilde;o efetiva. O argumento defendido &eacute; que a suposta dificuldade na gest&atilde;o levaria a projetos mais longos, insatisfa&ccedil;&atilde;o dos clientes e inefici&ecirc;ncia geral da TI.</p> 
 <p>Atualmente, existem alguns argumentos v&aacute;lidos tanto em prol quanto contra a pr&aacute;tica do desenvolvimento &aacute;gil, mas a comunidade deveria levar em conta o benef&iacute;cio que o Agile traz em rela&ccedil;&atilde;o ao pequeno preju&iacute;zo causado.</p> 
</blockquote>
<p>De acordo com Norman, uma das vantagens do Agile &eacute; sua flexibilidade:</p>
<blockquote> 
 <p>Com o Agile, o cronograma e os custos s&atilde;o fatores mais determinantes e &eacute; o escopo que muda para acomodar demandas de neg&oacute;cio aceit&aacute;veis, ou seja, as necessidades do cliente. Para equipes &aacute;geis maduras, esse n&iacute;vel de flexibilidade &eacute; adquirido por meio de anos de experi&ecirc;ncia trabalhando em conjunto.</p> 
 <p>O m&eacute;todo cascata tradicional n&atilde;o permite esse n&iacute;vel de flexibilidade ap&oacute;s o in&iacute;cio do projeto, pois adota estritamente a ideia de que um est&aacute;gio deve ser conclu&iacute;do antes de o pr&oacute;ximo come&ccedil;ar e que n&atilde;o se pode voltar para fazer ajustes.</p> 
</blockquote><br><br><br><br><br><br></body></html>