<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Lançamento do Java 8: Perguntas e Respostas</h3><p>O Java 8 &eacute; uma das atualiza&ccedil;&otilde;es de linguagem de programa&ccedil;&atilde;o mais esperadas em muitos anos. O lan&ccedil;amento cont&eacute;m a API de datas, API de stream e as lambdas. Inclui a remo&ccedil;&atilde;o do <em>permgen</em> e termina com um bom conjunto de melhorias. Para aprender mais sobre este lan&ccedil;amento, sentamos com <a href="https://www.linkedin.com/in/georgessaab">Georges Saab</a>, vice-presidente de desenvolvimento de software da Java Platform Group na Oracle.</p>
<p><strong>InfoQ: Para todos que n&atilde;o t&ecirc;m seguido o projeto lambda de perto, voc&ecirc; poderia nos dar uma ideia do que foi envolvido nesta implementa&ccedil;&atilde;o? Acredito que esta &eacute; a primeira vez que tanto a linguagem, a VM e as bibliotecas evolu&iacute;ram juntas de uma maneira coordenada.</strong></p>
<blockquote> 
 <p>A maioria das grandes funcionalidades em lan&ccedil;amentos anteriores foi feita de maneira que somente uma dessas tr&ecirc;s &aacute;reas foi afetada, ou alternativamente as mudan&ccedil;as em cada &aacute;rea foram introduzidas ao longo de uma s&eacute;rie de grandes lan&ccedil;amentos.</p> 
 <p>Com o Lambda no Java 8, fizemos um conjunto coordenado de mudan&ccedil;as envolvendo a linguagem, as bibliotecas e a JVM, no qual ao longo do desenvolvimento, cada &aacute;rea foi capaz de influenciar e fortalecer o design e implementa&ccedil;&atilde;o das demais.</p> 
 <p>Por exemplo, experimentamos com diversas implementa&ccedil;&otilde;es alternativas do Lambda na VM e descobrimos que poder&iacute;amos utilizar o InvokeDynamic. Ao faz&ecirc;-lo, encontramos pontos que poderiam ser melhorados no pr&oacute;prio InvokeDynamic. O desejo de se utilizar Lambdas de uma forma natural com as Collections nos levou ao design da Streams API, e ent&atilde;o aos m&eacute;todos de extens&atilde;o, os quais exigiam suporte da linguagem.</p> 
 <p>Este tem sido um processo evolutivo ao longo de v&aacute;rios anos com bastante feedback da comunidade ao longo do caminho.</p> 
</blockquote>
<p><strong>InfoQ: Voc&ecirc; acredita que a adi&ccedil;&atilde;o de lambdas ir&aacute; trazer de volta ao Java os desenvolvedores Groovy e Scala?</strong></p>
<blockquote> 
 <p>O interessante &eacute; que as duas linguagens mencionadas (bem como uma s&eacute;rie de outras) executam na JVM. Realmente trabalhamos bastante para suportar outras linguagens al&eacute;m do Java na JVM, e acho que h&aacute; muito para os implementadores de linguagens aprenderem com as experi&ecirc;ncias do que funciona bem e o que nem tanto. Claro que &eacute; muito mais f&aacute;cil experimentar com uma linguagem com poucos milhares de desenvolvedores que com muitos milh&otilde;es. Nosso enfoque tem realmente sido em abordar as coisas que v&atilde;o melhorar a vida dos milh&otilde;es de desenvolvedores Java por a&iacute;, evoluindo de uma forma consciente e respons&aacute;vel.</p> 
</blockquote>
<p><strong>InfoQ: A combina&ccedil;&atilde;o do Lambda e da Streams API nos ajuda a desenvolver c&oacute;digo limpo e conciso, mas algumas preocupa&ccedil;&otilde;es t&ecirc;m sido manifestadas em rela&ccedil;&atilde;o a uma sobrecarga potencial sobre o desempenho, como filtro ap&oacute;s filtro &eacute; aplicado para reduzir um conjunto de uma forma funcional. Isto &eacute; uma preocupa&ccedil;&atilde;o razo&aacute;vel? Quais otimiza&ccedil;&otilde;es foram introduzidas para mitigar essa sobrecarga?</strong></p>
<blockquote> 
 <p>As Streams permitem opera&ccedil;&otilde;es intermedi&aacute;rias e terminais. As opera&ccedil;&otilde;es intermedi&aacute;rias, tais como filtrar, n&atilde;o executam de fato nenhuma filtragem por si, ao inv&eacute;s disso criam um novo Stream, que quando percorrido, fornece os elementos que correspondem a um dado predicado. Assim, por um lado, a cria&ccedil;&atilde;o de filtros adicionais poderia resultar em um trabalho adicional a ser realizado em tempo de execu&ccedil;&atilde;o.</p> 
 <p>Por outro lado, o processamento de streams sob demanda, como todas as opera&ccedil;&otilde;es intermedi&aacute;rias de streams, permite ganhos de efici&ecirc;ncia importantes, como v&aacute;rias opera&ccedil;&otilde;es podem ser realizadas em uma &uacute;nica passagem sobre os dados. Em parceria com otimiza&ccedil;&otilde;es importantes da JVM nos bastidores que o design de lambdas habilita, o impacto de filtros adicionais pode ser significantemente reduzido.</p> 
 <p>Outro ponto a ser considerado &eacute; que a utiliza&ccedil;&atilde;o do paralelismo com Streams e Lambdas foi simplificado. Dessa forma, as opera&ccedil;&otilde;es de stream em paralelo podem se beneficiar da diminui&ccedil;&atilde;o das restri&ccedil;&otilde;es de ordena&ccedil;&atilde;o nas quais os usu&aacute;rios em particular n&atilde;o conhecem os conflitos de ordena&ccedil;&atilde;o do stream subjacente.</p> 
</blockquote>
<p><strong>InfoQ: Outra funcionalidade importante do Java 8 s&atilde;o as Annotations nos Java Types para permitir que verificadores de tipo plug&aacute;veis sejam desenvolvidos. Poderia nos falar um pouco mais sobre isso, como por exemplo, o que se espera ver os desenvolvedores fazerem com isso?</strong></p>
<blockquote> 
 <p>Essa funcionalidade permite o uso de anota&ccedil;&otilde;es nos nomes dos tipos na maioria dos lugares onde estes tipos podem ser usados. Como resultado dessa mudan&ccedil;a, os desenvolvedores podem agora escrever anota&ccedil;&otilde;es para detectar condi&ccedil;&otilde;es de erros em tempo de compila&ccedil;&atilde;o usando verificadores de tipos plug&aacute;veis. Tais verificadores e esquemas de anota&ccedil;&otilde;es est&atilde;o sendo desenvolvidos na comunidade para quest&otilde;es de erros de <em>null</em> <em>pointer</em>, <em>locking</em> e internationaliza&ccedil;&atilde;o.</p> 
 <p>Uma grande fonte de informa&ccedil;&atilde;o e implementa&ccedil;&atilde;o &eacute; o <em>Checker Framework</em> do Prof. Michael Ernst do <a href="http://checker-framework.org/">checker-framework.org</a>, que inclui um <em>checker</em> para n&atilde;o nulos, dentre mais de uma d&uacute;zia dessas ferramentas. Michael tamb&eacute;m atuou como l&iacute;der da co-spec na JSR 308, no qual esta funcionalidade da linguagem foi especificada.</p> 
 <p>Seria bom ver os resultados de pelo menos um desses esquemas de anota&ccedil;&otilde;es sendo aplicado sobre a base de c&oacute;digo da JDK no futuro, e claro, ver a comunidade mais ampla de desenvolvedores Java come&ccedil;ar a utilizar esta tecnologia em suas pr&oacute;prias bases de c&oacute;digo e desenvolver novos verificadores para outras quest&otilde;es de qualidade de software.</p> 
 <p>Especialmente no que diz respeito a sistemas embarcados e aqueles no qual o aspecto seguran&ccedil;a seja cr&iacute;tico, este tipo de inova&ccedil;&atilde;o pode permitir que propriedades cruciais e restri&ccedil;&otilde;es de tipos e seu uso ser qualificado e analisado ​​estatisticamente, como parte do processo de compila&ccedil;&atilde;o, fornecendo um caminho para usu&aacute;rios de outras linguagens de programa&ccedil;&atilde;o de dom&iacute;nio relevantes migrar para a plataforma Java no futuro.</p> 
</blockquote>
<p><strong>InfoQ: Quais s&atilde;o as maiores melhorias, em sua opini&atilde;o, para as linguagens din&acirc;micas no Java 8?</strong></p>
<blockquote> 
 <p>Em geral as melhorias de performance na HotSpot VM, e em particular o invokedynamic. Uma funcionalidade significativa nova no JDK 8 &eacute; o <em>Nashorn JavaScript Engine</em>, uma implementa&ccedil;&atilde;o leve de alta performance de uma linguagem din&acirc;mica popular. Melhorar o desempenho do Nashorn nos ajudou a encontrar novas oportunidades de otimiza&ccedil;&atilde;o na VM para implementa&ccedil;&otilde;es de linguagem din&acirc;mica.</p> 
 <p>Adicionalmente, o Nashorn agora fornece uma maneira muito conveniente para usar o Java a partir do JavaScript oferecendo acesso f&aacute;cil a classes Java, permitindo que aplica&ccedil;&otilde;es JavaFX inteiras possam ser escritas em JavaScript, executando na JVM. Esse tipo de interoperabilidade transparente entre linguagens din&acirc;micas executando na JVM e o Java oferece uma maneira poderosa de se escrever tais aplica&ccedil;&otilde;es.</p> 
</blockquote>
<p><strong>InfoQ: Preocupa&ccedil;&otilde;es relacionando o Java e seguran&ccedil;a raramente t&ecirc;m estado fora das manchetes do ano passado. O Java 8 cont&eacute;m alguma melhoria espec&iacute;fica, seja para o para o plug-in Java no navegador ou para quaisquer outros pontos?</strong></p>
<blockquote> 
 <p>Uma s&eacute;rie de melhorarias importantes de seguran&ccedil;a e novas funcionalidades foram entregues como parte das atualiza&ccedil;&otilde;es do Oracle Java SE 7, incluindo <a href="http://docs.oracle.com/javase/7/docs/technotes/guides/jweb/security/deployment_rules.html">Deployment Rule Sets</a>(funcionalidade para empresas que gerenciam o seu ambiente de desktop Java diretamente) e <a href="http://docs.oracle.com/javase/7/docs/technotes/guides/jweb/security/exception_site_list.html">Exception Site Lists</a>(Lista de sites de exce&ccedil;&atilde;o). Manter o valor da seguran&ccedil;a do Java &eacute; uma prioridade para n&oacute;s.</p> 
 <p>Al&eacute;m disso, o Java SE 8 cont&eacute;m v&aacute;rias funcionalidades novas de seguran&ccedil;a. Os mais percept&iacute;veis devem ser as melhorias na implementa&ccedil;&atilde;o do Transport Layer Security: TLS 1.2 &eacute; agora o padr&atilde;o da plataforma. Em termos globais de APIs de seguran&ccedil;a, existe uma s&eacute;rie de outras melhorias, desde melhorias na verifica&ccedil;&atilde;o de revoga&ccedil;&atilde;o de certificados at&eacute; novos algoritmos de criptografia.</p> 
</blockquote>
<p><strong>InfoQ: Voc&ecirc; sabe qual o percentual de desenvolvedores Java usando Java 5, 6 e 7? Existe algum plano para acelerar a ado&ccedil;&atilde;o do Java 8?</strong></p>
<blockquote> 
 <p>Ao longo dos &uacute;ltimos seis a nove meses, tenho falado em confer&ecirc;ncias ao redor do mundo e toda vez pergunto qual vers&atilde;o est&atilde;o usando. Apoiado sobre essa pesquisa informal e n&atilde;o cient&iacute;fica, diria que a maior parte dos desenvolvedores Java est&atilde;o usando o Java SE 7 hoje em dia, com uma (mas n&atilde;o insignificante) clara minoria ainda em 6, e um n&uacute;mero pequeno em vers&otilde;es mais antigas. Do ponto de vista do desenvolvedor, o Java SE 8 vem com muitas raz&otilde;es convincentes para a r&aacute;pida ado&ccedil;&atilde;o sob a forma de novos recursos da linguagem e das APIs. Com IDEs como NetBeans, Eclipse e IntelliJ IDEA trabalhando duro para oferecer ferramentas excelentes para esses recursos em seus pr&oacute;ximos lan&ccedil;amentos, eu esperaria ver os desenvolvedores adot&aacute;-lo rapidamente.</p> 
</blockquote>
<p><strong>InfoQ: Um dos grandes temas do JavaOne no &uacute;ltimo ano foi em torno da unifica&ccedil;&atilde;o do Java ME, SE e EE. At&eacute; que ponto o Java 8 caminhou nessa dire&ccedil;&atilde;o?</strong></p>
<blockquote> 
 <p>Uma das muitas novas funcionalidades no Java SE 8 &eacute; o suporte a <em>Compact Profiles</em>. Eles definem alguns subconjuntos de perfis da plataforma Java SE, permitindo que aplica&ccedil;&otilde;es que n&atilde;o requerem toda a plataforma serem publicadas e executadas em dispositivos menores. Juntamente com outras melhorias no HotSpot, como a redu&ccedil;&atilde;o do tamanho de metadados da classe, e o tamanho da VM em geral, este recurso permite que o JDK 8 possa ser escalado para o desenvolvimento de aplicativos e implanta&ccedil;&atilde;o em pequenos dispositivos. Para tornar isso mais f&aacute;cil, uma nova ferramenta chamada <strong>jdeps</strong> est&aacute; inclu&iacute;da no JDK 8 que permite aos desenvolvedores descubrirem de qual <em>Profile</em> seu c&oacute;digo depende.</p> 
 <p>Vindo de outra dire&ccedil;&atilde;o, o Java ME 8 est&aacute; sendo aprimorado para incluir uma linguagem mais pr&oacute;xima ao Java SE 8 com VM e alinhamento de bibliotecas. Enquanto ainda n&atilde;o &eacute; poss&iacute;vel utilizar as lambdas em c&oacute;digo Java ME 8, a plataforma agora suporta constru&ccedil;&otilde;es de linguagem Java introduzidas no Java SE 1.5, 6 e 7, como <em>assertions</em>, <em>generics</em>, <em>enumerations</em>, <em>strings</em> em <em>switches</em>, declara&ccedil;&otilde;es <em>try-with-resources</em> e o operador diamond. Da mesma forma, as classes das bibliotecas do n&uacute;cleo foram atualizadas com suporte para protocolos web modernos como IPv6 e funcionalidades avan&ccedil;adas de seguran&ccedil;a, incluindo o suporte para TLS 1.2, trazendo as plataformas Java SE e Java ME muito mais pr&oacute;ximas que no passado.</p> 
</blockquote>
<p><strong>InfoQ: Quando veremos</strong> <strong>Stripped Implementations</strong><strong> adicionadas ao Java?</strong></p>
<blockquote> 
 <p>Assim que o Java SE 8 for lan&ccedil;ado, precisaremos voltar a examinar como esta funcionalidade pode ser adicionada &agrave; plataforma em um lan&ccedil;amento anterior ao Java SE 9. N&atilde;o se trata de um problema t&eacute;cnico, mas de uma quest&atilde;o de garantir que o texto de especifica&ccedil;&atilde;o e o seu quadro jur&iacute;dico permitir&atilde;o casos de uso relevantes, evitando a fragmenta&ccedil;&atilde;o da plataforma Java.</p> 
</blockquote>
<p>Muito obrigado ao Georges por responder nossas quest&otilde;es. A Oracle <a href="http://eventreg.oracle.com/profile/web/index.cfm?PKWebId=0x637279c68&amp;source=InfoQ">apresentou formalmente o Java atrav&eacute;s de um Webinar</a>.</p><br><br><br><br><br><br></body></html>