<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>IntelliJ 13 Released</h3><p>JetBrains has announced the general release of <a href="http://www.jetbrains.com/idea/">IntelliJ IDEA version 13</a>. This release is in keeping with their traditional schedule of one major release per year, following version 12 which was released in December 2012. IntelliJ IDEA is the only one of the three popular IDE's (Eclipse, IntellJ, NetBeans) that offers a paid version.</p>
<p>Sporting a completely revamped user interface, the IDE has updated its support for many development technologies introduced this year including Java EE 7, Glassfish 4, Tomcat 8, and others. It has also refined much of the existing functionality, especially Spring support, Gradle integration, and Android development tools.&nbsp;It also provides full support for Java 8, the largest update to the Java platform since Java 5, scheduled for release in March 2014. A full<a href="http://www.jetbrains.com/idea/whatsnew/"> list of new features</a> can be found on the JetBrains website.</p>
<p>One important addition to the IDE is Android Studio, a new development environment built by Google on top of IntelliJ's free IDEA Community Edition in a non-commercial partnership.&nbsp;<br /> <br /> JetBrains has continued to work closely with Typesafe Inc, current stewards of Scala, to improve support for Scala. The new release features built-in integration for the SBT Scala build tool, and many other features.&nbsp;There is also a new dedicated Spring tool window.</p>
<p>Besides the technology support, there are also many new usability enhancements, including the Search Everywhere feature that provides a single dialog for locating anything from classes to IDE settings, a smart find features that augments the standard case-sensitive, whole-words only and regular-expressions searches, with &quot;Comments only&quot; and &quot;String literals only&quot; selections. There is also a new &quot;Presentation Mode&quot; that allows you to record, edit, and annotate a session for use as a presentation or talk.</p>
<p>InfoQ loaded-up the latest release of Ultimate Edition. Installation was fast, picking up the previous installation configuration, and the usage was as intuitive as ever. Support for Lambda expressions was apparent in several areas. First, refactorings for the new Collections API's are now offered as suggested refactorings. Additionally, even if you don't refactor to Lambdas, the code optionally folds to display the concise new Lambda syntax. One feature we'd like to see would be to suggest Lambda expressions as parameters.</p>
<p>Depending on what you're doing, you may be able to get by with the Community Edition. The <a href="http://www.jetbrains.com/idea/features/editions_comparison_matrix.html">comparison matrix</a> on the JetBrains website lists the features that are exclusive to the Ultimate Edition, including:</p>
<ul> 
 <li>UML Designer</li> 
 <li>Code Coverage tools</li> 
 <li>HTML, CSS, JavaScript, Struts</li> 
 <li>Spring Framework</li> 
 <li>JPA/Hibernate</li> 
 <li>Grails (Groovy is supported in Community Edition)</li> 
 <li>Application server support</li> 
 <li>Java EE 7 support</li> 
</ul>
<p>Community Edition is free. Ultimate Edition is listed at $199 for new individual users and $99 for upgrades. Both versions are available on Windows, Mac, and Linux, and can be downloaded from the <a href="http://www.jetbrains.com/idea/download/">IntelliJ IDEA download page</a>.</p>
<p>&nbsp;</p><br><br><br><br><br><br></body></html>