<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>PuppetLabsとOpscodeはどうやってオープンソースコミュニティを育てたか</h3><p><a target="_blank" href="http://www.infoq.com/news/2013/03/growing-communities;jsessionid=AF9C047ED9A962E8D8F1AC51ED5833D9"><em>原文(投稿日：2013/03/19)へのリンク</em></a></p> 
<div class="clearer-space">
 &nbsp;
</div> 
<div id="newsContent"> 
 <p class="p1">コミュニティを育てるには人々にきちんと接して、物事がどのようになされたかを透明にすることが重要だ、と<a target="_blank" href="http://twitter.com/puppetmasterd">Luke Kanies氏</a>と<a target="_blank" href="https://twitter.com/adamhjk">Adam Jacob氏</a>は言う。Luke Kanies氏はPuppetLabsの創業者、CEOであり、<a target="_blank" href="https://twitter.com/adamhjk">Adam Jacob氏</a>はOpscodeの共同創業者でありChefの開発者だ。両者ともコミュニティに対して真摯に関わることが必要だと主張している。<a target="_blank" href="https://puppetlabs.com/">PuppetLabs</a>と<a target="_blank" href="http://www.opscode.com">Opscode</a>はビジネスと共に活発なオープンソースコミュニティを作ることに成功した企業だ。</p> 
 <p class="p1"><a target="_blank" href="http://na.apachecon.com/schedule/presentation/222/">ApacheConfのキーノート</a>で<a target="_blank" href="http://www.linux.com/news/featured-blogs/196-zonker/707984-puppet-labs-ceo-how-to-grow-an-authentic-open-source-community">“多くの企業がコミュニティは強引に作成できると考えている”、しかしそれは間違いだとKanies氏</a>は言った。さらに、質問には誠実に答える必要があると付け加えたが、透明性とオープンネスは同じではないとも主張している。氏は<a target="_blank" href="http://www.linux.com/news/featured-blogs/196-zonker/707984-puppet-labs-ceo-how-to-grow-an-authentic-open-source-community">コミュニティ全体に公開していない資金調達などの話題については質問されても回答していない</a>。氏にとって重要なのは、変化を告知することではなく、コミュニティを惹き付けることなのだ。氏が例示したのは<a target="_blank" href="http://www.apache.org/licenses/LICENSE-2.0">Apache</a>から<a target="_blank" href="http://en.wikipedia.org/wiki/GNU_General_Public_License">GPL</a>へライセンスを変更したことだ。このプロセスには1ヶ月かかったが最終的には3000人のコミュニティメンバの内2人しか不満を言わなかった。</p> 
 <p class="p1">JacobはInfoQの取材に、コミュニティの基礎は尊敬の念だと答えた。成功の機会を手に入れるにはコミュニティに対して真剣に取り組むしかない。コミュニティの運用方針を透明にすることが重要だ。氏が例示したのは<a target="_blank" href="http://wiki.opscode.com/display/chef/How+to+Contribute">Contributor License Agreement (CLA)</a>だ。CLAを明記するための議論はだれも好まないが、CLAはすべての貢献者がOpscodeに対して全く同じ権利を持っていることを完全に明確にした。</p> 
 <p class="p1">氏が強調したのは、すべての企業はその企業の製品のオープンソースコミュニティとの関わり方について2つの選択肢を持っているということだ。製品をコミュニティへの贈り物としながら、コミュニティからの貢献を利用する方法か、すべての貢献者を同等として扱う方法のどちらかだ。氏曰く、Opscodeは後者の方法を採用している。</p> 
 <p id="lastElm">&nbsp;</p> 
</div> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>