<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Programa Adote uma JSR cresce, ganha força da Oracle e se envolve no Java EE 7</h3><p>O programa Adote uma JSR, liderado por grandes grupos de usu&aacute;rios Java, ganhou apoio oficial da Oracle. Arun Gupta, evangelista Java da empresa, <a href="https://blogs.oracle.com/arungupta/entry/transparency_and_community_participation_in">publicou recentemente</a> sobre a for&ccedil;a da participa&ccedil;&atilde;o da comunidade, que atrav&eacute;s de feedbacks e outras contribui&ccedil;&otilde;es tem apoiado a evolu&ccedil;&atilde;o do Java, mais especificamente o Java EE 7, que se encontra em desenvolvimento.</p> 
<p>Gupta frisou as vantagens do envolvimento da comunidade:</p> 
<blockquote> 
 <p>Todos esses esfor&ccedil;os mostram que o Java EE 7 est&aacute; contando com a participa&ccedil;&atilde;o das bases da comunidade global, o que permite feedback antecipado sobre a especifica&ccedil;&atilde;o e implementa&ccedil;&atilde;o partindo de usu&aacute;rios finais e desenvolvedores. No final, ser&atilde;o essas pessoas que utilizar&atilde;o as APIs. Como um todo, essa iniciativa leva a resultados de maior qualidade e, esperamos, ado&ccedil;&atilde;o mais r&aacute;pida tamb&eacute;m.</p> 
</blockquote> 
<p>O SouJava e o London Java Community, ambos membros do Comit&ecirc; Executivo do JCP, lan&ccedil;aram conjuntamente em 2011 <a href="http://www.infoq.com/br/news/2012/01/adote-uma-JSR;jsessionid=868DF01A66785F81EB3437D965672F1B">o programa Adote uma JSR</a>, com o objetivo de aumentar a participa&ccedil;&atilde;o da comunidade Java na evolu&ccedil;&atilde;o das especifica&ccedil;&otilde;es que definem o rumo da tecnologia. O foco inicial &eacute; o novo Java EE.</p> 
<p>Gupta destaca que a transpar&ecirc;ncia &eacute; um dos requisitos do JCP 2.8, vers&atilde;o mais recente do processo formal para cria&ccedil;&atilde;o de especifica&ccedil;&otilde;es da tecnologia Java, e que espera contar com mais colabora&ccedil;&atilde;o e feedback da comunidade. Todas as JSRs do Java EE atendem &agrave;s regras de transpar&ecirc;ncia definidas. Como consequ&ecirc;ncia, atualmente qualquer pessoa pode se inscrever na <a href="mailto:users@javaee-spec.java.net">lista de usu&aacute;rios do Java EE</a> e fornecer feedback. As JSRs da plataforma e os seus respectivos projetos est&atilde;o listados na <a href="http://java.net/projects/javaee-spec/pages/Home">p&aacute;gina inicial do Java EE 7</a>. Cada p&aacute;gina de cada JSR cont&eacute;m listas de endere&ccedil;os do Expert Group, vis&iacute;veis publicamente na forma de listas de usu&aacute;rios observadores. As listas de discuss&atilde;o recebem c&oacute;pias de todos os e-mails do grupo de especialistas, e permitem postar coment&aacute;rios e participar de discuss&otilde;es com os membros do grupo do JCP.</p> 
<p>Diferentes grupos de especialistas do Java EE 7 e JUGs <a href="https://blogs.oracle.com/theaquarium/entry/adopt_a_java_ee_7">divulgaram</a> o programa com temas mais espec&iacute;ficos, como o <a href="http://glassfish.java.net/adoptajsr/">Adote uma JSR do Java EE 7</a>, para incentivar ainda mais a participa&ccedil;&atilde;o de especialistas em cada &aacute;rea.</p> 
<p>Gupta destaca as principais contribui&ccedil;&otilde;es j&aacute; realizadas atrav&eacute;s do programa Adote uma JSR para o Java EE 7:</p> 
<ul> 
 <li>O London Java Community (LJC) organizou um <a href="http://www.meetup.com/Londonjavacommunity/events/101954512/">&quot;Hack Day&quot; de WebSocket e JSON</a>, e os <a href="http://java.net/projects/adoptajsr/downloads/download/wesocket-jsonhackday-130208072652-phpapp01.ppt">materiais de apresenta&ccedil;&atilde;o</a> e <a href="https://github.com/Adopt-a-JSR/JSR-353-JSON">fontes</a> foram disponibilizados;</li> 
 <li>O Chennai JUG (da cidade da &Iacute;ndia de mesmo nome) est&aacute; desenvolvendo um jogo multi-player que pode ser jogado pela Internet, e que usa APIs Java EE 7 como WebSocket 1.0, JPA 2.1 e JSF 2.2. Os <a href="https://github.com/jugchennaiadoptjava/UrbanTravellers/tree/develop">fontes est&atilde;o no GitHub</a>;</li> 
 <li>O Morocco JUG (Marrocos) far&aacute; apresenta&ccedil;&otilde;es sobre Java EE 7, WebSocket, e JSON na <a href="http://jdc2013.egjug.org/session/introduction_json_websocket_apis_hackday">Java Developer Conference</a>, em Cairo no Egito;</li> 
 <li>O Cologne JUG (Alemanha) realizou um encontro sobre JSF 2.2 e <a href="http://www.youtube.com/watch?v=YOeyKGwVafE&amp;feature=youtu.be">outro sobre CDI 1.1</a>;</li> 
 <li>O BeJUG (B&eacute;lgica) adotou a JSR 356 e planeja um <a href="http://www.bejug.org/confluenceBeJUG/display/BeJUG/Java+WebSockets+Hackathon">hackathon</a> usando WebSocket;</li> 
 <li>O grupo brasileiro Cear&aacute; JUG planeja diversas <a href="http://www.cejug.org/2013/02/22/cafe-com-tapioca-de-marco/">apresenta&ccedil;&otilde;es</a> sobre JAX-RS 2.0, Java API for JSON, JSF 2.2 e API de WebSocket 1.0;</li> 
 <li>O San Francisco JUG (EUA) organizou uma <a href="http://www.sfjava.org/events/93511462/">sess&atilde;o de Java EE 7 e WebSocket</a> e planeja uma pr&oacute;xima de JAX-RS 2.0;</li> 
 <li>Outro brasileiro, o SouJava, est&aacute; contribuindo com a adi&ccedil;&atilde;o de recursos do JSF 2.2 no projeto de exemplos do NetBeans <a href="http://netbeans.org/kb/samples/scrum-toys.html">Scrum Toys</a>.</li> 
</ul> 
<p>Para saber mais e se envolver na iniciativa Adote uma JSR, confira o <a href="http://adoptajsr.org/">site</a> do projeto.</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>