<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Anime version of Scrum overview diagram available from Scrum Primer website</h3><p>&nbsp;Bas Vodde is one of the authors of the <a href="http://www.infoq.com/minibooks/Scrum_Primer;jsessionid=6D8F4CF04BCA97F8E9E52911C1125FEF">Scrum Primer</a>&nbsp;available from <a href="http://www.infoq.com/minibooks/Scrum_Primer;jsessionid=6D8F4CF04BCA97F8E9E52911C1125FEF">InfoQ.com</a> and from the Scrum Primer <a href="http://www.scrumprimer.org/#home">website</a>.</p> 
<p>On the Scrum primer website there is a graphic which shows an <a href="http://www.scrumprimer.org/#overview">overview</a> of the Scrum process which has been made freely available under a Creative Commons license.&nbsp;</p> 
<p>Recently another version of the overview diagram was added to the website – one showing the Scrum process as an anime <a href="http://www.scrumprimer.org/#anime">cartoon</a>&nbsp;</p> 
<p><img src="/resource/news/2013/03/anime-scrum-primer/en/resources/anime_scrum_overview_small.png;jsessionid=6D8F4CF04BCA97F8E9E52911C1125FEF" width="512" height="365" alt="" _href="img://anime_scrum_overview_small.png" _p="true" /><br /> <br /> Bas spoke to InfoQ about the new graphic.</p> 
<p><strong>InfoQ</strong>: What inspired you to prepare an anime view of the Scrum process?<br /> <strong>Bas</strong>: It all happened quite accidentally. Over the last years, I've worked quite a lot in Japan, especially giving Scrum courses there. One day, a student brought some planning poker cards that were in anime style. He had made them himselves. I looked at them and thought they were really really great. So, I asked if we could replicate them. However, he had only four images and we wanted a different image on each card. So, we needed an artist and the Japanese agile coaches at Odd-e had a friend who could make anime really well, so we asked her. She made anime style planning poker cards which are now incredibly popular with our students and clients.</p> 
<p>The planning poker cards were Scrum-themed. So, one day, I was looking at them and noticed that we had all graphics to create a Scrum Overview picture. So, I asked my colleagues from Odd-e Japan what they thought about that and they said it was possible. So, we started making the Scrum Overview picture. We'll see what comes from it next. So far, it has mainly just been fun and cool.</p> 
<p><strong>InfoQ</strong>: Who was the artist?<br /> <strong>Bas</strong>: The artist is called Touko Okamoto. She's a good friend of our Odd-e Japan team and always helps us out with lots of things. And, as you can see, she is a great artist. I think we're really lucky to work with her :)</p> 
<p><strong>InfoQ</strong>: How many versions of the diagram did you produce?<br /> <strong>Bas</strong>: Well, before we have the ones we published, we went through a long cycle of review and change. I think this might have lasted for one and a half year as all of us are busy and the communication didn't always go smooth. My Japanese language skills are still really bad!</p> 
<p>In the end, we published three versions: blue, pink and green. These versions kind-of came by accident. I believe the original version was pink (the cutest) and then I figured it would be nice to have a blue version too. So, I asked for a blue version and I got back a green version. I'm still not sure why, but I liked the green version too, so we ended up with three versions so everyone can pick their style :P<br /> <br /> <strong>InfoQ</strong>: How has it been received by the community?<br /> <strong>Bas</strong>: So far, it has been received very well. The most common feedback has been that they are &quot;cute&quot;.</p> 
<p>Personally, one of my favorite feedback has been from an American friend of mine who works in the Finance industy. This was related to the planning poker cards. Each card he would say &quot;Oh no!&quot; and be amazed at them. In the end, he said he loved them, but he wouldn't be able to use them in the US. I thought that was an interesting comment. I wouldn't know as, well, I'm rarely in the US.</p> 
<p><strong>InfoQ</strong>: You’ve released the diagram under a <a href="http://creativecommons.org/licenses/by-nd/3.0/deed.en_US">Creative Commons</a> license – what restrictions are there on people using it?<br /> <strong>Bas</strong>: We published it under creative commons with &quot;attribution&quot; and &quot;no change&quot;. The no change means you can't change the image. Not sure who would want to do that anyways :). The attribution means you need to attribute it back to Odd-e or the Scrum Primer site. The image is allowed to use commercially, so it is easy to add it to a presentation or-so.</p> 
<p>&nbsp;</p> 
<p id="lastElm"></p></body></html>