<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Google、Dart 1.0をリリース</h3><p><a target="_blank" href="http://www.infoq.com/news/2013/11/dart-10"><em>原文(投稿日：2013/11/14)へのリンク</em></a></p>
<div class="article_page_left news_container text_content_container"> 
 <div class="text_info"> 
  <p>最初の発表とプレビュー版リリースから2年、<a href="http://www.devoxx.be">Devvox in Belgium</a>にて、<a href="http://googledevelopers.blogspot.com/2013/11/dart-10-stable-sdk-for-structured-web.html">Lars Bak氏がDartの最初の安定版リリースを発表した</a>。<a href="https://www.dartlang.org/">Dart</a>はGoogleの新しいWebプログラミング言語であり、最新のWebアプリケーションを開発するためのプラットフォームだ。</p> 
  <p>Dart 1.0は、<a href="https://www.dartlang.org/">再デザインされたWebサイト</a>、Dart VM、Dart2JS（DartコードをJavaScriptに変換する）、<a href="https://www.dartlang.org/tools/editor/">EclipseベースのIDE</a>、Dart VMを搭載したChromeの特別ビルドである<a href="https://www.dartlang.org/tools/dartium/">Dartium</a>とともに登場した。</p> 
  <p>この2年で、Dartのパフォーマンスは劇的に改善した。Dartコードの実行には、2つの方法がある。1つはネイティブのDart VMを使うもので、去年、<a href="http://www.infoq.com/jp/news/2013/05/Dart-Java-DeltaBlue">特定のベンチマークでJVMを打ち負かした</a>。Dartをネイティブにサポートしていないブラウザの場合（現在のところ、サポートしているプロダクションレベルのブラウザはない）、dart2jsツールを使うことで、DartコードをJavaScriptにコンパイルすることができる。最近、<a href="https://www.dartlang.org/performance/">dart2jsが生成したJavaScriptは手書きのJavaScriptコードよりも優れている</a>というベンチマークが出た。さらに、生成されるJavaScriptのコードサイズは<a href="http://googledevelopers.blogspot.com/2013/11/dart-10-stable-sdk-for-structured-web.html">劇的に小さくなっている</a>。</p> 
  <blockquote> 
   <p>同様に、dart2jsの出力コードサイズも大幅に削減されました。<a href="http://dart-lang.github.io/pop-pop-win/">Pop, Pop, Win!</a>というゲームで生成されたJavaScriptは、1年前と比べて<a href="http://work.j832.com/2013/10/dart-to-javascript-output-size-what.html">40%小さくなりました</a>。VMのパフォーマンスも改善し続けています。ベンチマークにもよりますが、V8で動作する同等のJavaScriptよりも、42%から130%まで高速になっています。</p> 
  </blockquote> 
  <p><a href="/resource/news/2013/11/dart-10/ja/resources/deltabluebenchmark.png" target="_blank"><img src="http://www.infoq.com/resource/news/2013/11/dart-10/ja/resources/deltabluebenchmark.png" _href="img://deltabluebenchmark.png" _p="true" alt="" /></a></p> 
  <p><a href="http://googledevelopers.blogspot.com/2013/11/dart-10-stable-sdk-for-structured-web.html">ブログでの発表</a>で、DartチームはプロダクションにDartを使っている会社の名前をいくつか明らかにした。<a href="http://www.infoq.com/jp/news/2013/04/blossom-dart-switch">InfoQでは、今年の初めにBlossomの人に話しを聞いた</a>が、彼らはアプリケーションを徐々にDartへポーティングしている。Dartのユーザには、<a href="http://www.montagebook.com/">Montage</a>、<a href="https://www.soundtrap.com/">Soundtrap</a>、<a href="http://mandrill.com/">Mandrill</a>、そしてGoogleの社内CRMアプリケーションや<a href="http://www.google.com/elections/ed/de/districts">Google Elections</a>などが含まれる。</p> 
  <p>Dartライブラリの領域にも、いろいろなことが起こっている。パッケージリポジトリである<a href="http://pub.dartlang.org/">Dart Pub</a>には、ユーザが寄贈した500のパッケージが含まれている。Googleも自身のフレームワークのいくつかをポーティングしている。これには、<a href="http://www.infoq.com/jp/news/2013/06/angularjs-dart">人気のあるAngularJSフレームワークのDartポート</a>である<a href="https://github.com/angular/angular.dart">Angular.dart</a>と、その<a href="http://www.infoq.com/jp/news/2013/05/webcomponents">Web Componentsシムライブラリ</a>である<a href="http://www.infoq.com/jp/news/2013/07/dart-polymer-web-ui">Polymerのポート</a>も含まれる。</p> 
  <p>Dartは公式に、安定していてプロダクションレディであると宣言された。Dart 1.0はフリーでオープンソースであり、<a href="https://www.dartlang.org/">主要なプラットフォーム向けに、そのWebサイトからダウンロードできる</a>。更新されたWebサイトには、Dartの<a href="https://www.dartlang.org/#code">5分間のウォークスルー</a>や<a href="https://www.dartlang.org/codelabs/darrrt/">1時間のチュートリアル</a>がある。</p> 
 </div> 
</div><br><br><br><br><br><br></body></html>