<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>QConSF2013ハイライト - パート１</h3><p><a target="_blank" href="http://www.infoq.com/news/2013/11/qconsf-2013-highlights"><em>原文(投稿日：2013/11/30)へのリンク</em></a></p>
<div class="article_page_left news_container text_content_container"> 
 <div class="text_info"> 
  <p><strong>もうひとつの</strong>QConがサンフランシスコで開催され，そして終了した。Clojureを開発したRich Hickey氏，<a href="http://qconsf.com/system/files/presentation-slides/LinkedIn%20Mobile.pdf" target="_blank">LinkedIn Mobile</a>のKiran Prasad氏，<a href="http://qconsf.com/system/files/presentation-slides/LinkedIn%20Mobile.pdf" target="_blank">Google Guice</a>の作者で<a href="https://squareup.com/" target="_blank">Square</a>のCTOを努めるBob Lee氏など，エンタープライズソフトウェア界の蒼々たるリーダたちによる，情報にあふれた議論の嵐だった。Rich Hickey氏がClojureの設計，構成，パフォーマンスに加え，<a href="http://qconsf.com/system/files/presentation-slides/Clojure.pdf" target="_blank">チャネルを使用した</a>CSP(Communicating Sequential Processes)に関するさまざまな議論を展開する一方では，GitHubの<a href="http://qconsf.com/user/zach-holman" target="_blank">Zach Holman</a>氏が同サイト成功の理由についての考察を提供していた。</p> 
  <p class="MsoNormal">Hyattの魅惑的な施設で行われたカンファレンスの３日間に<a href="http://www.infoq.com/conferences/qconsf2013/" target="_blank">隙間なく詰め込まれた</a>，自慢の講演や展示会などのアクティビティには，どのトラックやイベントに出席するべきかの判断に迷うほどだった。多数の参加者が集まった各セミナールームでは，コーディング手法やオンライン多変量テスト，<a href="http://www.infoq.com/presentations/machine-learning-netflix?utm_source=infoq&amp;utm_medium=QCon_EarlyAccessVideos&amp;utm_campaign=QConSanFrancisco2013" target="_blank">応用機械学習</a>といった，実証性にあふれた講演やプレゼンテーションが参加者たちに提供されていた。</p> 
  <p class="MsoNormal">企業向けソフトウェア中心にセミナーが行われたグランドボール・ルームは，大勢の講演者に対応するため，AからDまでに分割されていた。その他２階にも，ゴールデンゲート・ルームやマリーナ・ルームなどといった名称の付けられた，さまざまな大きさの部屋が用意されていた。参加者には椅子でレイアウトされたミーティングスペースが，講演者にはプレゼンテーションスクリーンを備えた演壇が用意された。</p> 
  <p class="MsoNormal">QConの常連のお目当ては没入型のトラックだ – &quot;Next Generation HTML and JavaScript&quot;や&quot;<a href="http://qconsf.com/track/hadoop-beyond-map-reduce" target="_blank">Hadoop:Beyond Map Reduce</a>&quot;，あるいはモバイルリバースエンジニアのChristian Legnitto氏によるFacebookの<a href="http://qconsf.com/system/files/presentation-slides/The-Facebook-Mobile-Release-Process.pdf" target="_blank">モバイルリリースプロセス</a>に関する裏話，といったような著名なソフトウェア開発者による講演は，いずれも部屋を満席にしていた。</p> 
  <p class="MsoNormal"><img src="http://www.infoq.com/resource/news/2013/12/qconsf-2013-highlights/ja/resources/1QConSF confer 1.jpg" alt="" _href="img://1QConSF confer 1.jpg" _p="true" /></p> 
  <p class="MsoNormal">QConSFカンファレンスの開催された３日間，セッションが終わると参加者たちは会場を飛び出してリフレッシュメントを探す一方で，API管理企業の<a href="http://www.3scale.net/">3scale</a>や<a href="http://www.compuware.com/en_us/application-performance-management.html">Compuware APM</a>, <a href="http://www.oracle.com/us/products/index.html">Oracle</a>, <a href="http://www.hansoft.com/">Hansoft</a>, <a href="http://www.appdynamics.com/">AppDynamics</a>, <a href="http://www.azulsystems.com/">AZUL Systems</a>, <a href="http://www.hugeinc.com/">HUGE</a>, <a href="http://www.layer7.com/">Layer7 Technologies</a>, <a href="http://www.salesforce.com/">Salesforce</a>, <a href="http://www.semanticmerge.com/">SemanticMerge</a>, <a href="javascript:void(0);">O'Reilly</a>, <a href="http://www.cloudera.com/">cloudera</a>, <a href="http://www.solacesystems.com/">Solace Systems</a>といったエンタープライズソリューションプロバイダのもとに殺到した。</p> 
  <p class="MsoNormal">カンファレンスの広大な展示フロアには，IBMもブースを構えていた。そこではBig Blueのテクニカルエバンジェリストである<a href="http://qconsf.com/user/tom-banks">Tom Banks</a>氏が，エンタープライズソフトウェア開発エクスペリエンスをゲーム化することのメリットを説きながら，Raspberry Piとラジオコントロールカーを使ってIBM WebSphere Server Liberty Profileの機能をデモしていた。
   <o:p></o:p></p> 
  <p class="MsoNormal">テレフォニプロバイダtwilioのブースではデベロッパエバンジェリストの<a href="https://www.twilio.com/blog/2013/10/building-screen-pops-with-twilio-client-and-fullcontact-api.html">Jon Gottfried</a>氏が，クラウド上のアプリで拡張性を持った通信機能を実現する方法についての説明を行っていた。QConSFで取材した氏のインタビューが近々InfoQでビデオ公開されるので，ぜひご覧頂きたい。</p> 
  <p class="MsoNormal">パーティやブレインストームセッションのせいで，翌日朝に予定されていた講演で大変な思いをした人たちもいたようだ。それでもQConSFは，年に１度の人脈作りのチャンスであり，それを最大限に利用しようとする人には，無料のシャトルサービスや専用の社交場などといった支援もある。</p> 
  <p class="MsoNormal">時にきまぐれなサンフランシスコの天気も，カンファレンスの要素のひとつだ。澄んで暖かい昼と夜が，ハイアットには宿泊していない参加者たちのための素晴らしい通勤時間を演出してくれる。配慮の行き届いたランチとディナーのビュッフェは，QConの常連たちが無数の情報や数字，コーディングノウハウを習得するのに十分な栄養補給を確信させてくれる。</p> 
  <p class="MsoNormal">そのようにして時は過ぎ，間もなく始まる<a href="http://qconlondon.com/?utm_source=infoq&amp;utm_medium=listing&amp;utm_campaign=footer">QCon London</a>はプロセスやアーキテクチャ，フロントエンドとバックエンドを中心としたものになる。どのQConも，それぞれが知識の引き出しとして，独自の存在感を持っているのだ。</p> 
 </div> 
</div><br><br><br><br><br><br></body></html>