<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Agilidade solitária: tornando-se Agile  antes da própria equipe</h3><p>&Eacute; comum que organiza&ccedil;&otilde;es realizem uma transforma&ccedil;&atilde;o &aacute;gil que atinge toda uma equipe, projeto ou departamento, tendo em vista que a agilidade &eacute; uma abordagem voltada a equipes. Mas existem profissionais que come&ccedil;am a utilizar pr&aacute;ticas &aacute;geis individualmente, ou que trabalham de forma &aacute;gil em equipes de apenas uma pessoa. Como essas pessoas podem adotar pr&aacute;ticas &aacute;geis e quais os tipos de benef&iacute;cios que podem obter com isso?</p>
<p><a href="http://techwhirl.com/author/fionahanington/">Fiona Hanington</a> escreveu um post intitulado &quot;<a href="http://techwhirl.com/can-i-be-an-agile-technical-communicator/">Posso ser um comunicador t&eacute;cnico &aacute;gil quando meu time n&atilde;o &eacute;?</a>&quot;, no qual discute as possibilidades para se adotar t&eacute;cnicas &aacute;geis individualmente. Hanington realizou alguns treinamentos que a inspiraram a querer adotar t&eacute;cnicas &aacute;geis e a mudar sua maneira de trabalhar, mesmo antes de saber quando sua unidade organizacional faria a transi&ccedil;&atilde;o:</p>
<blockquote> 
 <p>Preciso mesmo esperar o restante da equipe adotar m&eacute;todos &aacute;geis antes que eu possa faz&ecirc;-lo? Ou existem aspectos da metodologia &aacute;gil que posso incorporar em meu trabalho desde j&aacute;?</p> 
</blockquote>
<p>Como sua unidade organizacional ainda n&atilde;o est&aacute; realizando a transi&ccedil;&atilde;o &aacute;gil, Hanington reconhece algumas limita&ccedil;&otilde;es:</p>
<blockquote> 
 <p>Atualmente trabalhamos em um ambiente que segue o modelo cascata tradicional: primeiramente levantam-se os requisitos, depois acontecem as fases de execu&ccedil;&atilde;o, testes, corre&ccedil;&otilde;es, lan&ccedil;amento de vers&atilde;o beta, mais corre&ccedil;&otilde;es e, finalmente, o lan&ccedil;amento da vers&atilde;o comercial do produto. Para realizar certas entregas ao longo das fases do projeto, preciso confiar em documentos de planejamento e outros artefatos elaborados por outros grupos. Por conta disso, sou for&ccedil;ada a esperar por minha unidade se tornar &aacute;gil antes que eu possa ser realmente uma comunicadora t&eacute;cnica &aacute;gil.</p> 
</blockquote>
<p>Hanington explora diversas pr&aacute;ticas que podem ser adotadas para se tornar &aacute;gil por conta pr&oacute;pria, explicando como &eacute; poss&iacute;vel focar nas necessidades do cliente durante o trabalho di&aacute;rio, ao questionar os requisitos que chegam. Ela discute as possibilidades de usar t&eacute;cnicas de planejamento &aacute;gil, como dividir o trabalho em tarefas pequenas, usar um quadro de planejamento pessoal para tornar vis&iacute;vel o trabalho que est&aacute; realizando, focar no planejamento a curto prazo e responder a mudan&ccedil;as, usar <a href="http://en.wikipedia.org/wiki/Timeboxing">timeboxing</a>, Kanban e defini&ccedil;&atilde;o de prioridades para as tarefas que ir&aacute; realizar. Sua conclus&atilde;o &eacute; que &eacute; poss&iacute;vel adotar uma forma &aacute;gil de trabalhar individualmente:</p>
<blockquote> 
 <p>N&atilde;o preciso esperar pela possibilidade de fazer parte de uma equipe totalmente &aacute;gil para utilizar pr&aacute;ticas &aacute;geis. Mesmo no modelo de trabalho em cascata, comecei a trazer alguns dos princ&iacute;pios &aacute;geis para o meu dia a dia de trabalho. Ironicamente, os passos que tomei at&eacute; agora me fizeram sentir mais parte do time que antes, embora eu esteja tomando as pr&aacute;ticas emprestadas de um modelo diferente.</p> 
</blockquote>
<p>Em outro post, &quot;<a href="http://illustratedagile.com/2013/01/14/make-your-agile-transformation-personal/">Fa&ccedil;a sua transforma&ccedil;&atilde;o &aacute;gil pessoal</a>&quot;, <a href="http://www.linkedin.com/in/lenlagestee">Len Lagestee</a> discute o que pode significar para um indiv&iacute;duo se tornar &aacute;gil.</p>
<blockquote> 
 <p>Sua jornada pessoal atrav&eacute;s de um transforma&ccedil;&atilde;o organizacional ou imers&atilde;o em um ambiente &aacute;gil ser&aacute; uma experi&ecirc;ncia &uacute;nica. Voc&ecirc; pode ou n&atilde;o j&aacute; ter tido experi&ecirc;ncia com agilidade. A mudan&ccedil;a pode vir muito naturalmente ou gerar ansiedade.</p> 
</blockquote>
<p>Segundo Lagestee essa jornada pessoal inicia quando se entende o que &eacute; agilidade e ao experimentar algumas de suas pr&aacute;ticas. Ele deixa claro que os indiv&iacute;duos t&ecirc;m que adotar agilidade no seu pr&oacute;prio ritmo:</p>
<blockquote> 
 <p>N&atilde;o deixe que ningu&eacute;m lhe diga onde se deve estar no caminho ou como deveria estar se sentindo. Descubra em qual ciclo voc&ecirc; est&aacute; agora e determine o que precisa ser feito para alcan&ccedil;ar o pr&oacute;ximo n&iacute;vel.</p> 
</blockquote>
<p>Em outro post, <a href="https://twitter.com/itwphiljohnson">Phil Johnson</a> faz a seguinte pergunta: &quot;<a href="http://www.google.com/url?q=http%3A%2F%2Fwww.itworld.com%2Fit-management%2F318523%2Fcan-lone-developer-use-agile&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNHRpw4fmIGDwQguWKroXcGVadmSJw">Desenvolvedores que trabalham sozinhos podem adotar m&eacute;todos &aacute;geis?</a>&quot;</p>
<blockquote> 
 <p>Existem desenvolvedores que, por op&ccedil;&atilde;o pr&oacute;pria ou pelas circunst&acirc;ncias, trabalham em times de apenas uma pessoa. Esses desenvolvedores s&atilde;o exclu&iacute;dos do uso de m&eacute;todos &aacute;geis para gerir o pr&oacute;prio trabalho de desenvolvimento ou ser&aacute; que mesmo solit&aacute;rios podem adotar tais m&eacute;todos?</p> 
</blockquote>
<p>Johnson explica por que acredita que um indiv&iacute;duo pode utilizar m&eacute;todos &aacute;geis e se beneficiar com isso. Ele elaborou uma lista de pr&aacute;ticas &aacute;geis que incluem:</p>
<blockquote> 
 <ul class="c15 lst-kix_8mdiva23qlu-0 start"> 
  <li>Crie pequenos peda&ccedil;os de trabalho claramente definidos (exemplo, hist&oacute;rias de usu&aacute;rio);</li> 
  <li>Realize reuni&otilde;es di&aacute;rias (standups) antes de iniciar o trabalho;</li> 
  <li>Mantenha um controle de quanto tempo se leva para realizar as tarefas e quantas delas s&atilde;o conclu&iacute;das em cada sprint;</li> 
  <li>Comunique-se frequentemente com o cliente, para fornecer atualiza&ccedil;&otilde;es regulares e vers&otilde;es do produto, al&eacute;m de solicitar feedback e sugest&otilde;es.</li> 
 </ul> 
</blockquote>
<p>E voc&ecirc;, j&aacute; utilizou pr&aacute;ticas &aacute;geis mesmo antes que seu time tenha come&ccedil;ado a faz&ecirc;-lo? J&aacute; utilizou tais pr&aacute;ticas trabalhando em times de apenas uma pessoa? Obteve benef&iacute;cios ao adotar pr&aacute;ticas &aacute;geis individualmente?</p><br><br><br><br><br><br></body></html>