<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Using Process Improvement for Repeatable Results with Agile</h3><p>On November 14 and 15 the <a href="http://sepg.unicom.co.uk/">SEPG Europe 2013</a>&nbsp;conference will be held in Amsterdam. The conference program covers&nbsp;experience stories and&nbsp;presentations on using the Capability Maturity Model Integrated™ (CMMI) in agile environments.&nbsp;InfoQ will cover this conference, and&nbsp;did an interview with Eileen Forrester, CMMI Product Manager at the CMMI Institute about how the CMMI can support agile adoption and with Alec McCutcheon, Commercial Director of UNICOM about the focus of the SEPG Europe conference.</p>
<p><strong>InfoQ: The CMMI V1.3 has been published in 2010. Have there recently been new developments around the CMMI? Can you tell us more about them?</strong></p>
<blockquote> 
 <p><strong>Eileen:</strong> The most obvious development is that Carnegie Mellon and the SEI have rolled out the CMMI Institute—we are now independent of the SEI, still operated by Carnegie Mellon.&nbsp; This change allows us to be more customer and market driven, while still meeting the needs of our traditional users of CMMI.&nbsp; As part of our product strategy, we are building “profiles” to accompany CMMI that help users who work in particular domains, do specific work types, or want to use methods or frameworks smoothly with CMMI.&nbsp; Our first profile will be about agile and CMMI, and we are evaluating DevOps as another possible profile.&nbsp;&nbsp;</p> 
</blockquote>
<p><b>InfoQ: This idea of profiles sounds to me as something that can help organizations to apply models more effectively. Can you tell some more about the Agile and CMMI profile, what can we expect from it?</b></p>
<blockquote> 
 <p><strong>Eileen:</strong> That is exactly the idea—help organizations to apply the model more effectively.&nbsp; A strength of the CMMI models is that they are designed to be general enough to apply to many settings and uses.&nbsp; Still, whenever I teach an introductory class about CMMI, the first hurdle for new users is to translate those general practices into their context and language.&nbsp; With profiles, we want to make that step easier for known applications, like agile or DevOps, or for particular industries, like financial services or health care.&nbsp; For the last few years, we’ve seen a multitude of case reports, presentations, even whole books on using agile and CMMI together, and authors asserting that we really have no conflict between the two.&nbsp; And when we revised the CMMI and produced V1.3 in 2010, we deliberately added some supports for agile.&nbsp; That’s great information, but when it comes to getting started, we hear from users that they still need more.&nbsp; With profiles, we’ll be providing informative and explanatory material with the normal model content to make it more obvious how agile and CMMI fit together.&nbsp; Planning and monitoring of work, for example, occurs in an agile context, of course, but the traces or those practices may be different than in more traditional approaches.&nbsp; So what should users look for?&nbsp; And if they want to do an appraisal, how do they show that they are doing the practices without having to do extra work to produce artifacts that they don’t need? We want the tips and advice from people already making it work with agile and CMMI on how to do it, and the problems and challenges from people who aren’t sure how to proceed.&nbsp; We’ll be using an agile approach to build the first increment of an agile profile, of course, so we’re eager to discover with users exactly what is needed in the solution we build!</p> 
</blockquote>
<p><strong>InfoQ: The agile manifesto values individuals and interactions over processes and tools. The primary focus of the CMMI is process improvement. Doesn't that collide when an organization, who is used to doing process improvement, wants to adopt an agile mindset and culture?</strong></p>
<blockquote> 
 <p><strong>Eileen:</strong> When agile and CMMI collide, I think it is due to misapprehension more than necessity.&nbsp; The authors of <a href="http://cmmiinstitute.com/resource/cmmi-or-agile-why-not-embrace-both/">CMMI or Agile: Why Not Embrace Both</a> included thought leaders from both the agile and CMMI communities, and they explain this situation clearly.&nbsp; As a keynote speaker at an SEPG conference a few years ago, Alistair Cockburn said that he thought an organization needed to be using all the practices at maturity level 3 of CMMI to get full advantage of agile.&nbsp;&nbsp; I know few sincere advocates of process improvement who don’t value individuals and interactions!&nbsp; And as a longtime user myself of iterative, spiral, incremental, customer facing value solutions I simply don’t see the problem in appreciating both flexibility and adaptive process.&nbsp; Services are certainly already agile in many ways, so as the product manager for CMMI for Services, this seems like a false divide to me.&nbsp; I’d encourage organizations used to doing process improvement to treat their improvement system as an agile development.&nbsp; Work closely with the customers of the improvement to uncover the real requirements and regularly produce working solutions together.&nbsp;&nbsp;</p> 
</blockquote>
<p><strong>InfoQ: Are their examples of enterprises that are using the CMMI in their Agile or Lean transformation? How does combining the models help them?</strong></p>
<blockquote> 
 <p><strong>Eileen:</strong> We will have several cases at this SEPG Europe conference of enterprises getting great business results by using agile and lean along with CMMI.&nbsp; The combination is powerful, helping the enterprise to have repeatable and reliable results that they can sustain while remaining flexible and adaptive to shifting conditions in the market and evolving needs from customers.&nbsp; Of course it is possible to interpret the CMMI practices in a rigid and bureaucratic way, but the model itself does not prescribe any set&nbsp; way of performing practices.&nbsp; Kanban can be used to plan and monitor as easily as Gantt charts and earned value techniques.</p> 
</blockquote>
<p><strong>InfoQ: The high maturity levels in the CMMI focus on continuous improvement. Can you use agile practices like retrospectives to reach such a high maturity level? </strong></p>
<blockquote> 
 <p><strong>Eileen:</strong> Retrospectives are an important technique to encourage improvement at lower levels of maturity too!&nbsp; In fact, practitioners who use agile and CMMI together employ retrospectives, Kanban, kaizen events, and more to lead to faster process improvement and, yes, even to faster achievement of higher maturity.&nbsp; These techniques can be applied robustly, make the flow of work visible--which is crucial to process performance and modeling—help us to face facts and uncover causes for negative and positive outcomes.&nbsp; And David Anderson and others are showing how agile practices, especially Kanban, tend to lower resistance to change, which can only help with continuous improvement.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p> 
</blockquote>
<p><strong>InfoQ: The People-CMM is a supporting model for the CMMI. It covers topics like professional development, communication and collaboration. Do you know if and how it is used in agile adoption?</strong></p>
<blockquote> 
 <p><strong>Eileen:</strong> It also has a bias toward empowering individuals and teams, and for progressing to self-directed teams.&nbsp; These principles strike me as excellent supports for agile implementations.&nbsp; I have conducted research in the past showing that People CMM if adopted first can provide a basis for more effective management overall and ready an organization for other adoptions.&nbsp; I haven’t seen specific cases of People CMM clearing the path for agile adoption, but it wouldn’t surprise me.&nbsp; We are seeing cases of P-CMM process areas being used to reinforce high maturity practices too.</p> 
</blockquote>
<p><strong>InfoQ: Earlier you mentioned the upcoming CMMI profiles. Is it possible for InfoQ readers to participate in this initiative?</strong></p>
<blockquote> 
 <p><strong>Eileen:</strong> I’d like to encourage the agile and DevOps community along with CMMI practitioners to give us input for our profiles on agile and CMMI or on DevOps and CMMI.&nbsp; We will be looking for results and cases and welcome participants and reviewers as we do this work.</p> 
</blockquote>
<p><b>InfoQ: Alec, for people who do not know the SEPG conference, can you introduce it to them?</b></p>
<blockquote> 
 <p><b>Alec: </b>The SEPG Europe is the premier platform to learn, connect, apply and achieve CMMI practices to performance improvement in your organization. Software Engineering Process Group (SEPG) is a brand originally developed by the Software Engineering Institute (SEI), a famous ICT standards body. SEI is based in the Carnegie Melon University and formerly controlled the CMMI (Capability Maturity Model Integrated), a process improvement approach for improving performance. The SEI has transferred CMMI-related products and activities to the CMMI Institute, also based in Carnegie Melon University. CMMI Institute also inherited the SEPG series of conferences which is run in the US, Europe and Asia Pacific (Australia).</p> 
</blockquote>
<p><b>InfoQ: This is the first SEPG Europe conference that is co-organized with Unicom. What made you decide to do this event together with the CMMI Institute?</b></p>
<blockquote> 
 <p><b>Alec:</b> Yes, this is the first time we are collaborating with CMMI Institute formally. But they have worked with UNICOM a few times earlier as speakers for conferences and forums. Neither the SEI nor the CMMI Institute has the reach to promote effectively in UK and Europe. So the CMMI Institute started a dialogue with UNICOM to co-organize the conference.</p> 
</blockquote>
<p><b>InfoQ: What's the focus of the 2013 SEPG Europe conference? What can the attendees expect to get out of it?</b></p>
<blockquote> 
 <p><b>Alec: </b>This year’s SEPG Europe program features experience stories, expert presentations on using CMMI effectively in agile environments, and advanced topics for both beginners and expert users. Among the presentations are lean techniques for CMMI appraisals, adding security to CMMI implementations in a flexible manner, and business results from combined uses of CMMI for Development and Services. Multiple tracks of CMMI content over the two days focus on what matters most to CMMI implementers – results.</p> 
</blockquote><br><br><br><br><br><br></body></html>