<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>IBMのMobile First - MBaaS，ビッグデータ，それ以上のものをエンタープライズに</h3><p><a target="_blank" href="http://www.infoq.com/news/2013/04/ibm-mobile-first;jsessionid=640C85FF2FE85524E443EE36D8417332"><em>原文(投稿日：2013/04/09)へのリンク</em></a></p> 
<div class="clearer-space">
 &nbsp;
</div> 
<div id="newsContent"> 
 <p class="MsoNormal">IBMは，現在のモバイルコンピューティングのトレンドをキャッチアップする <a target="_blank" href="http://www.ibm.com/mobilefirst/us/en/">包括的システム</a>，ないしはスイート，あるいは同社の説明ではアプリケーション <i>ポートフォリオ</i> を構築した。Mobile Firstという名のこのシステムは，トレンドに乗り切れていない組織がいまだテーブルに残したままの数十億ドルの市場から，ユーザ企業がシェアを獲得するためデザインされたものだ。</p> 
 <p class="MsoNormal">Mobile Firstの中核となる <a target="_blank" href="http://www-01.ibm.com/software/mobile-solutions/worklight/components/mobile-development-platform/">開発プラットフォーム</a> は，HTML5, CSS3, Apache Cordovaに基づくもので，<a target="_blank" href="http://www-01.ibm.com/software/mobile-solutions/worklight/">Worklight Studio</a> と呼ばれる。Worklight StudioはEclipse上で動作するIDEである。完全なモバイルWebアプリ，あるいはAndroidやiOS，Blackberry用のOS対応アプリ開発に必要なコードは，すべてこの上で開発することができる。さらにAT&amp;TのクラウドベースAPIへのアクセスなど，バックエンド接続の実現に使用する数々のアダプタも備えている。一部はあらかじめ設定されているが，その他に開発者自身がSQLやHTTPを使って作成することも可能だ。</p> 
 <p class="MsoNormal">Worklight StudioにはJQuery Mobile, Sencha Touch, Dojo ToolkitなどのJavaScriptライブラリが統合されているので，モバイル開発者が既存のコード資産を組み込む時間の大幅な短縮が実現できる。使用するライブラリはアプリケーション作成ウィザードで簡単に選択可能である。</p> 
 <p class="MsoNormal">フレキシブルな認証フレームワークも装備されていて，フォームやクッキー，HTTPヘッダ，アダプタなどに基づく認証処理に対応している。&quot;Do It Yourself&quot; 派ならば，Authentication Configuration Editorを使って独自のフレームワークを構築することもできる。</p> 
 <p class="MsoNormal">用意されている <a target="_blank" href="http://www.ibm.com/developerworks/mobile/">補助ツール</a> の数も多く，モバイル開発ソリューション全般に対応する。Mobile FirstにおけるIBMのマントラは，おそらく &quot;倒すことのできない敵は <a target="_blank" href="http://itknowledgeexchange.techtarget.com/soa-talk/ibm-buys-in-to-mobile-middleware-acquires-worklight/">買収せよ</a>&quot; ということばがもっとも言い当てているだろう。 多彩なモバイルツールやサービスのコレクションを構成する１ダース近いツール群は，そのような行動の結果だ。</p> 
 <p style="line-height: normal" class="MsoNormal"><span>エンタープライズシステムはその定義上，硬直的で比較的変化が少なく，大規模な変更には時間を要するのが一般的である。ただしIBM用語で言う変更は選択の対象ではなく，義務であるというのが正確だ。</span><span>エンタープライズシステムで <a target="_blank" href="http://en.wikipedia.org/wiki/IBM"><span style="color: blue">IBM</span></a> に比肩するものはおそらく存在しないだろう。したがって同社が <a target="_blank" href="http://www.ibm.com/mobilefirst/us/en/why-ibm-for-mobile/?lnk=announce"><span style="color: blue">モバイルこそ一番 (Mobile is First)</span></a> と説くならば，それはある種の威厳を持つことばになる。</span><span><a target="_blank" href="http://www-03.ibm.com/press/us/en/pressrelease/40408.wss"><span style="color: blue">Mobile First</span></a> でIBMはユーザ企業に， <a target="_blank" href="http://articles.economictimes.indiatimes.com/2013-02-25/news/37289434_1_mobile-applications-mobile-analytics-mobile-commerce"><span style="color: blue">目を覚まして</span></a> コーヒーを味わうよう告げているのだ。</span></p> 
 <p style="line-height: normal" class="MsoNormal"><span>その意味から言うと，モバイルに不可欠な特質が <a target="_blank" href="http://gigaom.com/2013/02/21/ibms-mobile-first-plan-is-really-about-cloud-first-thats-all-you-need-to-know/"><span style="color: blue">ビッグデータに基づく</span></a> ものであるというのが，やや皮肉な事実に思われる。</span><span>モバイルコンピューティングという新しい概念に <a target="_blank" href="http://www.infoq.com/news/2012/11/Big-Data-Survey;jsessionid=D1851884A8B8A00F79DDDDF48236A485;jsessionid=640C85FF2FE85524E443EE36D8417332"><span style="color: blue">相反する</span></a> ものだからだ。</span><span>モバイル最優先というIBMのビジョンによれば，いまだエンタープライズシステムをモバイルデバイス対応に一新しない企業は敗者になるはずなのだ。</span></p> 
 <p class="MsoNormal">&nbsp;</p> 
 <p class="MsoNormal">中規模ないし小規模の開発者にとって，IBMのモバイル戦略に乗るのは <a target="_blank" href="https://www-112.ibm.com/software/howtobuy/buyingtools/paexpress/Express?P0=E1&amp;part_number=D0PMQLL,D0PMTLL,D0PMWLL,D0PMZLL,D0PN2LL,D0VBPLL&amp;catalogLocale=en_US&amp;locale=en_US&amp;country=USA&amp;PT=html">安くはない</a> が，そうでないユーザにはIBMの専門技術と <a target="_blank" href="http://www.ibm.com/developerworks/mobile/worklight/getting-started.html">深淵な機能セット</a> が賢明な投資を保証してくれるだろう。ただし，どの大企業にも批判者は存在する。たとえばgigaomのコメンテータ <i>Darth Vader's Mentor</i> は，</p> 
 <blockquote>
  IBM コンサルティング .... 300ドルのデバイスが起こす50万ドルの問題が，プロプライエタリAPIによるベンダロックインによって1,500万ドルのコンサルティング料金に転じた上に，オフショアヘルプは何もしてくれない，という代物。
 </blockquote> 
 <p><a target="_blank" href="http://www.youtube.com/watch?v=PSxihhBzCjk">映画「卒業」</a> のワンシーンのごとく，行き場を失ったハイテク世界のすべてに対して，ここにひとつのお告げの言葉が与えられる – <a target="_blank" href="https://engineering.purdue.edu/ECE/Academics/Undergraduates/UGO/Announcements/ibm-research-austin">未来とは</a> ただひとつ， &quot;モバイル&quot; だ，と。<a target="_blank" href="http://en.wikipedia.org/wiki/IBM_PC_DOS">PC DOS</a> の時の失敗とは違って，今回の時流をIBMが見逃すことは，どうやらなさそうなのだ。</p> 
 <p id="lastElm">&nbsp;</p> 
</div> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>