<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Ritmo sustentável: Como obtê-lo e melhorá-lo?</h3><p>Como um dos princ&iacute;pios do <a href="http://manifestoagil.com.br/">Manifesto &Aacute;gil</a>, o ritmo sustent&aacute;vel &eacute; considerado por muitos como fundamental para uma ado&ccedil;&atilde;o &aacute;gil. Atingir, por&eacute;m, um ritmo sustent&aacute;vel pode ser dif&iacute;cil, especialmente pela forma como as equipes s&atilde;o gerenciadas somado &agrave; cultura das organiza&ccedil;&otilde;es. Quando se pede &agrave;s equipes que melhorem suas velocidades, como isso pode ser feito para atingir um ritmo sustent&aacute;vel em um novo patamar?</p>
<p><a href="https://twitter.com/sustainablepace">Christoph Baudson</a> construiu um site falando sobre <a href="http://sustainablepace.net/what-is-sustainable-pace">o que &eacute; ritmo sustent&aacute;vel</a>. Baudson descreve as origens e os conceitos por tr&aacute;s do ritmo sustent&aacute;vel, referindo-se ao princ&iacute;pio do Manifesto &Aacute;gil, que ao seu ver &eacute; &quot;a defini&ccedil;&atilde;o mais comumente aceita&quot;:</p>
<blockquote> 
 <p>Processos &aacute;geis promovem um ambiente sustent&aacute;vel. Os patrocinadores, desenvolvedores e usu&aacute;rios, devem ser capazes de manter indefinidamente, passos constantes.</p> 
</blockquote>
<p>Baudson explica as raz&otilde;es pelas quais &eacute; importante trabalhar em um ritmo sustent&aacute;vel:</p>
<blockquote> 
 <p>O que ocorre quando o desenvolvimento de software &eacute; feito durante horas extras? Diversos estudos demonstram um aumento na produtividade na primeira semana de horas extras, o qual decai rapidamente at&eacute; finalmente cair a um n&iacute;vel de produtividade abaixo do normal das 40 horas de trabalho. Durante as horas extras, as pessoas tendem a n&atilde;o notar a queda em suas habilidades cognitivas, resultando em erros e finalmente em degrada&ccedil;&atilde;o da qualidade.</p> 
 <p>Ritmo sustent&aacute;vel n&atilde;o tem rela&ccedil;&atilde;o com &quot;pegar leve&quot; ou ir devagar. &Eacute; justamente o oposto, espera-se que se gaste energia vigorosamente para ent&atilde;o recuper&aacute;-la durante o descanso. No longo prazo, invista sua energia com sabedoria e leve em conta os resultados de pesquisas sobre felicidade ao estabelecer suas prioridades.</p> 
</blockquote>
<p>Em ocasi&otilde;es anteriores, a InfoQ norte-americana falou sobre ritmo sustent&aacute;vel em <a href="http://www.infoq.com/news/2008/05/sustainable-pace">does sustainable pace mean a 40 hour week?</a> (Ritmo sustent&aacute;vel significa 40 horas de trabalho semanal?) e <a href="http://www.infoq.com/news/2011/10/sustainable-pace-how">sustainable pace - what's it mean and how to achieve it?</a> (Ritmo sustent&aacute;vel - o que quer dizer e como conseguir?).</p>
<p>No post <a href="http://neilkillick.com/2012/10/24/sustainable-pace-the-fastest-way-to-deliver-software/">sustainable pace - the fastest way to deliver software</a> (Ritmo sustent&aacute;vel - a maneira mais r&aacute;pida de entregar software), <a href="https://twitter.com/neil_killick">Neil Killick</a> utiliza um exemplo para mostrar como &eacute; importante trabalhar em um ritmo sustent&aacute;vel. Killick descreve o impacto do aumento do n&uacute;mero de hist&oacute;rias de usu&aacute;rio que uma equipe tem para concluir em um sprint:</p>
<blockquote> 
 <p>Quanto mais hist&oacute;rias pedimos que a equipe entregue, menos tempo ela ter&aacute; para gastar em qualidade, mais prov&aacute;vel que atalhos sejam adotados e mais d&iacute;vidas t&eacute;cnicas sejam assumidas, mais prov&aacute;vel que a cultura e a efetividade sofram e que menos divers&atilde;o exista, mais cansada mentalmente a equipe estar&aacute; e menos previs&iacute;vel ser&aacute; sua entrega de software.</p> 
</blockquote>
<p>Medir a velocidade das equipes com o intuito de aument&aacute;-la pode prejudicar o ritmo sustent&aacute;vel no qual a equipe trabalha, como explica Steve Ropa no post <a href="http://blogs.versionone.com/agile_management/2013/08/09/reject-the-tyranny-of-metrics/">Reject the Tyranny of Metrics</a> (Rejeite a tirania das m&eacute;tricas):</p>
<blockquote> 
 <p>Tenho visto muitas equipes falarem sobre como aumentar a velocidade. O resultado final &eacute; sempre o mesmo. Estabelece-se uma velocidade como objetivo, ou pior ainda, uma taxa de acelera&ccedil;&atilde;o desejada. A conclus&atilde;o l&oacute;gica disso &eacute; igualmente previs&iacute;vel. As equipes come&ccedil;am a ficar paralisadas pela necessidade de que suas estimativas sejam corretas, j&aacute; que n&atilde;o haver&aacute; espa&ccedil;o para manobras caso haja algum erro. Logo depois, as equipes passam a estimar muito mais alto para conseguir uma margem para qualquer problema. Nenhum dos comportamentos permite o estabelecimento de um ritmo sustent&aacute;vel, nem est&aacute; condizente com o valor disposto no Manifesto &Aacute;gil de &quot;indiv&iacute;duos e intera&ccedil;&otilde;es entre eles mais que processos e ferramentas&quot;.</p> 
</blockquote>
<p><a href="https://twitter.com/derekhuether">Derek Huether</a> escreveu <a href="http://www.leadingagile.com/2012/09/a-lesson-in-process-improvement/">a lesson in process improvement</a> (uma li&ccedil;&atilde;o sobre melhoria no processo) no qual fala sobre a necessidade de se saber como o trabalho &eacute; executado antes de tentar se tornar mais r&aacute;pido:</p>
<blockquote> 
 <p>Um erro crucial que vejo frequentemente &eacute; o das organiza&ccedil;&otilde;es tentarem fazer as coisas mais rapidamente antes de entender de verdade seus pr&oacute;prios processos. Caso n&atilde;o se pare para perguntar se o processo como um todo foi otimizado antes de tentar ir mais r&aacute;pido, qualquer sucesso ser&aacute; ef&ecirc;mero. Garanto que rapidez sem otimiza&ccedil;&atilde;o n&atilde;o &eacute; sustent&aacute;vel.</p> 
</blockquote>
<p><a href="https://twitter.com/agilebuddha">Avienaash Shiralige</a> escreveu em <a href="http://www.agilebuddha.com/agile/sustainable-pace-does-culture-play-any-role-at-all/">sustainable pace: Does culture play any role at all?</a> (ritmo sustent&aacute;vel: Ser&aacute; que a cultura tem alguma influ&ecirc;ncia?)</p>
<blockquote> 
 <p>Ritmo sustent&aacute;vel n&atilde;o &eacute; uma maratona, &eacute; uma s&eacute;rie de corridas de tiro curto em que se pausa, reenergiza-se, reflete-se e come&ccedil;a-se de novo. Assim, &eacute; definitivamente necess&aacute;rio haver algum tempo livre no sprint para isso.</p> 
</blockquote>
<p>Shiralige cita a pesquisa do <a href="http://geert-hofstede.com/index.php">Geert Hofstede</a> sobre cultura. Um dos par&acirc;metros que o Geert mediu &eacute; o &iacute;ndice de dist&acirc;ncia do poder: &quot;o grau no qual os membros menos poderosos da sociedade aceitam e esperam que o poder seja distribu&iacute;do desigualmente&quot;. Em pa&iacute;ses nos quais esse &iacute;ndice &eacute; alto, pode ser dif&iacute;cil implementar um ritmo sustent&aacute;vel:</p>
<blockquote> 
 <p>Construir uma organiza&ccedil;&atilde;o que questiona, desafia ideias, compartilha abertamente pensamentos que eventualmente ajudem a criar equipes auto-organizadas, com absolutamente nenhum pensamento hier&aacute;rquico &eacute; extremamente dif&iacute;cil, ainda mais se for contra a pr&oacute;pria cultura ou forma de pensar.</p> 
</blockquote>
<p>Apesar da cultura ser algo dif&iacute;cil de se mudar, como Shiralige menciona, n&atilde;o podemos ignor&aacute;-la:</p>
<blockquote> 
 <p>A n&atilde;o ser que tratemos as quest&otilde;es culturais, a organiza&ccedil;&atilde;o n&atilde;o ser&aacute; capaz de obter a agilidade.</p> 
</blockquote>
<p>Qual sua experi&ecirc;ncia na ado&ccedil;&atilde;o de ritmo sustent&aacute;vel com sua equipe? Como foi a busca por melhorar a velocidade de entrega e estabelecer um ritmo sustent&aacute;vel em outro patamar?</p><br><br><br><br><br><br></body></html>