<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Dropbox anuncia o Pyston: uma nova implementação Python baseada em compilação JIT</h3><p>A Dropbox anunciou recentemente em seu <a href="https://www.google.com/url?q=https%3A%2F%2Ftech.dropbox.com%2F2014%2F04%2Fintroducing-pyston-an-upcoming-jit-based-python-implementation%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNGgr05qyLrKY2Kkz0MWoR8UZDsVUg">blog t&eacute;cnico</a> que est&aacute; desenvolvendo o Pyston, uma nova implementa&ccedil;&atilde;o em c&oacute;digo-aberto da linguagem <a href="https://www.google.com/url?q=https%3A%2F%2Fwww.python.org%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNGH1VGs4YIRW4hzrfqGYOAj43Qq-Q">Python</a>. O objetivo do Pyston &eacute; ser uma implementa&ccedil;&atilde;o de alta performance e ajudar a empresa a atingir suas metas de desempenho imposs&iacute;veis de alcan&ccedil;ar com o Python.</p>
<p>A necessidade de desenvolver o Pyston surgiu porque o Python &eacute; muito utilizado dentro da Dropbox. Entretanto, o c&oacute;digo Python acabava sendo reescrito em outra linguagem em algumas situa&ccedil;&otilde;es, devido &agrave;s necessidades de performance que eram exigidas quando o projeto era escalado.</p>
<p><a href="https://www.google.com/url?q=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fkevinmodzelewski&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNE4smTUv7s2eTNahDew8gQbAy9eOg">Kevin Modzelewski</a>, engenheiro de software da empresa sediada em S&atilde;o Francisco, explica como surgiu a ideia de desenvolver o Pyston:</p>
<blockquote> 
 <p>Ap&oacute;s abandonar algumas experi&ecirc;ncias com compila&ccedil;&atilde;o est&aacute;tica, n&oacute;s percebemos como as t&eacute;cnicas de compila&ccedil;&atilde;o just-in-time (JIT) t&ecirc;m sido aplicadas com sucesso no mundo JavaScript: o <a href="https://code.google.com/p/v8/">V8</a> do Chrome, em particular, aumentou consideravelmente o status quo da performance do JavaScript. Nossa esperan&ccedil;a &eacute; que ao usar t&eacute;cnicas semelhantes (de compila&ccedil;&atilde;o JIT), consigamos alcan&ccedil;ar resultados parecidos na performance do Python.</p> 
</blockquote>
<p>Apesar de j&aacute; existirem implementa&ccedil;&otilde;es Python - como por exemplo o <a href="http://www.google.com/url?q=http%3A%2F%2Fpypy.org%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNGquTIrDxASBq49FNZx8S95yPyRbg">PyPy</a>, o <a href="http://www.google.com/url?q=http%3A%2F%2Fwww.jython.org%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNFpHilNfknAvNGiriY1y6K_SFTZNg">Jython</a> e o <a href="http://www.google.com/url?q=http%3A%2F%2Fironpython.net%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNHOxmacTHQbh-iLmvmaWjm97vxUdg">IronPython</a> - que usam <a href="http://www.google.com/url?q=http%3A%2F%2Fen.wikipedia.org%2Fwiki%2FJust-in-time_compilation&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNGea6k56knjFR0lAncUrBeIBLLjTA">t&eacute;cnicas de compila&ccedil;&atilde;o JIT</a> sofisticadas, o Pyston &eacute; diferente porque o seu desenvolvimento &eacute; baseado na maioria das promissoras t&eacute;cnicas JIT que s&atilde;o incompat&iacute;veis com essas implementa&ccedil;&otilde;es. Por exemplo, o mundo JavaScript j&aacute; trocou as t&eacute;cnicas de <a href="http://www.google.com/url?q=http%3A%2F%2Fen.wikipedia.org%2Fwiki%2FTracing_just-in-time_compilation&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNErRp0bVnLzkYnitNcu5EXbEUkxow">rastreamento JIT</a>, utilizadas no PyPy, por t&eacute;cnicas method-at-a-time JIT devido aos seus benef&iacute;cios na performance.</p>
<p>Sobre se o Pyston ser&aacute; bem sucedido, Kevin Modzelewski comenta:</p>
<blockquote> 
 <p>Se as mesmas vantagens de performance se manter&atilde;o ou n&atilde;o com o Python &eacute; uma quest&atilde;o em aberto, mas uma vez que as duas abordagens (de t&eacute;cnicas JIT) s&atilde;o fundamentalmente incompat&iacute;veis, a &uacute;nica maneira de come&ccedil;ar a responder essa quest&atilde;o &eacute; construir (uma nova implementa&ccedil;&atilde;o baseada) em method-at-a-time JIT.&quot;</p> 
</blockquote>
<p>Outro ponto de diferencia&ccedil;&atilde;o do Pyston &eacute; o uso planejado de um <a href="http://www.google.com/url?q=http%3A%2F%2Fen.wikipedia.org%2Fwiki%2FBoehm_garbage_collector&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNH_C6vIk09pA7n5BAzbVqJ0wgyevA">garbage collector</a><a href="http://www.google.com/url?q=http%3A%2F%2Fen.wikipedia.org%2Fwiki%2FBoehm_garbage_collector&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNH_C6vIk09pA7n5BAzbVqJ0wgyevA"> conservativo</a> para apoiar eficientemente os m&oacute;dulos de extens&atilde;o. Al&eacute;m disso, o Pyston est&aacute; sendo constru&iacute;do em cima da <a href="http://www.google.com/url?q=http%3A%2F%2Fen.wikipedia.org%2Fwiki%2FLLVM&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNFuZO2BbnaiuqpFb37fs_jmyzTPyw">Low Level Virtual Machine</a> (<a href="http://www.google.com/url?q=http%3A%2F%2Fllvm.org%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNHFlFRqeswZHpIdTJG_Lnv98aj_UQ">LLVM</a>), uma infraestrutura de compila&ccedil;&atilde;o escrita em C++ projetada para realizar otimiza&ccedil;&otilde;es em tempo de compila&ccedil;&atilde;o, execu&ccedil;&atilde;o e &quot;ociosidade&quot; de programas escritos em qualquer linguagem.</p>
<p><strong>O estado atual do Pyston</strong></p>
<p>O desenvolvimento do Pyston ainda est&aacute; no in&iacute;cio, apenas um conjunto m&iacute;nimo da linguagem Python &eacute; suportado. Por conta disso, as avalia&ccedil;&otilde;es de desempenho tamb&eacute;m n&atilde;o s&atilde;o poss&iacute;veis, ainda falta dar suporte a um conjunto maior de benchmarks para ser representativo e ainda falta dar suporte a todos os recursos em tempo de execu&ccedil;&atilde;o do Python. Por enquanto, o Pyston &eacute; capaz de superar o desempenho do <a href="http://www.google.com/url?q=http%3A%2F%2Fpt.wikipedia.org%2Fwiki%2FCPython&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNHCRW644wDp8DyGbZtbAaojbHPRsQ">CPython</a>, mas ainda est&aacute; atr&aacute;s do PyPy.</p>
<p>A vers&atilde;o 0.1 do Pyston est&aacute; dispon&iacute;vel desde 4/2/2014. Por enquanto, &eacute; compat&iacute;vel somente com o Python 2.7, roda somente em plataformas x86_64 e foi testado somente no Ubuntu. Contudo, a compatibilidade com outras plataformas e com o Python 3 est&aacute; planejada para o futuro.</p>
<p>Para a vers&atilde;o 0.2, est&aacute; planejada a implementa&ccedil;&atilde;o dos seguintes recursos:</p>
<pre>
 <ul class="c6 lst-kix_5k86ednoiodr-0 start">
  <li>Exce&ccedil;&otilde;es;</li>
  <li>Heran&ccedil;a de classes e metaclasses;</li>
  <li>Argumentos default, keywords, *args e **kwargs;</li>
  <li>Closures;</li>
  <li>Generators;</li>
  <li>Integer promotion.</li>
 </ul></pre>
<p>O c&oacute;digo-fonte e demais informa&ccedil;&otilde;es do projeto est&atilde;o dispon&iacute;veis no <a href="https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fdropbox%2Fpyston&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNEvXmeAamM0PMrhuBi32ZEpPOwzvQ">Github</a> sob a licen&ccedil;a <a href="http://www.google.com/url?q=http%3A%2F%2Fwww.apache.org%2Flicenses%2FLICENSE-2.0&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNFPaSHdvCi6VD7GwgEkKspvD3d_tw">Apache 2.0</a>. Al&eacute;m disso, &eacute; poss&iacute;vel contribuir para o Pyston, basta assinar o <a href="https://www.google.com/url?q=https%3A%2F%2Fopensource.dropbox.com%2Fcla%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNGLNjanQfg3Hq5FT6Kj3lA4-z39zw">Acordo de Licen&ccedil;a de Contribuinte Dropbox</a>. Para acompanhar o progresso do projeto, existe tamb&eacute;m uma <a href="https://docs.google.com/forms/d/123MrTaeD5q2eq-VoJ9uv7OUSvZH-wTkrSPbNLKyTXcg/closedform">lista de not&iacute;cias</a> em que &eacute; poss&iacute;vel se inscrever.</p><br><br><br><br><br><br></body></html>