<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Webix 1.4 Released with WebSocket, IndexedDB, Data and Grid Suggest</h3><p><a href="http://docs.webix.com/desktop__whats_new_1_4.html">Webix 1.4</a> has been released with support for data&nbsp; and grid suggest in addition to WebSocket and IndexedDB. The data-suggest feature enables you to make use of either images or complex HTML content as select options. <br /> <br /> <img _p="true" _href="img://1Figure_1_Webix.png" alt="" src="http://www.infoq.com/resource/news/2014/01/webix-1-4/en/resources/1Figure_1_Webix.png" /></p>
<p>On the other hand, grid-suggest provides an ability to select data from a table with support for editing, sorting and filtering.<br /> <br /> <img _p="true" _href="img://Figure_2_Webix.png" alt="" src="http://www.infoq.com/resource/news/2014/01/webix-1-4/en/resources/Figure_2_Webix.png" /></p>
<p>Webix has been updated to provide WebSocket and indexedDB support for the purpose of data loading and saving. The WebSocket protocol enables the server to communicate to client side code when the when the data is changed by some user or some other server side action occurs. Meanwhile, the IndexedDB feature provides ability for your apps to work offline.</p>
<p>The latest release includes improvements in Window Positioning such as the ability to display in fullscreen mode in addition to zindexBase property and onReady event. It also adds autoConfig option including keyboard navigation for list component and improved styling for icon buttons with a data processor that automatically tracks events.</p>
<p>InfoQ had a brief chat with Veronica Lindorenko of xbsoftware to know more about the latest release<br /> <strong><br /> InfoQ: Does the new features work with .NET applications?</strong></p>
<blockquote>
  All client side features are available for all platforms, including .NET. In v1 we are introducing only one non-client side addition - support for web-sockets. It is based on 
 <a href="http://weblogs.asp.net/cibrax/archive/2011/12/12/transform-your-iis-into-a-real-time-pub-sub-engine-with-faye-node.aspx">Faye</a> library which uses nodejs, and while it is not directly .NET compatible, can be used with 
 <a href="http://weblogs.asp.net/cibrax/archive/2011/12/12/transform-your-iis-into-a-real-time-pub-sub-engine-with-faye-node.aspx">IIS</a> and Azure cloud. 
</blockquote>
<p><strong> InfoQ: Can you share with us more information about IndexedDB?</strong></p>
<blockquote>
  IndexDB is an inner database of the browser (supported by all modern browsers, except for Safari). Starting from version 1.4, you can use it the same as server side database for data loading and data saving. It possible to switch between server side database and browser database&nbsp; in one line of code. The main goal of such addition is to improve offline support of an app. When page is offline it can use indexDB for all data operation, and later, when online connection appears, data can be synced with server side database.
 <br type="_moz" /> 
</blockquote><br><br><br><br><br><br></body></html>