<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Fundação Eclipse lança Subsidiária Européia</h3><p>Na EclipseCon 2013 da Europa, a Funda&ccedil;&atilde;o Eclipse <a href="http://eclipse.org/org/press-release/20131029_efe.php">lan&ccedil;ou a Funda&ccedil;&atilde;o Eclipse GmbH Europ&eacute;ia</a>, uma funda&ccedil;&atilde;o subsidi&aacute;ria localizada in Zwingenberg (Hessen), Alemanha. A funda&ccedil;&atilde;o foi criada para promover o apoio para a comunidade open source do Eclipse na Europa.</p>
<p>Com mais de um quarto da comunidade residindo na Europa, no evento anual <a href="http://www.eclipsecon.org/europe2013/">EclipseCon Europa</a> e agora tamb&eacute;m no <a href="http://www.eclipsecon.org/france2013/toulouse">EclipseCon Fran&ccedil;a</a>, uma crescente base da funda&ccedil;&atilde;o precisa de suporte localizado.</p>
<p>Ralph Mueller foi apontado para controlar a dire&ccedil;&atilde;o da nova Funda&ccedil;&atilde;o Eclipse na Europa. Mueller desempenhou um papel muito importante no passado da <a href="https://www.eclipsecon.org/europe2013/past-conferences">EclipseCon Europa</a> (e o evento Eclipse Summit Europa).</p>
<p>Uma <a href="http://eclipse.org/org/press-release/20131029_efe_faq.php">FAQ</a> fala sobre as raz&otilde;es pela qual a Funda&ccedil;&atilde;o Europeia foi criada, incluindo o por que de ser localizada na Alemanha:</p>
<p><strong>Por que ela foi criada na Alemanha?</strong></p>
<blockquote> 
 <p>A resposta mais curta &eacute; por que &eacute; onde o Ralph Mueller mora. Mueller ser&aacute; o diretor da Funda&ccedil;&atilde;o Eclipse Europeia, e ser&aacute; respons&aacute;vel por suas opera&ccedil;&otilde;es. Para aqueles que est&atilde;o acostumados com a comunidade Eclipse na Europa sabe, o Mueller tem liderado a comunidade h&aacute; anos.</p> 
</blockquote>
<p><strong>A Funda&ccedil;&atilde;o Eclipse Europ&eacute;ia &eacute; uma organiza&ccedil;&atilde;o Alem&atilde; sem fins lucrativos?</strong></p>
<blockquote> 
 <p>Falando diretamente, n&atilde;o. A Funda&ccedil;&atilde;o Eclipse Europeia (EFE) &eacute; incorporada como uma GmbH, a qual &eacute; uma forma t&iacute;pica de incorpora&ccedil;&atilde;o para empresa com fins lucrativos na Alemanha. Mas dito isso, n&atilde;o temos a inten&ccedil;&atilde;o de mudar o modelo de neg&oacute;cio da Funda&ccedil;&atilde;o Eclipse e buscar lucros com nossas opera&ccedil;&otilde;es. O EFE ser&aacute; efetivamente operada como uma organiza&ccedil;&atilde;o sem fins lucrativos, dentro dos impostos e regulamenta&ccedil;&otilde;es exigidas pela Alemanha.</p> 
 <p>Olhamos para diversas op&ccedil;&otilde;es, quando est&aacute;vamos trabalhando para criar a EFE, incluindo uma Verein e uma organiza&ccedil;&atilde;o de caridade. Por&eacute;m a aproxima&ccedil;&atilde;o da GmbH foi a aproxima&ccedil;&atilde;o mais efetiva paras as nossas necessidades.</p> 
</blockquote>
<p><strong>Somos Membros de uma Funda&ccedil;&atilde;o Eclipse localizada na Europa. Dever&iacute;amos mudar nossos membros para a Funda&ccedil;&atilde;o Eclipse Europ&eacute;ia? Posso pagar minhas taxas de membro da Funda&ccedil;&atilde;o Eclipse em Euros?</strong></p>
<blockquote> 
 <p>N&atilde;o. Todos os membros continuar&atilde;o sendo mantidos diretamente pela Funda&ccedil;&atilde;o Eclipse, Inc. nos EUA. Por isso, as taxas para membros dever&atilde;o ser pagos em D&oacute;lares Americanos.</p> 
</blockquote>
<p>Al&eacute;m disso, a Funda&ccedil;&atilde;o Eclipse Europeia n&atilde;o hospedar&aacute; projetos, assim como a Canadense ser&aacute; usada para continuar hospedando seus projetos.</p><br><br><br><br><br><br></body></html>