<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>O quanto do Python pode ser escrito em Python?</h3><p><a href="https://plus.google.com/115362263245161504841/about">Brett Cannon</a>, um dos desenvolvedores da linguagem de programa&ccedil;&atilde;o <a href="http://www.python.org/">Python</a> e funcion&aacute;rio do Google, acredita que parte do compilador e a maioria de seus m&oacute;dulos internos podem ser reimplementados em Python puro. Tal ideia &eacute; discutida no artigo &quot;<a href="http://sayspy.blogspot.com.br/2012/12/how-much-of-python-can-be-written-in.html">O quanto de Python pode ser escrito em Python?</a>&quot; publicado no blog que mant&eacute;m sobre a linguagem de programa&ccedil;&atilde;o.</p> 
<p>O ganho em substituir o c&oacute;digo C existente no CPython, como &eacute; apelidado o compilador Python, por c&oacute;digo Python puro seria melhorar sua manutenabilidade e extensibilidade. Cannon apresenta um caso bem sucedido de substitui&ccedil;&atilde;o do c&oacute;digo C:</p> 
<blockquote> 
 <p>Temos agora no Python 3.3 a implementa&ccedil;&atilde;o do <em>import</em> em Python (tecnicamente, o loop de importa&ccedil;&atilde;o principal utilizado continua implementado em C para reduzir o tempo de inicializa&ccedil;&atilde;o em 5%, mas isso &eacute; completamente opcional e equivalente ao c&oacute;digo Python puro remanescente), e gra&ccedil;as ao cache de conte&uacute;do de diret&oacute;rio essa funcionalidade est&aacute;, na verdade, mais r&aacute;pida que a vers&atilde;o em C do Python 3.2. Logo, n&atilde;o &eacute; nada rid&iacute;culo imaginar o quanto poderia ser realizado da ideia de substituir o c&oacute;digo C no CPython com c&oacute;digo Python.</p> 
</blockquote> 
<p>O pr&oacute;prio Cannon come&ccedil;a a imaginar o que poderia ser substitu&iacute;do. Por exemplo, ele sugere que a reimplementa&ccedil;&atilde;o das fun&ccedil;&otilde;es - <em>any()</em>, <em>map()</em> e etc. - e dos demais recursos internos do Python poderia ser feita sem grandes dificuldades. Outra possibilidade seria a reimplementa&ccedil;&atilde;o do analisador sint&aacute;tico do CPython em Python puro. Contudo, essa seria uma op&ccedil;&atilde;o menos trivial, pois o analisador sint&aacute;tico n&atilde;o poderia ser usado para trabalhar com m&oacute;dulos especificados em linha de comando, uma vez que o custo poderia ficar muito alto se a performance n&atilde;o for boa o suficiente. E indo mais a fundo na cadeia do compilador, Cannon tamb&eacute;m considera que as rotinas de deriva&ccedil;&atilde;o da CST (<em>concrete syntax tree</em> ou &aacute;rvore de sintaxe concreta) para AST (<em>abstract syntax tree</em> ou &aacute;rvore de sintaxe abstrata) e de transforma&ccedil;&atilde;o da AST para bytecode<em> </em>seriam boas candidatas &agrave; reimplementa&ccedil;&atilde;o em Python.</p> 
<p>No entanto, Cannon alerta que existem duas restri&ccedil;&otilde;es que devem ser levadas em conta no momento de reescrever as implementa&ccedil;&otilde;es:</p> 
<blockquote> 
 <p>[...] Uma (das restri&ccedil;&otilde;es) &eacute; que o CPython n&atilde;o pode deixar de ser perform&aacute;tico. Sua performance deve ser o mais pr&oacute;xima poss&iacute;vel da implementa&ccedil;&atilde;o em C, a menos que a funcionalidade n&atilde;o seja executada constantemente. A outra restri&ccedil;&atilde;o &eacute; que (a implementa&ccedil;&atilde;o) n&atilde;o pode de modo algum ter depend&ecirc;ncias com a <em>stdlib</em> (a biblioteca padr&atilde;o do Python) nem com outros m&oacute;dulos internos. [...]</p> 
</blockquote> 
<p>Sobre as melhorias desenvolvidas na linguagem pela <a href="http://www.python.org/psf/">Python Software Foundation</a> (PSF), Cannon tamb&eacute;m comenta sobre a <a href="http://python.org/dev/peps/pep-0399/">PEP 399</a> (<em>Python Enhancement Proposal</em> ou Proposta de Melhoria no Python), de sua autoria, que solicita que cada m&oacute;dulo na <em>stdlib</em> que tenha implementa&ccedil;&otilde;es em Python puro e em C (total ou parcialmente) deva ter a parte em C homologada para funcionar como uma substituta da parte em Python quando necess&aacute;rio. E para atender essa PEP, o pr&oacute;prio Cannon abriu o <a href="http://bugs.python.org/issue16651">Chamado 16651</a>, com o intuito de identificar quais os m&oacute;dulos da <em>stdlib</em> que ainda n&atilde;o possuem uma implementa&ccedil;&atilde;o contraparte em Python puro.</p> 
<p>A conclus&atilde;o de Cannon &eacute; que existem diversos pontos onde seria interessante reescrever o CPython em Python puro, entretanto, nem todas elas seriam vi&aacute;veis devido &agrave; restri&ccedil;&atilde;o de performance. Para determinar o que poderia ser reescrito em Python, seria preciso realizar cada reimplementa&ccedil;&atilde;o e, assim, verificar a performance.</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>