<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Especificação JCACHE finalizada</h3><p>A Oracle <a href="https://blogs.oracle.com/theaquarium/entry/jcache_is_final_i_repeat">anunciou este m&ecirc;s</a> que a <a href="https://jcp.org/en/jsr/detail?id=107">especifica&ccedil;&atilde;o JCACHE</a> foi finalizada. Criada em 6 de mar&ccedil;o de 2001 a JSR-107 era a especifica&ccedil;&atilde;o mais antiga ainda aberta. Ap&oacute;s treze anos de evolu&ccedil;&atilde;o e desenvolvimento, a &quot;API Java Cache Temporary&quot; vai trazer uma interface comum para interagir com sistemas de cache.</p>
<p>A Oracle j&aacute; sabia do <a href="https://blogs.oracle.com/reza/entry/java_ee_7_survey_results">alto n&iacute;vel de interesse</a> para o JCACHE ser inclu&iacute;do no lan&ccedil;amento do Java EE 7, mas ap&oacute;s perder &quot;alguns prazos cr&iacute;ticos&quot;, <a href="https://blogs.oracle.com/theaquarium/entry/jcache_to_miss_java_ee">a JSR foi descartada da lista de candidatos</a>. No recente levantamento feito pela Oracle no <a href="https://java.net/downloads/javaee-spec/JavaEE8_Community_Survey_Results.pdf">Java EE 8 survey</a>, aproximadamente dois ter&ccedil;os de todas as respostas expressaram interesse de ter o JCACHE inclu&iacute;do como parte da linguagem na pr&oacute;xima edi&ccedil;&atilde;o Enterprise Edition. Com o an&uacute;ncio da finaliza&ccedil;&atilde;o da especifica&ccedil;&atilde;o, a Oracle fez um an&uacute;ncio informando que o projeto da <a href="https://github.com/jsr107/RI">implementa&ccedil;&atilde;o de refer&ecirc;ncia</a> pode ser utilizado em aplica&ccedil;&otilde;es Java EE 6 ou Java EE 7, sem ter que esperar pelo Java EE 8.</p>
<p>JCACHE fornece um Map-Like API para acesso aos caches, SPIs (Special Peripheral Interface) para spooling caches para persist&ecirc;ncia em disco, uma API para recuperar um named cache e uma API para registrar listeners de eventos. N&atilde;o &eacute;, no entanto, uma estrat&eacute;gia para especificar desalojamento, replica&ccedil;&atilde;o ou transa&ccedil;&otilde;es. O trabalho para definir as caracter&iacute;sticas do sistema de cache est&aacute; sendo feito como parte da <a href="https://jcp.org/en/jsr/detail?id=347">JSR-347-JGRID</a>, para o qual JCACHE &eacute; um precedente e um componente fundamental.</p>
<p>O InfoQ conversou com Ben Cotton, que &eacute; membro da JSR-107 e do grupo de peritos JSR-347, para fazer algumas perguntas sobre JCache e o futuro do cache na JVM:</p>
<p>InfoQ: Por que&nbsp;JCACHE?</p>
<blockquote> 
 <p>JCACHE ser&aacute; para a comunidade Java Caching exatamente o que o JDBC foi para a comunidade Java RDBMS.</p> 
 <p>Isto promete dar ao Java uma API padr&atilde;o com a qual os programadores poder&atilde;o utilizar o JCACHE de forma transparente para opera&ccedil;&atilde;o de dados, independente de sua localidade. Com pontos de jun&ccedil;&otilde;es explic&iacute;tas para Hibernate e JPA L2, n&atilde;o importando se a opera&ccedil;&atilde;o dos dados &eacute; de uma coluna em uma base de dados ou um Map.Entry.&quot;</p> 
</blockquote>
<p>InfoQ: Qual o planejamento para o futuro?</p>
<blockquote> 
 <p>&quot;O suporte transacional tem tido uma alta demanda, por isso estamos trabalhando nisso. Al&eacute;m disso, estamos construindo suporte a intera&ccedil;&atilde;o com o JGRID. Tamb&eacute;m estamos abrindo pontos de acesso para API de opera&ccedil;&atilde;o de dados altamente perform&aacute;ticas conhecidas como &quot;ultra-premium Java locality libraries&quot; (por exemplo, de Peter Lawrey <a href="https://github.com/OpenHFT/HugeCollections/wiki/When-to-use-SharedHashMap">OpenHFT SharedHashMap</a>)&quot;</p> 
</blockquote>
<p>Al&eacute;m da implementa&ccedil;&atilde;o de refer&ecirc;ncia de c&oacute;digo aberto, a especifica&ccedil;&atilde;o JSR-107 est&aacute; dispon&iacute;vel gratuitamente na p&aacute;gina do <a href="https://github.com/jsr107/jsr107spec">projeto no GitHub</a>, incluindo edi&ccedil;&otilde;es e hist&oacute;rico de atualiza&ccedil;&otilde;es.</p><br><br><br><br><br><br></body></html>