<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Polêmica sobre escalabilidade do MongoDB: 100 GB são uma barreira?</h3><p>Um controverso<a href="http://blog.mongodb.org/post/62899600960/scaling-advice-from-mongohq"> post</a> da MongoDB (antiga 10Gen) reacendeu desconfian&ccedil;as da comunidade em rela&ccedil;&atilde;o a tecnologias NoSQL. No texto s&atilde;o apontadas considera&ccedil;&otilde;es relativas &agrave; escalabilidade do MongoDB, especialmente em bases de dados maiores que 100 GB.</p>
<p>A primeira vers&atilde;o do post, criada para divulgar o semin&aacute;rio de Chris Winslett, <a href="http://www.mongohq.com/about">membro</a> do time do Mongo DB, com t&iacute;tulo&quot;Escalabilidade no Mongo DB para banco de dados acima de 100gb&quot;, iniciava com a seguinte afirma&ccedil;&atilde;o:</p>
<blockquote> 
 <p>Ultrapassar os 100GB de dados em uma aplica&ccedil;&atilde;o exige conhecimento profundo sobre a configura&ccedil;&atilde;o e opera&ccedil;&atilde;o do MongoDB.</p> 
</blockquote>
<p>O post foi depois temporariamente retirado do ar, mas sua frase de abertura repercutiu, sendo a principal fonte da pol&ecirc;mica em rela&ccedil;&atilde;o &agrave; escalabilidade do MongoDB. Markus Winand, no<a href="http://use-the-index-luke.com/blog/2013-10-01/mysql-is-to-sql-like-mongodb-to-nosql"> post</a> &quot;MongoDB est&aacute; para NoSQL assim como o MySQL est&aacute; para o SQL: da maneira mais perigosa poss&iacute;vel&quot;, fez a seguinte afirma&ccedil;&atilde;o:</p>
<blockquote> 
 <p>O MongoDB sempre prometeu a &quot;escalabilidade da web&quot;. Mesmo n&atilde;o existindo defini&ccedil;&atilde;o exata sobre o que isso quer dizer, o artigo me deixou com a impress&atilde;o que o MongoDB possui s&eacute;rios problemas de escalabilidade. Acredito que muitos acham que deveria ser simples gerenciar 100 gigabytes no MongoDB. At&eacute; porque atualmente 100GB n&atilde;o s&atilde;o nem mais classificados como Big Data, e podem ser facilmente gerenciados em grande parte dos bancos de dados relacionais.</p> 
</blockquote>
<p>Gwen Shapira, consultor de banco de dados, fez outra afirma&ccedil;&atilde;o pol&ecirc;mica em <a href="https://twitter.com/gwenshap/status/384657881137573888">sua conta</a> do Twitter, estranhando o fato de uma suposta plataforma de Big Data apresentar desafios de escalabilidade em base de dados maiores que 100GB.</p>
<p>Uma <a href="http://jaxenter.com/mongodb-mocked-after-posting-100gb-scaling-checklist-48377.html">nova vers&atilde;o</a> do post da MongoDB apresenta uma introdu&ccedil;&atilde;o mais ponderada ao assunto, afirmando que, em grande parte dos sistemas, &eacute; necess&aacute;rio conhecimento profundo, tanto para constru&ccedil;&atilde;o da aplica&ccedil;&atilde;o quanto pra gest&atilde;o do banco de dados, e que a ado&ccedil;&atilde;o do MongoDB, simplifica os primeiros 100GB da sua aplica&ccedil;&atilde;o. Contudo, a empresa voltou a indicar, de forma mais sutil, que a partir desse limiar a administra&ccedil;&atilde;o da infraestrutura exige conhecimento mais profundo da tecnologia.</p>
<p>Mais detalhes referentes aos desafios - e solu&ccedil;&otilde;es - de escalabilidade enfrentados pelo MongoDB em grandes bases de dados podem ser encontrados no <a href="http://www.mongodb.com/presentations/partner-webinar-scaling-checklist-mongodb-100gb-and-beyond">semin&aacute;rio</a> de Chris Winslett.</p><br><br><br><br><br><br></body></html>