<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>LLVM開発者らがACM Awards 2012 を受賞</h3><p><a target="_blank" href="http://www.infoq.com/news/2013/04/LLVM-ACM-Award-2012;jsessionid=1014FD95709C69ED4C7C975843AECD32"><em>原文(投稿日：2013/04/12)へのリンク</em></a></p> 
<div class="clearer-space">
 &nbsp;
</div> 
<div id="newsContent"> 
 <p>ACMは2012年のコンピューティング技術革新に対する表彰を行った。LLVM開発者らがソフトウェアシステム賞 (Software System Award) などを受賞している。</p> 
 <p><a target="_blank" href="http://www.acm.org/">ACM</a> (Association for Computing Machinery) は，2012年の &quot;コンピュータネットワーク，情報検索，コンピュータ科学教育，マルチエージェントシステム，コンピュータ技術全般，ユーザインターフェース技術における成果&quot; による，&quot;コンピュータ科学が実世界の課題を解決する上で多大な貢献&quot; に対して，<a target="_blank" href="http://www.acm.org/press-room/news-releases/2013/acm-tech-awards-2012">権威ある６つの賞の授与を発表した</a>。</p> 
 <p>その中のひとつである <a target="_blank" href="http://awards.acm.org/software_system/">ソフトウェアシステム賞</a> は，<a target="_blank" href="http://llvm.org/">LLVM Computer Infrastructure</a> プロジェクトによる貢献に対して，<a target="_blank" href="http://awards.acm.org/citation.cfm?id=3453297&amp;srt=year&amp;year=2012&amp;aw=149&amp;ao=SOFTWSYS&amp;yr=2012">Vikram S Adve</a>，<a target="_blank" href="http://awards.acm.org/citation.cfm?id=5756445&amp;srt=year&amp;year=2012&amp;aw=149&amp;ao=SOFTWSYS&amp;yr=2012">Evan Cheng</a>，<a target="_blank" href="http://awards.acm.org/citation.cfm?id=5074762&amp;srt=year&amp;year=2012&amp;aw=149&amp;ao=SOFTWSYS&amp;yr=2012">Chris Lattner</a> の各氏に贈られた。LLVMはプログラム言語のコード解析と変換を行うための汎用的なツールセットで，そのテクノロジはApple, Adobe, AMD, Arxan, AutoESL, Cray, Google, Intel, National Instruments, nVidia, REAL Software, XMOSなどが開発したさまざまな製品に応用されている。2012年12月にリリースされたLLVM 3.2に続き，<a target="_blank" href="http://llvm.org/docs/ReleaseNotes.html#whatsnew">バージョン3.3</a> が近日中にリリースされる予定だ。</p> 
 <p>1983年に始められたACMソフトウェアシステム賞は，これまで数々の有名人に対して贈られている。Dennis Ritchie, Ken Thompson両氏はUNIXで，Alan Kay氏はSmalltalkで，Michael Stonebraker氏はINGRESで，Vinton Cerf氏はTCP/IPで，Tim Berners-Lee氏はWWWで受賞している。その他にも，ここでは <a target="_blank" href="http://en.wikipedia.org/wiki/Software_System_Award">すべてのリスト</a> を紹介できないほど多くの受賞者がいる。</p> 
 <p><a target="_blank" href="http://dl.acm.org/author_page.cfm?id=81100383891">Martin Casado</a> と <a target="_blank" href="http://dl.acm.org/author_page.cfm?id=81100360141">Dina Katabi</a> の両氏はSDN (Software Defined Networking) の開発で，その年の傑出した若手コンピュータ技術者に与えられる <a target="_blank" href="http://awards.acm.org/hopper">グレース・ホッパー賞 (Grace Murray Hopper Award)</a> を受賞した。Casado氏は，ハードウェアベースのネットワークコンピュータを <a target="_blank" href="https://www.google.com/url?sa=t&amp;rct=j&amp;q=&amp;esrc=s&amp;source=web&amp;cd=1&amp;cad=rja&amp;ved=0CEIQFjAA&amp;url=http%3A%2F%2Fwww.openflow.org%2F&amp;ei=rR1oUfKLO8bQtQbHtYH4Bw&amp;usg=AFQjCNFN3iOsrLxBI4a5lMPwiJI5h2lEcQ&amp;sig2=foyCCBH8pzmtlD4eP-mtWg&amp;bvm=bv.45175338,d.Yms">OpenFlow</a> (オープンなAPIのひとつ) と <a target="_blank" href="https://www.google.com/url?sa=t&amp;rct=j&amp;q=&amp;esrc=s&amp;source=web&amp;cd=1&amp;cad=rja&amp;ved=0CDgQFjAA&amp;url=http%3A%2F%2Fopenvswitch.org%2F&amp;ei=3h1oUcb6IoictQby4oDwBA&amp;usg=AFQjCNEMBSVJPRvNp22GmAGIKJ_gnKiRcg&amp;sig2=QQ6btK-1Dx3Ogkx0XC8HnA&amp;bvm=bv.45175338,d.Yms">OpenVswitch</a> スイッチ，SDNコントローラの NOX と ONIX を使ってソフトウェアで実現した功績を評価された。一方のDina Katabi氏は，新しいアプローチを採用したネットワーク輻輳制御の設計を通じて重要な貢献をしている。</p> 
 <p>Andrei Broder, Moses Charikar, Piotr Indyk の各氏は，大規模データベースで類似したエントリを検索する <a target="_blank" href="http://en.wikipedia.org/wiki/Locality-sensitive_hashing">LSH (Locally-Sensitive Hashing)</a> アルゴリズムによって <a target="_blank" href="http://awards.acm.org/kanellakis">パリス・カネラキス実践的理論賞 (Paris Kanellakis Theory and Practice Award)</a> を受賞した。</p> 
 <p><a target="_blank" href="http://portal.acm.org/author_page.cfm?id=81325489795">Eric Roberts</a> 氏は，コンピュータ科学教育への貢献で <a target="_blank" href="http://awards.acm.org/homepage.cfm?awd=142">カール・カールストローム教育賞 (Karl V. Karlstrom Outstanding Educator Award)</a> を受賞した。<a target="_blank" href="http://dl.acm.org/citation.cfm?id=1076609&amp;coll=DL&amp;dl=GUIDE">Thinking Recursively</a> の著者であるRobert氏は，スタンフォード大学の学部生向けのコンピュータ科学プログラムと，バミューダの公立高校のためのコンピュータ用カリキュラムを開発している。</p> 
 <p>Yoav Shoham 氏とMoshe Tennenholtz氏は <a target="_blank" href="http://awards.acm.org/newell/">アレン・ニューウェル賞 (ACM/AAAI Allen Newell Award)</a> を受賞した。”コンピュータ科学，ゲーム理論，経済学にわたるマルチエージェントシステム&quot; への貢献が認められたものだ。Shoham氏は &quot;分散マルチエージェントシステムを特徴付ける方法論&quot; の，Tenneholtz氏は &quot;意思決定者間の相互作用をコンピュータで表現するための設計・解析への各種アプローチ&quot; の先駆者だ。Tennenholtz氏はさらに，環境との相互作用によって学習するアルゴリズムであるRMaxの開発者でもある。</p> 
 <p>Thomas Bartoschek, Johannes Sch&ouml;ning両氏は，&quot;学校の地理情報科学 (Geoinformatics at School, GI<img alt="" width="12" height="12" src="http://www.infoq.com/mag4media/repositories/fs/news/2013/04/LLVM-ACM-Award-2012/ja/resources/at-sign_arial_12px.gif;jsessionid=90C611FDEEBFB741768E10F2A69E70F4;jsessionid=1014FD95709C69ED4C7C975843AECD32" _href="img://at-sign_arial_12px.gif;jsessionid=90C611FDEEBFB741768E10F2A69E70F4" _p="true" />School)&quot; で <a target="_blank" href="http://awards.acm.org/lawler">ユージン.L.ローラ賞 (Eugene L. Lawler Award)</a> を受賞した。これは学生が &quot;地理情報とユーザインターフェース技術によって自らのコミュニティにおける問題解決を図る&quot; ことを可能にするプログラムだ。</p> 
 <p id="lastElm">&nbsp;</p> 
</div> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>