<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>DevOps採用の文化的問題</h3><p><a target="_blank" href="http://www.infoq.com/news/2014/02/devops-adoption-difficulties"><em>原文(投稿日：2014/02/03)へのリンク</em></a></p>
<div class="article_page_left news_container text_content_container"> 
 <div class="text_info"> 
  <p><a href="http://zeroturnaround.com/rebellabs">RebelLabs</a>を率いる<a href="http://zeroturnaround.com/author/oliver/">Oliver White</a>氏が<a href="http://zeroturnaround.com/rebellabs/why-your-organization-hates-devops-and-wont-implement-it-this-year-again/">先日の記事</a>で，DevOpsのメリットを明確に示す調査結果があるにも関わらず，IT組織のDevOps採用が困難であることを詳説している。InfoQは氏にインタビューするとともに，この問題に関する調査報告を再検討した。</p> 
  <p>氏とのインタビューは，DevOpsによる明らかな改善効果の存在を示唆した<a href="http://zeroturnaround.com/rebellabs/rebel-labs-release-it-ops-devops-productivity-report-2013/">2013年のRebelLabsのレポート</a>の話題で始まった。レポートの内容は，同じトピックを取り上げた<a href="https://puppetlabs.com/2013-state-of-devops-infographic">PupperLabsの &quot;2013 State of DevOps&quot;</a>や，あるいは<a href="http://www.informationweek.com/strategic-cio/executive-insights-and-innovation/state-of-devops-big-gains-elusive/d/d-id/1113307">InformationWeek</a>の調査結果とも概ね一致する。それらすべてが達した結論は，DevOpsはITシステムをより堅牢にするのみならず，迅速かつ頻繁なデプロイメントとの親和性もある，というものだ。</p> 
  <p>その一方で，昨年10月に実施されながら最近になって公表されたInformationWeekのDevOpsに関する調査報告では，DevOpsについて認識しているものは調査対象の75%，すでに実施しているものはわずか21%に過ぎない，という結果が出ている。RebelLabsの調査でも，DevOpsを活用しているのは全体の20%に過ぎなかったが，65%が重要なイニシアティブとして議論中であると回答している。これらの報告は，回答者の63%がDevOpsを運用中と報告したState of DevOpsによる調査とは対照的なものだ。ただし，これらの数字が相反しているとは言い切れない。DevOpsの採用ということ自体がイエス/ノーで回答できるものではない，という事情のある上に，いずれの調査においても，組織がDevOpsを具現化するために満たすべき基準を明確に定義できていないからだ。</p> 
  <p>DevOpsの採用には文化的な障壁が高い，と氏は見ている。&quot;DevOpsの掲げる進歩的理想は恥ずかしいほど単純なものです – そのために人々は，こんな簡単なこともできないのならば，何もかもがめちゃくちゃなのだから，もう打つ手はない，と思ってしまうのです。&quot;</p> 
  <p>InformationWeekの調査も同じく，DevOps活動の成功を阻害しかねない，いくつかの認識を思わせる – &quot;DevOpsを採用している技術プロ中で，セキュリティ向上を期待しているのは45%のみ，良否とも大きな影響はないと答えたのが32%，IT運用のセキュアを損なうという回答は7%です。&quot; 同じInformationWeekの記事ではMichael Davis氏が，従来型のIT組織が直面するかも知れない，別の困難さを指摘している – &quot;例えばWeb企業は膨大なコード変更を行いますが，アプリケーションの数はわずかです – 企業内のIT部門の多くが，迷路のようなレガシアプリの中で，変更を可能な限り少なくしようと努力するのとは対象的です。(...) 多分1980年代のシステムがあって，「ここにドラゴンがいる」といったソフトウェアドキュメントがあるのでしょう。システムがどうやって動いているのか，誰にも分かりません。いきおい，コードに手を出すな，という考え方になるのです。&quot;</p> 
  <p>DevOpsの採用を容易にするためには，どうやって文化的障壁を克服すればよいのだろうか。氏は次のように答えてくれた。</p> 
  <blockquote>
   スタートになるのは，目標を念頭においた現実的なロードマップを設定することでしょう。 その時点で &quot;100%のDevOps化&quot; を目標にする必要はないと思います。もっと抽象的な目標 – チームがお互いに対話し，ともに作業する環境でこそ，DevOpsは実現できるのではないでしょうか？結局のところ，これは保証されたものではないのです。カルシウムの吸収促進にビタミンDを採るようなものです。そうしなければ骨折する(あるいは骨粗鬆症になる)可能性は高くなるかもしれませんが，そうすれば骨が決して折れない，という訳でもありません - 多少可能性が低くなる程度です。DevOpsは万能ではありませんが，後押しにはなります。DevOpsはサプリメント以上だが万能薬ではない，と皆が理解し始めれば，それに従ってDevOpsの採用も簡単になるでしょうし，原則を取り入れることが難しいという認識もなくなっていくと思います。
  </blockquote> 
  <p>RebeLasbが2014年もDevOps調査を行うという保証はないが，氏は &quot;調査の対象として興味深い分野は，組織のDevOpsアプローチ採用を阻害している実際の問題が何なのかについて，実践的，文化的な両面から理解を深めること&quot; だ，と考えている。</p> 
 </div> 
</div><br><br><br><br><br><br></body></html>