<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Apache Solr 4.5: suporte a dados distribuídos customizável e Faceted Multithread</h3><p><img src="http://www.infoq.com/resource/news/2013/10/apache-solr-4.5/pt/resources/image00.jpg" alt="" _href="img://image00.jpg" _p="true" /></p>
<p>&nbsp;</p>
<p><a href="http://lucene.apache.org/solr/">Solr</a> &eacute; uma plataforma de busca NoSQL fornecida em c&oacute;digo livre que faz parte do projeto <a href="http://lucene.apache.org/core/">Apache Lucene</a>. Suas principais caracter&iacute;sticas incluem pesquisa completa em textos estruturados e n&atilde;o estruturados, destaques das informa&ccedil;&otilde;es em formato <a href="http://wiki.apache.org/solr/HighlightingParameters">highlighting</a>, exibi&ccedil;&atilde;o de resultados de uma busca no <a href="http://searchhub.org/2009/09/02/faceted-search-with-solr/">formato faceted</a>, integra&ccedil;&atilde;o com banco de dados, analise em documentos ricos como, por exemplo: DOC, XLS, PDF e MP3, al&eacute;m de permitir a realiza&ccedil;&atilde;o de <a href="http://wiki.apache.org/solr/SpatialSearch">buscas geoespaciais</a>.</p>
<p>Solr tornou-se uma plataforma popular para sites web devido a sua capacidade de indexar e fazer buscas em muitas fontes ao mesmo tempo retornando recomenda&ccedil;&otilde;es para conte&uacute;do baseado na <a href="http://pt.wikipedia.org/wiki/Taxonomia">taxonomia</a> da busca. &Eacute; utilizado por muitas empresas por permitir a indexa&ccedil;&atilde;o de documentos anexados em emails por exemplo.</p>
<p>Solr trabalha com HTTP e XML e oferece APIs pata v&aacute;rias linguagens de programa&ccedil;&atilde;o como, por exemplo: <a href="http://wiki.apache.org/solr/SolJSON">JSON</a>, <a href="http://wiki.apache.org/solr/SolPython">Python</a>, <a href="http://rubygems.org/gems/rsolr">Ruby</a> e <a href="http://code.google.com/p/solrnet/">.NET</a>.</p>
<p>No inicio de outubro a vers&atilde;o 4.5 foi lan&ccedil;ada e traz entre novos recursos, a possibilidade de fazer consultas em dados distribu&iacute;dos (sharding) de forma customiz&aacute;vel inclusive por campo, faceted em formato multithread, a classe <a href="http://lucene.apache.org/solr/4_5_0/solr-solrj/org/apache/solr/client/solrj/impl/CloudSolrServer.html">CloudSolrServer</a> &eacute; capaz de endere&ccedil;ar diretamente o n&oacute; l&iacute;der no cen&aacute;rio com dados distribu&iacute;dos provendo toler&acirc;ncia a falhas para os dados e seus &iacute;ndices. Entre os principais destaques desta nova vers&atilde;o est&atilde;o:</p>
<ul class="c6 lst-kix_peb2kw6ucqn-0 start"> 
 <li>Suporte customizado para dados distribu&iacute;dos (<a href="http://wiki.apache.org/solr/DistributedSearch">sharding</a>) incluindo a habilidade de realizar a distribui&ccedil;&atilde;o de dados por campo;</li> 
 <li>Melhorias no campo <a href="http://wiki.apache.org/solr/DocValues">DocValue</a> que agora n&atilde;o necessita mais de um valor padr&atilde;o e permite que campos do tipo <a href="https://cwiki.apache.org/confluence/display/solr/Dynamic+Fields">dynamicFields</a> aceite os <a href="http://wiki.apache.org/solr/DocValues#Lucene.27s_DocValues_types">tipos Doc</a>. Essas melhorias tamb&eacute;m permitem que a configura&ccedil;&atilde;o dos valores dos atributos sortMissingFirst e sortMissingLast sejam interpretados durante a busca para os tipos DocValue;</li> 
 <li>Possibilidade de armazenar o arquivo solr.xml no servidor <a href="http://zookeeper.apache.org/">Apache ZooKeeper</a>;</li> 
 <li>A classe <a href="http://lucene.apache.org/solr/4_5_0/solr-solrj/org/apache/solr/client/solrj/impl/CloudSolrServer.html">CloudSolrServer</a> agora permite que as atualiza&ccedil;&otilde;es de rotas sejam realizadas diretamente para o n&oacute; l&iacute;der no cen&aacute;rio distribu&iacute;do.</li> 
</ul>
<p>Solr 4.5 possui muitas outras funcionalidades assim como v&aacute;rias corre&ccedil;&otilde;es de bugs e melhorias de desempenho. Conhe&ccedil;a mais sobre o projeto Apache Solr em seu <a href="http://wiki.apache.org/solr/">wiki</a>.</p><br><br><br><br><br><br></body></html>