<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Java ME 8: Liberada a versão final</h3><p>Terrence Barr, diretor de produtos da Oracle, <a href="http://terrencebarr.wordpress.com/2014/04/30/java-me-8-released/">anunciou o lan&ccedil;amento</a> do Java ME 8. Ap&oacute;s dois anos de trabalho, essa vers&atilde;o foi lan&ccedil;ada um m&ecirc;s ap&oacute;s a Java SE 8. Houve um alinhamento das APIs do Java ME 8 com o Java SE 8 e tamb&eacute;m a prepara&ccedil;&atilde;o do Java para a Internet das Coisas e seus desafios em especial relacionados a desempenho, portabilidade e escalabilidade.</p>
<p>Nas palavras de Terrence Barr, o Java ME 8 &quot;fornece uma plataforma de arquitetura extens&iacute;vel e em camadas permitindo a constru&ccedil;&atilde;o de solu&ccedil;&otilde;es de softwares customizados de forma f&aacute;cil e que cobre uma grande diversidade de casos embarcados.&quot;</p>
<p>Essa vers&atilde;o foi criada a partir da especifica&ccedil;&atilde;o <a href="https://jcp.org/en/jsr/detail?id=360">JSR 360</a>&nbsp;<span id="docs-internal-guid-1d69c0db-5cd8-0004-d5b5-290fdbf3451b"><span style="font-size: 16px; font-family: Georgia; vertical-align: baseline; white-space: pre-wrap;">–</span></span>&nbsp;Java ME Connected Limited Device Configuration (CLDC) 8, fornecendo o n&uacute;cleo da JVM e ambiente de execu&ccedil;&atilde;o; e a <a href="https://jcp.org/en/jsr/detail?id=361">JSR 361</a>&nbsp;<span id="docs-internal-guid-1d69c0db-5cd8-0004-d5b5-290fdbf3451b"><span style="font-size: 16px; font-family: Georgia; vertical-align: baseline; white-space: pre-wrap;">–</span></span>&nbsp;Java ME Embedded Profile (MEEP) 8, que define uma avan&ccedil;ada plataforma de aplica&ccedil;&otilde;es. Essa vers&atilde;o veio dois anos depois que a Java Community Process ME foi mesclada com a SE/EE em um &uacute;nico comit&ecirc; executivo da JCP, de acordo com o documento de processos <a href="https://jcp.org/ja/procedures/jcp2_9">JCP 2.9</a>.</p>
<p>Conforme o an&uacute;ncio e a documenta&ccedil;&atilde;o, a lista a seguir apresenta as principais funcionalidades que foram inclu&iacute;das:</p>
<ol start="1"> 
 <li>Alinhamento com o Java 8 para o desenvolvimento eficiente em tr&ecirc;s &aacute;reas chaves, seguindo a portabilidade do c&oacute;digo entre o Java SE e o Java ME: 
  <ul> 
   <li>Funcionalidades da linguagem Java;</li> 
   <li>Bibliotecas e APIs principais;</li> 
   <li>Funcionalidades principais da maquina virtual.</li> 
  </ul> </li> 
 <li>Desenhado para embarcados&nbsp;<span id="docs-internal-guid-1d69c0db-5cd8-0004-d5b5-290fdbf3451b"><span style="font-size: 16px; font-family: Georgia; vertical-align: baseline; white-space: pre-wrap;">–</span></span>&nbsp;continua pequeno e eficiente, compat&iacute;vel com as vers&otilde;es anteriores e desenhado para tratar opera&ccedil;&otilde;es de longos processamentos;</li> 
 <li>Altamente port&aacute;vel e escal&aacute;vel;</li> 
 <li>Consistente entre os dispositivos;</li> 
 <li>Avan&ccedil;ada plataforma de aplica&ccedil;&otilde;es incluindo o modelo &quot;Multiplica&ccedil;&otilde;es&quot; que permite a execu&ccedil;&atilde;o isolada de m&uacute;ltiplas aplica&ccedil;&otilde;es.</li> 
 <li>Servi&ccedil;os de software modularizado;</li> 
 <li>Dom&iacute;nios Multi-Clientes (&quot;particionamento&quot;&nbsp;<span id="docs-internal-guid-1d69c0db-5cd8-0004-d5b5-290fdbf3451b"><span style="font-size: 16px; font-family: Georgia; vertical-align: baseline; white-space: pre-wrap;">–</span></span>&nbsp;pensado para a multi-tenancy exceto nos embarcados);</li> 
 <li>Acesso direto ao hardware do dispositivo&nbsp;<span id="docs-internal-guid-1d69c0db-5cd8-0004-d5b5-290fdbf3451b"><span style="font-size: 16px; font-family: Georgia; vertical-align: baseline; white-space: pre-wrap;">–</span></span>&nbsp;&quot;API de I/O do dispositivo&quot;, deixando as aplica&ccedil;&otilde;es Java com acesso direto independente da plataforma aos perif&eacute;ricos.</li> 
 <li>Compatibilidade com as APIs padr&otilde;es, tal como, I/O de arquivos, servi&ccedil;os web, mensagens wireless e servi&ccedil;os de seguran&ccedil;a;</li> 
 <li>Melhorias nas ferramentas e plugins para embarcados nas IDEs populares.</li> 
</ol>
<p>Ben Evans, Java Champion, disse ao InfoQ.com:</p>
<blockquote>
  &Eacute; otimo ver o Java ME ganhando uma nova vers&atilde;o. H&aacute; muito trabalho para ser feito na &aacute;rea da Internet das Coisas (Internet of Things - IoT)&nbsp;
 <span id="docs-internal-guid-1d69c0db-5cd8-0004-d5b5-290fdbf3451b"><span style="font-size: 16px; font-family: Georgia; vertical-align: baseline; white-space: pre-wrap;">–</span></span>&nbsp;e algo que ajude o Java a se preparar para isso &eacute; uma boa not&iacute;cia. Ainda precisamos fazer mais&nbsp;
 <span id="docs-internal-guid-1d69c0db-5cd8-0004-d5b5-290fdbf3451b"><span style="font-size: 16px; font-family: Georgia; vertical-align: baseline; white-space: pre-wrap;">–</span></span>&nbsp;principalmente nos protocolos de largura de banda ultra-low. Mas isso &eacute; um grande passo pela frente e uma not&iacute;cia muito bem vinda.
</blockquote>
<p>No <a href="http://www.oracle.com/technetwork/java/embedded/overview/javame/index.html">site de refer&ecirc;ncia</a> em Java ME da Oracle &eacute; poss&iacute;vel encontrar uma vis&atilde;o geral de todas as novidades.</p>
<p>Para come&ccedil;ar a desenvolver com o Java ME 8, baixe o <a href="http://www.oracle.com/technetwork/java/javame/javamobile/download/sdk/index.html">Java ME SDK 8</a> da Oracle, junto com o ambiente de emula&ccedil;&atilde;o de dispositivos e a documenta&ccedil;&atilde;o.</p><br><br><br><br><br><br></body></html>