<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Principios SOLID aplicado à modelagem de dados com PostgreSQL</h3><p><a href="http://www.metatrontech.com/about/chris_resume.pdf">Chris Travers</a> recentemente publicou uma s&eacute;rie de artigos intitulados &quot;Construindo Banco de Dados com princ&iacute;pios SOLID&quot;, que explicam diversas id&eacute;ias de como aplicar alguns dos princ&iacute;pios comuns da programa&ccedil;&atilde;o orientada a objetos como o Princ&iacute;pio da Responsabilidade &Uacute;nica, Segrega&ccedil;&atilde;o de Interface e Invers&atilde;o de Depend&ecirc;ncia para melhorar os modelos de dados e c&oacute;digo no banco de dados. Algumas dessas id&eacute;ias podem ser aplicadas parcialmente em qualquer banco de dados relacional, os artigos apresentam cen&aacute;rios que envolvem caracter&iacute;sticas como heran&ccedil;a entre tabelas o qual est&atilde;o dispon&iacute;veis em produtos como o <a href="http://www.postgresql.org/">PostgreSQL</a>.</p> 
<p>No <a href="http://ledgersmbdev.blogspot.in/2013/01/building-solid-databases-single.html">artigo</a> Normaliza&ccedil;&atilde;o e o Princ&iacute;pio de Responsabilidade &Uacute;nica (SRP), Chris explica as semelhan&ccedil;as e diferen&ccedil;as sutis existentes entre modelos de dados e modelos de classes. A normaliza&ccedil;&atilde;o &eacute; normalmente suficiente para reunir a SRP em bancos de dados relacionais puros, por&eacute;m a heran&ccedil;a entre tabelas pode ser usada para gerenciar campos que normalmente ocorrem em mais de uma tabela e que s&atilde;o dependentes de outros campos no banco de dados. Chris Travers exemplifica com a seguinte declara&ccedil;&atilde;o:</p> 
<blockquote> 
 <p>Um exemplo simples em que a composi&ccedil;&atilde;o faz uma grande diferen&ccedil;a &eacute; no gerenciamento de notas. As pessoas desejam anexar notas em qualquer tipo dado existente em um banco de dados e dessa forma n&atilde;o h&aacute; como afirmar que o texto ou o objeto de uma anota&ccedil;&atilde;o &eacute; mutuamente dependente.</p> 
 <p>Uma abordagem t&iacute;pica e puramente relacional &eacute; a de querer ter v&aacute;rias tabelas gerenciadas independentemente ou a de ter uma tabela &uacute;nica global que armazena as notas de todos. E desta forma ter m&uacute;ltiplas jun&ccedil;&otilde;es de tabelas com o objetivo de adicionar depend&ecirc;ncias de jun&ccedil;&otilde;es.</p> 
 <p>Uma abordagem objeto relacional poderia ser a de ter v&aacute;rias tabelas de notas, por&eacute;m que fosse capaz de herdar a estrutura de uma tabela comum como se fosse uma tabela de notas.</p> 
</blockquote> 
<p>O <a href="http://ledgersmbdev.blogspot.in/2013/01/building-solid-databases-openclosed.html">artigo</a> Princ&iacute;pio do Aberto / Fechado tem o objetivo de explicar como deixar o sistema extens&iacute;vel, sem criar extens&otilde;es quebr&aacute;veis quando a vers&atilde;o b&aacute;sica sofre alguma modifica&ccedil;&atilde;o. Novamente, heran&ccedil;a em tabelas pode fornecer um caminho flex&iacute;vel capaz de promover pontos de extens&atilde;o para os modelos de dados - o exemplo apresentado questiona como o <a href="http://pgxn.org/dist/pg_message_queue/">pg_message_queue 0.2</a> pode manusear v&aacute;rios tipos de dados tendo uma tabela separada que suporte cada tipo de dado e todas as heran&ccedil;as que s&atilde;o comuns a uma determinada tabela. Chris fornece tamb&eacute;m um outro exemplo simples que uma API segura &eacute; mantida extens&iacute;vel para o controle da seguran&ccedil;a e ao mesmo tempo est&aacute; fechada para modifica&ccedil;&otilde;es.</p> 
<p>Chris cita no <a href="http://en.wikipedia.org/wiki/Liskov_substitution_principle">artigo</a> Princ&iacute;pio da Substitui&ccedil;&atilde;o de Liskov que este normalmente n&atilde;o &eacute; um problema para banco de dados puramente relacionais por&eacute;m pode ser um problema que surgir&aacute; quando se faz uso de heran&ccedil;a em tabelas. Como exemplo, Chris cita duas tabelas, my_square que herda my_rectangle:</p> 
<pre>
CREATE TABLE my_rectangle ( id serial primary key, height  numeric, width numeric );
CREATE TABLE my_square ( check (height = width) ) INHERITS  (my_rectangle);
</pre> 
<p>ao executar um update na tabela my_rectangle</p> 
<pre>
UPDATE my_rectangle SET height = height * 2
</pre> 
<p>Esta a&ccedil;&atilde;o ir&aacute; causar problemas de integridade referencial na tabela my_square e falhar&aacute;. Formas de lidar com essa anomalia seria a de evitar atualiza&ccedil;&otilde;es completas (manter as linhas imut&aacute;veis) ou usar triggers para excluir linhas da tabela my_square e inserir em my_rectangle sempre que essas atualiza&ccedil;&otilde;es s&atilde;o executadas.</p> 
<p>A <a href="http://en.wikipedia.org/wiki/Interface_segregation_principle">Segrega&ccedil;&atilde;o de Interface</a> quando aplicada a banco de dados envolveria principalmente fun&ccedil;&otilde;es definidas pelo usu&aacute;rio ou stored procedures. Chris as considera como interfaces para dados escondidos e sugere que a fun&ccedil;&atilde;o ideal ou stored procedure teria uma grande consulta com uma l&oacute;gica circundante m&iacute;nima - nada mais que 5 consultas ou um grande n&uacute;mero de par&acirc;metros opcionais poderiam apontar para a complexidade reduz&iacute;vel que deve ser tratada por quebrar em v&aacute;rias fun&ccedil;&otilde;es separadas ou stored procedures, cada um com seu prop&oacute;sito espec&iacute;fico. Mais uma vez, este princ&iacute;pio anda de m&atilde;os dadas com o Princ&iacute;pio da Responsabilidade &Uacute;nica.</p> 
<p>No <a href="http://ledgersmbdev.blogspot.in/2013/02/building-solid-databases-dependency.html">artigo</a> Invers&atilde;o de Depend&ecirc;ncia e Interfaces de BD Robustas, Chris detalha que fechar o v&iacute;nculo entre a l&oacute;gica da aplica&ccedil;&atilde;o e stored procedures pode levar ao vazamento de abstra&ccedil;&otilde;es e sugere algumas potenciais solu&ccedil;&otilde;es. Algumas dessas solu&ccedil;&otilde;es est&atilde;o em fazer uso de algo semelhante a um localizador de padr&otilde;es de servi&ccedil;os, por meio de views ou fun&ccedil;&otilde;es, utilizando tipos de dados customizados ou por meio de gatilhos e notifica&ccedil;&otilde;es.</p> 
<p>A sugest&atilde;o de Chris Travers &eacute; a de observar e estudar as in&uacute;meras op&ccedil;&otilde;es dispon&iacute;veis e projetar o banco de dados como uma aplica&ccedil;&atilde;o que exp&otilde;e uma API devidamente apropriada.</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>