<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Será que o Agile gera projetos suicidas?</h3><p>Na publica&ccedil;&atilde;o recente no blog do Gartner, Thomas Murphy discute sobre o crescimento tendencioso de que projetos &aacute;geis transformem-se em cont&iacute;nuos ciclos suicidas.</p>
<p>Murphy diz que em um projeto cascata de 12 meses as equipes podem ter 10 meses de vida &quot;normal&quot; seguidos de 2 meses infernais &agrave; medida que a press&atilde;o se instala como forma de se cumprir tanto o escopo como as datas irreais.</p>
<p>Em contraste, em um projeto &aacute;gil com itera&ccedil;&otilde;es de duas semanas:</p>
<blockquote> 
 <p>Essa &eacute; uma possibilidade quando temos 26 sprints por ano. Se dois dias &uacute;teis do seu Sprint de 10 dias s&atilde;o suicidas, significa dizer que temos 52 dias por ano contra 40 dias no programa &quot;anualizado&quot;. Um acr&eacute;scimo de 25% em dias suicidas.</p> 
</blockquote>
<p>Murphy prossegue falando sobre a import&acirc;ncia do princ&iacute;pio &aacute;gil de se manter um ritmo sustent&aacute;vel e diz:</p>
<blockquote> 
 <p>A quest&atilde;o &eacute;, o que &eacute; sustent&aacute;vel? Ou&ccedil;o hist&oacute;rias que n&atilde;o soam como se apenas os &uacute;ltimos 2 dias de um sprint fossem uma marcha da morte, na verdade, todo dia parece ser uma marcha da morte. As organiza&ccedil;&otilde;es, ou melhor, as equipes na verdade precisam determinar o que &eacute; sustent&aacute;vel para a equipe. Os limites de trabalho em progresso precisam ser entendidos. Uma rodovia ocupada com 100% de sua capacidade &eacute; um estacionamento a c&eacute;u aberto. N&atilde;o deixe que uma mudan&ccedil;a para o Agile seja uma mudan&ccedil;a para uma corrida sem fim. Empresas globais e dispositivos m&oacute;veis apenas tornam isso uma batalha ainda mais desafiadora.</p> 
</blockquote>
<p>O autor referencia uma s&eacute;rie de postagens que discutem a necessidade de um ritmo sustent&aacute;vel e condi&ccedil;&otilde;es de trabalho realistas, incluindo uma <a href="http://www.bigvisible.com/2013/07/agile-transformation-sustainable-pace/">discuss&atilde;o</a> no blog Big Visible, que aborda como alcan&ccedil;ar a sustentabilidade:</p>
<blockquote> 
 <p>Ao ler literatura sobre o Agile, ou ao conversar com quem pratica a metodologia, muitas vezes ouve-se o termo &quot;ritmo sustent&aacute;vel&quot;. Qualquer pessoa que esteja sobrecarregada pode pensar duas coisas: ritmo sustent&aacute;vel soa maravilhoso, mas imposs&iacute;vel. Ao discutir o termo, muitas pessoas lutam contra a cren&ccedil;a de que o trabalho necess&aacute;rio poderia ser realizado sob essa restri&ccedil;&atilde;o. Alguns pensam que a cria&ccedil;&atilde;o de software e ritmo sustent&aacute;vel s&atilde;o mutuamente exclusivos.</p> 
</blockquote>
<p>Murphy est&aacute; longe de ser o &uacute;nico a escrever sobre esse assunto. No m&ecirc;s passado, <a href="http://www.infoq.com/author/Ben-Linders">Ben Linders</a> publicou uma <a href="http://www.infoq.com/news/2013/08/sustainable-pace-achieve-improve">not&iacute;cia</a> no InfoQ norte-americano falando sobre como atingir um ritmo sustent&aacute;vel.</p><br><br><br><br><br><br></body></html>