<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Líder de segurança da Oracle promete corrigir falhas e melhorar a comunicação</h3><p>Logo ap&oacute;s uma s&eacute;rie de falhas graves de seguran&ccedil;a, o respons&aacute;vel pela seguran&ccedil;a do Java da Oracle, Milton Smith, garante que a empresa est&aacute; atuando para que as falhas sejam corrigidas e para melhorar a comunica&ccedil;&atilde;o com membros da comunidade.</p> 
<p>&quot;O plano para seguran&ccedil;a em Java &eacute; bastante simples&quot;, disse Milton Smith durante uma <a href="http://www.google.com/url?q=http%3A%2F%2Fjava.net%2Fdownloads%2Fjugs%2FJan24_JUGLeaderCall.mp3&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNEcHg31CUkB80dXQZRsvtA2IVtBmw">audioconfer&ecirc;ncia</a> com l&iacute;deres de grupos de usu&aacute;rios Java:</p> 
<blockquote> 
 <p>A prioridade n&uacute;mero um &eacute; corrigir as falhas, e a segunda &eacute; divulgar amplamente os nossos esfor&ccedil;os; n&oacute;s simplesmente n&atilde;o podemos ter um sem o outro. Argumenta&ccedil;&otilde;es e justificativas n&atilde;o v&atilde;o deixar ningu&eacute;m feliz, ou fazer algo por n&oacute;s. O que temos que fazer &eacute; corrigir as falhas no Java.</p> 
</blockquote> 
<p>O foco est&aacute; no Java utilizado no navegador, onde a maioria das falhas de seguran&ccedil;a foram exploradas. Assim como as corre&ccedil;&otilde;es, Milton Smith ressaltou a inclus&atilde;o, no Java 7u10, de um bot&atilde;o slider de n&iacute;veis de seguran&ccedil;a ao painel de controle Java, juntamente com um checkbox que permita aos usu&aacute;rios desabilitar o Java de maneira mais f&aacute;cil. Os engenheiros tamb&eacute;m inclu&iacute;ram uma funcionalidade que garante que nenhum applet execute sem antes avisar os usu&aacute;rios, como uma maneira de prevenir a explora&ccedil;&atilde;o de falhas de seguran&ccedil;a.</p> 
<p>Com rela&ccedil;&atilde;o &agrave; comunica&ccedil;&atilde;o, Milton Smith disse estar atento a uma s&eacute;rie de coisas, e ressaltou a necessidade da Oracle em atingir todos os p&uacute;blicos, desde engenheiros a profissionais de TI operando data centers, e, obviamente embora n&atilde;o mencionado explicitamente, tamb&eacute;m os usu&aacute;rios finais. Ainda ser&aacute; definido exatamente como isso ser&aacute; feito, mas poderia incluir o fornecimento de mais informa&ccedil;&otilde;es aos l&iacute;deres de grupos de usu&aacute;rios, que seriam capazes de disseminar as informa&ccedil;&otilde;es aos membros do grupo, assim como tamb&eacute;m atrav&eacute;s de palestras em eventos e falando com a imprensa. A relut&acirc;ncia da Oracle em responder as quest&otilde;es feitas pela imprensa pode muito bem ter causado algumas das not&iacute;cias &quot;soltas&quot;, o que o Diretor da Gest&atilde;o de Produto do OpenJDK, Donald Smith, e outros mais, criticaram durante a audioconfer&ecirc;ncia.</p> 
<p>Em outro momento da confer&ecirc;ncia, Donald n&atilde;o demonstrou preocupa&ccedil;&atilde;o com o fato da instala&ccedil;&atilde;o da barra de ferramentas Ask demorar 10 minutos. Conforme foi <a href="http://www.infoq.com/news/2013/01/java-foistware;jsessionid=01846C488AC0087A4E10CDAB8D5AE7D6">publicado anteriormente</a>, Andrew Moers, Presidente da Ask Partner Network, disse ao InfoQ: &quot;Isso &eacute; para garantir que as atualiza&ccedil;&otilde;es do JRE sejam carregadas adequadamente sem interferir na performance geral do computador do usu&aacute;rio&quot;. J&aacute; Donald Smith disse apenas:</p> 
<blockquote> 
 <p>Esse seria um exemplo do tipo de informa&ccedil;&atilde;o que eu adoraria compartilhar, com rela&ccedil;&atilde;o ao porque das coisas serem feitas desta maneira. Por&eacute;m eu n&atilde;o pude fazer isso de forma unilateral. Ou&ccedil;o as pessoas, e concordo que, quando se analisa superficialmente a pr&aacute;tica de incluir a instala&ccedil;&atilde;o da barra de ferramentas do Ask, a pergunta que se faz &eacute;: &quot;Por que tem que ser desta maneira?&quot;, e pode ser que nunca tenhamos uma resposta satisfat&oacute;ria, mas espero que em algum momento sejamos capazes de esclarecer do que se trata e por qu&ecirc;.</p> 
</blockquote> 
<p>Parte do desafio que a Oracle enfrenta &eacute; a larga audi&ecirc;ncia que o Java possui: desde usu&aacute;rios dom&eacute;sticos, desenvolvedores, a grandes empresas. Um exemplo do conflito que isto causa surgiu quando os l&iacute;deres de grupos de usu&aacute;rios tamb&eacute;m questionaram se o Java poderia ser atualizado silenciosamente sem alertar o usu&aacute;rio atrav&eacute;s de um mecanismo de atualiza&ccedil;&atilde;o autom&aacute;tica, assim como ocorre nos navegadores Chrome e Firefox. Essa atualiza&ccedil;&atilde;o pode muito bem ser uma funcionalidade desej&aacute;vel pelos usu&aacute;rios finais do Java, por&eacute;m diversas empresas que tem controlado cuidadosamente ambientes desktop podem ser hostis a esta pr&aacute;tica - principalmente quando se aplicar a clusters de servidores executando aplica&ccedil;&otilde;es baseadas em Java. Donald disse:</p> 
<blockquote> 
 <p>Atualmente n&atilde;o h&aacute; planos para faz&ecirc;-lo, mas tamb&eacute;m n&atilde;o h&aacute; planos para n&atilde;o faz&ecirc;-lo, e &eacute; um assunto que est&aacute; em constante discuss&atilde;o. &Eacute; um desafio com certeza: h&aacute; um ecossistema com um longo hist&oacute;rico, que nunca funcionou desta maneira (atualiza&ccedil;&atilde;o autom&aacute;tica), e de repente haveria um grande n&uacute;mero de pessoas questionando, &quot;Como posso desabilitar essa atualiza&ccedil;&atilde;o?&quot;</p> 
</blockquote> 
<p>Milton Smith encerrou a audioconfer&ecirc;ncia ressaltando o quanto a equipe de desenvolvimento do Java aprecia os feedbacks da comunidade atrav&eacute;s da lista de emails - &quot;Todas as mensagens s&atilde;o lidas, encaminhadas e cuidadosamente consideradas&quot;.</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>