<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Wall Street Journal: Enterprises Are Not Ready for DevOps, but May Not Survive Without It</h3><p>Rachel Shannon-Solomon suggests that most enterprises are not ready for DevOps, while Gene Kim says that they must make themselves ready if they want to survive.</p>
<p>Rachel Shannon-Solomon, a venture associate at&nbsp;At Work-Bench, has recently written a blog post for <a href="http://online.wsj.com/">The Wall Street Journal</a> entitled <a href="http://blogs.wsj.com/cio/2014/05/13/devops-is-great-for-startups-but-for-enterprises-it-wont-work-yet/">DevOps Is Great for Startups, but for Enterprises It Won’t Work—Yet</a>, arguing that while DevOps is appealing to startups, there are important stumbling blocks in the path of DevOps adoption within the enterprise. While acknowledging that large companies such as Google and Facebook benefit from implementing DevOps, and that “there is no lack of appetite to experiment with DevOps practices” within “Fortune 500s and specifically financial services firms”, Shannon-Solomon remarks that “there are few true change agents within enterprise IT willing to affect DevOps implementations.” She&nbsp;has come to this conclusion based&nbsp;on “conversations with startup founders, technology incumbents offering DevOps solutions, and technologists within large enterprises.”</p>
<p>Shannon-Solomon brings four arguments to support her position:</p>
<p><strong>Siloed structures and organizational change</strong>. According to Shannon-Solomon, enterprises create siloed structures between teams because that’s how large organizations maximize value results, and one of DevOps’&nbsp;main purpose is to bring those&nbsp;silos down. Sometimes a large company relies on another vendor for operational support, and such vendors “tend to bring their own degree of siloing.” Also, it is expensive for an enterprise to invest into “holistic solutions to facilitate DevOps” after they “invested heavily on integration for existing solutions.”</p>
<p><strong>Buy vs. build. </strong>The tools needed to implement a DevOps culture are lacking. While some of the tools can be provided by vendors and&nbsp;others can be created&nbsp;within the enterprise, a process&nbsp;which takes a long period of time, “there is a marathon of organizational change and restructuring that must occur before such tools could ever be bought or built.”</p>
<p><strong>Vendors of DevOps solutions acknowledge that when selling to the enterprise, they are trying to sell a cultural revolution.</strong> According to Shannon-Solomon, it is hard to introduce DevOps to development teams because</p>
<blockquote> 
 <p>Vendors need to first win over individual developers with the efficiency of their solution, for example, by initially eschewing procurement and offering a sandbox environment directly to developers to test out the environment. …</p> 
 <p>Selling DevOps toolkits to the enterprise means facing the well-documented challenges of navigating procurement and a mindset currently more primed to build than buy DevOps tools.</p> 
</blockquote>
<p><strong>Return on investment</strong>. Shannon-Solomon cites a senior IT professional working at an investment bank saying that his company “has not been very successful at tracking DevOps projects occurring within individual business units using homegrown tools, and any evaluation of a project’s success has been limited to anecdotal assessments and perceived results.”</p>
<p>Shannon-Solomon&nbsp;ends her post wondering “how long will it be until enterprises are forced to accept that they must accelerate their experiments with DevOps” and hoping that “more individual change agents within large organizations may emerge” in the future.</p>
<p>In yet another WSJ blog post entitled <a href="http://blogs.wsj.com/cio/2014/05/22/enterprise-devops-adoption-isnt-mandatory-but-neither-is-survival/">Enterprise DevOps Adoption Isn’t Mandatory — but Neither Is Survival</a>, Gene Kim, a DevOps author and founder of Tripwire, an enterprise security company, argues that a “DevOps transformation is well underway, not just in startups, but in enterprises in all industry verticals and sizes”, offering as examples Nationwide Insurance and&nbsp;BNY Mellon Corp. in the financial services, The Gap Inc. and&nbsp;Macy’s Inc. in retailing, and UK.gov and the&nbsp;US Department of Homeland Security for governmental agencies. He believes that such large companies are embracing DevOps in spite of difficulties because “the business value … is even larger than we thought” and “those not transforming their IT organizations risk being left behind, missing out on one of the most disruptive and innovative periods in technology.”</p>
<p>Kim offers three reasons for DevOps adoption:</p>
<p><strong>The business value of DevOps.</strong> Kim compares the value brought by DevOps with Lean’s, DevOps being the&nbsp;“result of implementing Lean principles to the IT value stream.” To support his view, Kim calls <a href="https://puppetlabs.com/2013-state-of-devops-infographic/">a survey of 4,039 IT organizations</a> pointing to “astonishing levels of performance”:</p>
<blockquote> 
 <p>High performers were doing 8x more frequent production deployments, being performed 8000x faster, with 2x higher success rates, and fixing issues 12x faster when something went wrong.</p> 
</blockquote>
<p><strong>Survival is not mandatory (nor is adopting DevOps).</strong> Acknowledging that DevOps&nbsp;requires major changes within organizations, Kim goes on comparing this with changes needed to implement Lean by manufacturers in the 1980s.</p>
<blockquote> 
 <p>For perspective, consider again the Lean revolution in the 1980s. That revolution wasn’t easy, either.&nbsp;It required changing incentives for plant managers, work center supervisors and even business managers. It required overcoming work center silos, massive levels of training and re-skilling, and an integrated workforce focused on flow, as opposed to units produced.</p> 
</blockquote>
<p>He added that those who “refused to embark on this journey [introducing Lean], and others started but did not have skill or collective will to solve this problem” are those who are “no longer relevant,” practically saying that those who are not ready to do DevOps properly will not survive or will become irrelevant.</p>
<p><strong>Organizations adopting DevOps are reaping the rewards. </strong>According to another DevOps survey of over 9,200, “not only do the IT organizations using DevOps perform better, but more importantly, overall business performance is higher.”</p>
<p>In conclusion, while Shannon-Solomon&nbsp;sees few enterprises ready to embrace DevOps, Kim considers that no matter how hard it is for large companies, they do not have a choice, DevOps being a requisite for survival in the future.</p><br><br><br><br><br><br></body></html>