<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>NetBeans 7.4 agora com suporte ao JDK 8 e Aplicações Web Mobile</h3><p>Depois de apresentado no JavaOne, a Oracle <a href="http://www.oracle.com/us/corporate/press/2041397">lan&ccedil;ou oficialmente</a> o NetBeans 7.4. A nova vers&atilde;o permite que os desenvolvedores trabalhem com as vers&otilde;es pr&eacute;vias do JDK 8, adicionou suporte para a integra&ccedil;&atilde;o do HTML5 com aplica&ccedil;&otilde;es Java EE e fornece ferramentas para o desenvolvimento de aplica&ccedil;&otilde;es m&oacute;veis com o Apache Cordova.</p>
<p>Talvez a nova funcionalidade mais significante do JDK 8 seja a adi&ccedil;&atilde;o das express&otilde;es lambdas como uma maneira alternativa para escrever classes internas an&ocirc;nimas. O NetBeans fornece ferramentas para pesquisar por classes internas an&ocirc;nimas e ferramentas adicionais podem realizar a convers&atilde;o para express&otilde;es lambdas e vice-versa.</p>
<p><img src="http://www.infoq.com/resource/news/2013/11/netbeans41/pt/resources/Netbeans-JDK-8-Preview.jpg" alt="Lambda" _href="img://Netbeans-JDK-8-Preview.jpg" _p="true" /></p>
<p>O JDK 8 tamb&eacute;m introduziu tr&ecirc;s <a href="http://openjdk.java.net/jeps/161">perfis compactos</a>, um sub conjunto de funcionalidades pr&eacute; definidas desenhadas tal como aplica&ccedil;&otilde;es que n&atilde;o necessitam da plataforma inteira para serem publicadas e executadas em pequenos dispositivos. A IDE NetBeans deixa especificar o perfil que a aplica&ccedil;&atilde;o ir&aacute; utilizar. Dicas, analisadores e ferramentas de refatora&ccedil;&atilde;o tamb&eacute;m auxiliam para garantir a conformidade com determinado perfil. Tamb&eacute;m &eacute; poss&iacute;vel trocar entre perfis diferentes instantaneamente atrav&eacute;s da janela de propriedades.</p>
<p>Como o <a href="http://www.jetbrains.com/idea/whatsnew/">IntelliJ IDEA 12</a> j&aacute; fornece o suporte ao JDK 8 e o Eclipse fornece suporte as <a href="http://dev.eclipse.org/mhonarc/lists/eclipse-dev/msg09679.html">vers&otilde;es pr&eacute;vias</a>, est&aacute; claro que o JDK 8 tamb&eacute;m deveria ser suportado da perspectiva da IDE para fora.</p>
<p>O NetBeans fornece um suporte excelente ao HTML5 e continua sendo melhorado. Nessa vers&atilde;o, um auxiliador (wizard) foi adicionado para gerar o front-end com o <a href="http://backbonejs.org/">Backbone.js</a> conectando pela primeira vez com um end-point RESTful de uma aplica&ccedil;&atilde;o Java EE.</p>
<p>O editor de JavaScript do NetBeans foi atualizado para reconhecer os frameworks de JavaScript: <a href="http://angularjs.org/">AngularJS</a>, <a href="http://knockoutjs.com/">Knockout</a> e <a href="http://docs.sencha.com/extjs/4.2.2/">Ext JS</a>. Foi aprimorado o mecanismo de completar c&oacute;digo do JavaScript, com o editor de c&oacute;digo agora conhecendo todos os ids no DOM, bem como os nomes dos modelos do seu JavaScript. Como <a href="http://www.infoq.com/articles/javaone2013-roundup">previamente reportado</a>, o NetBeans tamb&eacute;m recebeu a funcionalidade de &quot;edi&ccedil;&atilde;o ao vivo&quot;. Similar ao plugin LiveEdit do IntelliJ IDEA, os desenvolvedores podem ajustar as propriedades no NetBeans e instantaneamente ser&aacute; refletido no navegador.</p>
<p>Os desenvolvedores web podem usar os pr&eacute;-processadores de arquivos <a href="http://sass-lang.com/">Sass CSS</a> e o <a href="http://lesscss.org/">LESS</a>, para economizar tempo de constru&ccedil;&atilde;o de CSS (Cascading Style Sheets) complexos das aplica&ccedil;&otilde;es.</p>
<p>Na interface m&oacute;vel, o suporte ao <a href="https://cordova.apache.org/">Apache Cordova</a> permite que os desenvolveres gerem aplica&ccedil;&otilde;es nativas para iOS e Android usando JavaScript, HTML e CSS. A IDE tamb&eacute;m fornece emuladores para que o desenvolvedor possa visualizar a apar&ecirc;ncia e comportamento das aplica&ccedil;&otilde;es HTML5 e funcionalidades de edi&ccedil;&atilde;o ao vivo funcionam tanto nos emuladores m&oacute;veis como nos navegadores desktop.</p>
<p>H&aacute; v&aacute;rias outras pequenas melhorias que incluem a integra&ccedil;&atilde;o com as issues do JIRA e do Bugzilla dentro da nova janela de Gerenciamento de Tarefas (Task Management). Tamb&eacute;m &eacute; poss&iacute;vel criar issues de dentro da IDE e trabalhar com elas diretamente do c&oacute;digo.</p>
<p>Para finalizar, o suporte do NetBeans ao Mercurial, Subversion e Git foram aprimorados refinando a diferen&ccedil;a de c&oacute;digo e a reintegra&ccedil;&atilde;o entre branches.</p>
<p>A IDE do NetBeans &eacute; gratuita, o c&oacute;digo fonte da IDE est&aacute; dispon&iacute;vel para Windows, OS X, Oracle Solaris, Oracle Linux e outras distribui&ccedil;&otilde;es Linux. O <a href="https://netbeans.org/downloads/">download</a> est&aacute; dispon&iacute;vel no site. Os usu&aacute;rios de OS X devem ficar cientes que a renderiza&ccedil;&atilde;o de texto do 7.4 parece ser menos claro que no 7.3. Um bug sobre isso <a href="https://netbeans.org/bugzilla/show_bug.cgi?id=216655">foi reportado</a>.</p><br><br><br><br><br><br></body></html>