<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Cocos2D V3 com editor para criação de jogos, recursos de física e portabilidade de iOS para Android</h3><p>Foi <a href="http://www.cocos2d-iphone.org/cocos2d-v3-rc1-release/">liberada</a> a vers&atilde;o Release Candidate do framework <a href="http://www.cocos2d-iphone.org/">Cocos2D</a> V3, que inclui tamb&eacute;m o SpriteBuilder, um editor profissional para criar intera&ccedil;&otilde;es com jogos. A integra&ccedil;&atilde;o com o Chipmunk2D permite desenvolver rapidamente jogos que utilizam f&iacute;sica e suporte &agrave; portabilidade de iOS para Android.</p>
<p>Para a nova vers&atilde;o V3 a equipe do Cocos2D trabalhou focando em facilitar a fase inicial do desenvolvimento tornando as configura&ccedil;&otilde;es mais simples e garantindo que a <a href="http://www.cocos2d-iphone.org/api-ref/3.0-rc1/">documenta&ccedil;&atilde;o</a> fosse adequadamente instalada.</p>
<p>O <a href="http://www.spritebuilder.com/">SpriteBuilder</a>, uma ferramenta de edi&ccedil;&atilde;o para cria&ccedil;&atilde;o r&aacute;pida de jogos 2D nativos para iOS e Android, passa a ter integra&ccedil;&atilde;o com o Cocos2D V3. No site do SpriteBuilder h&aacute; um <a href="http://www.spritebuilder.com/getting-started/">v&iacute;deo explicativo</a> de 6 minutos sobre como a ferramenta pode auxiliar a cria&ccedil;&atilde;o de um jogo.</p>
<p>A partir dessa vers&atilde;o o Cocos2D V3 suporta a integra&ccedil;&atilde;o com o <a href="http://chipmunk-physics.net/">Chipmunk2D</a> para o desenvolvimento de jogos que utilizam f&iacute;sica, como por exemplo para detec&ccedil;&atilde;o de colis&otilde;es. Foi disponibilizado um <a href="http://www.youtube.com/watch?v=z_Sx9N39KHk">v&iacute;deo promocional</a> no qual &eacute; poss&iacute;vel verificar alguns dos recursos fornecidos pelo Chipmunk2D.</p>
<p>Outras funcionalidades adicionadas nessa vers&atilde;o foram:</p>
<ul> 
 <li>Novas a&ccedil;&otilde;es baseadas no toque;</li> 
 <li>Um conjunto completo de componentes de interface gr&aacute;fica;</li> 
 <li>Novas transi&ccedil;&otilde;es de cenas;</li> 
 <li>A&ccedil;&otilde;es refatoradas;</li> 
 <li>Entre outros.</li> 
</ul>
<p>Para mais informa&ccedil;&otilde;es sobre a nova vers&atilde;o V3 do Cocos2D, acesse o <a href="http://www.cocos2d-iphone.org/cocos2d-v3-rc1-release/">post</a> sobre o lan&ccedil;amento da vers&atilde;o Release Candidate ou a p&aacute;gina com as <a href="http://www.cocos2d-iphone.org/download/">notas</a> de libera&ccedil;&atilde;o e download da vers&atilde;o.</p><br><br><br><br><br><br></body></html>