<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Facebook, Google, LinkedIn, and Twitter Want to Make Sure that MySQL Is “Web-Scale”</h3><p>Facebook, Google, LinkedIn, and Twitter have decided to make sure that a relational databases is “web-scale”, so they have put their efforts behind <a href="http://webscalesql.org/">WebScaleSQL</a>, a branch of MySQL 5.6 Community Edition.</p>
<p>MySQL is already used by the above mentioned companies at a web-scale level, but they are facing “similar challenges with the technology”, and they came up with the idea to “create and maintain the common set of changes required to use MySQL and further customize it for our needs, rather than each of us maintaining separate branches,” said Steaphan Greene, Software Engineer at Facebook, in an interview with InfoQ. The project is “open, so everyone in the MySQL community can benefit and contribute to the code,” added Greene.</p>
<p>When asked why MySQL and not MariaDB, Greene said that they “reached a consensus that MySQL-5.6 was the right choice for this, as it has the production-ready features we need to operate at scale, and the features planned for MySQL-5.7 seem like a fitting path forward for us,” but they will “continue to revisit this decision as the ecosystem evolves.”</p>
<p>It is important to note that this is a branch of MySQL 5.6.17 and not a fork, and the changes introduced in&nbsp;WebScaleSQL are going to be pushed back into the trunk as long as “MySQL community releases continue,” according to the <a href="http://webscalesql.org/faq.html">project’s FAQ</a>.</p>
<p>The 4 web-scale companies have collaborated on MySQL for the past few months, setting up an automated framework and a <a href="https://www.facebook.com/l.php?u=https%3A%2F%2Fgithub.com%2Fwebscalesql%2Fwebscalesql-5.6%2Fcommit%2F8b6adf69913226cab5cf8aaf45914e66b812692d&amp;h=yAQE0Aw1N&amp;s=1">suite of stress tests</a> for evaluating proposed changes to the codebase. When a code change is submitted it gets included in the codebase if it useful to at least another company from those participating to the project. Patches specific only to one company are not included.</p>
<p>So far LinkedIn has contributed “some changes to the test framework, suggested improvements and reviewed changes submitted by other members,” told us Davi Arnaut, a LinkedIn engineer.</p>
<p><a href="https://github.com/twitter/mysql/wiki/WebScaleSQL-and-Twitter-MySQL">Twitter has contributed</a> with a <a href="https://github.com/webscalesql/webscalesql-5.6/commit/d086837b5487647b130ce471c45f8c9093e87855">back port of a buffer pool optimization from MySQL 5.7</a>, support for <a href="https://github.com/webscalesql/webscalesql-5.6/commit/5c030170c88b9d30165919e903eb6b5f54246b65">NUMA interleave policy</a>, and a number of fixes.</p>
<p><a href="https://github.com/webscalesql/webscalesql-5.6/commits/webscalesql-5.6.16">All project commits</a> can be tracked on <a href="https://github.com/webscalesql">GitHub’s project</a> page.</p>
<p>For the near future, Facebook intends to contribute an asynchronous client, including “production-tested versions of table, user, and compression statistics,” compression and logical read-ahead.</p>
<p>For the long term future, WebScaleSQL will attempt to address the scalability issues that very large MySQL deployments face as they arrive.</p>
<p>WebScaleSQL will not provide builds but only source code. This allows each of the four companies to download the code, add company-specific patches and optimizations and&nbsp;create the builds as desired.</p><br><br><br><br><br><br></body></html>