<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Jolt Awards 2014: Mobile and Coding Tools</h3><p>Dr. Dobbs has awarded the Jolt Award for Mobile and Coding Tools for 2014.</p>
<p><a href="http://www.drdobbs.com/joltawards/">Dr. Dobb's Journal</a>&nbsp;has recently&nbsp;announced the winners of the <a href="http://www.drdobbs.com/joltawards/jolt-awards-mobile-development-tools/240166387?pgno=1">Jolt Awards for Mobile Development Tools</a>.&nbsp;This award is meant to recognize the best tools for creating mobile applications. This year’s award recognizes the improvements made by cross-platform mobile development tools, noting that if “they continue to close the gap with native applications, they might well become the tool of choice for all development, save the most demanding.”</p>
<p>Anyone could submit a tool for review, and the judges have selected six of them which were deeply reviewed and evaluated, but the methodology used was not disclosed. The winners are:</p>
<p><strong>Jolt Award: <a href="http://xamarin.com/">Xamarin 2.0</a></strong></p>
<p>Xamarin has received the award for “the elegance of this solution and its ability to work with familiar tools to target the principal mobile platforms.” Xamarin lets C# developers to create cross-platform mobile application in Visual Studio or Xamarin Studio, most of the code being independent from the platform it is developed for. Developers need to use Objective-C or Java only for the interface, Xamarin providing a fully native interface for applications, which is considered superior to the HTML5 cross-platform flavor.</p>
<p><font style="FONT-WEIGHT: bold">Jolt Productivity Award: </font><a href="http://phonegap.com/"><font style="FONT-WEIGHT: bold">PhoneGap</font></a></p>
<p>Adobe PhoneGap was awarded for its ability to create cross-platform applications with web technologies&nbsp;–JavaScript, HTML, CSS- for a large collection of mobile platforms -Amazon Fire OS, Android, BlackBerry, iOS, Symbian, Windows Phone, Windows 8.x, and Tizen-.</p>
<p>Among the features that recommended PhoneGap, it was mentioned: the code is open sourced as Apache Cordova, detailed documentation, PhoneGap Build provides automated support for building apps for multiple platforms, and developers need to know only JavaScript to program for many platforms.</p>
<p><font style="FONT-WEIGHT: bold">Jolt Productivity Award: </font><a href="http://www.appcelerator.com/titanium/titanium-studio/"><font style="FONT-WEIGHT: bold">Titanium Studio</font></a></p>
<p>Features that promoted Titanium Studio: ability to target the mobile Web, Android, Blackberry, iOS and Tizen, good integration between Alloy MVC&nbsp;– a framework built on Node.js, supporting Backbone.js and Underscore.js - and Eclipse IDE, good support for the entire development lifecycle, good separation between the interface, business code and data model, ability to test the app in the browser, and usefulness for data and cloud-oriented mobile apps.</p>
<p><font style="FONT-WEIGHT: bold">Finalist: </font><a href="http://coronalabs.com/products/corona-sdk/"><font style="FONT-WEIGHT: bold">Corona SDK</font></a></p>
<p>Corona uses Lua to build graphically intensive apps for Android, iOS, Kindle Fire, and Nook, with support for Windows 8 and WP 8 coming soon. Corona is recommended when one needs to “develop a 2D rich app with an animated UI or a game that needs to interact with the typical Facebook login and some RESTful services.” Other highlighted features: simple interaction with SQLite, good support for in-app purchases and monetization, extensive documentation, fast simulator, ability to call native C++, Objective-C or Java code from Lua (Enterprise edition).</p>
<p><font style="FONT-WEIGHT: bold">Finalist: </font><a href="http://www.sencha.com/products/touch"><font style="FONT-WEIGHT: bold">Sencha Touch 2.3.1</font></a></p>
<p>Sencha Touch was rewarded for its ability to create HTML5 apps for Android, BlackBerry, iOS, Windows 8.x, Windows Phone, and Tizen, having good performance, a large collection of UI controls, icons and themes, MVC, support for Apache Cordova and PhoneGap Build, and its success in “making HTML5 apps look like native apps on mobile devices.”</p>
<p><font style="FONT-WEIGHT: bold">Finalist: </font><a href="http://livecode.com/livecode-6-5/"><font style="FONT-WEIGHT: bold">LiveCode 6.5</font></a></p>
<p>LiveCode was included among finalists for being a RAD tool which provides a simple drag&amp;drop interface for beginner developers wanting to create iOS and Android apps. LiveCode uses a custom English-like scripting language to create cross-platform apps for iOS, Android, Windows, Linux and Mac OS X, but without a native look.</p>
<p>Earlier this year, Dr. Dobb's Journal awarded their prize for the best general <a href="http://www.drdobbs.com/joltawards/jolt-awards-coding-tools/240165725">Coding Tools</a>:</p>
<p><strong>Jolt Award: </strong><a href="http://www.visualstudio.com/products/visual-studio-premium-with-msdn-vs"><strong>Microsoft Visual Studio 2013, Premium Edition</strong></a></p>
<p><strong>Productivity Award: </strong><a href="http://www.jetbrains.com/idea/"><strong>JetBrains IntelliJ IDEA 13 Ultimate Edition</strong></a></p>
<p><strong>Productivity Award: </strong><a href="http://ipython.org/notebook.html"><strong>IPython Notebook</strong></a></p>
<p><strong>Finalist: </strong><a href="https://www.devexpress.com/Products/CodeRush/"><strong>Developer Express CodeRush 13.2</strong></a></p>
<p><strong>Finalist: </strong><a href="http://www.jetbrains.com/resharper/"><strong>JetBrains Resharper 8</strong></a></p>
<p><strong>Finalist: </strong><a href="https://c9.io/"><strong>Cloud9 IDE</strong></a></p>
<p>Dr. Dobb’s has given&nbsp;their Jolt Awards&nbsp;for books and software development tools since 1991. Any&nbsp;software tool&nbsp;can be submitted for evaluation&nbsp;(<a href="http://twimgs.com/ddj/images/article/2011/0811/JoltNomination.pdf">PDF form</a>). Only product release versions are accepted; no alphas, no betas. Nominations need to be made within the time frame specified by the <a href="http://www.drdobbs.com/joltawards/jolt-calendar/229403131">awards calendar</a>.</p><br><br><br><br><br><br></body></html>