<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>データラングリング・アズ・ア・サービスの簡易化を目指すTrifacta</h3><p><a target="_blank" href="http://www.infoq.com/news/2013/12/trifacta-data-wrangling"><em>原文(投稿日：2013/12/30)へのリンク</em></a></p>
<div class="article_page_left news_container text_content_container"> 
 <div class="text_info"> 
  <p>データ解析サービスプラットフォームの<a href="http://www.trifacta.com/">Trifacta</a>は先頃，データアナリストのデータラングリング(Data Wrangring)作業支援という同社の活動を推進するため，VCによる<a href="http://techcrunch.com/2013/12/05/trifacta-raises-12m-for-platform-that-uses-human-and-machine-interactions-to-prepare-data-for-analysis/">出資を受け入れた</a>。目標はデータ収集とクレンジング，マージといった作業を，現在よりはるかに少ない時間と労力で可能にすることだ。</p> 
  <p><a href="http://en.wikipedia.org/wiki/Data_wrangling">データラングリング</a>は従来，どのビッグデータプロジェクトにおいても非常に時間と労力を要する作業だった。現代はさまざまなデータがあふれて入り混じり，データソースの進化によってその特性も常に変化している。NoSQLデータベースはこの問いに対して，<a href="http://hbase.apache.org/">列ベース</a>あるいは<a href="http://www.mongodb.org/">文書ベース</a>などの手法で，ストレージ側からの回答を試み続けている。しかしデータを収集して意味付けするという問題が残ったままだ。</p> 
  <p>Trifactaはこの問題に対して，開発者ではなくユーザ中心の観点からアプローチしている。ビジネスアナリストとデータサイエンティストを対象に，ビジュアル指向の方法でデータセットのクレンジングを可能にするのだ。バークレー大学とスタンフォード大学の研究に基づくこのプラットフォームでは，オペレータとマシンの連携によってデータセットから洞察を抽出することを目指している。</p> 
  <p>ビッグデータからの自動スマートサンプリングとビジュアル化によって，アナリストは，注目すべきパターンを短時間で見つけ出すことができる。そうすればTrifactaが，機械学習アルゴリズムを適用して，取得した情報の再編成と形式化を行う方法を提案してくれる。アナリストはデータセットを情報の論理的集合にグループ化して，それを一歩ずつ正規化した上で，結果を作業工程に従ったユーザフレンドリな方法で視覚化する。最終ステップでは，半ば構造化されたデータセットを形式化することによって，データ全体を一般化する。プラットフォームは，データアナリストがデータ全体を徹底的に変換できるように，ユーザエクスペリエンスを念頭に置いてゼロからデザインされている。データをクレンジングしてデータウェアハウスに格納するために，複雑なパイプラインを開発する必要はない。</p> 
  <p>Trifactaの前身である研究プロジェクトの<a href="http://vis.stanford.edu/wrangler/">DataWrangler</a>とその<a href="http://vis.stanford.edu/papers/wrangler">研究論文</a>がオンラインで公開されている。Trifactaはまだクローズドベータで<a href="http://www.trifacta.com/product/early-access">招待制</a>のデモが計画されているのみだが，どのようなものかを垣間見ることはできる。</p> 
 </div> 
</div><br><br><br><br><br><br></body></html>