<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>A armadilha dos frameworks</h3><p>Robert Martin (Uncle Bob), autor de Clean Code (c&oacute;digo limpo), faz uma <a href="http://blog.8thlight.com/uncle-bob/2014/05/11/FrameworkBound.html">an&aacute;lise</a> sobre os riscos envolvidos na utiliza&ccedil;&atilde;o de frameworks de desenvolvimento. Para Martin, grande parte dos programadores acoplam cedo demais seus sistemas ao c&oacute;digo de frameworks, afetando negativamente o design das aplica&ccedil;&otilde;es:</p>
<blockquote> 
 <p>Comprometer-se com a utiliza&ccedil;&atilde;o de um framework &eacute; algo bastante comum entre as equipes de desenvolvimento. No in&iacute;cio dos projetos, o entusiasmo &eacute; grande e os times deliberadamente acoplam seu c&oacute;digo ao c&oacute;digo dos frameworks, para s&oacute; mais tarde descobrirem que o pr&oacute;prio framework se tornou um empecilho &agrave; evolu&ccedil;&atilde;o de seus sistemas.</p> 
</blockquote>
<p>Martin reconhece que os frameworks lidam com um grande n&uacute;mero de pequenos detalhes, cujo tratamento manual seria muito trabalhoso. Contudo, o autor explica que a utiliza&ccedil;&atilde;o de um framework requer bastante comprometimento, pois deve-se abrir m&atilde;o do controle sobre todos esses detalhes gerenciados pelo framework:</p>
<blockquote> 
 <p>Claro que isso parece ser algo bom e geralmente &eacute;. No entanto, existe uma armadilha &agrave; espera e &eacute; dif&iacute;cil v&ecirc;-la chegando. Antes que voc&ecirc; perceba, se encontrar&aacute; realizando todos os tipos de a&ccedil;&otilde;es antinaturais no seu c&oacute;digo [...] se curvando cada vez mais &agrave;s conven&ccedil;&otilde;es do framework, suas peculiaridades e idiossincrasias.</p> 
</blockquote>
<p>Para Martin, a explica&ccedil;&atilde;o desse problema est&aacute; no fato de que todo esse comprometimento com o framework n&atilde;o &eacute; rec&iacute;proco, uma vez que o pr&oacute;prio framework &eacute; livre para se evoluir em qualquer dire&ccedil;&atilde;o, mesmo que essa dire&ccedil;&atilde;o seja conflitante com as necessidades de sua aplica&ccedil;&atilde;o:</p>
<blockquote> 
 <p>Isso n&atilde;o deveria ser uma surpresa. Frameworks s&atilde;o escritos por pessoas para resolver problemas espec&iacute;ficos. Tais problemas podem ser semelhantes ao seu, mas n&atilde;o s&atilde;o exatamente iguais. &Agrave; medida que os problemas coincidem, o framework pode ser extremamente &uacute;til, mas a partir do momento que os problemas divergem, o framework pode ser um grande empecilho.</p> 
</blockquote>
<p>Martin conclui explicando sua pr&oacute;pria abordagem com rela&ccedil;&atilde;o &agrave; utiliza&ccedil;&atilde;o de frameworks:</p>
<blockquote> 
 <p>Ao longo dos anos, adotei um ceticismo saud&aacute;vel com rela&ccedil;&atilde;o aos frameworks. Embora reconhe&ccedil;a que eles possam ser extremamente &uacute;teis, tamb&eacute;m percebo que existem custos envolvidos.</p> 
</blockquote>
<p>Sua estrat&eacute;gia &eacute; sempre manter frameworks como Spring, Hibernate e Rails ao &quot;alcance das m&atilde;os&quot;, deixando-os atr&aacute;s de certos &quot;limites arquiteturais&quot;, confinando sua utiliza&ccedil;&atilde;o apenas a subsistemas perif&eacute;ricos, sem deixar que afetem as decis&otilde;es arquiteturais de alto n&iacute;vel e as regras de neg&oacute;cio centrais de suas aplica&ccedil;&otilde;es.</p><br><br><br><br><br><br></body></html>