<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Google Espresso: Automatizando os testes de UI do Android nas nuvens</h3><p>O Google abriu o c&oacute;digo fonte do <a href="https://code.google.com/p/android-test-kit/wiki/Espresso">Espresso</a>, um framework de testes automatizado para Android que permite executar testes em m&aacute;quinas x86 na nuvem, em um ambiente multi-thread, resolvendo os problemas de concorr&ecirc;ncia associados aos testes de UI.</p>
<p>Executar testes em dispositivos Android reais demanda muito tempo e &eacute; muito caro, devido ao grande n&uacute;mero e variedade de dispositivos. Uma solu&ccedil;&atilde;o &eacute; executar testes em um emulador, um ambiente controlado que suporta diversas vers&otilde;es do SO, resolu&ccedil;&otilde;es de tela e restri&ccedil;&otilde;es de mem&oacute;ria. Essa abordagem pode ajudar a encontrar muitos bugs no c&oacute;digo, deixando o restante para os testes em dispositivos reais e para testadores humanos.</p>
<p>O problema com os emuladores &eacute; o seu tempo de execu&ccedil;&atilde;o, o gargalo de executar o Android em um emulador de CPU ARM. Para resolver este problema, o Google criou uma vers&atilde;o do Android que executa diretamente em hardware x86 e usa acelera&ccedil;&atilde;o da VM. Outro gargalo &eacute; o tempo de inicializa&ccedil;&atilde;o do Android, que vem sendo resolvido mediante snapshots do SO e sua execu&ccedil;&atilde;o, oferecendo assim o SO desejado e configura&ccedil;&otilde;es das aplica&ccedil;&otilde;es em um curto espa&ccedil;o de tempo. Usando esta abordagem, o Google executou 82 milh&otilde;es de testes Android em mar&ccedil;o deste ano.</p>
<p>Comparando os testes no Nexus 4 versus um emulador, temos um acr&eacute;scimo de 65% de tempo no emulador, em compara&ccedil;&atilde;o ao dispositivo real, para finalizar a execu&ccedil;&atilde;o do teste. Deste modo, parece que um bom emulador pode resolver o problema de testes automatizados. Mas ainda h&aacute; outra pedra no caminho, os testes automatizados utilizam a API Instrumentation do Android, que executa as chamadas em threads diferentes da thread de UI. Ent&atilde;o, testar a interface de usu&aacute;rio de forma autom&aacute;tica pode trazer s&eacute;rios problemas de concorr&ecirc;ncia, resultando na inconsist&ecirc;ncia e inseguran&ccedil;a nos resultados dos testes.</p>
<p>A solu&ccedil;&atilde;o do Google para este problema &eacute; o <a href="https://code.google.com/p/android-test-kit/wiki/Espresso">Espresso</a>, um framework de testes que permite executar testes de UI de forma segura em ambientes multi-thread, e remove muito c&oacute;digo repetitivo associado &agrave; escrita dos testes. O Espresso trabalha com v&aacute;rios dispositivos m&oacute;veis, incluindo telefones, TVs, &oacute;culos inteligentes etc, com diferentes resolu&ccedil;&otilde;es de tela e espa&ccedil;os de mem&oacute;ria, muitas vers&otilde;es da API e diferentes redes. De acordo com a equipe por tr&aacute;s do Espresso, <a href="https://www.youtube.com/watch?v=uHoB0KzQGRg#t=2385">a solu&ccedil;&atilde;o captura cerca de 99% dos bugs</a> no Android e aplica&ccedil;&otilde;es, deixando apenas alguns deles para os testes em dispositivos reais e para pessoas que s&atilde;o testadoras, reduzindo todo o esfor&ccedil;o de teste.</p>
<p>Um exemplo de teste afirmando que uma view n&atilde;o &eacute; exibida, com o Espresso se assemelha ao que segue:</p>
<pre>
onView(withId(R.id.bottom_left)).check(matches(not(isDisplayed())));</pre>
<p>Outros exemplos de testes podem ser encontrados <a href="https://code.google.com/p/android-test-kit/wiki/EspressoSamples">aqui</a>.</p>
<p>Neste momento o Espresso est&aacute; na vers&atilde;o Developer Preview, e &eacute; oferecido no Google Code, mas a ideia &eacute; mov&ecirc;-lo para o Android SDK quando estiver suficientemente maduro e est&aacute;vel. O Espresso &eacute; usado pelo Google para testar mais de 30 de suas pr&oacute;prias aplica&ccedil;&otilde;es, incluindo: G+, Maps e Drive.</p><br><br><br><br><br><br></body></html>