<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Software entregue vs necessidade dos usuários</h3><p>Pela segunda vez em dois anos, a Avon volta atr&aacute;s e cancela um projeto milion&aacute;rio que prometia entregar facilidades e avan&ccedil;os para suas opera&ccedil;&otilde;es.</p>
<p><a href="http://online.wsj.com/news/articles/SB10001424052702303932504579251941619018078">Not&iacute;cia</a> originalmente publicada no Wall Street Journal no final de 2013, relata o caso do cancelamento de um projeto SAP conduzido pela unidade da Avon no Canad&aacute; para construir um novo sistema para gerenciamento de ordens de pagamentos.</p>
<p>Com investimento estimado em 125 milh&otilde;es de d&oacute;lares, a implanta&ccedil;&atilde;o do projeto globalmente foi cancelado por n&atilde;o atender as expectativas dos usu&aacute;rios causando interrup&ccedil;&atilde;o nas opera&ccedil;&otilde;es da empresa.</p>
<p>O colunista <a href="http://www.forbes.com/sites/benkepes/">Ben Kepes</a> <a href="http://www.forbes.com/sites/benkepes/2013/12/17/avons-failed-sap-implementation-a-perfect-example-of-enterprise-it-revolution/">escreveu</a> na Forbes que:</p>
<blockquote> 
 <p>A Avon desistiu do projeto ao perceber que a implanta&ccedil;&atilde;o interrompeu suas opera&ccedil;&otilde;es regulares e apresentou alto &iacute;ndice de rejei&ccedil;&atilde;o devido a dificuldades em utilizar o sistema por seus representantes, o que levou um n&uacute;mero significativo deles a deixarem a empresa.</p> 
</blockquote>
<p>Esta n&atilde;o &eacute; a primeira vez que a Avon sofre uma derrota na implanta&ccedil;&atilde;o de um software. H&aacute; aproximadamente dois anos, suas opera&ccedil;&otilde;es no Brasil sofreram um mesmo processo de desist&ecirc;ncia de globaliza&ccedil;&atilde;o na tentativa de implementar um ERP. A implanta&ccedil;&atilde;o deste ERP iria sustentar o n&uacute;cleo da cadeia de suprimentos e opera&ccedil;&otilde;es financeiras e trouxe enormes desafios para as opera&ccedil;&otilde;es da empresa no Brasil. Diante das dificuldades enfrentadas, o dia D precisou ser adiado v&aacute;rias vezes e como consequ&ecirc;ncia, a implanta&ccedil;&atilde;o global foi cancelada uma vez que a solu&ccedil;&atilde;o n&atilde;o se mostrou aderente &agrave;s necessidades de uso das milhares promotoras Avon no pa&iacute;s.</p>
<p>H&aacute; dois anos, <a href="http://itdecs.com/author/angelicamari/">Angelica Mari</a> publicou na IT Decision um <a href="http://itdecs.com/2011/12/an-insider-view-of-avons-erp-troubles-in-brazil/">artigo</a> explorando as dificuldades na implementa&ccedil;&atilde;o deste ERP no Brasil e conseguiu as seguintes declara&ccedil;&otilde;es de um executivo na Avon:</p>
<blockquote> 
 <p>O projeto t&eacute;cnico foi muito bem estruturado e era de se esperar que uma mudan&ccedil;a cultural fosse necess&aacute;ria para que ele funcionasse, mas para um projeto dessa magnitude &eacute; necess&aacute;rio um patrocinador na alta ger&ecirc;ncia. Assim, mesmo havendo resist&ecirc;ncia &agrave;s mudan&ccedil;as, as coisas seriam feitas com o apoio de cima.</p> 
</blockquote>
<p>Angelica Mari relata em seu artigo que encontrou dentro da Avon pessoas que trabalham no sentido de tornar a empresa um neg&oacute;cio verdadeiramente global e com processos globais, mas h&aacute; tamb&eacute;m pessoas interessadas ​​em manter o status quo e descreveu que:</p>
<blockquote> 
 <p>Os problemas em torno da implanta&ccedil;&atilde;o no Brasil resultaram no grande n&uacute;mero de pessoal de TI deixando a empresa num per&iacute;odo de 18 meses durante o projeto. Na &eacute;poca, foi apurado que havia uma forte desconex&atilde;o em termos de estrat&eacute;gia de TI na empresa, pois um projeto diferente de outro ERP de grande escala, havia sido iniciado com o objetivo de transformar outras &aacute;reas de atendimento ao cliente. Neste novo projeto, a SAP foi escolhida para fornecer os produtos.</p> 
</blockquote>
<h2>Ent&atilde;o o que est&aacute; acontecendo?</h2>
<p>Sistemas de TI corporativos devem tornar as empresas mais eficientes, n&atilde;o arrast&aacute;-las para baixo em um atoleiro de processos e inefici&ecirc;ncia. E certamente n&atilde;o podem resultar no &ecirc;xodo de trabalhadores das empresas que os adotam.</p>
<p>Sendo justo com a SAP e com o outro ERP no Brasil, os problemas destacados nas reportagens citadas n&atilde;o s&atilde;o problemas originados por implanta&ccedil;&otilde;es mal sucedidas dessas duas empresas e suas ferramentas. Muitas empresas, assim como a Avon, sofrem com implanta&ccedil;&otilde;es complexas como por exemplo, o modelo de vendas da Avon que se solidificou mundialmente com a venda porta a porta de suas promotoras por meio de um cat&aacute;logo.</p>
<p>Modelos corporativos complexos e muitas vezes mal interpretados ou com pobre levantamento de requisitos s&atilde;o os respons&aacute;veis por fracassos em projetos grandiosos como os da Avon.</p>
<p>Sobre o texto publicado no Wall Stret Journal, o que deveria soar como um alarme para o departamento de m&iacute;dia da SAP n&atilde;o se efetivou. Um representante da empresa escreveu ao Wall Street Journal que:</p>
<blockquote> 
 <p>Nosso software estava funcionando como projetado, apesar de todos os problemas que tivemos com a implanta&ccedil;&atilde;o do projeto.</p> 
</blockquote>
<p>Segundo o que escreveu Ben Kepes no artigo para o WSJ, este tipo de declara&ccedil;&atilde;o &eacute; um triste indiciamento de fornecedores de TI que consideram conclu&iacute;da uma implanta&ccedil;&atilde;o, mesmo que os usu&aacute;rios finais se recusem a usar o produto funcionando como projetado.</p>
<p>Ao comentar sobre o ocorrido, o analista de ind&uacute;strias <a href="http://www.cloudave.com/author/mkrigsman/">Michael Krigsman</a> colocou de forma sucinta:</p>
<blockquote> 
 <p>Os usu&aacute;rios est&atilde;o aceitando menos porcaria hoje em dia, quando se trata de software. Isso porque o mundo do software de consumo tornou-se f&aacute;cil e simples de usar, e tem treinado os usu&aacute;rios a esperar que o software comercial siga um modelo similar. Se isso n&atilde;o acontecer, as pessoas ser&atilde;o muito menos pacientes do que eram no passado.</p> 
</blockquote>
<p>Muitos argumentos s&atilde;o utilizados pelos fornecedores para justificar suas derrotas. Por&eacute;m, esses projetos fracassaram por falta de uma arquitetura corporativa realmente eficaz, disseminada em toda a empresa e que ao final consiga entregar uma solu&ccedil;&atilde;o aceita por quem realmente a utilizar&aacute;.</p>
<p>H&aacute; uma grande quantidade de novas startups proporcionando a no&ccedil;&atilde;o de &quot;consumo de TI&quot;. Embora essa tend&ecirc;ncia de consumismo de tecnologia seja muitas vezes exagerada, o que n&atilde;o pode ocorrer &eacute; o risco que os fornecedores tradicionais enfrentam se n&atilde;o come&ccedil;arem a tornar suas solu&ccedil;&otilde;es ajustadas em termos de funcionalidades focadas na facilidade de uso.</p>
<h2>Conclus&atilde;o</h2>
<p>As solu&ccedil;&otilde;es tecnol&oacute;gicas n&atilde;o podem mais ser impostas aos usu&aacute;rios, toda uma gera&ccedil;&atilde;o de startups est&atilde;o oferecendo solu&ccedil;&otilde;es que os usu&aacute;rios finais realmente querem usar. Isso &eacute; um fato quando vemos empresas como Whatsapp, Instagram e Waze sendo compradas por quantias milion&aacute;rias devido a sua forte ades&atilde;o por parte dos usu&aacute;rios. Grandes empresas precisam estar sintonizadas com as necessidades de seus usu&aacute;rios e oferecer solu&ccedil;&otilde;es que facilitem seu dia a dia na utiliza&ccedil;&atilde;o de softwares de gest&atilde;o, sejam de que tamanho e popularidade forem.</p><br><br><br><br><br><br></body></html>