<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Windows Phone アプリにバーコードを組み込む</h3><p><a target="_blank" href="http://www.infoq.com/news/2013/03/radbarcode;jsessionid=5FBB6DCD3E39FC6A8E470A6A26B3F2E7"><em>原文(投稿日：2013/03/23)へのリンク</em></a></p> 
<div class="clearer-space">
 &nbsp;
</div> 
<div id="newsContent"> 
 <p><a target="_blank" href="http://www.telerik.com/products/windows-phone/overview/all-controls/barcode.aspx">RadControls for Windows Phone Q1 2013</a> の <a target="_blank" href="http://blogs.telerik.com/blogs/13-03-13/barcode-for-windows-phone---q1-2013">RadBarcode</a> には，QR，UPCA，UPCE，UPCサプリメント2，UPCサプリメント5，POSTNET，PDF417，MSI，EAN8，EAN13，Codabar，93，93 Extended，39，39 Extended，25 ノンインターリーブド，25 インターリーブド，128，128A，128B，128C，11など，さまざまな形式の <a target="_blank" href="http://www.telerik.com/help/windows-phone/radbarcode-barcode-types-description.html">バーコード</a> を生成するコンポーネントが含まれている。</p> 
 <p>例えば999888という値のCodabarバーコードは，以下のコードとXMLネームスペース定義で簡単に生成することができる。</p> 
 <p><code>xmlns:telerikDataViz=&quot;clr-namespace:Telerik.Windows.Controls;assembly=Telerik.Windows.Controls.DataVisualization&quot; </code></p> 
 <p><code>&lt;Border Background=&quot;Gray&quot;</code><br /> <code>VerticalAlignment=&quot;Center&quot;&gt;</code><br /> <code>&lt;telerikDataViz:RadBarcodeCodebar Width=&quot;520&quot;</code><br /> <code>Height=&quot;150&quot;</code><br /> <code>Margin=&quot;30&quot;</code><br /> <code>Text=&quot;999888&quot;/&gt; </code><br /> <code>&lt;/Border&gt; </code><br /> <br /> QR(Quick Response)バーコードもサポートされている。RadBarcodeQRコントロールを使えば次のように生成可能だ。</p> 
 <p><code>&lt;Border Background=&quot;gray&quot;</code><br /> <code>VerticalAlignment=&quot;Center&quot;&gt;</code><br /> <code>&lt;telerikDataViz:RadBarcodeQR Width=&quot;300&quot;</code><br /> <code>Height=&quot;300&quot;</code><br /> <code>Version=&quot;7&quot;</code><br /> <code>Text=&quot;Mark mark@yahoo.com&quot;/&gt;</code><br /> <code>&lt;/Border&gt; </code></p> 
 <p>上のコードではバージョンプロパティとして７を設定しているが，それより上位のバージョンを指定すれば，さらに多くの情報をQRコードにエンコードすることができる。<br /> <br /> 連絡先情報をエンコードするQRコードジェネレータも用意されている。QRスキャナやカメラ付き携帯電話でスキャンして新しい連絡先情報を手軽に登録したり，スマートフォンの起動画面でPINコードとして使用するためのイメージを生成する。<br /> <br /> RadBarcodeでは <a target="_blank" href="http://msdn.microsoft.com/en-us/library/windowsphone/develop/jj207032(v=vs.105).aspx">Windows Phone Wallet</a> 用のショッピングアプリを開発することも可能だ。任意の数値データを業界標準のバーコード形式に変換したり，内蔵の自動入力検証機能を使って，使用した値を任意のバーコード形式の値と比較することもできる。<br /> <br /> その他にもRadControls for Windows Phone Q1 2013には50以上の <a target="_blank" href="http://www.telerik.com/products/windows-phone/overview/all-controls.aspx">コントロール</a> が用意されている。例えばLiveTileHelperコンポーネントでは，アプリケーションにリンクするタイルを生成して，新たに提供されるテンプレートを使った独自のUIElementをコンテントとして配置することが可能だ。</p> 
 <p id="lastElm">&nbsp;</p> 
</div> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>