<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>DataFuがApacheのインキュベーションプロジェクトに</h3><p><a target="_blank" href="http://www.infoq.com/news/2014/02/datafu-asf"><em>原文(投稿日：2014/02/04)へのリンク</em></a></p>
<div class="article_page_left news_container text_content_container"> 
 <div class="text_info"> 
  <p><a href="https://www.linkedin.com/">LinkedIn</a>によるHadoop用ライブラリのコレクション<a href="https://github.com/linkedin/datafu">DataFu</a>プロジェクトが１月第１週，正式に<a href="http://www.apache.org/">Apache Software Foundation(ASF)</a>の<a href="http://datafu.incubator.apache.org/">インキュベーション</a>プロジェクトになった。</p> 
  <p>DataFuは当初Pig用のUDF(User-Defined Function)のコレクションを中心として，2012年1月に開始されたプロジェクトだ。<a href="https://cwiki.apache.org/confluence/display/PIG/PiggyBank">Piggybank</a>など有名なUDFのコレクションに比較すると，分位数計算やサンプリング法といった，データマイニングあるいは統計機能が中心だ。しかし2013年10月には，DataFu <a href="http://datafu.incubator.apache.org/blog/2013/10/03/datafus-hourglass-incremental-data-processing-in-hadoop.html">Hourglass</a>という新しいライブラリがプロジェクトに加わった。Hourglassは，増分データをジョブで処理するためのMapReduce用ライブラリである。通常このような処理は，前回のジョブの状態をHDFS内に保存しておいて，新たな入力を処理するためにそれを使用する，という方法で行われる。どちらのプロジェクトも現在，インキュベータの一部となっている。</p> 
  <p>Apacheのインキュベーションになったのは，DataFuにとって偉業と呼ぶに相応しい。プロジェクトがインキュベーションに受け入れられるには，<a href="http://incubator.apache.org/incubation/Incubation_Policy.html">厳格な調査</a>を通過した上で，投票プロセスを経由しなければならないからだ。DataFuは2012年始めからApacheと関わりを持っていたが，インキュベータとして受け入れられたのは2014年始めになってからだった。インキュベーションにいるApacheプロジェクトの卒業には通常，かなり長い時間を必要とする。プロジェクトのインフラストラクチャ(wiki, メーリングリスト，チュートリアルなど)が完成すれば，DataFuはASFの独立したトッププロジェクトになるか，あるいはHadoopのサブプロジェクトになるだろう。</p> 
  <p>Apacheインキュベータに採用されたDataFuには，近い将来に向けた拡張計画が目白押しだ。もっとも重要な機能性のひとつは，より広範に採用されるために，UDF用と同じセットを<a href="http://hive.apache.org/">Hive</a>や<a href="https://crunch.apache.org/">Crunch</a>に対しても用意することである。その一環として，プロジェクトのビルドシステムを，DataFuコミュニティが<a href="https://issues.apache.org/jira/browse/DATAFU-27">現在開発中</a>である<a href="http://www.gradle.org/">Gradke</a>に移行する作業が進行中だ。<a href="http://ant.apache.org/">Ant</a>からGradleに切り替えることで，新機能の追加プロセスがより簡単になり，DataFuコミュニティの統合がさらに促進されると期待できる。</p> 
  <p>DataFuコミュティは小規模ながら，着実に拡大している。Russell Jurney氏による先日のコントリビューションによって，<a href="http://opennlp.apache.org/">Open NLP</a>プロジェクトがDataFu 1.3.0の一部として提供されるようになった。メーリングリストでの話題の中心は，UDFをさらに追加して，DataFuを“ビッグデータのWD-40(米国で一般的な潤滑スプレー)”にすることだ，とコントリビュータのMatthew Hayes，Sam Shah両氏は述べている。</p> 
 </div> 
</div><br><br><br><br><br><br></body></html>