<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>QCon London 2014チュートリアル: リアクティブエクステンション, モバイルデバイス, アジャイル，継続的デリバリ (3月3日〜7日)</h3><p><a target="_blank" href="http://www.infoq.com/news/2014/01/qcon-london-14"><em>原文(投稿日：2014/01/06)へのリンク</em></a></p>
<div class="article_page_left news_container text_content_container"> 
 <div class="text_info"> 
  <p>８年目を迎える<a href="http://qconlondon.com/?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">QCon London (2014年3月3日～7日)</a>では，プログラム言語の先駆者やプロジェクトリーダ，経験豊富な実践者たちが，２日間に渡ってハンズオン・チュートリアルを提供してくれる。QConチュートリアルは各3～6時間で，エンタープライズソフトウェア開発のイノベーションをリードする新しいテクノロジやメソトロジについて詳しく説明する。3日間のカンファレンスが<strong>1月8日</strong>までならば，<strong>236ユーロの割引</strong>で予約することができる。</p> 
  <p>今年は3月3日と4日，次のものを含む15のチュートリアルが実施される。</p> 
  <ul> 
   <li><a href="http://qconlondon.com/london-2014/presentation/Principles%20of%20Reactive%20Programming/?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">Principles of Reactive Programming</a>, <strong>Erik Meijer,</strong> LINQの開発者</li> 
   <li><a href="http://qconlondon.com/london-2014/presentations/show_presentation.jsp?oid=5897&amp;utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">Continuous Delivery</a>, <strong>Dave Farley</strong>, &quot;Continuous Delivery&quot; 共著者</li> 
   <li><a href="http://qconlondon.com/london-2014/presentations/show_presentation.jsp?oid=5899&amp;utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">Creating Android Apps with Xtend</a>, <strong>Sven Efftinge</strong>, Xtext Framework 創設者</li> 
   <li><a href="http://qconlondon.com/london-2014/presentations/show_presentation.jsp?oid=5907&amp;utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">Fast and Beautiful Mobile Apps with Phone Gap</a>, <strong>Brian LeRoux</strong>, PhoneGap プロジェクトリーダ, Adobe</li> 
   <li><a href="http://qconlondon.com/london-2014/presentations/show_presentation.jsp?oid=5904&amp;utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">Problem-solving and Decision-making in Software Development</a>, <strong>Linda Rising</strong>, パターンの女王</li> 
   <li><a href="http://qconlondon.com/london-2014/presentations/show_presentation.jsp?oid=5901&amp;utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">A Fluent API for Java and MongoDB</a>, <strong>Trisha Gee,</strong> ソフトウェア技術者, MongoDB</li> 
   <li><a href="http://qconlondon.com/london-2014/presentations/show_presentation.jsp?oid=5893&amp;utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">Getting the Most out of Your Distributed Team</a>, <strong>Shane Hastie</strong>, InfoQ アジャイル担当リードエディタ, アジャイルコーチ</li> 
   <li><a href="http://qconlondon.com/london-2014/presentations/show_presentation.jsp?oid=5896&amp;utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">Systems Thinking and Methods</a>, <strong>Michael T. Nygard</strong>, &quot;Release IT!&quot; 著者</li> 
   <li><a href="http://qconlondon.com/london-2014/presentations/show_presentation.jsp?oid=5900&amp;utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">Embracing Change: Building Adaptable Software with Events</a>, <strong>Russell Miles</strong>, &quot;Head First Software Development&quot; 共著者</li> 
   <li><a href="http://qconlondon.com/london-2014/presentations/show_presentation.jsp?oid=5898&amp;utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">The Psychological and Cognitive Mechanisms behind Good User Experience</a>, <strong>Janne Jul Jensen</strong>, シニアインタラクションデザイナ兼ユーザビリティスペシャリスト</li> 
  </ul> 
  <p>チュートリアルの完全なリストは<a href="http://qconlondon.com/london-2014/training/?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">こちら</a>。</p> 
  <p>その後に開催される丸３日間のカンファレンスデー(3月5日～7日)では，100人を越える講演者が，Java, ビッグデータ, アジャイル, クラウド, HTML5, モバイル, アーキテクチャなどのトピックをカバーするプレゼンテーションを，15のトラックに渡って実施する。</p> 
  <p>忘れてならないのは<a href="http://qconlondon.com/london-2014/upcomingevents/?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">QCon Nights</a>だ。講演者と参加者がともに参加して盛り上げる，無料のイブニングコミュニティイベントがある。ぜひ参加して，何かを学んで頂きたい。1月15日には，<strong>Elasticsearch Incのソフトウェア技術者であるMark Harwood氏</strong>の講演がある。参加して，<a href="http://qconlondon.com/london-2014/upcomingevents/?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">Elasticsearch 1.0の新機能</a>に関する話を聞いてみてはどうだろう。</p> 
  <p><b>同僚と一緒に参加したい？</b>&nbsp;QCon Londonでは，同一企業から5名以上のグループで登録した場合，特別な割引きが用意されている。<a href="https://secure.trifork.com/london-2014/registration/?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=12042013news">詳細はこちら</a>。</p> 
  <p>昨年のQCon London 2013には1,100人を越える参加者があり，数千のツイート，数百のブログ記事を生み出している。その内容は &quot;<a href="http://www.infoq.com/articles/QCon-London-2013">Key Takeaway Points and Lessons Learned from QCon London 2013</a>&quot; に要約されたとおりだ。読者もぜひ，QCon London 2014に参加してほしい。<strong>1月8日までに登録すれば236ユーロの割引を受けられる。</strong></p> 
  <p>QConはDanish GOTOカンファレンスを主催するTriforkとInfoQ.comの共催で行われる。</p> 
 </div> 
</div><br><br><br><br><br><br></body></html>