<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Lançada versão 2.0 do Slick, biblioteca de mapeamento funcional-relacional para Scala</h3><p>A &uacute;ltima vers&atilde;o do <a href="http://slick.typesafe.com/">Slick</a>, um biblioteca em <a href="http://en.wikipedia.org/wiki/Scala_(programming_language)">Scala</a> para <a href="https://typesafe.com/blog/slick-20-ga-functional-relational-mapping-made-easy">Mapeamento Funcional-Relacional</a>, traz suporte &agrave; engenharia reversa de schemas e uma nova arquitetura do driver que permite suportar bancos de dados n&atilde;o SQL. Mudan&ccedil;as na vers&atilde;o 2.0 lan&ccedil;ada recentemente incluem:</p>
<ul class="c13 lst-kix_zdlqxzsueb42-0 start"> 
 <li>Um gerador de c&oacute;digo para engenharia reversa de schemas do banco de dados, capaz de gerar todo o c&oacute;digo necess&aacute;rio;</li> 
 <li>Uma nova arquitetura para o driver permite suportar bancos de dados n&atilde;o SQL e n&atilde;o JDBC;</li> 
 <li>Para proje&ccedil;&otilde;es com *, foi removido a restri&ccedil;&atilde;o de tuplas planas, permitindo retornar qualquer tipo v&aacute;lido como tipo de retorno de uma <em>Query</em>;</li> 
 <li>Suporte de listas heterog&ecirc;neas para registros de tamanho arbitr&aacute;rio em adi&ccedil;&atilde;o &agrave;s tuplas do Scala;</li> 
 <li>Novo modelo de queries pr&eacute;-compiladas substitui a abstra&ccedil;&atilde;o <em>QueryTemplate.</em></li> 
</ul>
<ul class="c13 lst-kix_cng2bx2703bm-0 start"> 
 <li>Al&eacute;m de pesquisas, consultas pr&eacute;-compiladas podem ser utilizadas para opera&ccedil;&otilde;es de atualiza&ccedil;&atilde;o e remo&ccedil;&atilde;o;</li> 
 <li>Inser&ccedil;&otilde;es suaves tornam-se padr&atilde;o, removendo a necessidade de proje&ccedil;&otilde;es separadas para inser&ccedil;&otilde;es. Assim as colunas com auto-incremento s&atilde;o automaticamente ignoradas na inser&ccedil;&atilde;o quando utilizadas as opera&ccedil;&otilde;es +=<em>,</em> ++=<em>,</em> insert e insertAll. O comportamento anterior ainda &eacute; suportado;</li> 
 <li>Defini&ccedil;&otilde;es de tabelas de sintaxe novas e mais verbosas na API padr&atilde;o do Lifted Embedding para evitar confus&otilde;es nas vers&otilde;es anteriores;</li> 
 <li>Suporte &agrave; convers&otilde;es de Options do lado do servidor. Por exemplo, utilizar o m&eacute;todo <em>getOrElse</em> em colunas Option;</li> 
 <li>Uma funcionalidade experimental que permite agendamento de Query, possibilitando o uso de tabelas de m&uacute;ltiplos bancos de dados em uma &uacute;nica consulta;</li> 
 <li>Um novo modelo para o Activator com o objetivo de simplificar os primeiros passos com o Stick.</li> 
</ul>
<p>Al&eacute;m das atualiza&ccedil;&otilde;es citadas, mais 200 mudan&ccedil;as foram inclu&iacute;das nesta nova atualiza&ccedil;&atilde;o. A equipe tamb&eacute;m atualizou a <a href="http://slick.typesafe.com/doc/2.0.0/">documenta&ccedil;&atilde;o</a>, incluindo o <a href="http://typesafe.com/activator/template/hello-slick">guia de primeiros passos</a>. Essa atualiza&ccedil;&atilde;o n&atilde;o &eacute; retro-compat&iacute;vel e o <a href="http://slick.typesafe.com/doc/2.0.0/migration.html">guia para migra&ccedil;&atilde;o</a> descreve as mudan&ccedil;as da vers&atilde;o 1.0 para 2.0.</p>
<p>O Slick &eacute; uma biblioteca de acesso a banco de dados relacional para a linguagem funcional Scala; semelhante ao <a href="http://en.wikipedia.org/wiki/Object-relational_mapping">Mapeamento Objeto-Relacional</a>, ORM, das linguagens orientadas a objetos, por exemplo, o Hibernate.</p>
<p>Uma <a href="https://groups.google.com/forum/#!forum/scalaquery">lista de e-mail</a> de usu&aacute;rios do Slick est&aacute; dispon&iacute;vel com mais de 700 membros.</p>
<p>O Slick &eacute; um produto open source com uma <a href="https://github.com/slick/slick/blob/master/LICENSE.txt">licen&ccedil;a</a> similar ao BSD. <a href="http://slick.typesafe.com/doc/2.0.0/introduction.html#supported-database-systems">Os sistemas de banco de dados suportados</a> incluem H2, MySQL e PostgreSQL. Drivers para Oracle, IBM DB2 e Microsoft SQL Server est&atilde;o dispon&iacute;veis em uma <a href="http://slick.typesafe.com/doc/2.0.0/extensions.html">extens&atilde;o comercial do Slick</a>.</p><br><br><br><br><br><br></body></html>