<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>O Java 8 resolverá o ‘PermGen OutOfMemoryError’?</h3><p>Como parte do projeto em andamento para mesclar o c&oacute;digo do HotSpot e JRockit, a Oracle anunciou que <a href="https://blogs.oracle.com/java/entry/java_7_questions_answers">ir&aacute; remover a PermGen</a> da JVM HotSpot no Java 8, e muitas pessoas t&ecirc;m interpretado esse an&uacute;ncio como indicativo de que todos os erros de PermGen ir&atilde;o desaparecer. Como impacto da remo&ccedil;&atilde;o da PermGen pode agora ser verificado com os builds do <a href="http://jdk8.java.net/download.html">Java 8 Early Access</a>, pode-se descobrir se todos os problemas foram realmente resolvidos.</p> 
<p>Em 2006, Jon Masamitsu, desenvolvedor da JVM na Oracle, explicou em seu blog o <a href="https://blogs.oracle.com/jonthecollector/entry/presenting_the_permanent_generation">pr&oacute;p&oacute;sito do PermGen</a> (gera&ccedil;&atilde;o permanente): guardar informa&ccedil;&otilde;es sobre as classes Java, como bytecode, nomes e informa&ccedil;&otilde;es do compilador JIT. Essas informa&ccedil;&otilde;es s&atilde;o armazenadas em um espa&ccedil;o reservado porque a maioria &eacute; est&aacute;tica, e a opera&ccedil;&atilde;o do coletor de lixo pode ser muito mais otimizada mantendo a gera&ccedil;&atilde;o permanente separada.</p> 
<p>Muitos desenvolvedores j&aacute; se depararam com o erro &quot;java.lang.OutOfMemoryError: PermGen space&quot; em seus sistemas, o que &eacute; geralmente causado pelo vazamento de mem&oacute;ria em <a href="http://www.infoq.com/br/presentations/classloaders;jsessionid=0C891AA410D8AEA2FD2711871003ADE2">classloaders</a> e &agrave; cria&ccedil;&atilde;o de novos classloaders. Esse vazamento geralmente acontece durante o hot deploy de c&oacute;digo, por isso a ocorr&ecirc;ncia do erro &eacute; mais frequente em ambiente de desenvolvimento do que de produ&ccedil;&atilde;o. Quando ocorre em produ&ccedil;&atilde;o, os desenvolvedores podem analisar o <a href="http://docs.oracle.com/javase/6/docs/technotes/guides/visualvm/heapdump.html">despejo de heap</a> gerado com uma ferramenta como o <a href="http://www.eclipse.org/mat/">Eclipse Memory Analyzer Toolkit</a>, para procurar por classloaders que n&atilde;o deveriam estar mais presentes, mas que por algum motivo ainda est&atilde;o.</p> 
<p>A cole&ccedil;&atilde;o permanente &eacute; coletada, a menos que uma configura&ccedil;&atilde;o espec&iacute;fica o impe&ccedil;a. Entretanto, quando ocorre vazamento de mem&oacute;ria, n&atilde;o h&aacute; nada a ser coletado. Em ambiente de produ&ccedil;&atilde;o o problema mais comum decorre do uso do valor padr&atilde;o da PermGen: 64MB, um tamanho muito baixo. Como forma de remediar esse problema, normalmente se configura o tamanho de 256MB.</p> 
<p>Em seu <a href="http://mail.openjdk.java.net/pipermail/hotspot-dev/2012-September/006679.html">email na lista de desenvolvimento do HotSpot</a>, Jon Masamitsu explica o que ir&aacute; mudar no Java 8 e a remo&ccedil;&atilde;o da PermGen. Algumas partes, como as Strings internas, foram movidas para a heap normal j&aacute; existente no Java 7. No Java 8, as estruturas restantes ser&atilde;o movidas para uma regi&atilde;o de mem&oacute;ria nativa chamada &quot;Metaspace&quot;, que crescer&aacute; automaticamente por padr&atilde;o e ser&aacute; coletada pelo garbage collector. Haver&aacute; duas flags: MetaspaceSize e MaxMetaspaceSize.</p> 
<p>A pedido do InfoQ.com, Jon Masamitsu explicou o objetivo por tr&aacute;s dessa nova arquitetura:</p> 
<blockquote> 
 <p>Um objetivo da remo&ccedil;&atilde;o da PermGen foi para que os usu&aacute;rios n&atilde;o tivessem que se preocupar em dimensionar o tamanho correto dessa &aacute;rea.</p> 
 <p>Configura-se a flag MetaspaceSize para um valor maior que o padr&atilde;o se a aplica&ccedil;&atilde;o precisar de espa&ccedil;o maior para armazenar dados de classes. Isso evita algumas execu&ccedil;&otilde;es do garbage collector durante a inicializa&ccedil;&atilde;o. N&atilde;o h&aacute; necessidade de realizar essa configura&ccedil;&atilde;o a menos que se queira evitar ao m&aacute;ximo a execu&ccedil;&atilde;o do garbage collector.</p> 
 <p>Configura-se a flag MaxMetaspaceSize para limitar o espa&ccedil;o reservado para armazenar os dados de classes. Essa configura&ccedil;&atilde;o pode ser realizada quando existirem suspeitas de vazamento de classloaders e for desej&aacute;vel parar a aplica&ccedil;&atilde;o, antes que consuma excessivamente a mem&oacute;ria nativa. Outro cen&aacute;rio de utiliza&ccedil;&atilde;o ocorre quando h&aacute; m&uacute;ltiplas aplica&ccedil;&otilde;es rodando no mesmo servidor e for desej&aacute;vel limitar a quantidade de espa&ccedil;o que cada aplica&ccedil;&atilde;o usa para armazenar dados de classes.</p> 
</blockquote> 
<p>Assim MetaspaceSize pode afetar as primeiras execu&ccedil;&otilde;es do garbage collector e n&atilde;o deve ser importante na maioria dos casos. Assim se assemelha com a velha flag PermSize.</p> 
<p>Quando a flag MaxMetaspaceSize &eacute; configurada, o espa&ccedil;o reservado ainda pode ficar sem mem&oacute;ria, o que causar&aacute; o erro &quot;java.lang.OutOfMemoryError: Metadata space&quot;. Devido &agrave; possibilidade de vazamentos em classloaders, parece sensato configurar um limite semelhante ao que era configurado com MaxPermSize. De forma parecida com o que acontece no PermGen, o log detalhado do garbage collector (verbose) imprime o consumo atual do Metaspace. Usando as flags PermSize ou MaxPermSize via linha de comando ser&aacute; apresentado um aviso, instruindo o usu&aacute;rio a mudar para as novas flags.</p> 
<p>Como o conceito de Metaspace e PermGen &eacute; na maior parte do tempo o mesmo, um administrador atualizando o Java 7 para Java 8 pode simplesmente mudar as flags executando sed 'e/Perm/Metaspace/g'.</p> 
<p><strong>Conclus&otilde;es</strong></p> 
<p>No geral, essa mudan&ccedil;a parece ser menor do que o esperado. Ao tornar o Metaspace ilimitado por padr&atilde;o, evita-se a defini&ccedil;&atilde;o de uma quantidade de mem&oacute;ria default muito pequena, por&eacute;m ainda ser&aacute; necess&aacute;rio configurar um tamanho m&aacute;ximo para garantir a estabilidade do sistema. Felizmente, &eacute; poss&iacute;vel reusar a configura&ccedil;&atilde;o de PermSize e MaxPermSize, e apenas renomear a flag. Por outro lado, a mudan&ccedil;a de heap gerenciado do Java para mem&oacute;ria nativa significa que h&aacute; muito menos informa&ccedil;&otilde;es &uacute;teis no heap dump para resolver os problemas, assim como foi <a href="http://mail.openjdk.java.net/pipermail/hotspot-dev/2012-September/006684.html">levantado</a> por Kirk Pepperdine. Os vazamentos de classloaders ainda podem acontecer, como antes.</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>