<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Crescente da Programação Reativa</h3><p>A Programa&ccedil;&atilde;o Reativa baseia-se em fluxos de dados e na propaga&ccedil;&atilde;o de mudan&ccedil;as, com o modelo de execu&ccedil;&atilde;o de uma linguagem de programa&ccedil;&atilde;o repercutindo automaticamente altera&ccedil;&otilde;es atrav&eacute;s do fluxo de dados. Com a popularidade de arquiteturas orientadas a eventos, escal&aacute;veis e interativas, tanto do lado do cliente quanto do servidor, o conceito de &quot;reatividade&quot; est&aacute; ganhando cada vez mais aten&ccedil;&atilde;o.</p>
<p><a href="http://www.infoq.com/reactive-extensions/">O InfoQ j&aacute; vem acompanhando esse paradigma h&aacute; alguns anos</a>. Algumas semanas atr&aacute;s o grupo de pesquisa Gartner incluiu os termos &quot;Programa&ccedil;&atilde;o Reativa&quot; e &quot;Web orientada a eventos&quot; em sua publica&ccedil;&atilde;o &quot;<a href="http://www.gartner.com/DisplayDocument?doc_cd=249070">Hype Cycle for Application Development, 2013</a>&quot;, na se&ccedil;&atilde;o &quot;On the rise&quot; (Em crescimento).</p>
<p>Recentemente, <a href="http://www.infoq.com/search.action?queryString=Bruce+Eckel&amp;page=1&amp;searchOrder=">Bruce Eckel</a>, autor de v&aacute;rios livros sobre programa&ccedil;&atilde;o, e <a href="http://www.infoq.com/author/Jonas-Bon%E9r">Jonas Boner</a>, criador do <a href="http://typesafe.com/platform/runtime/akka">Akka</a> e CTO da <a href="http://typesafe.com/">Typesafe</a>, publicaram o &quot;Manifesto Reativo&quot;, o qual visa definir <a href="http://www.reactivemanifesto.org">o que s&atilde;o aplica&ccedil;&otilde;es reativas</a>.</p>
<p>Segundo os autores, essas aplica&ccedil;&otilde;es devem ser capazes de:</p>
<blockquote> 
 <ul class="c7 lst-kix_6fup1fj4yr55-0 start"> 
  <li>Reagir a eventos - a natureza de ser orientada a eventos permite as demais qualidades;</li> 
  <li>Reagir a cargas - foco na escalabilidade ao inv&eacute;s de performance voltada a um usu&aacute;rio apenas;</li> 
  <li>Reagir a falhas - ser resiliente com a capacidade de recupera&ccedil;&atilde;o em todos os n&iacute;veis;</li> 
  <li>Reagir aos usu&aacute;rios - combinar as caracter&iacute;sticas acima para proporcionar uma experi&ecirc;ncia de usu&aacute;rio interativa.</li> 
 </ul> 
</blockquote>
<p>Seguindo a publica&ccedil;&atilde;o desse manifesto, <a href="http://www.infoq.com/search.action?queryString=Martin+Odersky&amp;page=1&amp;searchOrder=">Martin Odersky</a>, criador do Scala, <a href="http://www.infoq.com/author/Erik-Meijer">Erik Meijer</a>, criador do <a href="http://rx.codeplex.com">Reactive Extensions</a> e <a href="http://www.infoq.com/author/Roland-Kuhn">Roland Kuhn</a>, l&iacute;der t&eacute;cnico do Akka, anunciaram um curso gratuito chamado &quot;<a href="https://www.coursera.org/course/reactive">Princ&iacute;pios de Programa&ccedil;&atilde;o Reativa</a>&quot;, no Coursera.</p>
<blockquote> 
 <p>O intuito do curso &eacute; ensinar os princ&iacute;pios de Programa&ccedil;&atilde;o Reativa, uma disciplina emergente que combina sistemas concorrentes, sistemas orientados a eventos e sistemas ass&iacute;ncronos. &Eacute; essencial para a escrita de qualquer sistema distribu&iacute;do ou baseado em web services; tamb&eacute;m &eacute; de extrema import&acirc;ncia para muitos sistemas concorrentes de alto desempenho. A Programa&ccedil;&atilde;o Reativa pode ser vista como uma extens&atilde;o da programa&ccedil;&atilde;o funcional mais abstrata voltada a sistemas concorrentes que lidam com estado distribu&iacute;do, coordenando e orquestrando cadeias de dados ass&iacute;ncronos trocadas pelos atores.</p> 
</blockquote>
<p><a href="http://techblog.netflix.com/2013/01/optimizing-netflix-api.html">Uma empresa que tem utilizado muito a Programa&ccedil;&atilde;o Reativa &eacute; o Netflix</a>. Inclusive contribuiu com o <a href="http://techblog.netflix.com/2013/02/rxjava-netflix-api.html">porte do Rx para o Java</a>:</p>
<blockquote> 
 <p>A Programa&ccedil;&atilde;o Reativa Funcional tem possibilitado aos desenvolvedores do Netflix elevar a concorr&ecirc;ncia do lado do servidor sem as t&iacute;picas preocupa&ccedil;&otilde;es com sincroniza&ccedil;&atilde;o ou <em>thread-safety</em>. A implementa&ccedil;&atilde;o da camada de servi&ccedil;os da API tem total controle sobre os detalhes espec&iacute;ficos da concorr&ecirc;ncia. Isso nos permite procurar cada vez mais por melhorias no desempenho sem o receio de quebrar o c&oacute;digo do cliente. O RxJava &eacute; eficaz no servidor e est&aacute; cada vez mais presente em nosso c&oacute;digo.</p> 
</blockquote>
<p>O Facebook tamb&eacute;m lan&ccedil;ou recentemente a biblioteca <a href="http://facebook.github.io/react/">React JavaScript</a>, para constru&ccedil;&atilde;o de interfaces com usu&aacute;rios sofisticadas. <a href="http://www.linkedin.com/in/stoyanstefanov">Stoyan Stefanov</a>, engenheiro do Facebook, explica <a href="http://www.phpied.com/remarkable-react/">o principal conceito por tr&aacute;s do React</a>:</p>
<blockquote> 
 <p>O React permite construir aplica&ccedil;&otilde;es utilizando componentes capazes de renderizar dados. Quando os dados mudam, os componentes s&atilde;o automaticamente atualizados de maneira muito eficiente e apenas quando necess&aacute;rio. Todo o trabalho de vincular e desvincular gerenciadores de eventos fica por conta do React. Tamb&eacute;m de maneira eficiente - usando delega&ccedil;&atilde;o.</p> 
</blockquote>
<p>A Programa&ccedil;&atilde;o Reativa j&aacute; est&aacute; chamando a aten&ccedil;&atilde;o da comunidade de desenvolvedores de front-end. Tal interesse iniciou no ano de 2009 com o <a href="http://cs.brown.edu/~sk/Publications/Papers/Published/mgbcgbk-flapjax/paper.pdf">paper Flapjax</a> [PDF], e contribuiu com diversas bibliotecas que implementaram os princ&iacute;pios da Programa&ccedil;&atilde;o Reativa, tais como <a href="https://github.com/baconjs/bacon.js">Bacon.js</a>, <a href="http://knockoutjs.com">Knockout</a>, <a href="http://www.meteor.com">Meteor</a>, <a href="http://www.reactjs.com">React.js</a>, <a href="http://yang.github.io/reactive-coffee/">Reactive.coffe</a> e <a href="https://github.com/Reactive-Extensions/RxJS">RxJS</a>.</p>
<p>No QCon de San Francisco de 2013, haver&aacute; uma grande cobertura do paradigma Reativo por toda as tend&ecirc;ncias de TI e inova&ccedil;&atilde;o, tanto em tutoriais e em tracks regulares.</p><br><br><br><br><br><br></body></html>