<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>CQRS Framework Axon 2.1 with Increased Event Handler Support and Performance Improvements</h3><p>The latest version of <a href="http://en.wikipedia.org/wiki/CQRS">CQRS</a> framework <a href="http://www.axonframework.org/">Axon</a> supports annotations and ordering of event handlers together with performance improvements. The recently released <a href="http://blog.trifork.com/2014/02/13/new-in-axon-2-1/">version 2.1</a> also adds compatibility with OSGi. Improvements in this new version includes:</p>
<ul> 
 <li><a href="http://www.rabbitmq.com/confirms.html">Publisher Acknowledgements</a> as an alternative to transactions for increased speed when using the <a href="http://en.wikipedia.org/wiki/Advanced_Message_Queuing_Protocol">AMQP</a> connector, implemented e.g. by <a href="http://www.rabbitmq.com/">RabbitMQ</a>.</li> 
 <li>A more efficient conflict resolution for an aggregate by only loading events describing the conflict and needed for the resolution instead of loading a new instance of the aggregate.</li> 
 <li>New annotations for event handlers to make a clear separation from event listeners.</li> 
 <li>With several handlers for a specific event, the order of invocation of each handler can be specified.</li> 
 <li>Meta data may be attached to an event also during a unit of work, e.g. just before an event is stored and published.</li> 
 <li>When events are replayed a filter can now be applied to remove events not of interest, thus increasing speed by only replaying part of the history.</li> 
 <li>Post-processing on asynchronous event handlers for performing actions after an event is processed.</li> 
 <li>All components delivered by Axon are now compatible with OSGi. Currently no optimizations are provided, but the intention is to include concrete optimizations for OSGi environments in future versions.</li> 
</ul>
<p>The revised <a href="http://www.axonframework.org/docs/2.1/">documentation</a> includes a <a href="http://www.axonframework.org/axon-2-quickstart-guide/">QuickStart</a> Guide with the steps needed to build a simple system based on Axon.</p>
<p>Axon Framework provides the building blocks for systems based on the <a href="http://martinfowler.com/bliki/CQRS.html">CQRS</a> and <a href="http://martinfowler.com/eaaDev/EventSourcing.html">Event Sourcing</a> architectural patterns. The framework was founded by <a href="http://blog.trifork.com/author/allard/">Allard Buijze</a> as an open source product, licensed under the Apache License, Version 2.0, with commercial support as an option.</p>
<p>A <a href="https://groups.google.com/forum/?fromgroups=#!forum/axonframework">forum</a> for Axon users is available with about 250 members and so far around 450 topics. An ongoing discussion about <a href="http://stackoverflow.com/questions/9646884/real-life-experience-with-the-axon-framework">real life experiences</a> reveals both positive and negative feedback.</p><br><br><br><br><br><br></body></html>