<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>リモートからクライアントとサーバのメモリをダンプできてしまう脆弱性Heartbleed</h3><p><a target="_blank" href="http://www.infoq.com/news/2014/04/heartbleed-ssl"><em>原文(投稿日：2014/04/09)へのリンク</em></a></p>
<div class="article_page_left news_container text_content_container"> 
 <div class="text_info"> 
  <p><a href="http://heartbleed.com">Heartbleedバグ</a>、または<a href="https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0160">CVE-2014-0160</a>(またはCVE-2014-0346)として知られるセキュリティホールはOpenSSLのバージョン1.0.1から1.0.fにある重大な欠陥でリモートの攻撃者がサーバ上のメモリ上の任意のセクションのダンプを取得できてしまう。そのほかのバージョンのOpenSSLにはこの脆弱性はない。新しくリリースされたバージョンの1.0.1gからはこの問題は解決されている。また、OpenSSHには影響はない。</p> 
  <p>この脆弱性があるOpenSSLのバージョンは直近の2年間に利用されていた。1.0.1でTLS 1.1と1.2(これ自体が<a href="http://en.wikipedia.org/wiki/Transport_Layer_Security#BEAST_attack">BEAST</a>攻撃への対処だったのだが)が導入されたので、広く普及した。OSXだけが古いバージョンである0.9.8を使っていたので今回の問題に影響を受けていない。影響を受けているのは<a href="http://arstechnica.com/security/2014/04/critical-crypto-bug-exposes-yahoo-mail-passwords-russian-roulette-style/">Yahoo! Mail</a>や<a href="https://aws.amazon.com/security/security-bulletins/aws-services-updated-to-address-openssl-vulnerability/">Amazon Web Services</a>などだ。@ivanristicによれば、<a href="https://twitter.com/ivanristic/status/453275675625922560">30%のサーバがTLS 1.2をサポートしており</a>、そのほとんどが今回の脆弱性を抱えている可能性がある。</p> 
  <p>このバグは<a href="https://tools.ietf.org/html/rfc6520">heartbeat拡張(RFC 6520)</a>が原因で生まれたため、heartbeatにちなんだ名前が付けられた。<a href="http://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=4817504">OpenSSL 1.0.1に追加された</a>拡張で必要なレンジチェックをしないという<a href="http://blog.cryptographyengineering.com/2014/04/attack-of-week-openssl-heartbleed.html">バグ</a>があったのだ。heartbeatのプロトコルはサーバへメモリのパケット(64kバイト)を送信し、さらにそれをコピーしてクライアントに送る。送るデータにはペイロード長のヘッダが含まれているが、要求されたのより少ないデータを返すとひとつのリクエストでサーバのメモリ上から64kバイトのデータを読むことができてしまう。</p> 
  <p>サーバのアロケーションはmallocで確保されたメモリ配列でできているため、機密性が高い可能性の情報がリークしてしまう。メモリのアドレスがリースするとは限らないが、64kバイトもあればURLのセグメントをキャプチャして、平文のパスワードデータを手に入れることも可能だ。また秘密鍵も漏洩する可能性がある。セッションキーなども同様だ。</p> 
  <p>このバージョンのOpenSSLはすでにパッチが適用されており、ほとんどのLinuxディストリビューションで利用できる。また、セキュリティ更新センター経由でも利用できる。Apache、ngnix、その他OpenSSLを使っているライブラリを利用しているサーバ管理者はセキュリティ更新を行い、影響のあるプロセスを再起動するべきだ。または、サーバを再起動して古いバージョンをメモリから完全に除去するのもいいかもしれない。</p> 
  <p>また、ユーザもユーザ名/パスワードが破られていないことを確かめ、変更するべきだ。同様に、機密情報を扱う証明書は再作成したほうがいいだろう。</p> 
 </div> 
</div><br><br><br><br><br><br></body></html>