<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Hadoop-as-a-Service Provider Qubole Now Runs on Google Compute Engine</h3><p>Qubole, a managed Hadoop-as-a-Service offering is <a href="http://googlecloudplatform.blogspot.com/2013/12/qubole-helps-you-run-hadoop-on-google-compute-engine.html">now available</a> on Google Compute Engine (GCE). Qubole was so far only <a href="http://www.qubole.com/company/partners/">available</a> on Amazon’s AWS and this announcement follows only a few days after Google <a href="http://www.infoq.com/news/2013/12/gcega">releasing GCE into general availability</a>.</p>
<p>Community reactions were by and large positive and it seems people consider the <a href="http://nosql.mypopescu.com/post/69829120078/google-compute-engine-and-data">Big Data theme</a> as a <a href="http://gigaom.com/2013/12/13/maybe-big-data-is-the-killer-app-for-googles-cloud/">potential killer app</a> for GCE. Alex Popescu of DataStax puts it like this:</p>
<blockquote>
 If you look at these, you’ll notice a theme: covering data from every angle; Cassandra/DSE from DataStax for OLTP, DataTorrent for stream processing, Qubole for Hadoop, MapR for their Hadoop-like solution. I can see this continuing for a while and making Google Compute Engine a strong competitor for Amazon Web Services.
</blockquote>
<p>With Hadoop-as-a-Service (HaaS, also known as Hadoop in the cloud) come different options:</p>
<ul> 
 <li>Rolling your own deployment, that is, installing Apache Hadoop or one of the distributions (Cloudera, Hortonworks, MapR) in an IaaS offering, such as GCE or EC2. This allows for fine-grained control over what is running but also comes with deployment and management complexity.</li> 
 <li>Pre-packaged services such as Amazon’s <a href="http://aws.amazon.com/elasticmapreduce/">EMR</a> or <a href="http://www.savvis.com/big-data#foundation-services">Savvis’ Big Data offering</a> that help with reduced deployment complexity and offer mid-level control over installed services.</li> 
 <li>Managed HaaS such as Qubole or <a href="http://mortardata.com/">Mortar</a>, promising <a href="https://vimeo.com/80872062">reduced deployment and management complexity</a>.</li> 
</ul>
<p>The <a href="https://vimeo.com/80872062">key differences</a> of HaaS versus on-premise deployments are around elasticity, spot pricing, separation between compute and storage (for example, eventually consistent object stores such as Amazon’s S3 or <a href="https://cloud.google.com/products/cloud-storage/">Google’s Cloud Storage</a>, and enhanced security standards. Managed HaaS offerings such as Qubole <a href="https://vimeo.com/80872062">are often used</a> in development cases, for evaluation and testing, short-running analysis jobs and to realise hybrid cloud setups. They do, however, also come with their own limitations:</p>
<ul> 
 <li>Getting data into the cloud and getting it out again has its own price tag.</li> 
 <li>There may be privacy and data protection issues stemming from legal requirements that prevent or limit the use cases.</li> 
 <li>The TCO of a 24/7 operation has to be calculated through on a case-by-case basis.</li> 
 <li>There is a general mismatch between Hadoop, Hive, etc. on the one hand and the eventually consistent object stores on the other.</li> 
</ul>
<p>Ashish Thusoo and Joydeep Sen Sarma gathered experience running Hadoop and Hive during their tenure at Facebook, where they ran a data infrastructure team. Then, in June 2012, they launched <a href="http://www.qubole.com/">Qubole</a> that completed <a href="http://gigaom.com/2013/04/23/hadoop-startup-qubole-raises-7m-for-hive-as-a-service/">a $7 million Series A funding round</a> in April 2013. Joydeep gave a deep-dive on the challenges they faced implementing their HaaS offering and provided insights on the internals in his Hive London Meetup talk <a href="http://sdrv.ms/11XQ5K6">Cloud Friendly Hadoop &amp; Hive</a>. Further, Christian Prokopp (Data Scientist at Rangespan) recently <a href="http://www.bigdatarepublic.com/author.asp?section_id=2840&amp;doc_id=266304">wrote up</a> a detailed rundown and comparison of Qubole and EMR.</p><br><br><br><br><br><br></body></html>