<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Homeopatia Arquitetural: você devia ter feito como eu disse</h3><p>Em 2012, Steve Jones, da CapGemini, publicou no InfoQ.com um artigo afirmando que &quot;pensar est&aacute; em desuso&quot;, e como<a href="http://www.infoq.com/br/news/2012/09/tecnologia-pensamento-riscos;jsessionid=4895EF72BA973B61DB50DB15A0EDD6BB"> a TI valoriza mais a tecnologia do que pensamentos</a>. Na &eacute;poca, o artigo gerou longas discuss&otilde;es, em que muitos concordaram com Steve. Recentemente, Jones se deparou com outro aspecto dessa abordagem &quot;sem pensamento&quot;, com um<a href="http://service-architecture.blogspot.co.uk/2012/12/architectural-homeopathy.html">exemplo bem real</a>:</p> 
<blockquote> 
 <p>Ouvi uma coisa brilhante numa reuni&atilde;o: &quot;Estamos doentes; vamos parar de fingir que somos cirurgi&otilde;es?&quot;. Historicamente, naquela empresa, eram comuns opini&otilde;es e cr&iacute;ticas quanto a decis&otilde;es tomadas sem base em dados, e sem identificar quais implementa&ccedil;&otilde;es obtiveram sucesso.</p> 
</blockquote> 
<p>Para o mundo de TI, Steve chamou essa situa&ccedil;&atilde;o de &quot;Homeopatia Arquitetural&quot;, em que se tomam decis&otilde;es arquiteturais baseadas puramente em opini&otilde;es pessoais, sem apoio em fatos ou exemplos do porqu&ecirc; a decis&atilde;o tomada resultar&aacute; em sucesso e onde o sucesso das implementa&ccedil;&otilde;es n&atilde;o &eacute; medido, exceto na sua implanta&ccedil;&atilde;o. &Eacute; nessa falta de fatos para direcionar decis&otilde;es que Steve foca para ilustrar o seu ponto de vista:</p> 
<blockquote> 
 <p>Um bom desafio arquitetural &eacute; dizer que &quot;X n&atilde;o vai funcionar porque n&atilde;o trabalhamos de modo centralizado; precisamos fazer Y porque temos equipes distribu&iacute;das e Y j&aacute; provou que funciona aqui&quot;. J&aacute; na Homeopatia Arquitetural funciona mais ou menos assim: &quot;X n&atilde;o vai funcionar, devemos usar Y&quot;. E se algum problema ocorrer, o Homeopata Arquitetural dir&aacute; &quot;Voc&ecirc; devia ter feito como eu disse&quot;.</p> 
</blockquote> 
<p>Steve Jones acredita que os chamados Homeopatas Arquiteturais podem construir uma carreira inteira baseada nessa abordagem, argumentando algo como &quot;funcionou para mim&quot;, e continuar sem compreender as escolhas maiores que podem ter impulsionado o sucesso. Tamb&eacute;m acredita que essas pessoas tipicamente criticam as abordagens comprovadas. com base em falhas conhecidas. O autor argumenta tamb&eacute;m que os Homeopatas Arquiteturais s&atilde;o exatamente aqueles que questionam o uso de REST na integra&ccedil;&atilde;o corporativa, sem entender completamente o dom&iacute;nio do problema ou o raz&atilde;o de outras tecnologias serem muito mais adequadas.</p> 
<blockquote> 
 <p>S&atilde;o essas pessoas que prop&otilde;em vis&otilde;es arquiteturais sem realmente coloc&aacute;-las em produ&ccedil;&atilde;o, e treinam outras pessoas para que sigam a mesma abordagem.</p> 
</blockquote> 
<p>Levando ou n&atilde;o em conta a exist&ecirc;ncia da Homeopatas Arquiteturais, dentre os pontos principais levantados por Steve est&atilde;o o embasamento em fatos (dados) na tomada de decis&atilde;o; e, quando as escolhas feitas n&atilde;o funcionam, a adi&ccedil;&atilde;o desses dados para que se possa aprender com eles.</p> 
<blockquote> 
 <p>N&atilde;o concordo com a promo&ccedil;&atilde;o de abordagens arquiteturais (ou mesmo abordagens de neg&oacute;cio) que sejam baseadas em uma s&eacute;rie de PPTs e opini&otilde;es com sinais fortes de Homeopatia. Esses Homeopatas lan&ccedil;am coment&aacute;rios baseados na ignor&acirc;ncia e em cren&ccedil;as pessoais; atrapalham o progresso e adoram dizer que &quot;teria sido melhor do meu jeito&quot;, sem explicar em detalhes o que significa o &quot;jeito&quot; deles.</p> 
</blockquote> 
<p>Veja o post <a href="http://service-architecture.blogspot.co.uk/2012/07/thinking-is-dead.html">original</a> de Steve Jones e o <a href="http://service-architecture.blogspot.com.br/2012/12/architectural-homeopathy.html">mais recente</a>.</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>