<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>XML vs JSON: A diferença de desempenho era apenas um boato?</h3><p>Muitas das suposi&ccedil;&otilde;es sobre o qu&atilde;o lento, dispendioso e &quot;gordo&quot; o <a href="http://en.wikipedia.org/wiki/XML">XML</a> &eacute; se comparado &agrave; leveza do <a href="http://json.org/">JSON</a>, n&atilde;o foram sustentadas pelo teste feito por <a href="http://www.meetup.com/sohmug/members/39938032/">David Lee</a>, engenheiro l&iacute;der na <a href="http://www.marklogic.com/">Marklogic</a>, ap&oacute;s a execu&ccedil;&atilde;o de um experimento &quot;crowd sourcing&quot; com 33 documentos diferentes e aproximadamente 1200 testes, em uma grande quantidade de navegadores e sistemas operacionais mais utilizados. David <a href="http://balisage.net/Proceedings/vol10/html/Lee01/BalisageVol10-Lee01.html">afirma</a> ter descoberto que o desempenho total da experi&ecirc;ncia de usu&aacute;rio ‒ transfer&ecirc;ncia, an&aacute;lise (parsing) e consulta (querying) de um documento ‒ &eacute; quase id&ecirc;ntico em ambos os formatos: XML e JSON.</p>
<p>Para o seu experimento David criou e divulgou publicamente um ambiente de teste que imita um caso de uso em que documentos XML e JSON s&atilde;o entregues por um servidor web, para serem analisados e consultados em um navegador web. O servidor abastece o cliente com uma fonte de dados, e coleta os resultados provenientes do cliente. O cliente &eacute; uma aplica&ccedil;&atilde;o JavaScript executada no navegador, codificada especificamente para medir performance, exceto a parte que faz as medi&ccedil;&otilde;es de desempenho do jQuery.</p>
<p>Al&eacute;m de usar sete documentos diferentes com tamanhos entre 100Kb e 1Mb, e cada documento apresentar duas variantes JSON e tr&ecirc;s variantes XML, David tamb&eacute;m tentou cobrir uma gama de dispositivos, navegadores, sistemas operacionais e redes em seu teste. Ele fez isso atrav&eacute;s de <a href="http://pt.wikipedia.org/wiki/Crowdsourcing">&quot;</a><a href="http://pt.wikipedia.org/wiki/Crowdsourcing">crowd sourcing&quot;</a>, ou seja, tornou p&uacute;blica a URL do ambiente de testes e divulgou em v&aacute;rias listas de e-mail e sites de m&iacute;dia social. O resultado de aproximadamente 1200 testes distintos e bem sucedidos foram coletados at&eacute; agora, abrangendo os navegadores e sistemas operacionais mais utilizados. Em seu artigo, David documentou todos os dados do teste, bem como os seus resultados.</p>
<p>Algumas das conclus&otilde;es obtidas ap&oacute;s a experi&ecirc;ncia de David s&atilde;o:</p>
<ul class="c4 lst-kix_7f425gy6lgs2-0 start"> 
 <li>A velocidade de an&aacute;lise (parsing) varia de acordo com a t&eacute;cnica usada. A an&aacute;lise com JavaScript puro &eacute; mais r&aacute;pida para XML do que para o JSON, enquanto a consulta &eacute; normalmente mais r&aacute;pida para o JSON. Ambos apresentando exce&ccedil;&otilde;es, em que o contr&aacute;rio &eacute; verdadeiro;</li> 
 <li>O uso da biblioteca JavaScript jQuery imp&otilde;e uma penalidade exagerada para o JSON, e pior ainda para o XML;</li> 
 <li>Documentos compactados em todos os formados, mesmo representa&ccedil;&otilde;es muito grandes em JSON ou XML apresentam tamanho id&ecirc;ntico ap&oacute;s a compress&atilde;o, o que indica que ambos possuem o mesmo conte&uacute;do de informa&ccedil;&atilde;o;</li> 
 <li>A transfer&ecirc;ncia de documentos para uma grande variedade de dispositivos leva efetivamente o mesmo tempo em cada dispositivo, independentemente do formato adotado (XML ou JSON).</li> 
</ul>
<p>Baseando-se em seu experimento, David inclui algumas sugest&otilde;es para arquitetos e desenvolvedores:</p>
<ul class="c4 lst-kix_s7pypqxdgmjf-0 start"> 
 <li>Usar Compress&atilde;o HTTP, na maioria das vezes, &eacute; o fator mais importante no desempenho total;</li> 
 <li>Otimizar a marca&ccedil;&atilde;o para transmiss&atilde;o e consulta;</li> 
 <li>N&atilde;o tentar otimizar, a menos que a transmiss&atilde;o de dados, a an&aacute;lise e a consulta sejam problemas significativos se comparados &agrave;s outras quest&otilde;es.</li> 
</ul>
<p>E para finalizar, David deixa um conselho:</p>
<blockquote> 
 <p>N&atilde;o confie em ningu&eacute;m.</p> 
 <p>N&atilde;o acredite cegamente no que dizem. Fa&ccedil;a experi&ecirc;ncias, teste seus pr&oacute;prios dados e codifique com os seus pr&oacute;prios usu&aacute;rios e dispositivos. O que &quot;parece &oacute;bvio&quot; nem sempre &eacute; verdade.</p> 
</blockquote><br><br><br><br><br><br></body></html>