<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>IDE Integrated Search Engines</h3><p class="MsoNormal">&nbsp;</p>
<p class="MsoNormal">The ease of Google searches and the popularity of code advice community message boards like StackOverflow do well to indicate the popularity of coding through web search.&nbsp; Scott Hanselman wrote <a href="http://www.hanselman.com/blog/AmIReallyADeveloperOrJustAGoodGoogler.aspx">about</a> the similar of idea of programming through copying.&nbsp; Microsoft Research has observed these trends and taken the next evolutionary step by producing a plugin for Visual Studio 2013 that enables developers to conduct a code search directly from their IDE.
 <o:p></o:p></p>
<p class="MsoNormal"><a href="http://visualstudiogallery.msdn.microsoft.com/a1166718-a2d9-4a48-a5fd-504ff4ad1b65">Bing Code Search for C#</a> has been developed by a collaboration between the Visual Studio, Bing, and Microsoft Research teams.&nbsp; This plugin integrates with VS2013’s editor and is activated by choosing the new “How do I…” option from the IntelliSense drop-down menu.&nbsp; When selected, an expanded window opens inline allowing you to enter search terms for Bing to analyze.&nbsp; After entering a query Bing will search for relevant answers across MSDN, StackOverflow, Dotnetperls, and CSharp411.&nbsp; The results are easily indexed through, and each sample’s origin is clearly labeled.
 <o:p></o:p></p>
<p class="MsoNormal">A Microsoft spokesman indicated that Microsoft has made agreements with these particular websites to share their content with Visual Studio users.&nbsp; Answers sourced from StackOverflow additionally have a link back to the original contributor of the code snippet. &nbsp;While it is possible to add additional providers, nothing is planned at this time.
 <o:p></o:p></p>
<p class="MsoNormal">The plugin uses various pieces of “magic” to retrieve what considers to be useful answers including the semantic context and the type of project being worked on.&nbsp; Microsoft Program Manager Ala Shiban <a href="http://blogs.msdn.com/b/visualstudio/archive/2014/02/17/introducing-bing-code-search-for-c.aspx">notes</a> that this is one of the uses for the Roslyn compiler project.
 <o:p></o:p></p>
<p class="MsoNormal">Of interest is what of type of security and protections the code entered for queries received, as developers working on proprietary software projects may run into conflicts with corporate policies if company code is being transmitted outside their employer.&nbsp; At the time this article was published no information was available about specific privacy protections.&nbsp; 
 <o:p></o:p>
 <o:p>
  &nbsp;
 </o:p></p>
<p class="MsoNormal">Beyond making the plugin <a href="http://visualstudiogallery.msdn.microsoft.com/a1166718-a2d9-4a48-a5fd-504ff4ad1b65">available</a> for Visual Studio 2013 users, Microsoft Research has also produced an <a href="http://codesnippet.research.microsoft.com/">online demo</a> for those interested in sampling the plugin before installing.&nbsp; Microsoft’s Bing isn’t the only search engine with programming-specific customizations, The Hacker News recently <a href="http://thehackernews.com/2014/02/programming-tutorials-with-DuckDuckGo_21.html">reported</a> search engine DuckDuckGo has also programmer focused search tools <a href="https://duckduckgo.com/goodies#Programming">available</a> (albeit without an IDE plugin as of yet.)
 <o:p></o:p></p>
<p>&nbsp;</p><br><br><br><br><br><br></body></html>