<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Is Getting Rid of All Projects a Good Idea?</h3><p><span style="font-size: 12px;">In the session </span><a href="http://www.xpdays.net/Xpday2013/XPDays/Program.html#session_178" style="font-size: 12px;">kill all projects</a><span style="font-size: 12px;">&nbsp;at the </span><a href="http://www.xpdays.net/" style="font-size: 12px;">XP Days Benelux 2013 conference</a><span style="font-size: 12px;">, Paul Kuijten questioned&nbsp;if&nbsp;getting rid of all projects could be a good idea. InfoQ did an interview with Paul about project management practices that can be valuable for agile, and the&nbsp;funding of&nbsp;product development.</span></p>
<p><strong>InfoQ: Your XP Days session is titled &quot;Kill all projects&quot;. Isn't that a harsh statement to make?</strong></p>
<blockquote> 
 <p><strong>Paul:</strong> I don't think so. It is intended to provoke some different thinking. My aim for the session was to clarify how well &quot;doing projects&quot; fits with product development in a complex environment, and to see if we can come up with alternative ways, keeping the benefits, and getting rid of the flaws.&nbsp;&nbsp;&nbsp;</p> 
</blockquote>
<p><strong>InfoQ:&nbsp;If we stop doing projects, does that also mean that we do not need project managers anymore?</strong></p>
<blockquote> 
 <p><strong>Paul: </strong>Yes. As a matter of fact, I now work with a very large organization that just got rid of the job title project manager. They have teams, they have products, and these are directly driven by business needs. Does this mean that these people they used to call project manager don't have any skills that the company still needs? Not at all. They typically transition to another role, depending on their skill set.</p> 
</blockquote>
<p><strong>InfoQ: Can you mention some of the good practices for managing projects that can be valuable for agile teams?</strong></p>
<blockquote> 
 <p><strong>Paul:</strong> Managing the what, the how, the money and the timelines is still very much necessary. There are tons of good practices in what we call project management. Almost all of them are very applicable if you are doing product development without projects. The practices we mainly want to get rid of are the ones misused for predictive and command and control management. We have found these are very closely tied in with &quot;doing projects&quot;. And then there are things that a project organization in our experience isn't concerned enough with, mainly having to do with people, quality and value. That's why I think it is worth thinking about how to do development without &quot;doing projects&quot;</p> 
</blockquote>
<p><strong>InfoQ: If we kill all projects, How do you fund your product development?</strong></p>
<blockquote> 
 <p><strong>Paul: </strong>The typical way organizations fund their product development now is through budgets. A budget is about the dumbest instrument that you could use. It locks you into an annual cycle in which you resist anything you didn't foresee a year ahead. How agile is that? Furthermore, if people didn't need the budget they requested by the end of the year, they will spend it anyway, because otherwise you get less budget next year. More and more companies are funding their development in an iterative and incremental way, judging every investment by its own merits. The most pressing example of this would be something called &quot;beyond budgeting&quot;. It's in many ways &quot;agile for financial controllers&quot;. Svenka Handelsbanken has been doing this for many years now, and with astonishing results.&nbsp;</p> 
</blockquote><br><br><br><br><br><br></body></html>