<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Adoção Ágil: a importância das práticas técnicas, pensamento sistêmico e cultura</h3><p>Simplicidade, <i>feedback</i>, comunica&ccedil;&atilde;o, respeito e coragem. Estes valores do eXtreme Programming (XP) continuam a inspirar a equipe da confer&ecirc;ncia <a href="http://www.xpday.net/Xpday2013/FrontPage.html">XP Days Benelux 2013</a>. O programa desta confer&ecirc;ncia consiste em dois dias de sess&otilde;es que abrangem muitos aspectos do <i>Agile</i>, como: t&eacute;cnicas de testes e desenvolvimento, planejamento e clientes, indiv&iacute;duos, equipes, processos e melhoria cont&iacute;nua.</p>
<p>O InfoQ.com entrevistou dois dos anfitri&otilde;es da confer&ecirc;ncia, Merlijn Van Minderhout e Pascal Van Cauwenberghe, sobre novidades no <i>Agile</i>, transforma&ccedil;&otilde;es &aacute;geis bem sucedidas e as necessidades das organiza&ccedil;&otilde;es Europeias na ado&ccedil;&atilde;o do <i>Agile</i>.</p>
<p><strong>InfoQ.com: Quais desenvolvimentos novos est&atilde;o ocorrendo nas comunidades &aacute;geis? Qual o motivo para os novos desenvolvimentos? Sabem o que est&aacute; causando isso?</strong></p>
<blockquote> 
 <p><strong>Pascal:</strong> Pode ser uma tend&ecirc;ncia em confirma&ccedil;&atilde;o, mas vejo mais sess&otilde;es sobre as praticas t&eacute;cnicas XP e trabalho com c&oacute;digo legado. Passamos por um per&iacute;odo de &quot;r&aacute;pido desenvolvimento&quot; em que a excel&ecirc;ncia t&eacute;cnica tem sido negligenciada, e agora todos estes projetos &quot;&aacute;geis&quot; podem ser paralisados devido a &quot;d&iacute;vida t&eacute;cnica&quot;. Isso &eacute; bom para perceber que mais e mais pessoas tomaram consci&ecirc;ncia do fato de que n&atilde;o h&aacute; como se manter &aacute;gil se n&atilde;o mantiverem c&oacute;digo male&aacute;vel.</p> 
</blockquote>
<p><strong>InfoQ.com: H&aacute; trilhas na confer&ecirc;ncia sobre assuntos t&eacute;cnicos, equipes e indiv&iacute;duos, processos e tamb&eacute;m clientes, e planejamento. Se uma transforma&ccedil;&atilde;o &aacute;gil precisasse considerar todas estas &aacute;reas, n&atilde;o seria muito dif&iacute;cil planejar e executar?</strong></p>
<blockquote> 
 <p><strong>Pascal:</strong> Em poucas palavras: sim. Em uma resposta mais longa: sim, e &eacute; por isso que &eacute; necess&aacute;ria uma abordagem sist&ecirc;mica (pensamento sist&ecirc;mico, pensamento complexo, teoria das restri&ccedil;&otilde;es…), para gui&aacute;-lo no entendimento do sistema e na percep&ccedil;&atilde;o de como est&atilde;o os pontos de alavancagem. N&atilde;o &eacute; somente um &quot;planejar e executar&quot;, mas um ciclo intermin&aacute;vel de: entender, planejar uma mudan&ccedil;a, realizar um experimento, e revisar. &Eacute; por isso que a organiza&ccedil;&atilde;o por tr&aacute;s do XP Days &eacute; chamada de &quot;Agile Systems&quot;: Pensamentos Sist&ecirc;micos + &Aacute;geis para construir sistemas &aacute;geis.</p> 
</blockquote>
<p><strong>InfoQ.com: &Agrave;s vezes ouvimos sobre transforma&ccedil;&otilde;es &aacute;geis que n&atilde;o s&atilde;o bem sucedidas. Sabem as raz&otilde;es pela qual falharam? E o que pode ser feito para aumentar as chances de sucesso com a ado&ccedil;&atilde;o do</strong> <strong>Agile</strong><strong>?</strong></p>
<blockquote> 
 <p><strong>Merlijn</strong>: Embora v&aacute;rias pr&aacute;ticas &aacute;geis terem pontos de partida simples, uma transi&ccedil;&atilde;o para o <i>Agile</i> n&atilde;o &eacute; simples. Como dito nas quest&otilde;es e respostas anteriores, envolve v&aacute;rias &aacute;reas. &Eacute; dai que surge a complexidade e &eacute; quando as coisas se tornam complexas: erros ser&atilde;o cometidos. E na verdade, cometer erros (ou n&atilde;o, de prefer&ecirc;ncia cedo e muitas vezes) &eacute; a chave para a aprendizagem efetiva e melhoria. Muitas organiza&ccedil;&otilde;es param no ponto em que falham, em vez de tom&aacute;-lo como um novo ponto de partida.</p> 
</blockquote>
<p><strong>InfoQ.com: A ado&ccedil;&atilde;o do</strong> <strong>Agile</strong><strong> na Europa &eacute; diferente se comparada a outros continentes? As organiza&ccedil;&otilde;es t&ecirc;m diferentes necessidades na Europa, ou abordagens diferentes que s&atilde;o usadas ​​pelos</strong> <strong>coaches</strong><strong> </strong><strong>&aacute;geis na Europa?</strong></p>
<blockquote> 
 <p><strong>Merlijn</strong>: J&aacute; vi v&aacute;rias diferen&ccedil;as dentro da Europa e mesmo em outro pa&iacute;s. A cultura de uma empresa tem uma grande influ&ecirc;ncia sobre a forma de abordar a mudan&ccedil;a &aacute;gil. Ter mente aberta, toler&acirc;ncia a erros, algu&eacute;m autorizado a falar, etc. Eu diria que a cultura da empresa tem mais influ&ecirc;ncia no sucesso da ado&ccedil;&atilde;o do <i>Agile</i> do que a sua localiza&ccedil;&atilde;o espec&iacute;fica no mundo. Claro que muitas vezes a cultura da empresa est&aacute; fortemente relacionada &agrave; cultura de um pa&iacute;s.</p> 
</blockquote>
<p><strong>InfoQ.com: A confer&ecirc;ncia XP Days Benelux cobre mais do que o XP, tamb&eacute;m vejo sess&otilde;es abrangendo Scrum, Kanban e mudan&ccedil;as organizacionais. J&aacute; consideraram alterar o nome da confer&ecirc;ncia?</strong></p>
<blockquote> 
 <p><strong>Pascal</strong>: sim, consideramos isso todos os anos. Est&aacute; se tornando um tipo de ritual. E sempre chegamos &agrave; mesma conclus&atilde;o (at&eacute; agora): o &quot;esp&iacute;rito XP&quot;, o valores do XP continuam importantes para n&oacute;s. Estes valores inspiram como organizamos o XP Days: simplicidade, <i>feedback</i>, comunica&ccedil;&atilde;o, respeito e coragem. Coragem para informar o que n&atilde;o funciona; coragem para estar aberto e tentar novas coisas; coragem para reconhecer o que n&atilde;o sabemos (ainda); coragem para ampliar as fronteiras, para sempre tentar fazer o melhor, para n&atilde;o estagnar no conservadorismo confort&aacute;vel. E no final do dia voc&ecirc; n&atilde;o constr&oacute;i sistemas com Post-its. Excelentes pr&aacute;ticas t&eacute;cnicas s&atilde;o um pr&eacute;-requisito para a agilidade sustent&aacute;vel.</p> 
</blockquote>
<p>A confer&ecirc;ncia ser&aacute; realizada nos dias 28 e 29 novembro, em Mechelen (B&eacute;lgica). XP Days Benelux &eacute; apoiada pela <a href="http://www.agilesystems.org/">Agile Systems</a>, uma organiza&ccedil;&atilde;o sem fins lucrativos cujos objetivos s&atilde;o desenvolver e difundir conhecimentos e experi&ecirc;ncias relacionadas aos m&eacute;todos &aacute;geis e pensamento sist&ecirc;mico. O InfoQ.com cobriu a confer&ecirc;ncia XP Days Benelux 2012 com not&iacute;cias sobre as <a href="http://www.infoq.com/news/2012/11/xpdays-benelux-day-1">sess&otilde;es do primeiro</a> e <a href="http://www.infoq.com/news/2012/11/xpdays-benelux-day-2">segundo dia</a>.</p><br><br><br><br><br><br></body></html>