<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Tizen SDK for Wearableを使用したSamsung Gear向けアプリ開発</h3><p><a target="_blank" href="http://www.infoq.com/news/2014/03/samsung-gear-wearable-sdk"><em>原文(投稿日：2014/03/18)へのリンク</em></a></p>
<div class="article_page_left news_container text_content_container"> 
 <div class="text_info"> 
  <p>Androidを搭載した第１世代のウェアラブルデバイスに続いてSamsungは，Intelと共同で開発したオープンソースのモバイルオペレーティングシステムである<a href="http://www.infoq.com/news/2011/09/Tizen">Tizen</a>を基盤とした，第２世代のデバイスの市場投入を決定した。そして今回，アプリケーション開発のための<a href="https://developer.tizen.org/downloads/tizen-sdk#wearable">SDK</a>がリリースされている。</p> 
  <p>Samsung Gearのアプリには２つのタイプがある。ひとつはデバイス上でのみ動作する，ネットワーク接続の不要な&quot;Standalone&quot;，もうひとつはスマートフォンやタブレット上で動作するAndroidアプリケーションと，Gearデバイス上で動作するTizen側ウィジェットという，２つのコンポーネントを持った&quot;Host-Gear&quot;だ。コンポーネント間の通信にはBluetoothを使用する。ウィジェットの開発はTizen Wearable IDE上で，エミュレータを使って行う。作成したアプリは対応するホストアプリと別々に，あるいは一緒にパッケージした上で<a href="http://seller.samsungapps.com/">Samsung App Seller Office</a>に提出して，同社のアプリストアへの受け入れ前にレビューを受ける。App StoreやGoogle Playの場合と同様，Gearアプリの販売から生じる収入の30%はSamsumgが収得する。ユーザは，ホストとなるスマートフォンにインストールされたGear Managerを使ってアクセスし，アプリケーションをダウンロードする。</p> 
  <p>デバイス上でのウィジェットは，Tizenの<a href="https://developer.tizen.org/dev-guide/2.2.0/org.tizen.web.appprogramming/html/basics_tizen_programming/web_runtime.htm">Web Runtime</a>内に表示される。Web Runtimeは，Chromeを使用しないHTML5 アプリケーション用ブラウザウィンドウだ。Tizen SDK for WearableはUbuntu 32および64bit，Windows 7 32および64bit，Max OS X上で動作する。</p> 
  <p>Tizenプロジェクトが開始されたのは2011年9月のことだった。Samsungは今年のMWC 2014で，このオペレーティングシステムを使用した最初のスマートフォンを公開した。Ars Technicaではこのデバイスを評して&quot;優れた機能を備えたAndroidクローン&quot;と呼び，Andoirdに匹敵する豊富な機能と優れた性能に注目している。Samsungは，最終的にTizenが向かう方向を伺っているように思える。Androidと対等に競うことのできるOSに仕上げることは可能だろうが，大きな問題が残っている – アプリケーションだ。生まれたばかりのマーケットに対して，開発者たちはアプリを作ってくれるだろうか？</p> 
  <p>Gearアプリに関しては，事態はさらに難しくなっている。AndroidとTizenの両方で開発しなければならないからだ。２つの異なったAPIを学び，2つのSDKで作業する必要がある。さらにウェアラブルデバイス用のGoogle SDKの登場も間近に迫っている。CNETによれば，<a href="http://news.cnet.com/8301-1023_3-57620090-93/google-to-launch-sdk-for-android-wearables-in-two-weeks/">今週中には発表されるはず</a>だ。</p> 
 </div> 
</div><br><br><br><br><br><br></body></html>