<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>SparkRを使ってRでSparkを動かす</h3><p><a target="_blank" href="http://www.infoq.com/news/2014/02/sparkr-announcement"><em>原文(投稿日：2014/02/11)へのリンク</em></a></p>
<div class="article_page_left news_container text_content_container"> 
 <div class="text_info"> 
  <p>Rはデータサイエンティストにとって最も強力な言語のひとつであり、2014年1月にUCバークレーの<a href="https://amplab.cs.berkeley.edu/">AMPLab</a>がApache SparkをRから使うための仕組みであるSparkRプロジェクトの<a href="https://groups.google.com/forum/#!topic/apache-spark-user-mirror/tZs0dHeM6bk">開発者プレビュー</a>を発表したことでさらに強力になった。</p> 
  <p>インメモリデータ処理のためのビッグデータフレームワークである<a href="http://spark.incubator.apache.org/">Apache Spark</a>はClouderaのような大企業の牽引力を手に入れた。Clouderaは最近、Cloudera Distribution for Hadoop (CDH)から <a href="http://blog.cloudera.com/blog/2014/02/spark-is-now-generally-available-for-cloudera-enterprise/">Sparkを正式にサポート</a>したとアナウンスした。最新のリリースである<a href="http://spark.incubator.apache.org/news/spark-0-9-0-released.html">Spark 0.9</a>をサポートしているが、このバージョンはSparkRの動作要件だ。SparkRはちょうどいいタイミングで現れたといえるだろう。というのも、CDHは最も人気のあるHadoopディストリビューションのひとつで、データサイエンスの分野での導入を後押しするはずだ。データサイエンティストはJavaやScalaよりもRに親しんでいる。O'Reillyの<a href="http://blog.revolutionanalytics.com/2014/01/in-data-scientist-survey-r-is-the-most-used-tool-other-than-databases.html">最新の調査</a>の通りだ。</p> 
  <p>SparkRはSparkからRを使うための軽量なフロントエンドと言えるだろう。つまりSparkRはJavaやScalaほどの拡張性のあるAPIは持たないだろう。しかし、SparkのジョブをRから実行しデータを操作するには十分なAPIだ。クロージャをシリアライズする機能が重要な機能のひとつだろう。これによって変数をSparkクラスタに透過的にコピーできる。さらにSparkRはRのモジュールと組み込み関数経由で統合されており、Sparkクラスタに、計算に必要な特定のモジュールをロードするよう指示できる。しかし、クロージャとは違い、これは手動で設定しなければならない。技術についてのより詳細な説明は、<a href="http://amplab-extras.github.io/SparkR-pkg/">この要約</a>に書いてある。SparkRはSparkの<a href="http://spark.incubator.apache.org/docs/latest/ec2-scripts.html">EC2スクリプト</a>を活用して、EC2上で簡単にセットアップできるようになっている。この点についてもGithub上で<a href="https://github.com/amplab-extras/SparkR-pkg/wiki/SparkR-on-EC2">解説されている</a>。</p> 
  <p>データサイエンス界隈の人たちはSparkRに注目している。中でもTwitterはこのプロジェクトに対してサポートメッセージを送っている。<a href="http://www.mlsecproject.org/">MLSecProject</a>を推進している<a href="https://twitter.com/alexcpsec">Alex Pinto氏</a>は次のようなツイートをしている。</p> 
  <blockquote> 
   <p>これは凄い。@amplabのSparkR。私の好きな技術でデータ分析ができる。</p> 
  </blockquote> 
  <p>プロジェクトは<a href="http://github.com/amplab-extras/SparkR-pkg">Github上</a>にあり、既に100スター近くを集めている活発なコミュニティを持っている。このプロジェクトが生まれてまだ1ヶ月程度しか経っていないことを考えれば、素晴らしい成長だ。まだ、いくつかの課題がオープンのままになっており、コミュニティが活発に活動しているのが伺える。</p> 
  <p>AMPLabのチームは将来SparkRを機会学習ライブラリである<a href="http://spark.incubator.apache.org/mllib/">MLlib</a>に組み込むことに興味を持っており、これが実現すれば、手動で定義をしなくてもアルゴリズムをシームレスに実行することができる。MLlibは機会学習プロジェクトである<a href="http://www.mlbase.org/">MLBase</a>の中のひとつのコンポーネントだ。MLBaseもまた、高いレベルの抽象と最適化機構を提供する。MLlibは最も急速に成長している機会学習ライブラリであり、137人以上の貢献者がいる。したがって、Rからこのライブラリが使えるようにするのはAMPLabにとって合理的だ。</p> 
 </div> 
</div><br><br><br><br><br><br></body></html>