<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Uma introdução a redes neurais utilizando C#</h3><p>O doutor James McCaffrey da Microsoft Research fez uma <a href="http://channel9.msdn.com/Events/Build/2013/2-401">apresenta&ccedil;&atilde;o interessante</a> sobre redes neurais na confer&ecirc;ncia Build 2013. Apresar do t&iacute;tulo da apresenta&ccedil;&atilde;o &quot;Desenvolvendo redes neurais utilizando o Visual Studio&quot; sugerir que o conte&uacute;do seja algo espec&iacute;fico para o Visual Studio (VS), &eacute; na verdade aplic&aacute;vel a qualquer desenvolvedor que deseja aprender mais a respeito de redes neurais (RN). James McCaffrey possui doutorado em matem&aacute;tica, mas na empolgante apresenta&ccedil;&atilde;o ele tem algo de desenvolvedor com conhecimentos em ci&ecirc;ncias da computa&ccedil;&atilde;o.</p>
<p>A abordagem serve como uma &uacute;til introdu&ccedil;&atilde;o ao conceito de redes neurais e os espectadores conheceram bem os conceitos fundamentais para um estudo posterior mais aprofundado. Na apresenta&ccedil;&atilde;o, James McCaffrey aborda um problema fict&iacute;cio de prever a afilia&ccedil;&atilde;o pol&iacute;tica de um indiv&iacute;duo com base em sua idade, renda, sexo e religi&atilde;o. Foi um exemplo &uacute;til e f&aacute;cil de se entender e um exemplo pr&aacute;tico de utiliza&ccedil;&atilde;o de redes neurais.</p>
<p>Durante a palestra, James McCaffrey cobriu o que ele chama dos sete conceitos principais para utiliza&ccedil;&atilde;o de redes neurais:</p>
<ul class="c9 lst-kix_s3tsbc3uei7r-0 start"> 
 <li>Tipos de redes neurais (<a href="http://en.wikipedia.org/wiki/Directed_cycle">c&iacute;clica</a> ou <a href="http://en.wikipedia.org/wiki/Directed_cycle">recorrente</a>);</li> 
 <li>Ativa&ccedil;&atilde;o;</li> 
 <li>Codifica&ccedil;&atilde;o dos dados;</li> 
 <li>Erro;</li> 
 <li>Treinamento;</li> 
 <li>Par&acirc;metros livres;</li> 
 <li><a href="http://en.wikipedia.org/wiki/Overfitting">Otimiza&ccedil;&atilde;o excessiva</a> (acaba gerando cen&aacute;rios de falso positivo).</li> 
</ul>
<p>McCaffrey nota que muitos novatos na utiliza&ccedil;&atilde;o de redes neurais podem se defrontar com a falta de documenta&ccedil;&atilde;o confi&aacute;vel. Ele endere&ccedil;a esse problema apresentando uma lista do que considera ser uma fonte confi&aacute;vel de informa&ccedil;&otilde;es. Apesar de seu entusiasmo claro a respeito do tema, ele consegue ser imparcial e tamb&eacute;m descreve os pontos fortes e fracos da t&eacute;cnica da redes neurais (RN). Indo al&eacute;m, ele apresenta seis m&eacute;todos alternativos a redes neurais assim como especifica quando eles podem ser mais apropriados de acordo com o problema que precisa ser resolvido.</p>
<p>Ao final de sua apresenta&ccedil;&atilde;o, James McCaffrey forneceu o c&oacute;digo C# da solu&ccedil;&atilde;o que demonstra a utiliza&ccedil;&atilde;o da t&eacute;cnica de redes neurais para os espectadores poderem efetuar testes ap&oacute;s o evento. O exemplo utiliza o conjunto de dados Iris Flower, que &eacute; normalmente utilizado para testar algoritmos de m&aacute;quinas de aprendizado (machine learning). (Observa&ccedil;&atilde;o: No momento desta tradu&ccedil;&atilde;o era necess&aacute;rio adicionar um ponto e v&iacute;rgula na linha 756 para que o programa compilasse sem erros). James McCaffrey fez uma palestra similar no evento Microsoft Summit em abril de 2013, mas a apresenta&ccedil;&atilde;o no evento Build foi mais abrangente sendo a edi&ccedil;&atilde;o que deve ser assistida.</p><br><br><br><br><br><br></body></html>