<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>DevDocs, a One Stop Shop for Reference Documentation</h3><p><a href="http://devdocs.io">DevDocs</a> combines multiple reference documentation sets, commonly used by software developers, in a single web site. DevDocs takes advantage of this centralization to offer crosscutting features to all the APIs such as a searchable interface, keyboard shortcuts, common layouts or a common table of contents.</p>
<p>According to DevDoc's vision statement:</p>
<blockquote>
  DevDocs aims to make reading and searching reference documentation fast, easy and enjoyable. The app's main goals are to: keep booting and loading times as short as possible; improve the quality, speed, and order of search results; maximize the use of caching and other performance optimizations; maintain a clean, readable user interface; support full keyboard navigation; reduce &quot;context switch&quot; by using a consistent typography and design across all documentation sets; reduce clutter by focusing on a specific category of content (API/reference) and by indexing only the minimum useful to most developers. 
</blockquote>
<p>DevDocs currently offers documentation mainly targeted for web development including: standards (e.g.: <a href="http://devdocs.io/html/">HTML</a>, <a href="http://devdocs.io/http/">HTTP</a>, <a href="http://devdocs.io/css/">CSS</a>); languages (e.g.: <a href="http://devdocs.io/ruby/">Ruby</a>, <a href="http://devdocs.io/python/">Python</a>, <a href="http://devdocs.io/javascript/">JavaScript</a>); libraries (e.g.: <a href="http://devdocs.io/jquery/">jQuery</a>, <a href="http://devdocs.io/ember/">Ember</a>) and products (e.g.: <a href="http://devdocs.io/rails/">Ruby on Rails</a>, <a href="http://devdocs.io/postgresql/">PostgreSQL</a>, <a href="http://devdocs.io/redis/">Redis</a>, <a href="http://devdocs.io/git/">Git</a>).</p>
<p>Thibaut Courouble, DevDocs' creator, told InfoQ that additional documentation sets are on the pipeline: &quot;I recently started working on the Linux man pages, with Bash, C, C++, D3.js and Knockout.js also on my short-term todo list&quot;.</p>
<p>The DevDoc's HTML home page is an illustrative example of what DevDocs looks like:</p>
<p><img src="http://www.infoq.com/resource/news/2013/12/devdocs-api-documentation/en/resources/DevDocs_500.png" alt="" _href="img://DevDocs_500.png" _p="true" /></p>
<p>Since all the documentation published on DevDocs is <a href="https://github.com/Thibaut/devdocs#scraper">scrapped</a>, the update process is not instantaneous. Thibaut asserts &quot;the existing documentations are updated often, usually within a few days of a new version being released. If I miss a release, DevDocs's users are welcome to request an update on our Trello board&quot;.</p>
<p>DevDocs has been <a href="https://github.com/Thibaut/devdocs">open sourced</a> and <a href="https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md">welcomes contributors</a>. There is also a <a href="https://trello.com/b/6BmTulfx/devdocs-documentation">voting system</a> in place to request new documentation sets, although anyone can contribute, as explained by Thibaut:</p>
<blockquote> 
 <p>Anyone is welcome to contribute new documentations. Much work went into creating a flexible scraper/toolchain that helps with adding new docs and maintaining the existing ones. The only requirements are a few <a href="https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#contributing-new-documentations">&quot;quality guidelines&quot;</a> and that the doc's license allows redistribution of modified versions (which Microsoft, Apple and Oracle prohibit).</p> 
 <p>As for choosing which documentations to work on myself, votes are definitely a major factor, personal preference another (though I've now added most of the ones I want), and also how organized the original docs are (i.e. how long it'll take to add it).&nbsp;</p> 
</blockquote>
<p>The future plans for the site can usually be tracked on GitHub, says Thibaut:</p>
<blockquote> 
 <p>Part of my plans can be tracked on <a href="https://github.com/Thibaut/devdocs/issues?direction=desc&amp;labels=feature&amp;page=1&amp;sort=updated&amp;state=open">GitHub</a>. Speed and ease of use are my top priorities, so I have many ideas about optimizations and UI tweaks.</p> 
 <p>I'd like to create an offline-enabled version that works out-of-the-box (currently you have to download the code to use DevDocs offline) as well as smartphone/PhoneGap apps (the current app is already optimized for mobile but native apps would bundle the docs for offline reading).</p> 
 <p>Further down the road we could imagine deep integrations with IDEs. People have already created <a href="http://devdocs.io/about#plugins">plugins</a> for <a href="http://www.sublimetext.com/">Sublime Text</a> and <a href="http://brackets.io/">Brackets</a>.</p> 
</blockquote><br><br><br><br><br><br></body></html>