<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Google abre código-fonte do Gumbo, uma biblioteca para parsing de HTML5</h3><p>O Google abriu o c&oacute;digo-fonte do <a href="https://github.com/google/gumbo-parser">Gumbo</a>, uma biblioteca para parsing de HTML escrita em C. O Gumbo segue o <a href="http://www.whatwg.org/specs/web-apps/current-work/multipage/parsing.html#parsing">algoritmo de parsing de HTML5</a>, passando em todos os testes da biblioteca <a href="https://github.com/html5lib/html5lib-tests">html5lib-0.95</a>, al&eacute;m de ter sido testado em 2,5 bilh&otilde;es de p&aacute;ginas indexadas pelo Google.</p>
<p>De acordo com a p&aacute;gina de descri&ccedil;&atilde;o do projeto, o prop&oacute;sito em lan&ccedil;ar o Gumbo &eacute; dar aos desenvolvedores uma biblioteca para parse HTML que n&atilde;o possui depend&ecirc;ncias externas e pode ser chamado a partir da maioria das linguagens. A biblioteca poderia ser inclu&iacute;da em validadores de p&aacute;ginas web, analisadores est&aacute;ticos, linguagens de template, ferramentas de refatora&ccedil;&atilde;o, etc.</p>
<p>O Google considera o Gumbo como &quot;robusto e flex&iacute;vel a uma entrada mal escrita&quot;, por&eacute;m n&atilde;o recomenda que se possua ponteiros para algumas de suas estruturas internas de dados, pois &eacute; prov&aacute;vel que a API mude no futuro. Apesar da API ser considerada como est&aacute;vel, a equipe est&aacute; esperando por coment&aacute;rios dos usu&aacute;rios antes de lan&ccedil;ar a vers&atilde;o 1.0, o que deve ocorrer no futuro pr&oacute;ximo.</p>
<p>Algumas das funcionalidades que ser&atilde;o adicionadas no futuro s&atilde;o:</p>
<blockquote> 
 <ul class="c7 lst-kix_61p7wmqv86ly-0 start"> 
  <li>Suporte para mudan&ccedil;as recentes na especifica&ccedil;&atilde;o do HTML5 para suportar a tag template;</li> 
  <li>Suporte a parse de fragmentos;</li> 
  <li>Relat&oacute;rios de erro com diversos recursos;</li> 
  <li>Acoplamento em outras linguagens.</li> 
 </ul> 
</blockquote>
<p>Antes da padroniza&ccedil;&atilde;o do algoritmo de parse do HTML 5, cada navegador escolhia como iria interpretar as p&aacute;ginas de entrada e como iria apresent&aacute;-las ao usu&aacute;rio. Apesar do HTML 4 possuir especifica&ccedil;&otilde;es a respeito de remarca&ccedil;&otilde;es v&aacute;lidas, n&atilde;o existia nenhuma diretiva a respeito de como o navegador deveria se comportar quando a entrada n&atilde;o era v&aacute;lida, somado ao fato de <a href="http://dev.opera.com/articles/view/mama-markup-validation-report/">95% das p&aacute;ginas web do mundo</a> n&atilde;o passarem no <a href="http://validator.w3.org/">validador de refer&ecirc;ncia do W3C</a>. Validar p&aacute;ginas HTML com uma ferramenta como o Gumbo garante que p&aacute;ginas ser&atilde;o apropriadamente convertidas e exibidas em todos os grandes navegadores.</p><br><br><br><br><br><br></body></html>