<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Software Craftsmen são Egocêntricos?</h3><p>Em um <a href="http://blogs.tedneward.com/2013/01/24/On+The+Dark+Side+Of+Craftsmanship.aspx">recente post</a> em seu blog, <a href="http://www.tedneward.com/about.aspx">Ted Neward</a> apontou um lado negro no movimento <a href="http://en.wikipedia.org/wiki/Software_craftsmanship">Software Craftsmanship</a>. De acordo com Neward, a comunidade dos &quot;artes&atilde;os de software&quot; (software craftsmen) imp&otilde;e uma segrega&ccedil;&atilde;o &agrave; comunidade de desenvolvimento, separando-a entre os craftsmen, que buscam com afinco o aprimoramento do seu estilo de programa&ccedil;&atilde;o, dos trabalhadores comuns, que encaram o software apenas como uma profiss&atilde;o a ser executada durante o hor&aacute;rio comercial.</p> 
<p>Segundo Neward, o mundo precisa tanto dos artes&atilde;os quanto dos trabalhadores comuns. No entanto, ainda segundo o autor, o grupo de artes&atilde;os denominado &quot;Software Craftspeople&quot; constantemente age de forma egoc&ecirc;ntrica, criticando indiscriminadamente quem n&atilde;o busca a perfei&ccedil;&atilde;o no seu trabalho di&aacute;rio.</p> 
<p>O post teve como origem a <a href="https://github.com/harthur/replace">rea&ccedil;&atilde;o</a> que <a href="https://twitter.com/harthvader">Heather Arthur</a> obteve ap&oacute;s publicar no github o c&oacute;digo de uma ferramenta de &quot;Search and Replace&quot; escrita em JavaScript. O <a href="http://harthur.wordpress.com/2013/01/24/771/">trabalho</a> de Arthur foi bastante criticado no twitter, dando origem aos questionamentos de Ted Neward.</p> 
<p>Neward aponta sinais de narcisismo no movimento, pois muitos Craftsman agem com egocentrismo, buscando e evangelizando o c&oacute;digo elegante e compromisso profissional somente com o objetivo de demonstrar sua superioridade.</p> 
<p>O autor ainda aponta a dificuldade de se julgar o c&oacute;digo alheio:</p> 
<blockquote> 
 <p>Se retirarmos o autor e contexto de um c&oacute;digo fonte, um julgamento que defina o que &eacute; c&oacute;digo elegante e o que &eacute; c&oacute;digo de hack &eacute; uma tarefa complexa sem as restri&ccedil;&otilde;es no qual o software estava inserido.</p> 
</blockquote> 
<p>Por fim, Neward afirma que existe no mundo lugar para apaixonados por desenvolvimento de software e para os que encaram software apenas como uma profiss&atilde;o. O ponto fundamental segundo o autor &eacute; o respeito m&uacute;tuo da comunidade, tanto no &acirc;mbito pessoal quanto profissional.</p> 
<p>O post, gerou uma rea&ccedil;&atilde;o do <a href="http://en.wikipedia.org/wiki/Robert_Cecil_Martin">Uncle Bob</a> no blog da <a href="http://blog.8thlight.com/">8thlight</a>. Denominado &quot;The Humble Crafstman&quot; (O artes&atilde;o humilde), Uncle Bob afirma que, apesar de concordar que existam Craftsmen que agem com arrog&acirc;ncia, a dicotomia apontada por Neward n&atilde;o existe e o movimento n&atilde;o cria uma elite de desenvolvimento teoricamente superior &agrave; massa de desenvolvedores.</p> 
<p>Bob segue afirmando que o caminho mais comum para se tornar um artes&atilde;o de software &eacute; baseado na tentativa e erro.</p> 
<blockquote> 
 <p>Em nossa ind&uacute;stria, a melhor e provavelmente a &uacute;nica forma de aprimoramento profissional &eacute; atrav&eacute;s de uma s&eacute;rie de erros e ciclo de aprendizado cont&iacute;nuo.</p> 
</blockquote> 
<p>Esse processo, muitas vezes, &eacute; realizado atrav&eacute;s da exposi&ccedil;&atilde;o de c&oacute;digo fonte de projetos. Devemos ser gratos a essas pessoas por compartilharem seus erros, fornecendo um aprendizado de muito valor &agrave; comunidade de desenvolvimento.</p> 
<p>Contudo, ainda segundo Uncle Bob, a melhor maneira de demonstrar respeito e honrar um c&oacute;digo fonte &eacute; atrav&eacute;s da cr&iacute;tica, pois nenhum c&oacute;digo &eacute; perfeito e ausente de pontos de melhoria. A revis&atilde;o de c&oacute;digo por parte de um colega &eacute; a maior honra que um desenvolvedor pode receber.</p> 
<p>Bob ainda afirma que se voc&ecirc; chama um c&oacute;digo fonte de est&uacute;pido, lembre-se que voc&ecirc; est&aacute; utilizando uma palavra que na verdade o descreve como desenvolvedor, pois a &uacute;nica maneira de avaliar algo como est&uacute;pido &eacute; ter cometido a estupidez no passado.</p> 
<p>Outra rea&ccedil;&atilde;o adversa ao post de Neward &eacute; <a href="http://rtigger.com/blog/2013/01/25/its-okay-to-love-your-job/">apresentada</a> por <a href="http://rtigger.com/">Chad McCallum</a> em seu post &quot;It's Okay to Love Your Job&quot;. O autor, um apaixonado pelo desenvolvimento de software, entende que nem toda a comunidade de desenvolvimento partilha da mesma paix&atilde;o com que ele encara o desenvolvimento de software. Contudo, ele pede respeito aos Craftsmen afirmando que nem todos s&atilde;o egoc&ecirc;ntricos e narcisistas, apenas amam a sua profiss&atilde;o e buscam a perfei&ccedil;&atilde;o com afinco.</p> 
<p>Ap&oacute;s uma acalorada rea&ccedil;&atilde;o da comunidade, <a href="http://blogs.tedneward.com/2013/01/26/More+On+Craftsmanship.aspx">Ted Neward</a> publicou em seu blog algumas considera&ccedil;&otilde;es referentes ao seu post anterior. Contudo, apesar de considerar o movimento Craftsmanship v&aacute;lido quando ligado a uma meta pessoal de um desenvolvedor, ele reafirma que muitas vezes, o movimento &eacute; utilizado como uma forma de atacar e denegrir a imagem de desenvolvedores que escolheram n&atilde;o investir tempo e energia significativos no estudo de programa&ccedil;&atilde;o e aprimoramento profissional.</p> 
<p>Apesar da dicotomia apresentada por Ted Neward ser um pouco exagerada e discriminat&oacute;ria, ambos os estilos profissionais devem ser respeitados. Vale retormar o texto escrito por <a href="http://pt.wikipedia.org/wiki/Edsger_Dijkstra">Edsger Dijkstra</a> em 1972, denominado &quot;<a href="http://awards.acm.org/turing/addl_info/articles/4860551.pdf">The Humble Programmer</a>&quot;. Nele, Dijsktra afirma que grande parte da arte de programa&ccedil;&atilde;o baseia-se na tentativa de compensar o tamanho limitado de nossos cr&acirc;nios. Os melhores desenvolvedores s&atilde;o aqueles que conhecem suas limita&ccedil;&otilde;es em rela&ccedil;&atilde;o aos problemas e reconhecem o tamanho pequeno dos seus c&eacute;rebros. Segundo Dijikstra, este &eacute; o desenvolvedor humilde.</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>