<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Resources to Start Developing for Firefox OS</h3><p>Firefox OS, developed by Mozilla, pursues “<a href="http://groups.google.com/group/mozilla.dev.platform/browse_thread/thread/7668a9d46a43e482?pli=1">the goal of building a complete, standalone operating system for the open web</a>” and lets users install and run applications created using HTML, CSS, and JavaScript. It is based on Linux and Mozilla's Gecko and is a <a href="http://www.knowyourmobile.com/products/16409/mozillas-boot-2-gecko-and-why-it-could-change-world">completely open stack that is 100 per cent free</a> from proprietary technology.</p>
<h2>Contributing to Firefox OS</h2>
<p>Firefox OS is fully open source and can be <a href="https://www.cms.infoq.com/mag4media/scripts/FCKeditor/editor/git%20clone%20git://github.com/mozilla-b2g/B2G.git">cloned from GitHub</a>. On Mozilla Developer's portal, you can find fully <a href="https://developer.mozilla.org/en-US/Firefox_OS/Building_and_installing_Firefox_OS?redirectlocale=en-US&amp;redirectslug=Firefox_OS/Building_and_installing_Firefox_OS">detailed instructions to build and install it</a> on an emulator or <a href="https://developer.mozilla.org/en-US/Firefox_OS/Installing_on_a_mobile_device">mobile device</a>, e.g., an <a href="https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_OS/Dual_boot_of_B2G_and_Android_on_SGS2">Android handset configured for dual boot</a>.</p>
<p>Firefox OS core technologies are organized in <a href="https://developer.mozilla.org/en-US/Firefox_OS/Platform/Architecture">three major layers</a>:</p>
<ul> 
 <li><a href="https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_OS/Gaia">Gaia</a>, which is the user interface of Firefox OS. Gaia includes, among other things, a lock/home screen, telephone dialer and contacts application, plus the classic phone apps: mail, calendar, calculator and marketplace. Gaia is written entirely in HTML, CSS, and JavaScript.</li> 
 <li><a href="https://developer.mozilla.org/en-US/docs/Gecko">Gecko</a>, which is the OS application runtime and implements open standards for HTML, CSS, and JavaScript. Gecko includes a networking stack, graphics stack, layout engine, and JavaScript virtual machine.</li> 
 <li><a href="https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_OS/Gonk">Gonk</a>, which consists of a Linux kernel and a user-space hardware abstraction layer (HAL) and is the lower level OS on which Gecko runs. Gonk exposes to Gecko interfaces to get, e.g., direct access to the full telephony stack or to the display framebuffer, which are not usually accessible to Gecko on any other OS.</li> 
</ul>
<p>Among the skills required to contribute to Gonk and Gecko is knowledge of C++, while knowledge of JavaScript or HTML/CSS is required to be able to contribute to Gaia.</p>
<p>A fundamental resource for contributing to Firefox OS is <a href="https://bugzilla.mozilla.org/query.cgi">bugzilla</a>, Mozilla's defect database. Apart from choosing and fixing any bug from bugzilla, Mozilla has made an effort to help newcomers to get acquainted with the platform and processes by establishing <a href="http://www.joshmatthews.net/bugsahoy/">mentored bugs</a>. Mentored bugs should contain enough information to get started and also feature a mentor who has committed to help along the process. If no appropriate mentored bugs are available, an older “<a href="https://bugzil.la/sw:[good%20first%20bug]">good first bug</a>” list could offer a useful starting point.</p>
<p>Once fixed the bug, the developer should <a href="https://developer.mozilla.org/en-US/docs/Developer_Guide/How_to_Submit_a_Patch">submit her patch for review</a> and finally have it checked in by someone with enough privileges.</p>
<h2>Developing Apps for Firefox OS</h2>
<p>If you'd rather not get your hands dirty with the lower-level OS components, you can develop an app running on Firefox OS. The basic tools for Firefox OS app development are the latest <a href="http://www.mozilla.org/en-US/firefox/new/">Firefox browser</a>, <a href="https://getfirebug.com/">Firebug</a>, and the <a href="http://people.mozilla.com/%7Emyk/r2d2b2g/">Firefox OS Simulator Addon</a>.</p>
<p>More useful resources to know about are:</p>
<ul> 
 <li><a href="https://hacks.mozilla.org/2013/01/introducing-the-firefox-os-boilerplate-app/">Boilerplate app</a>: a basic template showing an app's structure and <a href="https://wiki.mozilla.org/WebAPI">WebAPI</a> usage;</li> 
 <li><a href="https://developer.mozilla.org/en/docs/IndexedDB">IndexedDB</a>: an API for client-side storage of significant amounts of structured data, whereas <a href="https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/Storage?redirectlocale=en-US&amp;redirectslug=Web/Guide/DOM/Storage">DOM Storage</a> is suitable to store smaller amounts of data;</li> 
 <li><a href="https://developer.mozilla.org/en-US/Apps/Developing/Manifest?redirectlocale=en-US&amp;redirectslug=Web/Apps/Manifest#appcache_path">App Manifest</a>: a manifest is one of the key things distinguishing an Open Web App from a website. It is a JSON file with a name and description for the app, and it can also contain the origin of the app, icons, and the permissions required by the app, among other things;</li> 
 <li><a href="https://developer.mozilla.org/en-US/Firefox_OS/Using_the_App_Manager">App Manager</a>: a set of tools to manage local apps, devices, and development toolboxes (inspector, debugger, etc.);</li> 
 <li><a href="https://hacks.mozilla.org/2013/08/introducing-brick-minimal-markup-web-components-for-faster-app-development/">Brick web components</a>: a specification to support HTML5 reuse through components;</li> 
 <li><a href="http://www.mozilla.org/en-US/styleguide/products/firefox-os/">Firefox OS style guide</a>: human interaction guideline describing all elements of appearance and UI behavior.</li> 
</ul>
<p>Mozilla Rep Shafiul Azam has also made available a <a href="http://shafiul.github.io/slides/kickstart_fxos.html">presentation describing the basic steps to develop an app for Firefox OS</a>.</p><br><br><br><br><br><br></body></html>