<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>ビッグデータ革命と遺伝子情報解析</h3><p><a target="_blank" href="http://www.infoq.com/news/2014/01/genomics-big-data-revolution"><em>原文(投稿日：2014/01/17)へのリンク</em></a></p>
<div class="article_page_left news_container text_content_container"> 
 <div class="text_info"> 
  <p class="p1">Curoverse 社とTute Genomics 社は、遺伝子の配列解析技術を一般消費者のもとへと届けることを目指している企業であるが、先月、双方とも担保付き債権1500万ドルの資金提供を受けた。Curoverse は、生物医学系の企業に対するプライベートクラウドプラットフォームであり、オープンソースの生物情報学プラットフォームである <a href="https://arvados.org/"><span class="s1">Arvados</span></a> をベースにしている。一方の Tute Genomics 社は、研究者がヒトのエクソームやゲノムのデータから遺伝子配列を解読するのを支援するクラウドベースの遺伝子解析ソリューションを提供している。</p> 
  <p class="p2">遺伝子配列解析に必要なコストは年々<a href="http://en.wikipedia.org/wiki/$1,000_genome"><span class="s1">低下</span></a>してきており、より多くのユーザに向けてサービスを市場展開するのが容易になってきている。同時に、ストレージ容量とコンピュータの計算能力も<a href="http://en.wikipedia.org/wiki/Moore's_law"><span class="s1">ムーアの法則</span></a>に従って増大しつづけており、ヒトのゲノム全体を一箇所に格納して解析するのも簡単になってきている。</p> 
  <p class="p2">とはいえ、ヒトのゲノム全体の完全な配列データは100・,000GBの容量である。100万人分の顧客のデータならばエクサバイト、つまり1,000,000TBもの容量にも達する。UCバークレイの研究者たちは、このような<a href="http://www.eecs.berkeley.edu/Pubs/TechRpts/2012/EECS-2012-211.pdf"><span class="s1">データベース</span></a>を管理するための実現可能な方法を提案している。それは３つに階層化されたストレージであり、その最終階層は100PBに達するものだが、第2の階層は1ペタバイト級データを扱い、第3の階層ではテラバイト級データを扱うという構成になっている。また、この第3階層だけがRDBMSベースとしている。この研究の最大の目標は、<a href="http://www.slideshare.net/rgrossman/bionimbus-towards-one-million-genomes-xldb-2012-lecture/8"><span class="s1">個人別のオーダメイド医療</span></a>の実現である。ヒトは<a href="http://www.genome.gov/17516714"><span class="s1">DNAの99.9％</span></a>が共通と言われており、仮説によれば多数の患者の全ゲノム配列の解析を実施すれば、残りの0.1％に何があるのか解明できるだろうと言われている。これが実証されれば、ガンを含む多くの疾病の予知や治療に役立つに違いない。</p> &gt; 
  <p class="p2">コンピュータの能力の側面でみると、<a href="http://gigaom.com/2012/04/30/straight-outta-stanford-bina-wants-to-remake-genome-analysis/"><span class="s1">ゲノム解析を高速化</span></a>するために専用設計のハードウェアが利用されるようになっている。この10年で、ヒトの遺伝子配列解析にかかるコストは<a href="https://www.youtube.com/watch?v=LJ4a0iDTpi8#t=6"><span class="s1">1/100,000</span></a>に低下しており、解析に要する時間は、かつては<a href="http://www.slideshare.net/gcoates/next-generation-genomcs-petascale-data-in-the-life-sciences/6"><span class="s1">13年を要するとされていたものが３日以下にまで</span></a>短縮している。</p> 
  <p class="p2">研究の世界では、ゲノムデータを解析して保存している解析センターが既にいくつか存在しているが、それらの<a href="http://www.slideshare.net/gcoates/life-sciencesoverview/8"><span class="s1">データ</span></a>は全て少数の患者から採取されたものである。真の課題は、これらの異なる形式のアーカイブ群を横断的に統合して一つデータセットにすることであり、患者の治療内容や治療成績について<a href="http://www.slideshare.net/gcoates/life-sciencesoverview/11"><span class="s1">相互参照</span></a>を実現することである。</p> 
  <p class="p2">この何年かで、いくつかの民間企業が大衆向けのゲノム解析の提供ビジネスに参入しはじめている。<a href="http://www.illumina.com/"><span class="s1">Illumina社</span></a>, <a href="https://www.sbgenomics.com/">Seven Briges Genomics社</a>、<a href="http://www.completegenomics.com/"><span class="s1">Complete Genomics社</span></a>等のような企業は、研究者や民間組織に対して、４桁ドル台（1,000～9,999ドル）の価格で全ゲノム配列の解読を提供している。Illumina 社は最近、かねてから<a href="http://www.nytimes.com/2006/07/18/science/18dna.html?pagewanted=all&amp;_r=0"><span class="s1">待望の</span></a>1,000ドルのゲノム解析サービス <a href="http://investor.illumina.com/phoenix.zhtml?c=121127&amp;p=irol-newsArticle&amp;ID=1890696"><span class="s1">HiSeq X Ten</span></a> を発表した。</p> 
  <p class="p2">Illumina 社は、<a href="https://basespace.illumina.com/home/index"><span class="s1">BaseSpace</span></a>と呼ばれるクラウド型コンピューティング＆ストレージプラットフォームをサービス開始したが、このプラットフォームは科学者達が <a href="http://aws.amazon.com/solutions/case-studies/illumina/"><span class="s1">Amazon Web Services</span></a>内に格納したデータについて配列を決定し、解析し、そして共同作業を実施できるようにするものである。また、専用の<a href="https://developer.basespace.illumina.com/"><span class="s1">APIとSDK</span></a>を使って、生命情報科学向けのアプリケーションを開発することもできる。</p> 
  <p class="p2">一方で、<span class="s1"><a href="https://www.sbgenomics.com/">Seven Brigeds Genomics</a></span>社は、ヒトゲノムの配列<a href="http://aws.amazon.com/solutions/case-studies/seven-bridges-genomics/"><span class="s1">解析</span></a>に、Amazon EC2, S3と<a href="http://www.mongodb.com/press/seven-bridges-genomics-relies-mongodb-next-generation-sequencing-analysis"><span class="s1">MongoDB</span></a>のようなクラウドとNoSQLデータベース技術を組み合わせて使用している。データストレージのコストを下げるため、 Amazon Glacier も使われている。Seven Bridges の PaaS では、データパイプラインの設定のためのGUIを提供している。このGUIは、事前に定義されたモデルを使ったり、目的のタスクに合うように手動で修正することもできる。</p> 
  <p class="p2">意欲的な生命情報科学系の開発者にとって、<a href="http://bowtie-bio.sourceforge.net/crossbow/index.shtml"><span class="s1">Crossbow</span></a> はゲノム全体のリシーケンス<a href="http://www.slideshare.net/fccoelho/fabricio-cloud-20131025/16"><span class="s1">解析</span></a>（既知の配列との差分解析）のために使えるツールの一つである。幾つかのライブラリを結合することにより、Crossbowは100ドル未満のAWS使用料金で、3時間以内にヒトゲノムの解析ができる。インテル社は段階的に学べる Crossbow の<a href="http://www.intel.com/content/dam/www/public/us/en/documents/reports/genome-resequencing-with-crossbow-report.pdf"><span class="s1">ガイド</span></a>を提供しており、<a href="https://github.com/BenLangmead/crossbow"><span class="s1">GitHub</span></a>上でそのソースコードも公開している。</p> 
  <p class="p1"><a href="http://techcrunch.com/2013/03/25/with-6-5m-in-tow-bina-technologies-wants-to-bring-big-data-insight-to-genomic-sequencing/"><span class="s1">150億ドル</span></a>の遺伝子解析産業はちょうどヒートアップを始めたばかりであり、技術の進歩は、我々が現在までに目にしてきたものを遥かに超えて、<a href="http://en.wikipedia.org/wiki/Quantified_Self"><span class="s1">Quantifid Self</span></a>（医学的ライフログ） の概念を拡張していくことだろう。</p> 
  <p class="p2">&nbsp;</p> 
  <p class="p1">&nbsp;</p> 
  <p class="p2">&nbsp;</p> 
 </div> 
</div><br><br><br><br><br><br></body></html>