<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Amazon Web Services、新しいインスタンスタイプを3つ発表</h3><p><a target="_blank" href="http://www.infoq.com/news/2013/11/aws-3-new-instance-types"><em>原文(投稿日：2013/11/22)へのリンク</em></a></p>
<div class="article_page_left news_container text_content_container"> 
 <div class="text_info"> 
  <p>2回目の<a href="http://reinvent.awsevents.com/">re:invent</a>カンファレンスにて、Amazon Web ServicesはEC2 (Elastic Compute Cloud) IaaSの新しいインスタンスタイプを3つ発表した。<a href="http://aws.typepad.com/aws/2013/11/coming-soon-the-i2-instance-type-high-io-performance-via-ssd.html">I2インスタンス</a>はSSDを使って、高いI/Oパフォーマンスを実現する。<a href="http://aws.typepad.com/aws/2013/11/a-generation-of-ec2-instances-for-compute-intensive-workloads.html">C3インスタンス</a>は高負荷な計算のために各仮想CPUをハードウェアハイパースレッドに結びつける。<a href="http://aws.typepad.com/aws/2013/11/build-3d-streaming-applications-with-ec2s-new-g2-instance-type.html">G2インスタンス</a>は3Dアプリケーション向けにNvidiaのGPUを提供する。</p> 
  <p>最大のI2インスタンスであるi2.8xlargeは、32のvCPUs、244GiBのRAM、非永続的ストレージのための8つの720GB SSDで構成され、350,000のリードIOPS（1秒当たりのI/O操作）および320,000のライトIOPSを提供することができる。その性能レベルは、トランザクションシステムやNoSQLデータベースのような高いランダムI/O性能が要求されるアプリケーションをターゲットにしている。このインスタンスファミリーは全性能を16分の1にしたi2.largeまでスケールダウンできる。基本となるハードウェアはクロック2.5GHzのIntel Xeon E5-2670v2プロセッサをベースにしている。Netflixクラウドアーキテクトの<a href="http://www.infoq.com/author/Adrian-Cockcroft">Adrian Cockcroft</a>氏は、「m1.smallに基づくクラウドベンチマークを出す人がいたら、i2.8xlargeを使って叩き出してやろう」と<a href="https://twitter.com/adrianco/status/401052816627597312">コメントした</a>。</p> 
  <p>C3インスタンスはI2よりも高速なCPU、クロック2.8GHzのXeon E5-2680v2をベースにしているが、RAMとSSDストレージの容量は小さい。このインスタンスファミリーはハイパフォーマンスコンピューティング(HPC)やHadoopのようなフレームワークを使った膨大なデータセットの分析といった、計算負荷の高いアプリケーションをターゲットにしている。仮想CPUをハードウェアCPUにより合わせることに加え、VPC (Virtual Private Cloud)内のネットワーク性能改善も提供し、高スループット、低レイテンシ、低ジッターを実現している。こうしたネットワーク改善の恩恵を得るには、<a href="http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html">ネットワーク強化</a>されたHVM（ハードウェア仮想マシン）を動かす必要がある。その導入プロセスを簡単にするため、C3向けにHVMをサポートした多数のAMI（Amazon Machine Image）が提供されている。</p> 
  <p>G2インスタンスタイプが提供するのはg2.2xlargeだけだ。これは8つの仮想CPU（Intelの古いSandy Bridgeプロセッサをベースとする）、15GiBのRAMと60GBのSSDストレージを提供する。ほかのインスタンスタイプとの違いは、1536コアと4GBのビデオRAMを搭載したNvidia GK104 GPUの存在だ。これは3Dレンダリングやビデオエンコーディングといったグラフィックス負荷の高いアプリケーションに使うことができる。G2はCG1インスタンスタイプの倍精度浮動小数点演算とエラー訂正メモリをサポートしていないので、Amazonは<a href="http://en.wikipedia.org/wiki/Gpgpu">GPGPU</a>を意図したものではないと説明するのに苦労している。</p> 
  <p>I2インスタンスが利用可能になると、Amazonの顧客は7つのファミリー、28の<a href="https://aws.amazon.com/ec2/instance-types/">インスタンスタイプ</a>から選択することになる。これは多少困惑するところで、デプロイメント環境に対してアプリケーションがフィットするかベンチマークをとりながら、注意深く分析、選択する必要があるだろう。Amazonは「負荷のプロファイルと規模に一番合ったインスタンスタイプを選択」し、「アプリケーションの要求が変化すれば、インスタンスタイプを変更」することを推奨している。開発および運用チームが最適な選択を追い求めるのは、かなりの作業になるだろう。<a href="http://www.infoq.com/jp/news/2013/10/aws-flex-reserved-instances">さまざまなサブスクリプションモデル</a>との組み合わせを考えると、パブリッククラウドアプリケーションを可能な限り経済的に効率良くするのは、大きなチャレンジになるだろう。</p> 
 </div> 
</div><br><br><br><br><br><br></body></html>