<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Java EE 8: Oracle busca mais feedback</h3><p>A Oracle lan&ccedil;ou a segunda parte de sua pesquisa do Java EE 8 na comunidade com nuvem, seguran&ccedil;a, rastreio, publica&ccedil;&atilde;o, testes, perfis e cortes entre os t&oacute;picos.</p>
<p>&quot;Durante as &uacute;ltimas 5 semanas, temos sido positivamente surpreendidos pelas respostas da comunidade sobre a primeira parte da pesquisa,&quot; <a href="https://blogs.oracle.com/theaquarium/entry/java_ee_8_community_survey">escreveu</a> David Delabassee. &quot;Temos recebido muitos feedbacks valiosos! Isso significa que temos muitos dados para processar, realmente um problema muito bom para encarar!&quot;</p>
<p>Um dos maiores t&oacute;picos &agrave; considerar &eacute; se agora &eacute; apropriado padronizar o suporte para PaaS, SaaS e multiloca&ccedil;&atilde;o. Esse trabalho foi originalmente planejado para o Java EE 7 mas depois arquivado, pelo menos em parte porque se considerou demasiadamente cedo para tentar padronizar. Na &eacute;poca Linda DeMichiel <a href="https://blogs.oracle.com/theaquarium/entry/java_ee_7_roadmap">escreveu</a>:</p>
<blockquote> 
 <p>Apesar de nossas melhores inten&ccedil;&otilde;es, nosso progresso tem sido lento no lado da nuvem em nossa agenda. Parcialmente isso se deve a falta de maturidade no espa&ccedil;o para a provis&atilde;o, multiloca&ccedil;&atilde;o, elasticidade e a publica&ccedil;&atilde;o de aplica&ccedil;&otilde;es na nuvem. E &eacute; parcialmente devido a nossa abordagem conservadora na tentativa de fazer as coisas &quot;certas&quot;, tendo em vista a experi&ecirc;ncia limitada da ind&uacute;stria na nuvem quando come&ccedil;amos este trabalho. Por conta disso, acreditamos que fornecer um suporte s&oacute;lido padronizado para programa&ccedil;&atilde;o com base em PaaS e multiloca&ccedil;&atilde;o atrasaria o lan&ccedil;amento do Java EE 7 at&eacute; a primavera de 2014 - ou seja , daqui a dois anos e ao longo de um ano de atraso. Em nossa opini&atilde;o, um caminho muito longo.</p> 
</blockquote>
<p>A Oracle est&aacute; agora interessada em saber se a vasta comunidade Java acha que vale a pena tentar novamente.</p>
<p>Outras ideias que est&atilde;o sendo contempladas incluem uma API padr&atilde;o para permitir que os desenvolvedores rastreiem os efeitos de uma &uacute;nica requisi&ccedil;&atilde;o atrav&eacute;s do sistema, para ver quais servi&ccedil;os s&atilde;o usados, quais outras requisi&ccedil;&otilde;es s&atilde;o feitas, etc. Al&eacute;m disso, a Oracle est&aacute; considerando adicionar suporte para um web container embarcado e Java EE container embarcado. Propostas de seguran&ccedil;a incluem a normaliza&ccedil;&atilde;o para o <a href="https://java.net/jira/browse/JAVAEE_SPEC-20">grupo de mapeamento de fun&ccedil;&atilde;o</a>, <a href="https://java.net/jira/browse/JAVAEE_SPEC-29">EL-enabled anota&ccedil;&otilde;es para autoriza&ccedil;&atilde;o</a>, e <a href="https://java.net/jira/browse/JAVAEE_SPEC-28">padroniza&ccedil;&atilde;o dos provedores de seguran&ccedil;a simples</a></p>
<p>A Oracle tamb&eacute;m est&aacute; ponderando a possibilidade de ter outra chance de padronizar um modelo de implanta&ccedil;&atilde;o. A tentativa inicial para isso, Java EE Application Deployment [JSR 88], teoricamente permite que qualquer aplica&ccedil;&atilde;o Java EE seja implantada em qualquer ambiente compat&iacute;vel com o Java EE usando a mesma ferramenta de implanta&ccedil;&atilde;o, mas tem sido mal suportado por fornecedores e foi considerado a ser descartado no Java EE 6.</p>
<p>Na mesma linha &agrave; JSR 88, Java EE Management [JSR 77] fornece APIs de ferramentas de gerenciamento para consultar um servidor de aplica&ccedil;&otilde;es Java EE para determinar o seu estado atual, aplica&ccedil;&otilde;es implantadas, e assim por diante. Ferramentas de gerenciamento de servidores constru&iacute;das usando essas APIs funcionam em v&aacute;rios fornecedores fornecendo aos administradores de sistema um meio de mudar os servidores de aplica&ccedil;&atilde;o sem alterar processos e ferramentas de gest&atilde;o, ou para gerenciar uma rede com v&aacute;rios servidores Java EE que consistem em v&aacute;rias implementa&ccedil;&otilde;es de fornecedores da plataforma. Como a JSR 88 essa API tem sofrido com o fraco suporte dos fornecedores, foi considerada para ser descartada no EE 7 e est&aacute; de volta na lista dessa vez. Outros candidatos a descarte incluem EJB 2.x, exibi&ccedil;&atilde;o do cliente remoto e local (interfaces <i>EJBObject</i>, <i>EJBLocalObject</i>, <i>EJBHome</i> e <i>EJBLocalHome</i>) e o CORBA.</p>
<p>A pesquisa cont&eacute;m 28 quest&otilde;es. Como antes, cada quest&atilde;o fornece valiosas informa&ccedil;&otilde;es no conceito da tecnologia relacionada para ajudar os participantes a tomar uma decis&atilde;o informada. Voc&ecirc; pode encontrar a pesquisa <a href="https://blogs.oracle.com/theaquarium/entry/java_ee_8_community_survey">aqui</a>.</p><br><br><br><br><br><br></body></html>