<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Google Releases Dart 1.0</h3><p>Two years after its initial announcement and preview release, <a href="http://googledevelopers.blogspot.com/2013/11/dart-10-stable-sdk-for-structured-web.html">Lars Bak announced the first stable release</a> of Dart at <a href="http://www.devoxx.be">Devvox in Belgium</a> today. <a href="https://www.dartlang.org/">Dart</a> is Google’s new web programming language and platform for developing modern web applications.</p>
<p>Dart 1.0 comes with <a href="https://www.dartlang.org/">a redesigned website</a>, the Dart VM, Dart2JS (to compile Dart to JavaScript code), an <a href="https://www.dartlang.org/tools/editor/">Eclipse-based IDE</a>, and <a href="https://www.dartlang.org/tools/dartium/">Dartium</a>, a specialized build of Chrome with the Dart VM included.</p>
<p>Over the past two years performance of Dart has improved dramatically. Dart code can run in two ways: either using the native Dart VM, which in the past year <a href="http://www.infoq.com/news/2013/05/Dart-Java-DeltaBlue">beat the JVM in certain benchmarks</a>. For browsers that do not support Dart natively (currently no production browsers do), Dart code can be compiled to JavaScript using the dart2js tool. Recently, <a href="https://www.dartlang.org/performance/">certain benchmarks dart2js generated JavaScript surpasses hand-written JavaScript code</a>. In addition, the size of generated JavaScript code has been <a href="http://googledevelopers.blogspot.com/2013/11/dart-10-stable-sdk-for-structured-web.html">dramatically reduced</a>:</p>
<blockquote> 
 <p>Similarly, dart2js output code size has been reduced substantially. The generated JavaScript for the game&nbsp;<a href="http://dart-lang.github.io/pop-pop-win/">Pop, Pop, Win!</a> is now&nbsp;<a href="http://work.j832.com/2013/10/dart-to-javascript-output-size-what.html">40% smaller</a> than it was a year ago. Performance of the VM continues to improve as well; it’s now between 42% to 130% faster than idiomatic JavaScript running in V8, depending on the benchmark.</p> 
</blockquote>
<p><img src="http://www.infoq.com/resource/news/2013/11/dart-10/en/resources/deltabluebenchmark.png" alt="" _href="img://deltabluebenchmark.png" _p="true" /></p>
<p>In its <a href="http://googledevelopers.blogspot.com/2013/11/dart-10-stable-sdk-for-structured-web.html">announcement blog post</a>&nbsp;the team also revealed the names of some companies already using Dart in production. <a href="http://www.infoq.com/news/2013/04/blossom-dart-switch">InfoQ spoke to the people of Blossom</a> earlier this year, who are gradually porting their application to Dart. Other users of Dart include <a href="http://www.montagebook.com/">Montage</a>, <a href="https://www.soundtrap.com/">Soundtrap</a>, <a href="http://mandrill.com/">Mandrill</a>, and Google’s internal CRM application as well as <a href="http://www.google.com/elections/ed/de/districts">Google Elections</a>.&nbsp;</p>
<p>A lot is also happening on the Dart library front. <a href="http://pub.dartlang.org/">Dart Pub</a>, its package repository now contains 500 user contributed packages. Google is also porting some of its own frameworks, inculding a <a href="http://www.infoq.com/news/2013/06/angularjs-dart">Dart port of its popular AngularJS framework</a>&nbsp;named&nbsp;<a href="https://github.com/angular/angular.dart">Angular.dart</a>&nbsp;and a <a href="http://www.infoq.com/news/2013/07/dart-polymer-web-ui">port of Polymer</a>, its <a href="http://www.infoq.com/news/2013/05/webcomponents">web components shim library</a>.</p>
<p>Dart is now officially declared stable and production ready. Dart 1.0 is free and open source, and can be <a href="https://www.dartlang.org/">downloaded from its website for all major platforms</a>. The refreshed website contains a <a href="https://www.dartlang.org/#code">5 minute walk-through</a> of Dart, as well as <a href="https://www.dartlang.org/codelabs/darrrt/">an hour-long tutorial</a>.</p><br><br><br><br><br><br></body></html>