<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>NetBeans 7.3: foco em HTML5</h3><p>Na vers&atilde;o 7.3, a mais recente do NetBeans, a Oracle atualizou a IDE para que os desenvolvedores possam criar mais facilmente interfaces com o usu&aacute;rio baseadas em HTML5, para aplica&ccedil;&otilde;es m&oacute;veis e web.</p> 
<p>Um novo projeto do tipo HTML5 permite a inclus&atilde;o autom&aacute;tica de frameworks JavaScript populares como <a href="http://backbonejs.org/">Backbone</a> e <a href="http://jquery.com/">jQuery</a>, que s&atilde;o baixados de redes p&uacute;blicas de distribui&ccedil;&atilde;o de conte&uacute;do. V&aacute;rios exemplos de aplica&ccedil;&otilde;es em HTML5 tamb&eacute;m podem ser abertos diretamente do assistente &quot;Novo Projeto&quot;. Alguns deles est&atilde;o inclu&iacute;dos no NetBeans; outros s&atilde;o baixados diretamente do GitHub.</p> 
<p>O novo NetBeans tamb&eacute;m inclui um assistente para gera&ccedil;&atilde;o de c&oacute;digo de clientes JavaScript, para acesso a servi&ccedil;os baseados em REST. &Eacute; gerado c&oacute;digo JS usando a biblioteca Backbone.js e opcionalmente um arquivo HTML. O HTML inclui um esqueleto que fornece indica&ccedil;&otilde;es sobre como o c&oacute;digo gerado pode ser customizado. Se o servi&ccedil;o REST tiver uma interface em torno de uma cole&ccedil;&atilde;o de dados e for usado o Tablesorter UI, ent&atilde;o os dados s&atilde;o renderizados como tabela usando o plugin Tablesorter jQuery.</p> 
<p>Durante a programa&ccedil;&atilde;o, o editor oferece autocomplementa&ccedil;&atilde;o de c&oacute;digo HTML5, JavaScript, jQuery e CSS3 (usando o <a href="http://wiki.netbeans.org/HTML5">Projeto Easel</a>). O editor e depurador JavaScript foram completamente reescritos usando a plataforma <a href="http://en.wikipedia.org/wiki/Nashorn_(JavaScript_engine)">Nashorn</a> da Oracle, que substitui o Rhino como ambiente de execu&ccedil;&atilde;o JavaScript padr&atilde;o no Java 8. O editor inclui suporte para os documentadores mais comuns de JS, como <a href="https://wiki.appcelerator.org/display/tis/scriptdoc%2b(sdoc)%2b2.0%2bspecification">ScriptDoc</a>, <a href="http://code.google.com/p/ext-doc/">Ext-Doc</a> e <a href="http://code.google.com/p/jsdoc-toolkit/">JsDoc.</a></p> 
<p>O novo NetBeans tem como um dos objetivos ajudar os desenvolvedores na depura&ccedil;&atilde;o de interfaces web. As pr&eacute;-visualiza&ccedil;&otilde;es de HTML na IDE s&atilde;o fornecidas por um navegador interno baseado no WebKit, enquanto uma extens&atilde;o do navegador Chrome usa o protocolo de depura&ccedil;&atilde;o remoto do WebKit para depurar aplica&ccedil;&otilde;es web a partir do NetBeans. &Eacute; suportada tanto a depura&ccedil;&atilde;o de arquivos locais na pr&oacute;pria aplica&ccedil;&atilde;o HTML5, como a de arquivos JavaScript remotos ligados &agrave; aplica&ccedil;&atilde;o, mas sem fontes. O depurador oferece quatro visualiza&ccedil;&otilde;es:</p> 
<ul> 
 <li><strong>Pontos de interrup&ccedil;&atilde;o</strong><strong> (breakpoints):</strong> de linha, disparados quando o script atinge uma determinada linha de c&oacute;digo; Pontos de interrup&ccedil;&atilde;o DOM (quando acontece uma altera&ccedil;&atilde;o em determinado n&oacute; DOM); de eventos (quando um evento em particular ocorre na p&aacute;gina); e de XMLHttpRequest (quando ocorre comunica&ccedil;&atilde;o de rede por meio do XMLHttpRequest).</li> 
 <li><strong>Pilha de chamadas</strong>: mostra a pilha de chamadas (call stack) atual de um programa JavaScript. A janela tem tr&ecirc;s a&ccedil;&otilde;es de contexto: &quot;Tornar Atual&quot; (que muda o quadro no qual as vari&aacute;veis s&atilde;o avaliadas), &quot;Ir para os fontes&quot; e &quot;Copiar pilha&quot; (que copia a pilha de chamadas para a &aacute;rea de transfer&ecirc;ncia).</li> 
 <li><strong>Vari&aacute;veis</strong>: mostra as vari&aacute;veis v&aacute;lidas no escopo atual, e permite inspe&ccedil;&atilde;o. Tamb&eacute;m possui um avaliador, tornando poss&iacute;vel analisar express&otilde;es arbitr&aacute;rias.</li> 
 <li>O <strong>Log do Navegador</strong>: mostra todas as exce&ccedil;&otilde;es, erros, avisos etc, na medida que acontecem no navegador/browser.</li> 
</ul> 
<p>Testes de unidade de JavaScript tamb&eacute;m s&atilde;o suportados com o js-test-driver (que tamb&eacute;m &eacute; suportado pelo Eclipse e IntelliJ). A execu&ccedil;&atilde;o e depura&ccedil;&atilde;o de testes de unidade JavaScript ocorre da mesma forma que com outras linguagens.</p> 
<p>Indo al&eacute;m da programa&ccedil;&atilde;o para web, o NetBeans 7.3 inclui um novo editor exclusivo para JPQL (Java Persistence Query Language, a linguagem de consultas do JPA), que possibilita que os desenvolvedores testem consultas JPQL diretamente na IDE. Finalmente, a nova ver&atilde;o suporta o profiling de aplica&ccedil;&otilde;es Java em sistemas Linux ARM, incluindo o Raspberry Pi.</p> 
<p>O NetBeans &eacute; um IDE open source, licenciado sob a licen&ccedil;a CDDL v1.0 w GPL V2. Al&eacute;m do Java, suporta o Groovy (incluindo a vers&atilde;o 2.0) , PHP, C e C++. Est&aacute; dispon&iacute;vel para <a href="http://netbeans.org/downloads/">download</a> para as plataformas Windows, OS X, Solaris e Linux.</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>