<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Experiências em serviços: lições para obter sucesso em SOA</h3><p>Ao longo dos anos, o InfoQ fez uma cobertura extensa sobre os <a href="http://www.infoq.com/br/soa/;jsessionid=F2C9512DDC58FE778C4E0C9277BEF571">princ&iacute;pios de SOA</a> e sobre o que pode ajudar ou dificultar na sua ado&ccedil;&atilde;o. Com mais de sete anos de artigos e not&iacute;cias escritos sobre o tema, &eacute; poss&iacute;vel acompanhar a evolu&ccedil;&atilde;o de SOA desde a propaganda inicial exagerada, passando pela ado&ccedil;&atilde;o empresarial em larga escala, web services e a influ&ecirc;ncia relativamente recente do REST. Ao longo desse per&iacute;odo, muitas vezes foi dif&iacute;cil encontrar hist&oacute;rias de sucesso envolvendo SOA. Pesquisas indicam que apenas <a href="http://www.infoq.com/news/2008/07/Only1;jsessionid=F2C9512DDC58FE778C4E0C9277BEF571">20% dos projetos baseados em SOA obtiveram sucesso</a>. Entretanto, a lista de casos de sucesso inclui alguns exemplos not&aacute;veis, como <a href="http://www.infoq.com/news/2009/01/soa-case-study-cisco;jsessionid=F2C9512DDC58FE778C4E0C9277BEF571">CISCO</a> e <a href="http://www.infoq.com/presentations/SOA-eBay;jsessionid=F2C9512DDC58FE778C4E0C9277BEF571">eBay</a>.</p> 
<p>Um dos editores do InfoQ norte-americano, <a href="http://www.infoq.com/author/Jean~Jacques-Dubray;jsessionid=F2C9512DDC58FE778C4E0C9277BEF571">Jean-Jacques Dubray</a> ajudou a acompanhar o SOA durante sua evolu&ccedil;&atilde;o e tamb&eacute;m teve muito a contribuir. Dubray influenciou o SOA e ajudou a implantar com sucesso muitos sistemas baseados nos seus princ&iacute;pios. &Eacute; com esse hist&oacute;rico de experi&ecirc;ncias em mente que Jean-Jacques (ou apenas JJ) publicou recentemente <a href="http://www.ebpml.org/blog2/index.php/2013/02/21/four-principles-to-succeed-at">em seu blo</a>g quatro princ&iacute;pios que acredita ajudar a obter sucesso com SOA:</p> 
<p>1. Interfaces de servi&ccedil;os devem ser desacopladas de suas implementa&ccedil;&otilde;es</p> 
<p>2. Toda a l&oacute;gica de neg&oacute;cio deve ser normalizada</p> 
<p>3. Mudar um servi&ccedil;o deve ser simples</p> 
<p>- Mudan&ccedil;as devem ser escondidas dos consumidores de servi&ccedil;os at&eacute; que estejam preparados para elas</p> 
<p>- Mudan&ccedil;as devem ser f&aacute;ceis de consumir, quando o consumidor estiver preparado</p> 
<p>4. O versionamento de servi&ccedil;os deve ser baseado em compatibilidade</p> 
<p>JJ acredita que, se esses princ&iacute;pios forem seguidos consistentemente atrav&eacute;s de todas as fases de design e desenvolvimento, as chances de sucesso s&atilde;o muito maiores. Infelizmente ele n&atilde;o entra em mais detalhes sobre esses princ&iacute;pios em sua publica&ccedil;&atilde;o, embora sejam relativamente simples de entender. Em rela&ccedil;&atilde;o a &quot;interfaces de servi&ccedil;o&quot;, JJ complementa:</p> 
<blockquote> 
 <p>As pessoas, na sua maioria, falham em SOA porque pensam em servi&ccedil;o como uma abstra&ccedil;&atilde;o, algo parecido com uma &quot;classe&quot; em orienta&ccedil;&atilde;o a objetos. A interface de servi&ccedil;o &eacute; um contrato que permite que mudan&ccedil;as sejam expl&iacute;citas e controladas. [...] N&atilde;o se preocupe com as fronteiras dos servi&ccedil;os; invista em construir a melhor interface de servi&ccedil;o poss&iacute;vel (ou seja, que seja eficiente na ger&ecirc;ncia de mudan&ccedil;as).</p> 
</blockquote> 
<p>Dubray cobre outros assuntos que causaram preocupa&ccedil;&otilde;es em torno de SOA no passado, inclusive governan&ccedil;a. Nessa &aacute;rea, ele sugere:</p> 
<blockquote> 
 <p>N&atilde;o &quot;governe&quot; em excesso. A governan&ccedil;a deve permanecer m&iacute;nima e baseada em senso comum e num horizonte de curto prazo (de tr&ecirc;s a seis meses). A governan&ccedil;a de dados &eacute; muito mais importante, uma vez que qualquer mudan&ccedil;a no modelo de informa&ccedil;&otilde;es geralmente causa impacto nas interfaces de servi&ccedil;os.</p> 
</blockquote> 
<p>O acoplamento fraco &eacute; frequentemente citado como pe&ccedil;a fundamental para obter sucesso em SOA. JJ sugere que isso pode ser alcan&ccedil;ado quando:</p> 
<blockquote> 
 <p>A l&oacute;gica de neg&oacute;cio implementada por tr&aacute;s da interface do servi&ccedil;o n&atilde;o &eacute; envolvida no contexto de intera&ccedil;&atilde;o com o consumidor. N&atilde;o deve haver nenhuma duplica&ccedil;&atilde;o da l&oacute;gica de neg&oacute;cio ao gerenciar os estados de sistemas nos consumidores da interface.</p> 
</blockquote> 
<p>Outra &aacute;rea de SOA que &eacute; frequentemente citada como importante, mas indicada como dif&iacute;cil de alcan&ccedil;ar, &eacute; o reuso de servi&ccedil;os. <a href="http://www.infoq.com/news/2009/07/service-reuse;jsessionid=F2C9512DDC58FE778C4E0C9277BEF571">Em 2009</a>, Richard Watson do Burton Group disse:</p> 
<blockquote> 
 <p>Mesmo que um servi&ccedil;o nunca chegue a ser reutilizado, ainda pode agregar valor de outras formas: sendo adapt&aacute;vel e de baixo custo de manuten&ccedil;&atilde;o; reduzindo a redund&acirc;ncia; aumentando a seguran&ccedil;a e a conformidade atrav&eacute;s da aplica&ccedil;&atilde;o consistente de pol&iacute;ticas; entre outros resultados desejados. O foco exclusivo em reuso n&atilde;o nos permite enxergar esses outros valores.</p> 
</blockquote> 
<p>JJ concorda:</p> 
<blockquote> 
 <p>Ningu&eacute;m pode construir um servi&ccedil;o hoje esperando que esteja preparado para ser usado por novos consumidores tr&ecirc;s anos depois. Isso &eacute; absurdo. Se pensar em reuso dessa forma, voc&ecirc; ir&aacute; falhar instantaneamente e chegar&aacute; a conclus&otilde;es tolas como &quot;SOA n&atilde;o funciona&quot;. Em SOA (e tamb&eacute;m no mundo real), o reuso funciona de forma inversa: n&atilde;o &eacute; um consumidor novo quem est&aacute; reusando um servi&ccedil;o antigo; &eacute; quase exclusivamente uma nova vers&atilde;o de um servi&ccedil;o (alterado para suportar novos consumidores) que pode ser reusada por consumidores antigos sem quebr&aacute;-los.</p> 
</blockquote> 
<p>Quanto ao artigo de Richard Watson em 2009, JJ disse o seguinte nos coment&aacute;rios:</p> 
<blockquote> 
 <p>O que muitas pessoas ainda n&atilde;o entendem &eacute; que &quot;reuso&quot; em SOA n&atilde;o tem o mesmo significado, comparado com o que elas geralmente entendem quando ouvem a palavra &quot;reuso&quot;. Reuso em SOA &eacute; reuso para a frente ou &quot;para cima&quot;. Em SOA, reuso significa que a nova vers&atilde;o de um servi&ccedil;o constru&iacute;do para novos consumidores n&atilde;o quebra os consumidores existentes.</p> 
</blockquote> 
<p>Veja mais opini&otilde;es de JJ sobre SOA no seu <a href="http://www.ebpml.org/blog2/index.php/soa/">blog</a>.</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>