<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Google Compute Engineの一般提供</h3><p><a target="_blank" href="http://www.infoq.com/news/2013/12/gcega"><em>原文(投稿日：2013/12/04)へのリンク</em></a></p>
<div class="article_page_left news_container text_content_container"> 
 <div class="text_info"> 
  <p>Google Computer Engine (<a href="https://cloud.google.com/products/compute-engine/">GCE</a>) インフラストラクチャ・アズ・ア・サービスの<a href="http://googlecloudplatform.blogspot.co.uk/2013/12/google-compute-engine-is-now-generally-available.html">一般向け提供(GA/General Availability)が開始された</a>。ローンチには価格の引き下げに加え，新たなストレージモデル，サポート対象オペレーティングシステムの拡張，透過的メンテナンスのためのライブマイグレーション機能も含まれる。</p> 
  <p>Microsoft Azureと同じように，これまでGoogleは，分単位の課金モデルを用意することでAmazonの価格設定を下回ろうとする意図があった。今回の価格設定で同社は，'標準的なCompute Engineインスタンスとしてもっとも需要の多い' オンデマンドのインスタンス課金を10%引き下げるという，これまでよりはっきりとした動きを見せている。４仮想CPUと15GB RAMのn1-standard-4インスタンスが0.415ドル/時間というGoogleの価格に対して，(先月値下げしたばかりの) Amazonのm3.xlargsは0.450ドル／時間である。他の比較はこれほど簡単ではない。どちらのプロバイダもCPUとRAMで比較すれば同等のサービスを持っているのだが，Amazonのサービスの大部分がストレージをバンドルしているのに対して，Googleは現在ストレージをバンドルしていないためだ。Netflixのクラウドアーキテクトである<a href="http://www.infoq.com/author/Adrian-Cockcroft">Adrian Cockcroft</a>氏が，<a href="https://docs.google.com/spreadsheet/ccc?key=0AgPzdjntX0fSdEFMTXJ1X1NSdmtKcGxORGU1cU5Ea2c&amp;usp=drive_web#gid=0">各種のオプションを一覧表にまとめている</a>。</p> 
  <p>GCEマシン全般用のストレージには，新しい永続化ディスクモデルが，0.04ドル/GB/月の均一価格で提供される。ディスクのIO処理に関する追加料金はないが，TB単位で<a href="https://developers.google.com/compute/docs/disks#pdperformance">パフォーマンスの上限</a>が設定されている。小サイズの読み込みは300 IOPS，小サイズの書き込みは1500 IOPS，ストリーミング読み込みスループットは120MB/秒，ストリーム書き込みスループットは90MB/秒が可能な値だ。ただしブートアップ時やインストール作業については，高速化を計るために，これらの制限を超えるバースト処理が許可されている。また，コア数によるスケーリングによっても，IOPSや仮想マシン単位のスループットに制限のあることが公表されている。全体的に見たGoogleのストレージは，AmazonのプロビジョンドIOPS(<a href="https://aws.amazon.com/ebs/piops/">PIOPS</a>)を加えたElastic Block Store(<a href="https://aws.amazon.com/ebs/">EBS</a>)相当のものと考えられる。この条件で比較した場合，1TBと300 IOPSがGoogleでは40ドル/月，Amazonは151.80ドル/月になる。ただし，現実的な有用性はユースケース毎に違ってくるだろう。Amazonがサイズとパフォーマンスのスケーリングに柔軟性があるのに対して，Googleではサイズとパフォーマンスの条件が強く結び付いているため，特定のアプリケーションに対して適当なキャパシティを選択するために，どちらかでオーバープロビジョニングを必要とする可能性があるからだ。Googleでは，Amazonのインスタンスストアに相当するスクラッチディスクを非推奨にしている。</p> 
  <p>GCEはより広範なオペレーティングシステムをサポートするために，Linuxカーネル選択の制限を排除した。本記事の時点でWebコンソールから利用可能なのはDebian 7とContos 6のみだが，GoogleはRedHatとのEnterprise Linux (RHEL) に関する<a href="http://googlecloudplatform.blogspot.co.uk/2013/12/red-hat-and-google-compute-engine.html">パートナシップを発表</a>し，限定的なプレビューの形式で公開している。SUSEやFreeBSDのサポートも発表されている。<a href="http://coreos.com/">CoreOS</a>にフォーカスする<a href="http://www.docker.io/">Docker</a>などのサービスも，他のLinuxディストリビューションで動作するようになるはずだ。インポートされる仮想マシンイメージには，それ自身のカーネルに加えて，GCEのKVMハイパーバイザを実行するための初期化RAMディスクが必要になる。</p> 
  <p>一般提供に先立って，<a href="https://groups.google.com/forum/#!topic/gce-announce/_W06AcqEviY">ライブマイグレーションと自動リスタート</a>という機能が発表された。これにより，定期メンテナンスを実行中の仮想マシンでも，別のアベイラビリティゾーンに移動することが可能になる。GCEに定期メンテナンスがあるという事実は，継続実行を基本とする他のパブリックIaaSに対する欠点であると解釈されていた。ライブマイグレーションはそれを回避するためのものだ。 他のサービスで行われているように，VMが解放対象としてスケジュールされているので手動で移動させなければならない，という通知を受ける方法は，より多くのケースに適しているだろう。Googleのこの機能には，複数のアベイラビリティゾーンやリージョンにまたがることが可能な同社のネットワークモデルが有効に働いている。このためにVMはIPアドレスや接続しているネットワークを離れることなく移動が可能なのだ。同社が利用しているKVMがマイグレーション時のマシン仕様に対して比較的寛容であることも，この機能に一役買っている (VMwareではCPUのステッピングレベルに至るまで，同一のハードウェアであることが求められる)。これはGoogleにとって，GCEの基盤となっているハードウェアを，ユーザへのサービスを停止することなく，継続的にアップグレード可能だという意味も持っている。</p> 
  <p>16仮想CPUを持つ大規模なインスタンスタイプが現在，限定プレビューの一部として提供されている。このマシンにはRAM容量によって，30GBのstandard，104GBのhigh memory，14.4GBのhigh CPUという３つのタイプがある。</p> 
  <p>Googleはこれまで，GCEをDNAシーケンシング(sequencing)に使用していた<a href="http://googlecloudplatform.blogspot.co.uk/2013/12/google-compute-engine-helps-mendelics-diagnose-genetic-diseases.html">Mendelics</a>などのケーススタディを元に。大量のCPUやストレージを必要とする，非常に大規模なクラウドユーザを販売の対象としていた。GAに伴う価格引き下げやオペレーティングシステムサポートの改善は，サービスの魅力を向上する上で有効だろう。ただしWindowsをサポートするという徴候はまだないようだ。</p> 
 </div> 
</div><br><br><br><br><br><br></body></html>