<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>O presente e o futuro do desempenho dos aplicativos web moveis</h3><p>Em um artigo s&oacute;lido, bem fundamentado, Drew Crawford exp&otilde;e todas as <a href="http://sealedabstract.com/rants/why-mobile-web-apps-are-slow/">raz&otilde;es pelas quais ele acredita que os</a> <a href="http://sealedabstract.com/rants/why-mobile-web-apps-are-slow/">aplicativos web mobile</a><a href="http://sealedabstract.com/rants/why-mobile-web-apps-are-slow/"> s&atilde;o lentas</a> hoje e porque ele n&atilde;o espera por uma melhoria relevante no futuro pr&oacute;ximo. O artigo &eacute; o seguimento de um <a href="http://sealedabstract.com/rants/mobile-web-apps-are-slow/">artigo anterior</a> no qual ele aponta que o desempenho do JavaScript em dispositivos m&oacute;veis &eacute; uma ordem de grandeza mais lento do que em computadores desktop. Este artigo foi duramente criticado, ent&atilde;o Drew escreveu esse artigo muito mais elaborado. As raz&otilde;es para o baixo desempenho e a falta de melhorias dividem-se em tr&ecirc;s categorias:</p>
<ol class="c5 lst-kix_vneru1wjog08-0 start" start="1"> 
 <li>Velocidade dos procesadores ARM dos dispositivos m&oacute;veis versus dos processadores x86 dos computadores desktop;</li> 
 <li>Tend&ecirc;ncias de desempenho dos interpretadores de JavaScript;</li> 
 <li>Consumo de mem&oacute;ria particularmente relacionada ao garbage collection.</li> 
</ol>
<p>Os dois gargalos que Drew descreve s&atilde;o CPU e mem&oacute;ria. A limita&ccedil;&atilde;o pela CPU tem dois aspectos: o poder da sua CPU e a efici&ecirc;ncia de execu&ccedil;&atilde;o. Drew aponta que a gera&ccedil;&atilde;o atual de processadores x86 s&atilde;o 10 vezes mais r&aacute;pidos do que a atual gera&ccedil;&atilde;o de processadores ARM que s&atilde;o usados nos dispositivos m&oacute;veis de hoje como o iPhone e dispositivos de alta qualidade com Android.</p>
<p>Eu n&atilde;o sou um engenheiro de hardware, mas certa vez trabalhei para uma grande companhia de semicondutores e as pessoas me dizem que o desempenho atual &eacute; principalmente uma fun&ccedil;&atilde;o do seu processo (por exemplo, a coisa que eles medem em &quot;nan&ocirc;metros&quot;). O desempenho impressionante do iPhone 5 deve-se, de maneira significativa, ao encolhimento do processo de 45nm para 32nm - uma redu&ccedil;&atilde;o de cerca de um ter&ccedil;o. Mas para repetir o feito, a Apple teria de reduzir para um processo de 22nm.</p>
<p>O conhecimento e investimento na redu&ccedil;&atilde;o do tamanho de transistores est&aacute; principalmente na m&atilde;o da Intel. Drew afirma que n&atilde;o &eacute; prov&aacute;vel que o ARM surpreender&aacute; num futuro previs&iacute;vel. Na verdade, &eacute; muito mais prov&aacute;vel que a Intel venha a produzir um processador x86 para competir em estrat&eacute;gia de consumo de energia, com o ARM do que fazer com que o ARM elimine esta lacuna de desempenho.</p>
<p>O segundo aspecto do desempenho &eacute; a efici&ecirc;ncia. Qu&atilde;o eficientemente os ciclos da CPU s&atilde;o usados, isto &eacute;, qu&atilde;o eficiente podem ser as instru&ccedil;&otilde;es de m&aacute;quina geradas a partir de c&oacute;digo JavaScript?</p>
<p>&Eacute; aqui que muitos engenheiros da computa&ccedil;&atilde;o competentes trope&ccedil;am. Sua forma de pensar funciona da seguinte maneira: JavaScript tem se tornado mais r&aacute;pido! Ele continuar&aacute; ficando mais r&aacute;pido!</p>
<p>A primeira parte &eacute; verdade. JavaScript tornou-se muito mais r&aacute;pido. Mas estamos agora no Pico JavaScript. N&atilde;o fica muito mais r&aacute;pido daqui pra frente.</p>
<p>Este &eacute; o Chrome v8 no meu Mac (o mais antigo que ainda funciona, Dez 2010). E este &eacute; o v26:</p>
<p><img src="http://www.infoq.com/resource/news/2013/11/desempenho-aplicativos-moveis/pt/resources/performance-chromes.png" alt="" _href="img://performance-chromes.png" _p="true" /></p>
<p>N&atilde;o percebe a diferen&ccedil;a? &Eacute; porque n&atilde;o h&aacute;. <strong>Nada terrivelmente importante aconteceu ao JavaScript ultimamente, no que diz respeito &agrave; limita&ccedil;&atilde;o pela CPU.</strong></p>
<p>Se a rede parece mais r&aacute;pida do que em 2010, &eacute; provavelmente porque o computador mais r&aacute;pido, mas n&atilde;o tem nada a ver com melhorias do Chrome.</p>
<p>O motivo pelo qual o desempenho do JavaScript n&atilde;o tem mudado significativamente &eacute; claro, segundo Drew:</p>
<p>A quest&atilde;o &eacute;, usar uma abordagem JIT com JavaScript foi uma ideia de 60 anos de idade com 60 anos de pesquisa e literalmente milhares de implementa&ccedil;&otilde;es para cada linguagem de programa&ccedil;&atilde;o conceb&iacute;vel demonstrando que era uma boa ideia. Mas agora que terminamos, ficamos sem ideias de 60 anos de idade. &Eacute; isso, pessoal. Talvez possamos criar outra boa ideia nos pr&oacute;ximos 60 anos.</p>
<p>A segunda limita&ccedil;&atilde;o da Internet m&oacute;vel &eacute; a <i>mem&oacute;ria</i>. Mais uma vez h&aacute; dois aspectos ligados ao uso da mem&oacute;ria: a <i>quantidade</i> dispon&iacute;vel e a <i>efici&ecirc;ncia</i> do uso.</p>
<p>Enquanto dispositivos m&oacute;veis modernos tem uma quantidade razo&aacute;vel de mem&oacute;ria (normalmente 512MB ou 1GB de mem&oacute;ria), o sistema operacional n&atilde;o permite o aplicativo usar essa quantidade toda. Muita mem&oacute;ria &eacute; usada pelo sistema operacional em si, assim como por outros aplicativos trabalhando (multi-tarefa)</p>
<p>[...] essencialmente no iPhone 4S, &eacute; necess&aacute;rio se preocupar quando a aplica&ccedil;&atilde;o usar em torno de 40MB, por que se atingir 213MB a aplica&ccedil;&atilde;o &eacute; encerrada. No iPad 3, preste aten&ccedil;&atilde;o quando chegar a 400MB porque a aplica&ccedil;&atilde;o &eacute; encerrada se atingir 550MB.</p>
<p>Drew nota que com a resolu&ccedil;&atilde;o do iPhone 4S, uma &uacute;nica foto tirada com a c&acirc;mera consome at&eacute; 30MB de dados bitmap. Isso significa que h&aacute; espa&ccedil;o dispon&iacute;vel para 7 fotos na RAM antes que o sistema operacional desligue o aplicativo porque ficou sem mem&oacute;ria. Portanto, especialmente se um aplicativo lida com imagens e v&iacute;deo, ele deve ser extremamente cuidadoso com que mant&eacute;m na mem&oacute;ria e por quanto tempo, uma vez que a mem&oacute;ria &eacute; <i>extremamente limitada</i>.</p>
<p>O segundo aspecto da mem&oacute;ria &eacute; efici&ecirc;ncia. O JavaScript &eacute; uma linguagem com garbage collector. O desenvolvedor n&atilde;o tem de fazer o gerenciamento manual da mem&oacute;ria, o que &eacute; desenhado para tornar a vida mais f&aacute;cil para o desenvolvedor. Contudo, a garbage collection tem seu pre&ccedil;o. Um pre&ccedil;o que aumenta exponencialmente em ambientes restritos pela mem&oacute;ria.</p>
<p><img src="http://www.infoq.com/resource/news/2013/11/desempenho-aplicativos-moveis/pt/resources/chart.png" alt="" _href="img://chart.png" _p="true" /></p>
<p>O que esse gr&aacute;fico diz &eacute;: &quot;Enquanto tiver cerca de 6 vezes a quantidade de mem&oacute;ria que realmente precisa, estar&aacute; bem. Mas ter&aacute; problemas se tiver menos do que 4x a mem&oacute;ria necess&aacute;ria&quot;.</p>
<p>A verdade &eacute; que no ambiente limitado pela mem&oacute;ria, o desempenho do garbage collection decai exponencialmente. Se escrever Python ou Ruby ou JS que roda em computadores desktop, &eacute; poss&iacute;vel que toda sua experi&ecirc;ncia esteja no lado direito do gr&aacute;fico, e pode passar toda sua vida sem experimentar um garbage collector lento. Gaste algum tempo do lado esquerdo do gr&aacute;fico e veja com o que o resto de n&oacute;s lida.</p>
<p>Esse comportamento poderia ser a raz&atilde;o pela qual a Apple nunca tenha dado suporte ao garbage collector do Objective-C no iOS e o esteja substituindo pelo ARC (no iOS e no Mac), que n&atilde;o &eacute; um garbage collector.</p>
<p>Apesar de Drew levantar pontos interessantes em seu artigo, como apontado por Brendan Eich em um tweet, nem todos os aplicativos s&atilde;o limitados por CPU ou mem&oacute;ria. Apenas uma certa categoria de aplicativos esbarra nesses problemas, por exemplo: jogos e aplicativos de fotos e v&iacute;deos. De qualquer maneira, o artigo de Drew (com 10.000 palavras) vale ser lido por qualquer um interessado em desempenho na Internet m&oacute;vel.</p><br><br><br><br><br><br></body></html>