<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Q&A with VersionOne CEO Robert Holler – Agile Live Webinars</h3><p>Continuing our coverage of the interview with Robert Holler about the Winter product <a href="http://www.infoq.com/news/2014/02/versionone-winter2014-release">release</a>, and the 8th <a href="http://www.infoq.com/news/2014/02/versionone-2014-stateofagile">State of Agile™</a> survey results, Holler also spoke about the AgileLIVE™ webinar series the company is hosting. <br /> Details of the webinar series can be found <a href="http://www.versionone.com/agilelive/">here</a>.</p>
<p>InfoQ: Please can you tell us about the AgileLIVE webinar series you are hosting.</p>
<blockquote>
  We’ve been running the AgileLIVE webinar series for the last several years. Last year and this year the webinars have been focused on scaling agile. Last year a couple of the webinars focused primarily on the Scaled Agile FrameworkTM (SAFe), leadership and collaboration. 
 <br /> This year we’re kicking off the series looking at program and portfolio management. How do I organise, how do I prioritise, how do I collaborate, how do I make better decisions, and how do I ensure predictability at scale? We will probably have four or five of these webinars this year, all around scaling enterprise agile. 
 <br /> VersionOne has been around for nearly 12 years now, and we have a set of agile coaches who have worked for and with some of the largest organisations in the world; we’re going to share this experience and knowledge in our upcoming webinars. 
 <br /> We often do this in conjunction with our partners – we’ve previously had David Hussman from 
 <a href="http://devjam.com/">DevJam</a>, Mike Cottmeyer with 
 <a href="http://www.leadingagile.com/">LeadingAgile</a>,&nbsp;Pete Behrens with 
 <a href="http://www.trailridgeconsulting.com/">Trail Ridge Consulting</a>&nbsp;and Dean Leffingwell, author of 
 <a href="http://www.amazon.com/Scaling-Software-Agility-Enterprises-Development-ebook/dp/B0027976NQ/ref=sr_1_2">Scaling Software Agility</a>. 
 <br /> This time we’re presenting many of our own experiences from working in some very large-scale implementations, and we’re looking forward to sharing that knowledge.
</blockquote>
<p>InfoQ: What does Scaling Agile really mean?</p>
<blockquote>
 What it is NOT is just a large number of teams practicing agile side by side in the same organization. Clearly you’re not scaling agile effectively if that’s all you’re doing.
 <br /> Scaling agile is about navigating the often complex layers of organizational hierarchy, business alignment, visibility and transparency that exist in large organisations. You need to implement a collaborative infrastructure to support accelerated information and adaptive decision-making in this new world – it doesn’t matter if your structure is primarily hierarchical or matrixed; what’s important is that there is organizational alignment in the communication flow. Ideally when a team member is working on a task within an iteration, the decisions being made and activity result from your strategy, from which emanate goals, objectives, initiatives, projects, epics and stories - right down to the lowest-level task. 
 <br /> The scaling aspect is about ensuring the organisation is optimizing the delivery of business value across the entire value stream. These challenges have been dealt with by other software development methods for quite some time, but when you overlay agile – incremental, iterative and ideally done in a much more rapid fashion – you do inflict pain on an organisation. And let’s not only change, but let’s speed up change! This has amplified the need to quickly make sense of this chaos. I’ve got to make decisions in the context of all that’s going on in my organisation right now vs. a year ago, aligning with the strategy of the organisation right now and doing it in a way that I’m not wasting the organisation’s time and money. 
 <br /> It’s an exercise in truly applying Lean thinking – you want to optimize value across the entire system, you want to reduce all the waste you possibly can and you want to do that in alignment with the company strategy. This means we’re no longer aligning strategy on an annual or semi-annual basis; we’re aligning strategy in near-real time. This exacerbates the need for accelerated collaboration. Collaborative alignment is happening even within the context of an iteration, as a story moves from one state to another on a Kanban board. 
 <br /> In one sense agile makes things easier, but in another it really puts stress on the value chain. Without consistent processes in place, without collaboration, without transparency, without being able to manage rapid change, the system can crumble. That’s why we think that a collaborative management infrastructure like VersionOne is so helpful to companies making this transition.
 <br /> Scaling agile is not about getting a whole bunch of teams doing agile; it’s about getting teams aligned, collaborating, sharing, etc. and then providing real-time visibility into the state of the system across all the stakeholders in the organisation.
</blockquote>
<p>&nbsp;InfoQ: Thanks very much for taking the time to talk to us over these topics.</p>
<blockquote>
 It’s a pleasure
</blockquote>
<hr />
<p><br /> The first webinar of 2014 will be in two parts, on the 19th and 26th of February. Details and registration can be found <a href="http://pm.versionone.com/scaling-agile-to-program-portfolio-level-webinar">here</a>.<br /> They will be recorded and available for listening to after the event.</p><br><br><br><br><br><br></body></html>