<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Usando deployments “canário” para testes em produção</h3><p>De acordo com a empresa Nolio, em seu <a href="http://www.noliosoft.com/resources/videos/webinar/canary/show/1/">primeiro video de uma s&eacute;rie de melhores pr&aacute;ticas para DevOps</a>, empresas utilizam a t&eacute;cnica de &quot;Canary Deployments&quot; para testar software em produ&ccedil;&atilde;o, redirecionando um subgrupo de usu&aacute;rios para uma nova funcionalidade como parte das pr&aacute;ticas de continuous delivery (entregas cont&iacute;nuas). Um deploy &quot;canary&quot; (de <a href="http://bloglaurabotelho.blogspot.com.br/2011/01/canario-numa-mina-de-carvao.html">can&aacute;rio de mina</a>) &eacute; um tipo de vers&atilde;o incremental, instalada em paralelo &agrave; vers&atilde;o de produ&ccedil;&atilde;o. Executar m&uacute;ltiplas vers&otilde;es de um produto em uma mesma infraestrutura depende de software projetado para este tipo de configura&ccedil;&atilde;o e de uma perfeita automa&ccedil;&atilde;o do processo de deploy.</p> 
<p>Superar os desafios t&eacute;cnicos relacionados aos Canary Deployments reduz os riscos no processo de deploy, e possibilita <a href="http://blogs.msdn.com/b/seliot/archive/2009/12/25/don-t-just-listen-to-your-users-watch-them-with-online-experiments.aspx">testes A/B</a> e <a href="http://highscalability.com/blog/2011/12/12/netflix-developing-deploying-and-supporting-software-accordi.html">testes de performance</a> preventivos. Testes A/B permitem que os testes de novos requisitos se restrinjam apenas a um grupo reduzido de usu&aacute;rios, sem afetar o sistema por completo. Al&eacute;m disso, a execu&ccedil;&atilde;o de testes de performance n&atilde;o afeta o desempenho do sistema como um todo.</p> 
<p>Segundo a Nolio, a aplica&ccedil;&atilde;o de Canary Deployments consiste das seguintes etapas:</p> 
<ol start="1"> 
 <li>Estabelecer uma plataforma de artefatos para deploy incluindo artefatos de build, scripts de testes, arquivos de configura&ccedil;&atilde;o e manifestos de deploy;</li> 
 <li>Remover servidores can&aacute;rio do balanceador de carga;</li> 
 <li>Atualizar a aplica&ccedil;&atilde;o can&aacute;rio (drenagem e implanta&ccedil;&atilde;o);</li> 
 <li>Realizar testes automatizados da aplica&ccedil;&atilde;o;</li> 
 <li>Recuperar servidores can&aacute;rio de volta ao balanceador de carga (conectividade e testes de sanidade);</li> 
 <li>Atualizar o restante dos servidores, caso os testes da vers&atilde;o can&aacute;rio forem bem sucedidos (ou executar rollback caso contr&aacute;rio).</li> 
</ol> 
<p>A Nolio incluiu na sua apresenta&ccedil;&atilde;o uma <a href="http://www.noliosoft.com/product/zero-touch-deployment">vis&atilde;o geral do uso de seu produto</a>, para uma orquestra&ccedil;&atilde;o de n&iacute;vel mais alto referente os deploys &quot;can&aacute;rio&quot;. A empresa utiliza um modelo de aplica&ccedil;&atilde;o que pode ser reutilizado em diversos processos, guiando o uso destes atrav&eacute;s de seus dados. A administra&ccedil;&atilde;o, assim como a emiss&atilde;o de relat&oacute;rios pode ser realizada de forma paralela ao &quot;deploy can&aacute;rio&quot;.</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>