<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Twitter abre o código do Summingbird</h3><div> 
 <p class="p1">O Twitter abriu o c&oacute;digo do Summingbird, uma biblioteca para constru&ccedil;&atilde;o de solu&ccedil;&otilde;es MapReduce que permite a execu&ccedil;&atilde;o em batch, real-time ou h&iacute;brido.</p> 
 <p class="p1">Em seu blog o Twitter explica que, quando era necess&aacute;rio escrever solu&ccedil;&otilde;es MapReduce baseadas em streaming de dados, utilizava-se bibliotecas como o <a href="http://pig.apache.org/"><span class="s1">Pig</span></a> ou o <a href="https://github.com/twitter/scalding"><span class="s1">Scalding</span></a> para escrever a l&oacute;gica e o <a href="http://hadoop.apache.org/"><span class="s1">Hadoop</span></a> para execut&aacute;-las. Tais solu&ccedil;&otilde;es eram geralmente executadas com intervalos de horas ou dias e, sim, eram muito eficientes.</p> 
 <p class="p1">Por&eacute;m, havia a necessidade da an&aacute;lise de dados em tempo real, e da&iacute; surgiu o desenvolvimento do <a href="http://storm-project.net/"><span class="s1">Storm</span></a>. Sacrificando a garantia de toler&acirc;ncia a falhas encontrada no Hadoop, o Storm possibilitou a execu&ccedil;&atilde;o de aplica&ccedil;&otilde;es MapReduce pr&oacute;ximo ao chamado tempo real.</p> 
 <p class="p1">Com uma solu&ccedil;&atilde;o que mistura a execu&ccedil;&atilde;o em batch e em tempo real das fontes de dados, algumas dificuldades surgiram, tais como:</p> 
 <ul class="ul1"> 
  <li class="li2">A necessidade de manter duas l&oacute;gicas em diferentes sistemas;</li> 
  <li class="li2">A serializa&ccedil;&atilde;o consistente dos conjuntos chave-valor entre os diferentes sistemas e a aplica&ccedil;&atilde;o cliente que ir&aacute; consumir o resultado da aplica&ccedil;&atilde;o MapReduce e;</li> 
  <li class="li2">A necessidade de implementa&ccedil;&atilde;o de um mecanismo na aplica&ccedil;&atilde;o cliente de &quot;merge&quot; dos resultados providos pelos dois sistemas.</li> 
 </ul> 
 <p class="p1">E &eacute; para esses problemas que o Summingbird foi desenvolvido. O summingbird permite a execu&ccedil;&atilde;o dessas aplica&ccedil;&otilde;es MapReduce baseadas em streaming de dados pelo Hadoop e cuida do armazenamento dos resultados em um banco de dados de somente leitura. Os dados que n&atilde;o s&atilde;o processados pelo Hadoop s&atilde;o processados pelo Storm. O Summingbird tamb&eacute;m &eacute; respons&aacute;vel por ler os resultados dos dois sistemas e fazer o merge das informa&ccedil;&otilde;es para as aplica&ccedil;&otilde;es clientes.</p> 
 <p class="p1">O projeto possui um <a href="https://github.com/twitter/summingbird/wiki"><span class="s1">wiki</span></a> com os detalhes da biblioteca. Para quem est&aacute; interessado em contribuir, h&aacute; diversas frentes para o desenvolvimento do Summingbird, como o desenvolvimento do suporte a mais plataformas de execu&ccedil;&atilde;o (Akka e Spark) e a constru&ccedil;&atilde;o de extens&otilde;es ao projetos relacionados ao Summingbird.</p> 
 <p class="p3"><span class="s2">O <a href="https://github.com/twitter/summingbird"><span class="s3">Summingbird</span></a> &eacute; disponibilizado atrav&eacute;s da <a href="http://www.apache.org/licenses/LICENSE-2.0.html"><span class="s3">licen&ccedil;a Apache Vers&atilde;o 2.0</span></a>.</span></p> 
</div><br><br><br><br><br><br></body></html>