<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Windows Embedded 8: versão final e alinhamento com Windows 8</h3><p>A Microsoft <a href="http://www.microsoft.com/en-us/news/Press/2013/mar13/03-20Embedded8PR.aspx">anunciou</a> o lan&ccedil;amento do <a href="http://www.getwindowsembedded8.com/">Windows Embedded 8</a> (WE8), a vers&atilde;o do Windows projetada para aplica&ccedil;&otilde;es comerciais e industriais. Em contraste com o Windows 8 lan&ccedil;ado recentemente, a vers&atilde;o para sistemas embarcados &eacute; projetada para uso em dispositivos de pontos-de-vendas dedicados, equipamentos da &aacute;rea da sa&uacute;de e sistemas de fabrica&ccedil;&atilde;o, entre outros.</p> 
<p>A plataforma do WE8 &eacute; composta de tr&ecirc;s diferentes edi&ccedil;&otilde;es: Standard, Pro e Industry Release Preview. Cada edi&ccedil;&atilde;o visa diferentes mercados, assim descritas pela Microsoft:</p> 
<blockquote> 
 <ul> 
  <li><strong>Standard</strong> - ... vers&atilde;o totalmente funcional do sistema operacional desktop da Microsoft destinado ao uso em uma solu&ccedil;&atilde;o embarcada, que consista de hardware especificamente constru&iacute;do e de software de aplica&ccedil;&atilde;o.</li> 
  <li><strong>Pro</strong> - ... vers&atilde;o componentizada e mais completa do Windows 8, com tecnologias adicionais que ampliam o poder do Windows para dispositivos especializados.</li> 
  <li><strong>Industry, Release Preview</strong> - vers&atilde;o projetada para a constru&ccedil;&atilde;o de dispositivos diferenciados que fazem parte de <a href="http://www.google.com/url?q=http%3A%2F%2Fwww.getwindowsembedded8.com%2Ffiles%2FWindows%2520Embedded%2520Intelligent%2520Systems%2520-%2520IDG%2520-%2520Whitepaper.pdf&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNHGZTB6S9RH3WIPwZMwlgPIUbkSnQ">sistemas inteligentes</a> [encontrados nos setores de varejo, financeiro, de hotelaria etc.].</li> 
 </ul> 
</blockquote> 
<p>O Windows Embedded oferece o <a href="http://blogs.msdn.com/b/windows-embedded/archive/2012/06/18/what-is-lockdown-and-branding-in-windows-embedded-standard-8-and-where-are-my-eefs.aspx">Lockdown</a>, conjunto de funcionalidades projetadas para dar maior controle sobre opera&ccedil;&otilde;es do Windows, aos fabricantes de equipamentos originais (sigla OEM, em ingl&ecirc;s), al&eacute;m de fabricantes de dispositivos. Dentre estas funcionalidades est&atilde;o o Keyboard Filter, o Dialog Filter, o Application Launcher (inicializador de aplicativos) e o Embedded Lockdown Manager.</p> 
<p>Outro benef&iacute;cio de usar o Windows Embedded em rela&ccedil;&atilde;o ao Windows desktop tradicional &eacute; o maior ciclo de vida de suporte do produto. As s&eacute;ries embedded t&ecirc;m per&iacute;odo de suporte de 10 anos e disponibilidade global do produto de 15 anos. Note que, diferentemente do <a href="http://www.microsoft.com/windowsembedded/en-us/evaluate/choose-a-windows-embedded-operating-system.aspx?DeviceTypeID=8">Windows Embedded Compact 7</a>, a plataforma WE8 requer o uso de um plug-in de terceiros para fornecer suporte do sistema operacional em tempo real.</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>