<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Bletchley ParkとTMNOCとの大きな問題</h3><p><a target="_blank" href="http://www.infoq.com/news/2014/02/bletchley-part"><em>原文(投稿日：2014/02/05)へのリンク</em></a></p>
<div class="article_page_left news_container text_content_container"> 
 <div class="text_info"> 
  <p><img src="http://www.infoq.com/resource/news/2014/02/bletchley-part/ja/resources/1Colossus.jpg" width="25%" align="right" alt="" _href="img://1Colossus.jpg" _p="true" />今日2月5日は，最初の電子計算機である<a href="http://www.tnmoc.org/news/news-releases/veterans-celebrate-colossus-70">Colossusの開発から70周年</a>にあたる日だ。ColossusはLorenzの暗号メッセージ解読を目的として1944年2月5日に運用が開始され，同年6月にはMark IIがサービスに加わっている。機密上の理由のため，それよりも有名なENIAC(1946年に製造された)の方が，最初に作られたコンピュータだと一般的に思われていた。しかしColossusが最初の電子計算機であったとはいえ，ENIACがプログラム可能なコンピュータの第1号であるという事実に変わりはない。Closssusのタスクは固定的なものだったからだ。</p> 
  <p>Colossusは今，Bletchley Park内の<a href="http://www.tnmoc.org">National Museum of Computing</a>にある，<a href="http://www.tnmoc.org/explore/colossus-gallery">Colossusギャラリ</a>に置かれている。Clossusが再生されたのは<a href="http://en.wikipedia.org/wiki/Tony_Sale">Tony Sale</a>氏の多大な努力に加えて，同地域の住宅建設ブームに伴う再開発からマシンと<a href="http://www.codesandciphers.org.uk/lorenz/rebuild.htm">Bletchley Parkとを守った</a>，多くの人々の協力によるものだ。</p> 
  <p>Colossusの再生が可能だったのは，さまざまな技術者たちの記憶を頼りに，最初の原理と発見された断片的な情報からマシンを復元することができたからだ。英国の読者は，<a href="http://www.bbc.co.uk/programmes/p01qt674">BBCワールドサービス</a>で何人かの技術者のインタビューを聞くことができる。またTony Sale氏の個人的なサイトには，Colossusが復元されることになった状況に関する説明が<a href="http://www.codesandciphers.org.uk/lorenz/rebuild.htm">現在も公開されている</a>。 TNMOCを訪れてみれば，暗号ホイールの組み合わせを検索してコードを解読すべく高速動作するColossusマシンを見ることができる。</p> 
  <p>しかしながら，Bletchley Parkのすべてがうまくいっている訳ではない。<a href="http://www.bbc.co.uk/news/uk-england-beds-bucks-herts-15171726">HLF(Heritage Lottery Fund, 遺産宝くじ基金)から460万ポンドの助成金</a>を獲得してからは，<a href="http://www.bletchleypark.org.uk">Bletchley Park Trust</a>(実現にはTony Sale氏の尽力があった)が公園の運営を一手に引き受けている。最初の問題は，建屋の一部を所有していた<a href="http://www.rmweb.co.uk/community/index.php?/topic/57966-milton-keynes-mrs-to-close-at-bletchley-park/">Model Railway Society</a>が，将来的なアトラクションのために再開発を予定していたことだった。次に火種となったのは<a href="http://www.miltonkeynes.co.uk/what-s-on/arts/exhibition-closure-is-sad-for-family-1-5163600">チャーチル記念館</a>で，同じような理由で施設の退去を求めてきた。毎年恒例だったBletchley Park花火大会(Blitz Night)が<a hre="http://www.mkweb.co.uk/News/Building-work-forces-postponement-of-popular-Bletchley-events-20131013150000.htm">短期間で中止された</a>理由も同じだ。</p> 
  <p>Bletchley Parkにおける他の展示 – <a href="http://www.mkheritage.co.uk/bpt/mkars/station_x.html">Station X</a>や<a href="http://www.tnmoc.org">The National Museum of Computing</a>なども同じように，訪問者の混乱から始まって，Bletch Park自身が直接所有していない歴史的展示物の意図的な排除に至るまで，さまざまな懸念を抱えている。HLFのファンドがサイトの歴史的建造物保存に使用されるはずだったにも関わらず，TMNOCはBletchley Parkに<a href="http://www.tnmoc.org/news/news-releases/deciphering-discontent-statement-tnmoc-trustees">毎年100,000ポンド</a>を支払っているのだ。</p> 
  <p><img src="http://www.infoq.com/resource/news/2014/02/bletchley-part/ja/resources/1TonyCarroll.png" width="25%" align="right" alt="" _href="img://1TonyCarroll.png" _p="true" />先週には，大胆にもColossus展示を来訪者に紹介していたBletchley Parkのツアーガイドが<a href="http://www.independent.co.uk/news/uk/home-news/sacked-for-breaking-code-of-conduct-rivalry-between-bletchley-park-charities-tumbles-out-of-control-9091672.html">無造作に解雇される</a>，という事態も起きている。その様子は<a href="http://www.bbc.co.uk/news/uk-25916048">BBCによる調査</a>の一環として<a href="http://www.youtube.com/watch?v=d5n9eVVtKeA">カメラで撮影された</a>。この件が，<a href="http://www.bletchleypark.org.uk/news/v.rhtm/Crossed_Wires_at_Bletchley_Park-755638.html">暗号解析作業にまつわる物語を国民に伝える責任がある</a>にも関わらず，Bletchley ParkがClossusを歴史から抹消しようとしている，という<a href="http://www.tnmoc.org/news/notes-museum/deciphering-dissent-bletchley-park">批判</a>を呼んでいる。ニュースで報道されたボランティアのTony Carroll氏は，ツアーの職務を剥奪されたものの，教育コンサルタントとしての職務は続けている。</p> 
  <p><img src="http://www.infoq.com/resource/news/2014/02/bletchley-part/ja/resources/1CheckpointCharlie.jpg" width="25%" align="left" alt="" _href="img://1CheckpointCharlie.jpg" _p="true" />Bletchley Parkを巡る分裂は，Bletchley ParkのメインパークとColossusの場所を結ぶ道を分断する&quot;<a href="https://twitter.com/Craig_Lewis77/status/429533132782829568">Checkpoint Charlie</a>&quot;(統一前の東西ベルリンに配置された国境検問所)によって続いている。来訪者のエクスペリエンスを統一するため，チケットを組み合わせて両施設の訪問を簡単にしようという呼びかけがある一方で，Bletchley Parkの現在の経営陣は，<a href="http://www.tnmoc.org/news/news-releases/bigger-picture-fragmenting-heritage-site">エクスペリエンスを統一する動きに対して抵抗を示している</a>。現在，Bletchley Parkの来訪者に対して，Colossusマシンやその復元プロジェクトに関する言及はまったくない。遺産基金の適用については引用されているにも関わらず，来訪者の多くは国家の重要な歴史のひとつを見ることさえないのだ。</p> 
  <p><img src="http://www.infoq.com/resource/news/2014/02/bletchley-part/ja/resources/NoCheckpoint.png" width="25%" align="right" alt="" _href="img://NoCheckpoint.png" _p="true" /><a href="http://www.bbc.co.uk/news/magazine-15739984">Google</a>も<a href="http://www.theregister.co.uk/2011/12/15/google_give_half_a_mill_to_computer_museum/">Bletchley Parkに対して貢献</a>を行っている。HLF基金の一部として50万ポンドを寄贈した際，同社の元CEOであるSimon Grenish氏は，&quot;私たちのコンピューティング遺産の保存を支援するため，Googleの例にぜひ続いてほしいと思います&quot;と語っている。しかしこの資金はその後，メインパークとこのコンピューティング遺産とを隔てるフェンスの設置に使用されてしまった。 少なくとも<a href="http://www.google.com/culturalinstitute/exhibit/bletchley-park-home-of-the-codebreakers/wRANFg9s?position=38%2C0">Google Cultural Institute</a> には，Colossusに関する言及はない。ここはまた，マップを修正編集するオンラインツールの<a href="http://www.miltonkeynes.co.uk/news/local/google-map-maker-launched-at-bletchley-park-1-4989372">MapMaker</a>のローンチ場所として，Googleが選択したロケーションでもある。GoogleのカメラカーにもBletchley Park周辺の建造物が撮影されている。皮肉なことにGoogleカメラカーは<a href="http://goo.gl/MAh2TW">フェンスが設置される前のCheckpoint Charlieの位置を示している</a>ため，現在のBletchley Park管理団体の主導した変更の様子がはっきりと確認できる。</p> 
  <p>最近になってThe National Museum of Computingは，<a href="http://www.mkweb.co.uk/News/Education/The-National-Museum-of-Computing-wins-prestigious-award-20140203200000.htm">権威あるBETT(British Educational Technology and Training)賞</a>を獲得し，現在もBletchley Parkサイトでオープンしている。<a href="http://freelance.halfacree.co.uk/2014/01/disharmony-at-bletchley-park/">少なくとも今のところは</a>。いつまでこの状態が続くのだろうか。</p> 
 </div> 
</div><br><br><br><br><br><br></body></html>