<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Backbone.js 1.0: primeira versão maior em 2 anos</h3><p>Ap&oacute;s dois anos e meio de desenvolvimento, a vers&atilde;o 1.0 do Backbone.js foi lan&ccedil;ada. O Backbone.js &eacute; uma popular biblioteca JavaScript que segue o modelo Model/View, utilizada por v&aacute;rios aplicativos web populares, incluindo USA Today, Rdio e Airbnb.</p> 
<p>O Backbone.js oferece tr&ecirc;s principais componentes de constru&ccedil;&atilde;o para os usu&aacute;rios:</p> 
<ol start="1"> 
 <li>Os <strong>Models</strong> s&atilde;o usados para representar objetos persistentes. Usando a funcionalidade de sincroniza&ccedil;&atilde;o do Backbone.js, os modelos podem automaticamente sincronizar com uma fonte de dados remota (por padr&atilde;o, um Web Service RESTful). Da mesma forma, o Backbone.js oferece facilidades para gerenciar e sincronizar cole&ccedil;&otilde;es de modelos com o servidor.</li> 
 <li>As<strong> </strong><strong>Views</strong> s&atilde;o usadas na constru&ccedil;&atilde;o de interfaces de aplica&ccedil;&otilde;es web e podem ser configuradas para ouvir eventos de mudan&ccedil;as dos modelos que elas representam, tornando f&aacute;cil manter a interface atualizada com o modelo e vice-versa.</li> 
 <li>O <strong>roteador</strong><em> </em>(router) d&aacute; suporte a navega&ccedil;&atilde;o em uma aplica&ccedil;&atilde;o Backbone.js. Embora as aplica&ccedil;&otilde;es baseadas em Backbone.js sejam normalmente interfaces de uma p&aacute;gina, &eacute; desej&aacute;vel ter URLs que possam ser adicionadas aos favoritos, al&eacute;m de se permitir a utiliza&ccedil;&atilde;o do bot&atilde;o voltar na navega&ccedil;&atilde;o. O roteador do Backbone.js adiciona essas funcionalidades atrav&eacute;s da nova API de hist&oacute;rico do HTML5 e, quando esta &uacute;ltima n&atilde;o &eacute; suportada, utiliza o modelo antigo de hash de URL.</li> 
</ol> 
<p>A vers&atilde;o 1.0 do Backbone.js traz algumas mudan&ccedil;as em compara&ccedil;&atilde;o com vers&otilde;es da s&eacute;rie 0.9, que incluem uma maneira mais inteligente de realizar atualiza&ccedil;&otilde;es em massa de cole&ccedil;&otilde;es; decodifica&ccedil;&atilde;o autom&aacute;tica de segmentos de URL; e os novos m&eacute;todos <strong>listenTo</strong> e <strong>stopListening</strong> para emissores de eventos. Por padr&atilde;o, a valida&ccedil;&atilde;o de modelos agora &eacute; adiada at&eacute; o momento em que os modelos s&atilde;o salvos, enquanto em vers&otilde;es anteriores, a valida&ccedil;&atilde;o ocorria imediatamente ao configurar as propriedades de um modelo. Nenhuma dessas mudan&ccedil;as acarreta quebra de compatibilidade, portanto atualiza&ccedil;&otilde;es da vers&atilde;o 0.9 para 1.0 devem ser tranquilas.</p> 
<p>A premissa essencial no cora&ccedil;&atilde;o do Backbone tem sido sempre encontrar e descobrir o conjunto m&iacute;nimo de primitivas na estrutura&ccedil;&atilde;o de dados (Modelos e Cole&ccedil;&otilde;es) e de interface do usu&aacute;rio (Views e URLs) que sejam &uacute;teis na constru&ccedil;&atilde;o de aplica&ccedil;&otilde;es web com JavaScript. Continuaremos procurando esse tipo espec&iacute;fico de caracter&iacute;stica, e se voc&ecirc; acha que encontrou uma dessas caracter&iacute;sticas, avise-nos. Em um ecossistema onde frameworks abrangentes do tipo &quot;decidimos-tudo-por-voc&ecirc;&quot; s&atilde;o comuns, e muitas bibliotecas exigem que seu site seja reestruturado para se encaixar nas apar&ecirc;ncias e comportamentos padr&otilde;es delas, o Backbone continuar&aacute; a ser uma ferramenta que lhe d&aacute; a liberdade para projetar a experi&ecirc;ncia completa para suas aplica&ccedil;&otilde;es web.</p> 
<p>A vers&atilde;o 1.0 do Backbone.js pode ser baixada como uma &uacute;nico arquivo fonte JavaScript. A vers&atilde;o minimizada e comprimida tem 6.3KB. O Backbone.js tem como depend&ecirc;ncias o underscore.js, assim como o jQuery ou o Zepto, quando se faz uso de funcionalidades que trabalham com DOM, como as Views e o Router.</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>