<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Design Patterns para aplicações hospedadas na nuvem</h3><p>O <a href="http://pnp.azurewebsites.net/en-us/">grupo de padr&otilde;es e pr&aacute;ticas</a> da Microsoft liberou um <a href="http://msdn.microsoft.com/en-us/library/dn568099.aspx">guia</a> com solu&ccedil;&otilde;es e padr&otilde;es adequados ao implementar aplicativos hospedados na nuvem. O guia aborda os problemas que diferentes padr&otilde;es enfrentam juntos com os benef&iacute;cios e poss&iacute;veis desvantagens. A ambi&ccedil;&atilde;o do grupo tem sido o de fornecer orienta&ccedil;&otilde;es para sistemas independente da plataforma na nuvem, embora os exemplos dados sejam dirigidos ao <a href="http://www.windowsazure.com/">Windows Azure</a>.</p>
<p>Usando o feedback da comunidade de desenvolvedores, o grupo identificou oito categorias de problemas que acreditam cobrir as &aacute;reas mais comuns no desenvolvimento de aplicativos na nuvem:</p>
<ul class="c2 lst-kix_iryl10sclpa9-0 start"> 
 <li><a href="http://msdn.microsoft.com/en-us/library/dn600219.aspx">Disponibilidade</a></li> 
 <li><a href="http://msdn.microsoft.com/en-us/library/dn600216.aspx">Gerenciamento de dados</a></li> 
 <li><a href="http://msdn.microsoft.com/en-us/library/dn600217.aspx">Implementa&ccedil;&atilde;o e Design</a></li> 
 <li><a href="http://msdn.microsoft.com/en-us/library/dn600220.aspx">Mensagens</a></li> 
 <li><a href="http://msdn.microsoft.com/en-us/library/dn600218.aspx">Gest&atilde;o e Monitoramento</a></li> 
 <li><a href="http://msdn.microsoft.com/en-us/library/dn600224.aspx">Performance e Escalabilidade</a></li> 
 <li><a href="http://msdn.microsoft.com/en-us/library/dn600215.aspx">Elasticidade</a></li> 
 <li><a href="http://msdn.microsoft.com/en-us/library/dn600221.aspx">Seguran&ccedil;a</a></li> 
</ul>
<p>Para cada uma dessas categorias, o grupo criou manuais e documentou padr&otilde;es comuns para ajudar os desenvolvedores na solu&ccedil;&atilde;o de problemas frequentemente encontrados.</p>
<p>O guia cont&eacute;m dez cartilhas e t&oacute;picos de orienta&ccedil;&atilde;o fornecendo conhecimentos b&aacute;sicos e t&eacute;cnicas de boas pr&aacute;ticas, cada uma cobrindo um aspecto do desenvolvimento da aplica&ccedil;&atilde;o e visando uma das categorias. Entre os t&oacute;picos cobertos est&atilde;o inclusos Asynchronous Messaging, Caching e Data Consistency.</p>
<p>Tamb&eacute;m est&atilde;o inclusos 24 design patterns que o grupo encontrou utilidade em aplica&ccedil;&otilde;es hospedadas na nuvem, cada padr&atilde;o pertence a uma ou mais das categorias descritas. Exemplos de padr&otilde;es inclusos s&atilde;o Compensating Transaction, Command and Query Responsibility Segregation (CQRS) e Pipes e Filters. Cada padr&atilde;o &eacute; descrito em um formato comum com o contexto e problema em que se aplica, a solu&ccedil;&atilde;o dada pelo padr&atilde;o juntamente com quest&otilde;es e considera&ccedil;&otilde;es para a aplica&ccedil;&atilde;o do padr&atilde;o. Um exemplo para o Azure tamb&eacute;m &eacute; fornecida para cada padr&atilde;o.</p>
<p>Para demonstrar o uso dos design patterns descritos o grupo criou dez aplica&ccedil;&otilde;es de exemplo com todo o c&oacute;digo dispon&iacute;vel para <a href="http://www.microsoft.com/en-us/download/details.aspx?id=41673">download</a>. Os exemplos incluem uma aplica&ccedil;&atilde;o sobre consumo concorrente que recebe mensagens de um service bus e um outro exemplo utilizando filtros para simula&ccedil;&atilde;o de pipelines.</p>
<p>O grupo P &amp; P enfatiza que os exemplos est&atilde;o simplificados e n&atilde;o foram concebidos para uso em produ&ccedil;&atilde;o.</p>
<p>Windows Azure &eacute; a plataforma na nuvem fornecida pela Microsoft.</p><br><br><br><br><br><br></body></html>