<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>SDKやコンパイル、コードの署名なしにデバイス上のPhoneGapアプリケーションをテストする</h3><p><a target="_blank" href="http://www.infoq.com/news/2014/04/phonegap-developer-app"><em>原文(投稿日：2014/04/23)へのリンク</em></a></p>
<div class="article_page_left news_container text_content_container"> 
 <div class="text_info"> 
  <p>PhoneGapがアプリケーションのテストツールである<a href="http://app.phonegap.com/">PhoneGap Developer App</a>をリリースした。このツールは、アプリケーション開発時のテストにおいて、SDK一式やコンパイル、コードの署名が必要ないというものである。なお、GapReloadと組み合わせたLiveReloadも同じことを行うことができる。</p> 
  <p>このアプリケーションを使うには、<a href="http://phonegap.com/install/">PhoneGap CLI</a>を開発マシンに用意し、<a href="https://itunes.apple.com/app/id843536693">iOS App Store</a>もしくは<a href="https://play.google.com/store/apps/details?id=com.adobe.phonegap.app">Google Play</a>からPhoneGap Developer Appをインストールする必要がある。なお、近日中のWindowsサポートが期待されている。モバイルアプリケーションに特化したPhoneGap CLIの<code>serve</code>コマンドを実行することによって、開発マシンがサーバとなり、WiFi経由でPhoneGapアプリケーションとペアになる。サーバはコードの変更を監視し、ネイティブのコンパイル処理やコードの署名なしに、自動で端末に変更内容を送信する。AdobeのPhoneGap開発者である<a href="http://www.raymondcamden.com/index.cfm/2014/4/21/PhoneGap-Developer-App">Raymond Camden氏によると</a>、このことは、WindowsマシンからiOSアプリケーションをテストすることをも可能にするという。</p> 
  <p>個別にインストールせずに済むように、PhoneGap Developer AppにはPhoneGapの主要なプラグインが同梱されている。なお<a href="http://www.raymondcamden.com/index.cfm/2014/4/21/PhoneGap-Developer-App#c41C71F06-EE43-763E-57166ED3DF528B98">Shazron氏</a>は、Adobe社はこのところアプリケーションのオープンソース化を推し進めており、そのため、サードパーティ製プラグイン追加の拡張が可能であると述べた。</p> 
  <p>現在、コードの変更やデバイスへの転送の際にアプリケーションページが再読み込みされる。なお、Camden氏によると、Developer AppとSafariもしくはChromeのリモードデバッガを同時に動かすことはできないが、<a href="http://people.apache.org/~pmuellr/weinre/docs/latest/Home.html">Weinre</a>は動作するという。</p> 
  <p>同じようなことをする他の方法としては、<a href="http://livereload.com/">LiveReload</a>と<a href="https://github.com/fingerproof/cordova-plugin-gapreload">GapReload</a>というオープンソースのアプリケーションを組み合わせる方法がある。LiveReloadはWebアプリケーションで動作し、iOSデバイスとWindowsにコードを転送できる。このツールの父である<a href="http://feedback.livereload.com/forums/157942-general/suggestions/2943105-android-support">Andrey Tarantsov氏によると</a>、次のバージョンでAndroidサポートが入るという。GapReloadは、PhoneGap/Cordovaアプリケーションのサポートに特化したLiveReloadプラグインである。LiveReloadよりも優れている点としては、ページのリロードのためにコードを変更する必要がないという点である。<a href="http://twitter.com/@_sebastienp">Sebastien Paul氏は</a>、「CSSファイルを編集しても、LiveReloadならページを全更新する必要がなく、すぐさま新しいルールを適用します。これは本当に便利です」と述べている。</p> 
 </div> 
</div><br><br><br><br><br><br></body></html>