<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Netflix Gives Up Silverlight, Chooses HTML5</h3><p>Netflix has announced their intent to switch their video player&nbsp;from Silverlight to HTML5, the first implementation of the new player being done in Chrome/Chrome OS, with Windows and Mac OS X following soon.</p> 
<p>Netflix is responsible for <a href="http://www.infoq.com/presentations/Netflix-Architecture;jsessionid=F8E29ED4D56B90BE82C13AE049131765">one third of all downloaded traffic</a> in North America, according to Adrian Cockcroft,&nbsp;Director of Architecture for the Cloud Systems&nbsp;at Netflix, and all those bytes have been streamed to a Silverlight application so far, but that is about to change.</p> 
<p>Netflix has recently announced the <a href="http://techblog.netflix.com/2013/04/html5-video-at-netflix.html">intention to switch to HTML5</a> from Silverlight. Among the main reasons they mention Microsoft’s mention to <a href="http://support.microsoft.com/gp/lifean45#sl5">stop supporting Silverlight 5 in 2021</a> without any word being spoken about Silverlight 6. They also blame the fact that one has to install the Silverlight plug-in before being able to stream content, and some users refuse to install such plug-ins for security reasons.&nbsp;Also, a&nbsp;problem is that newer&nbsp;browsers do not support plug-ins, such as Safari&nbsp;on iOS or IE on Windows 8/Metro. Another problem we could add is that <a href="http://www.microsoft.com/getsilverlight/locale/en-us/html/installation-win-SL5.html">Windows 8 and Linux are not listed among Silverlight-compatible operating systems</a>. And most comments to Netflix’s announcement were requests for official Linux support.</p> 
<p>Netflix will solve those problems by embracing HTML5, and the first application has been developed and is being under testing on Chrome OS. Google has shown interest in implementing a number of HTML5 enhancements requested by Netflix, named “HTML5 Premium Video Extensions”:</p> 
<ul> 
 <li><a href="http://www.w3.org/TR/media-source/">Media Source Extensions</a>&nbsp;– enables an application to use JavaScript for streaming content. This provides flexibility for a web app&nbsp;in choosing the right CDN for streaming and switching to another where there are issues with the first one.</li> 
 <li><a href="https://dvcs.w3.org/hg/html-media/raw-file/tip/encrypted-media/encrypted-media.html">Encrypted Media Extensions</a>&nbsp;– adds DRM support</li> 
 <li><a href="http://www.w3.org/TR/WebCryptoAPI/">Web Cryptography API</a>&nbsp;– a JavaScript API providing encryption support. Netflix encrypts most communication with back-end servers to ensure viewer’s privacy. Netflix sends a lot of logging information back to their servers, more exactly about 4.5% of all North America upwards traffic, according to Cockcroft.</li> 
</ul> 
<p>Currently Netflix uses a Pepper plug-in for encryption purposes until Google implements Web Cryptography API in Chrome, at that point Netflix intending to open up their HTML5 video application for testing under Windows and Mac OS X.</p> 
<p>Rumors regarding Silverlight’s demise have circulated at least since 2010 when <a href="http://www.infoq.com/news/2010/09/Silverlight-Web-Apps;jsessionid=F8E29ED4D56B90BE82C13AE049131765">it’s future started being debated</a>, with <a href="http://www.infoq.com/news/2011/09/Silverlight-5-RC;jsessionid=F8E29ED4D56B90BE82C13AE049131765">Microsoft showing their commitment for the platform</a> with the release of Silverlight 5 in 2011, followed by contradictory messages later on and <a href="http://www.infoq.com/news/2011/09/Metro-Plug-ins;jsessionid=F8E29ED4D56B90BE82C13AE049131765">the decision to stop supporting any plug-ins in IE Metro</a>. If there were any doubts before, now we can say with a high degree of confidence that Silverlight has no future. With Flash suffering from similar problems, it remains for HTML5 to occupy the RIA space in the following years.</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>