<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>DXperience 13.2 - 新しいASP.NETアイコンライブラリ，新テーマ，スマートタグサポートの拡大と強化</h3><p><a target="_blank" href="http://www.infoq.com/news/2013/11/dxperience-13-2"><em>原文(投稿日：2013/11/16)へのリンク</em></a></p>
<div class="article_page_left news_container text_content_container"> 
 <div class="text_info"> 
  <p>DXperience 13.2には新しい<a href="https://community.devexpress.com/blogs/aspnet/archive/2013/11/07/asp-net-icon-library-what-s-new-in-13-2.aspx">アイコンライブラリ</a>が付属する。DevExpress ASP.NETのコントロールからは，IconIDプロパティを使って利用できる。ナビゲーションバーコントロールにアイコンが必要ならばItems.Image.IconIDプロパティを使う，という具合だ。IconIDプロパティを選択すれば，アイコンの選択が可能な編集ダイアログが表示される。<br /> <br /> <img src="http://www.infoq.com/resource/news/2013/12/dxperience-13-2/ja/resources/Icon_Library.png" alt="" _href="img://Icon_Library.png" _p="true" /></p> 
  <p>公式発表によると，ライブラリに含まれるアイコンはImagePropertiesクラスから継承され，16x16と32x32フォーマットのカラーおよびグレースケールの形式が用意される。<br /> <br /> さらに，要素の大部分の描画に最新のCSS3技術を使用した<a href="https://community.devexpress.com/blogs/aspnet/archive/2013/11/13/asp-net-moderno-theme-what-39-s-new-in-13-2.aspx">Moderno</a>テーマも追加される。パッドのサイズが大きいため，タッチベースのモバイルデバイスにも問題なく対応する。</p> 
  <p><a href="/resource/news/2013/12/dxperience-13-2/ja/resources/Moderno_Padding_Original.png" target="_blank"><img src="http://www.infoq.com/resource/news/2013/12/dxperience-13-2/ja/resources/Moderno_Padding.png" alt="" _href="img://Moderno_Padding.png" _p="true" /></a></p> 
  <p>今回のリリースにはWinForms用のテーマが３つ，新たに含まれる。Visual Studio Color Themeがすべてのコントロールデザイナでサポートされることも合わせて，従来より改良されたデザイン時エクスペリエンスを提供する。新機能を使えば，デザイナのスキン設定を修正して，Visual Studioのカラーテーマにマッチさせることも可能になる。スマートタグのサポートも含まれている。BarCodeControlやButtonEdit, CalcEdit, CheckButton, ComboBoxEditなど，WinForms Data Editors Libraryのコントロールも含むすべてのコントロールが対象だ。</p> 
  <p>DXperience 13.2の新しいリボンコントロールは，データバインディングをサポートすると同時に，テンプレートに加えてレイアウトやリッチクライアント側のイベントにも対応する。ASP.NETスプレッドシートコントロールも今回のリリースで新しくなった。自動化された数式演算エンジン，スプレッドシート組み込み関数，セル参照，セルフォーマットなどの機能を備えたＵＩの自動生成が可能だ。グラフ生成や画像，ワークシート管理などの機能も装備する。<br /> <br /> Gridコントロールではバッチ編集がサポートされた。レコードをクライアント側でバッチ編集して，単一のリクエストでサーバに送信することができる。Token Ｂｏｘという新しいコントロールが追加され，定義済のリストと凡例チェックボックスを使って，グラフ要素のさまざまな表示形式をユーザが選択できるようになる。ちなみにチャートコントロールは，グラフのサイズやズームレベルに基づいてデータレンダリングを行う。</p> 
  <p>カラー選択コントロールも新しくなった。クッキーのコレクションとして指定されるドロップダウンを通じて，独自の色を選択することができる。データバインディングやヘルプテキスト描画，タブ，グループボックスコンテナをサポートする，新しいMVCエクステンションも追加された。DevExpressデータエディタとシームレスに統合されている。Grid検索エクステンションには，今回のリリースで複数レコード選択のサポート，項目テンプレート，高度なフィルタオプションなどが追加される。格付け(Rating)コンポーネントも新たに追加された。その他にも，読取り専用モードのサポートや，各エクステンションのタイトルやイメージのカスタマイズ，SharePoint 2013サポートなどが含まれている。</p> 
 </div> 
</div><br><br><br><br><br><br></body></html>