<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Webix 1.3リリース - 新しいスキンとHTML5ビデオを追加，チャートウィジェットをアップデート</h3><p><a target="_blank" href="http://www.infoq.com/news/2013/12/webix-1-3"><em>原文(投稿日：2013/12/14)へのリンク</em></a></p>
<div class="article_page_left news_container text_content_container"> 
 <div class="text_info"> 
  <p><a href="http://docs.webix.com/desktop__whats_new_1_3.html">Webix 1.3</a>が新しいスキンとUI要素，いくつかの改良を加えてリリースされた。エア，コンパクト，雲，魅惑(glamour), ライト，テラス, Webなどのスキンを使って，アプリケーションのユーザインターフェースをソフトにしたり，あるいは非常に明るくするような変更が可能だ。</p> 
  <p>スキンに関連するCSSファイルは，パッケージのcodebase/skinsフォルダに配置されているので，アプリケーションにも簡単にスキンを組み込むことができる。“エア”スキンを適用するには，次のようなコードを使えばよい。</p> 
  <p><code>&lt;script src=&quot;../codebase/webix.js&quot;&gt;&lt;/script&gt;&nbsp;&nbsp; <br /> &lt;link href=&quot;../codebase/webix.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt; </code><br /> <br /> 同じように，”クラウド”スキンを使うアプリケーションは次のようになる。<br /> <br /> <code> &lt;script src=&quot;../codebase/webix.js&quot;&gt;&lt;/script&gt;<br /> &lt;link href=&quot;../codebase/skins/clouds.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt; </code></p> 
  <p>Webixの公式<a href="http://docs.webix.com/desktop__skins.html">資料</a>には，すべての新しいスキンの使用方法が詳細に説明されている。Webix 1.3には新たにMP4, WebM, Oggをサポートする<a href="http://docs.webix.com/desktop__video.html">HTML5 video</a>要素が追加され，マルチメディアベースのアプリ開発が可能になった。以下のように使用する。<br /> <br /> <code> webix.ui({<br /> &nbsp;&nbsp;&nbsp; view:&quot;video&quot;,<br /> &nbsp;&nbsp;&nbsp; id:&quot;video1&quot;, <br /> &nbsp;&nbsp;&nbsp; container:&quot;video_div&quot;<br /> &nbsp;&nbsp;&nbsp; src: [&quot;data/movie.ogv&quot;,&quot;data/movie.mp4&quot;]<br /> }); </code><br /> <br /> Carouselも改良された。さまざまなナビゲーションタイプを提供するとともに，使い勝手もよくなっている。Carouselは主として複数のコンポーネントを，専用ボタンあるいはタッチデバイスのスライドで切り替え可能な，単一のビューとして表示するように設計されている。使用方法は次のようになる。<br /> <br /> <code> webix.ui({<br /> &nbsp;&nbsp;&nbsp; view:&quot;carousel&quot;,<br /> &nbsp;&nbsp;&nbsp; id:&quot;carousel&quot;,<br /> &nbsp;&nbsp;&nbsp; cols:[<br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { view:&quot;template&quot; },<br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { view:&quot;chart&quot; },<br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { view:&quot;datatable&quot; },<br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; { rows:[...]} //layout<br /> &nbsp;&nbsp;&nbsp; ]<br /> }); </code></p> 
  <p>Chartウィジェットもアップデートされた。対数スケールが使用可能になり，データ表現の選択肢が拡大されている。</p> 
 </div> 
</div><br><br><br><br><br><br></body></html>