<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Swarming: Ajudando equipes a entregarem mais e melhor</h3><p>Um dos objetivos do desenvolvimento &aacute;gil de software &eacute; realizar entregas funcionais de forma r&aacute;pida e frequente. O <a href="http://www.infoq.com/br/articles/swarming-across-distance;jsessionid=603A8B2639E880A3C94631B9AF1C2AC8">swarming</a><strong> </strong>[que literalmente vem de &quot;enxame&quot;, tamb&eacute;m sendo traduzido para &quot;mutir&atilde;o&quot;] &eacute; uma t&eacute;cnica que ajuda equipes &aacute;geis a colaborar de forma multifuncional para uma melhor produ&ccedil;&atilde;o das atividades.</p> 
<p><a href="https://twitter.com/BrainsLink">Vin D'Amico</a> explica, em seu post <a href="http://brainslink.com/2013/01/agile-teams-swarm-to-greatness/">Equipes &aacute;geis fazem swarming para o sucesso</a>, que as equipes que utilizam o desenvolvimento &aacute;gil de software podem entregar mais produtos com menos planejamento e reagir mais rapidamente &agrave;s mudan&ccedil;as:</p> 
<blockquote> 
 <p>A equipe sai rapidamente do planejamento para a fase de projeto, passando por codifica&ccedil;&atilde;o e testes, at&eacute; a conclus&atilde;o. Isso &eacute; feito at&eacute; que o software atinja os objetivos definidos pelos clientes e partes interessadas.</p> 
</blockquote> 
<p>Mas como as equipes &aacute;geis reagem t&atilde;o rapidamente? Segundo D'Amico:</p> 
<blockquote> 
 <p>Equipes excelentes fazem <em>swarming</em>, pois tentam resolver o problema ou remover o impedimento imediatamente. Apenas como &uacute;ltimo recurso a equipe devolve o item para o <em>backlog</em>.</p> 
</blockquote> 
<p>No post <a href="http://tobeagile.com/2012/12/11/seven-strategies-for-team-swarming/">Sete estrat&eacute;gias para swarming de equipes</a>, <a href="http://www.linkedin.com/pub/david-bernstein/0/1a0/960">David Bernstein</a> explica como o swarming pode ser &uacute;til na constru&ccedil;&atilde;o de uma equipe eficaz e com foco, capaz de resolver problemas complexos:</p> 
<blockquote> 
 <p>Ao realizar o <em>swarming</em>, a equipe toda trabalha em conjunto no mesmo problema, o que ajuda a fazer com que os membros da equipe conhe&ccedil;am melhor uns aos outros. Geralmente os grupos precisam passar pelas fases de <strong>forma&ccedil;&atilde;o</strong> (conhecimento m&uacute;tuo) e de <strong>tempestade</strong> (passar por conflitos e resolv&ecirc;-los) antes de atingir o bom desempenho (ser uma equipe altamente funcional). D&ecirc; espa&ccedil;o, ent&atilde;o, para que as pessoas possam de fato formar uma equipe.</p> 
</blockquote> 
<p>O <em>swarming</em> funciona de forma similar &agrave; programa&ccedil;&atilde;o em pares, pois acaba colocando as pessoas para trabalhar em conjunto para realizar uma tarefa:</p> 
<blockquote> 
 <p>Em vez de trabalhar sozinho, veja se tarefas individuais podem ser feitas por duas ou tr&ecirc;s pessoas. &Eacute; comum que a impuls&atilde;o obtida ao se trabalhar em pares seja positiva o suficiente para compensar a coloca&ccedil;&atilde;o de duas pessoas em uma &uacute;nica tarefa. Lembre-se que equipes de alto desempenho quase sempre realizam as tarefas em pares.</p> 
</blockquote> 
<p>O que ent&atilde;o &eacute; Swarming? Alguns anos atr&aacute;s, a InfoQ norte-americano publicou um resumo do grupo de discuss&atilde;o do Yahoo sobre swarming: &quot;<a href="http://www.infoq.com/news/2011/01/swarming;jsessionid=603A8B2639E880A3C94631B9AF1C2AC8">Swarming: para que isso?</a>&quot;, em que se explica o prop&oacute;sito do swarming: &quot;fazer com que a equipe coloque foco em entregar o trabalho que o neg&oacute;cio valoriza&quot; e &quot;aumentar a qualidade e consist&ecirc;ncia ao envolver toda a equipe em uma hist&oacute;ria t&atilde;o cedo quanto poss&iacute;vel&quot;. De acordo com Vin D'Amico, &quot;o Swarming &eacute; simplesmente o ato de se juntar para resolver um problema ou concluir alguma coisa rapidamente&quot;. David Bernstein d&aacute; sua defini&ccedil;&atilde;o: &quot;o swarming significa juntar toda a equipe para dar prioridade &agrave; resolu&ccedil;&atilde;o de um &uacute;nico problema&quot;.</p> 
<p><a href="http://www.linkedin.com/pub/oleksi-derkatch/42/b52/863">Oleksi Derkatch</a> descreve <a href="http://oleksiderkatch.blogspot.nl/2011/03/swarming.html">como a t&eacute;cnica funciona</a> e para que pode servir:</p> 
<blockquote> 
 <p>A ideia &eacute; colocar todos os desenvolvedores para trabalhar (fazer swarm) em uma &uacute;nica hist&oacute;ria, ao inv&eacute;s de v&ecirc;-los trabalhando cada um em uma hist&oacute;ria separada. O objetivo &eacute; conseguir que mais hist&oacute;rias sejam plenamente conclu&iacute;das. &Eacute; melhor que 80% das funcionalidades estejam 100% conclu&iacute;das que ter 100% das funcionalidades 80% conclu&iacute;das.</p> 
</blockquote> 
<p><a href="http://agileforest.com/author/agileforest/">Renee Troughton</a> explica como empresas podem utilizar o swarming como maneira de cultivar equipes mais inovadoras, no post <a href="http://www.google.com/url?q=http%3A%2F%2Fagileforest.com%2F2011%2F12%2F20%2Fthe-new-age-of-business%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNEVoOGIZlvzfVXiBYGl4cnjzu4CDA">A nova era dos neg&oacute;cios</a>:</p> 
<blockquote> 
 <p>A maioria das organiza&ccedil;&otilde;es remaneja seus &quot;recursos&quot; de projeto a projeto sem pensar se as pessoas alocadas est&atilde;o interessadas e animadas com esse tipo de projeto. Ali&aacute;s, tudo &eacute; feito sem a devida considera&ccedil;&atilde;o sobre velocidade real e a rela&ccedil;&atilde;o com o retorno sobre o investimento.</p> 
 <p>Para energizar o trabalho precisamos de gente &quot;apaixonada&quot;, que adote a ideia como se fosse um filho. Os empregados interessados em ser parte de uma empreitada devem poder se candidatar ao trabalho e come&ccedil;&aacute;-lo imediatamente.</p> 
</blockquote> 
<p>Suas equipes fazem swarming? Isso ajuda na entrega r&aacute;pida e frequente de software em funcionamento?</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>