<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>OpenKit: quadro de líderes sociais entre diversas plataformas</h3><p>Quando o OpenFeint foi descontinuado no final de 2012, muitos desenvolvedores de jogos iOS e Android ficaram sem funcionalidades sociais ou conex&otilde;es com redes sociais em seus software. Os jogos populares como Ninja Fruit, Fieldrunners ou Pocket God foram afetados. Agora, os cofundadores do OpenFeint liberaram o <a href="http://openkit.io/">OpenKit</a>, uma API substituta para servi&ccedil;os sociais entre v&aacute;rias plataformas.</p>
<p>O OpenKit oferece APIs para jogos baseados em iOS, Android e <a href="http://unity3d.com/">Unity</a>, e suporta um mecanismo de autentica&ccedil;&atilde;o universal para os IDs dos usu&aacute;rios do Game Center, Google+ e Facebook para integrar perfeitamente com esses servi&ccedil;os.</p>
<p>O SDK do OpenKit foca engajamento e reengajamento dos jogos com as seguintes funcionalidades:</p>
<ul> 
 <li>Quadro de l&iacute;deres sociais − Rastreamento de pontua&ccedil;&otilde;es em diferentes plataformas e redes do usu&aacute;rio. Al&eacute;m de usar o quadro de l&iacute;deres do Game Center e do Google+, a pontua&ccedil;&atilde;o tamb&eacute;m pode ser comparada usando o Facebook;</li> 
 <li>Desafios sociais − Chamando a aten&ccedil;&atilde;o dos jogadores do jogo atrav&eacute;s de notifica&ccedil;&otilde;es via push, que alertam quando a pontua&ccedil;&atilde;o do jogador foi alcan&ccedil;ada por seus amigos;</li> 
 <li>Convites inteligentes − Crescimento da base de usu&aacute;rios do jogo atrav&eacute;s de cartas de usu&aacute;rios convidando seus amigos, n&atilde;o importando em qual plataforma ou rede de usu&aacute;rios ele utilize;</li> 
 <li>Ghosting − Adicionando informa&ccedil;&otilde;es do jogo para os quadro de l&iacute;deres, ent&atilde;o os amigos podem jogar um contra o outro de forma ass&iacute;ncrona. Atrav&eacute;s da repeti&ccedil;&atilde;o dos dados, os jogos solos podem ser transformados em jogos &quot;virtualmente&quot; multi jogadores;</li> 
 <li>Conquistas − Permite que o usu&aacute;rio compare o seu progresso no jogo com os dos seus amigos, atrav&eacute;s de suas conquistas. As conquistas motivam os usu&aacute;rios a explorarem mais o jogo. O desbloqueio de uma conquista pode ser postada no Twitter e no Facebook.</li> 
</ul>
<p>O OpenKit pode ser usado para hospedar servi&ccedil;os com mais de 150 mil usu&aacute;rios ativos por m&ecirc;s de forma gratuita. Entre 150 mil e um milh&atilde;o de usu&aacute;rios ativos, &eacute; pago um valor por m&ecirc;s entre $100 e $1000. Como o OpenKit &eacute; open source, os servi&ccedil;os tamb&eacute;m podem ser hospedados pelos pr&oacute;prios desenvolvedores do jogo permitindo o controle total das informa&ccedil;&otilde;es dos seus usu&aacute;rios.</p><br><br><br><br><br><br></body></html>