<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>QCon London '14: Damian Conway, Tim Lister, Gunter Dueck Keynotes, 45% Speakers Confirmed (Mar 3-7)</h3><p>45/100 speakers and 3 keynotes have been confirmed for <a href="http://qconlondon.com/?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=12042013news">QCon London 2014 (Mar 3-7, 2014)</a>. &nbsp;The eight annual conference will feature talks from language pioneers, project leads, and practitioner case studies from companies like Netflix, NASA, Spotify, Financial Times, and more. Registration is open and new speakers and sessions are being posted to the conference site every week. You can get in early by reserving your seat now <strong>saving &nbsp;&pound;325</strong> by <strong>Dec 15th.</strong></p>
<p>Keynote speakers confirmed so far:&nbsp;</p>
<ul> 
 <li><a href="http://qconlondon.com/london-2014/speaker/Damian+Conway?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=12042013news"><strong>Damian Conway</strong> </a>- Perl Boffin, Author &quot;Perl Best Practices&quot;</li> 
 <li><strong>Tim Lister </strong>- Fellow, Cutter Consortium; Author &quot;Peoplware: Productive Projects and Teams&quot;</li> 
 <li><strong>Gunter Dueck</strong> - Former CTO, IBM Germany; Philosopher and Mathematician</li> 
</ul>
<p>Other confirmed speakers for QCon London 2014 include:</p>
<ul> 
 <li><a href="http://qconlondon.com/london-2014/speaker/Martin+Thompson?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=12042013news"><strong>Martin</strong>&nbsp;<strong>Thompson</strong></a>&nbsp;- High-Performance Computing Specialist</li> 
 <li><strong><a href="http://qconlondon.com/london-2014/speaker/Erik+Meijer?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=12042013news">Erik Meijer</a></strong>&nbsp;- Creator of LINQ</li> 
 <li><a href="http://qconlondon.com/london-2014/speaker/Joe+Armstrong?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=12042013news"><strong>Joe</strong>&nbsp;<strong>Armstrong</strong></a>&nbsp;- Co-inventor of Erlang</li> 
 <li><strong><a href="http://qconlondon.com/london-2014/speaker/Adrian+Cockcroft?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=12042013news">Adrian Cockcroft</a></strong> - Director of Architecture for the Cloud Systems team at Netflix</li> 
 <li><a href="http://qconlondon.com/london-2014/speaker/Dave+Farley?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=12042013news"><strong>Dave</strong>&nbsp;<strong>Farley</strong></a>&nbsp;- Co-author of the book &quot;Continuous Delivery&quot;</li> 
 <li><a href="http://qconlondon.com/london-2014/speaker/Tim+Fox?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=12042013news"><strong>Tim</strong> <strong>Fox</strong> </a>- vert.x Project Lead at VMware</li> 
 <li><a href="http://qconlondon.com/london-2014/speaker/Ruslan+Meshenberg?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=12042013news"><strong>Ruslan</strong> <strong>Meshenberg</strong></a> - Director of Engineering at Netflix</li> 
 <li><a href="http://qconlondon.com/london-2014/speaker/Eva+Andreasson?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=12042013news"><strong>Eva</strong> <strong>Andreasson</strong></a> - Pioneer of Deterministic Garbage Collection</li> 
 <li><a href="http://qconlondon.com/london-2014/speaker/Linda+Rising?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=12042013news"><strong>Linda</strong> <strong>Rising</strong></a> - Queen of Patterns. Author of numerous Books</li> 
 <li><a href="http://qconlondon.com/london-2014/speaker/Michael+T.+Nygard?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=12042013news"><strong>Michael</strong> <strong>T. Nygard</strong></a> - Author of &quot;Release It!&quot;</li> 
 <li><a href="http://qconlondon.com/london-2014/speaker/Nathan+Marz?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=12042013news"><strong>Nathan</strong> <strong>Marz</strong> </a>- Creator of the Storm and Cascalog open-source projects</li> 
 <li><a href="http://qconlondon.com/london-2014/speaker/Stefan+Tilkov?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=12042013news"><strong>Stefan</strong> <strong>Tilkov</strong></a> - SOA and REST authority, innoQ founder</li> 
 <li><strong>Chris</strong>&nbsp;<strong>Mattmann</strong>&nbsp;- Data Scientist, NASA</li> 
</ul>
<p>QCon London is the premier enterprise software development conference designed exclusively for technical team leads, architects, project managers, and software engineers. There is no other event in the UK with similar opportunities for learning, networking, and tracking innovation occurring in the Java, Big Data, Agile, Cloud Computing, HTML5/Mobile and Architecture communities.</p>
<p>QCon London 2013 drew over 1,100 attendees this year - among the largest QCons to date - and elicited thousands of tweets and hundreds of blogs all of which are summarized in the&nbsp;<a href="http://www.infoq.com/articles/QCon-London-2013">Key Takeaway Points and Lessons Learned from QCon London 2013</a>.&nbsp;&nbsp;We hope you can join us for QCon London 2014. <a href="https://secure.trifork.com/london-2014/registration/?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=12042013news"><strong>Register before December 15th and save &pound;325.</strong></a>&nbsp;</p>
<p><b>Attending with your colleagues?</b> QCon London offers special savings when you register a group of five or more people from your company. <a href="https://secure.trifork.com/london-2014/registration/?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=12042013news">Click here for more details</a>. &nbsp;</p>
<p>QCon is co-produced by InfoQ.com and Trifork, producer of the Danish GOTO conference.</p>
<p>&nbsp;</p><br><br><br><br><br><br></body></html>