<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Study: Clojure, CoffeeScript and Haskell Are the Most Expressive General-purpose Languages</h3><p>According to a study, the most expressive general-purpose languages are Clojure, CoffeeScript and Haskell. The study uses LoC/commit as the measuring unit of expressiveness.</p> 
<p>Donnie Berkholz, a RedMonk's resident PhD, has conducted a <a href="http://redmonk.com/dberkholz/2013/03/25/programming-languages-ranked-by-expressiveness/">study meant to quantify the expressiveness</a> of various programming languages. The study is based on data provided by <a href="http://www.ohloh.net/">Ohlol</a>, a repository keeping track of over 500,000 open source projects written in about 100 languages spanning around 20 years.</p> 
<p>Berkholz used as the expressiveness measuring unit LoC/commit, adding that he started from the assumption that “commits are generally used to add a single conceptual piece”. Also, the results are not a measure of maintainability or productivity, nor telling how readable is the resulting code or how long it takes to write it.</p> 
<p>The following graphic shows the expressiveness of over 50 languages which are colored based on their popularity according to <a href="http://redmonk.com/sogrady/2013/02/28/language-rankings-1-13/">RedMonks’s language rankings</a> published earlier this year: red - most popular languages, blue – 2nd tier in popularity, and black – 3rd tier (click to enlarge).</p> 
<p class="image-wide"><a href="/resource/news/2013/03/Language-Expressiveness/en/resources/Expresiveness-1.png;jsessionid=B2F97CC931C0734D6B87D675618530D7" target="_self"><img title="image" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" border="0" alt="image" src="http://www.infoq.com/resource/news/2013/03/Language-Expressiveness/en/resources/Expresiveness-1.png;jsessionid=B2F97CC931C0734D6B87D675618530D7" width="640" height="217" _href="img://Expresiveness-1.png" _p="true" /></a></p> 
<p>Each language has LoC/commit distributed over a range since the study covers many different projects/language, each with its own average. Languages are ranked by their median - the black line inside the box representing LoC/commit for 50% of the corresponding projects –, the bottom and the top of the box represent 25% and 75% of the projects, while the whiskers go down to 10% and up to 90%.</p> 
<p>Some of Berkholz’ conclusions are:</p> 
<blockquote> 
 <p>Third-tier languages are heavily biased toward high expressiveness.</p> 
 <p>Functional languages tend to be highly expressive.</p> 
 <p>Domain-specific languages are biased toward high expressiveness.</p> 
 <p>Compilation does not imply lower expressiveness.</p> 
 <p>CoffeeScript (#6) appears dramatically more expressive than JavaScript (#51), in fact among the best of all languages.</p> 
 <p>Clojure (#7) is the most expressive of Lisp variants.</p> 
 <p>Although Go (#24) is getting increasingly hot, it’s not outstandingly expressive. … Despite that, it does trump all the tier-one languages, so someone who only had experience with them could certainly see an improvement when trying Go.</p> 
</blockquote> 
<p>The conclusion that “Third-tier languages are heavily biased toward high expressiveness”makes one wonder why highly expressive languages do not become popular? Does their conciseness make it difficult for the average programmer to grasp and use such languages? Are there other reasons?</p> 
<p>Berkholz also ranked languages based on their expressiveness consistency, measured by the height of the box, resulting in the next graphic (click to enlarge):</p> 
<p class="image-wide"><a href="/resource/news/2013/03/Language-Expressiveness/en/resources/Expresiveness-2.png;jsessionid=B2F97CC931C0734D6B87D675618530D7" target="_self"><img title="image" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" border="0" alt="image" src="http://www.infoq.com/resource/news/2013/03/Language-Expressiveness/en/resources/Expresiveness-2.png;jsessionid=B2F97CC931C0734D6B87D675618530D7" width="640" height="223" _href="img://Expresiveness-2.png" _p="true" /></a></p> 
<p>Berkholz’ conclusions are:</p> 
<blockquote> 
 <p>Tier-one languages put in a much stronger showing here.&nbsp;&nbsp;</p> 
 <p>Tier-one languages tend to be remarkably consistent, regardless of their expressiveness.</p> 
 <p>This suggests that a primary characteristic of a tier-one language is its predictability, even more so than its productivity.</p> 
 <p>Tier-three languages make a poorer showing here.</p> 
 <p>Java turns in the strongest performance of “enterprisey” languages (C, C++, Java).</p> 
 <p>CoffeeScript is #1 for consistency, with an IQR spread of only 23 LOC/commit compared to even #4 Clojure at 51 LOC/commit.</p> 
</blockquote> 
<p>Based on expressiveness consistency result and Redmonk’s ranking on language popularity, Berkholz’ concludes that Clojure, CoffeeScript and Haskell are most expressive high-purpose languages. His study is partially backed up by <a href="http://hammerprinciple.com/therighttool/statements/this-language-is-expressive">another study</a> conducted by <a href="http://www.drmaciver.com/">David R. MacIver</a> which interviewed 2576 programmers using the <a href="http://en.wikipedia.org/wiki/Law_of_the_instrument">Hammer Principle</a>. According to Maclver, the most expressive languages are Haskell, Clojure and Scala while the least expressive are C, PHP and ultimately TCL. Maclver’s study did not include CoffeeScript.</p> 
<p>Berkholz post triggered a large number of comments both on his <a href="http://redmonk.com/dberkholz/2013/03/25/programming-languages-ranked-by-expressiveness/#comments">original post</a>, <a href="https://news.ycombinator.com/item?id=5438755">Hacker News</a>, and <a href="https://twitter.com/search/realtime?q=http%3A%2F%2Fredmonk.com%2Fdberkholz%2F2013%2F03%2F25%2Fprogramming-languages-ranked-by-expressiveness%2F&amp;src=typd">Twitter</a>, many considering that LoC/commit does not accurately represent the expressiveness of a language, expressiveness should consider code readability and maintainability, DSLs should not be included, and many others.</p> 
<p>Berkholz insists that his study is not about language readability and maintainability, but “rather something about the state of the code in the repository, the development practices in use, potentially the level of bugs you're likely to get (given the correlation between bugs and LOC)”, explaining in greater detail in a <a href="http://redmonk.com/dberkholz/2013/03/26/what-does-expressiveness-via-loc-per-commit-measure-in-practice/">separate post</a> why he used LoC/commit to measure expressiveness.</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>