<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Agile Brazil 2013: Submissão de palestras fecha este final de semana</h3><p>Bras&iacute;lia receber&aacute; em junho mais uma edi&ccedil;&atilde;o do maior evento nacional voltado &agrave; agilidade, o&nbsp;<a href="http://www.agilebrazil.com/2013/">Agile Brazil 2013</a>. A confer&ecirc;ncia trar&aacute; cursos, palestras e keynotes com grandes personalidades do Brasil e do exterior. Esta edi&ccedil;&atilde;o promover&aacute; a integra&ccedil;&atilde;o do ecossistema &aacute;gil com t&oacute;picos importantes como governo, grandes empresas e startups.</p> 
<p>Alguns palestrantes confirmados s&atilde;o&nbsp;<a href="http://www.agilebrazil.com/2013/programa/patrick-kua/">Patrick Kua</a>,&nbsp;<a href="http://www.agilebrazil.com/2013/programa/ale-gomes/">Alexandre Gomes</a> e&nbsp;<a href="http://www.agilebrazil.com/2013/programa/niels-pflaeging/">Niels Pflaeging</a>. A chamada de&nbsp;<a href="http://submissoes.agilebrazil.com/">submiss&otilde;es de palestra</a> &eacute; aberta &agrave; toda comunidade &aacute;gil e tem prazo at&eacute; 7 de abril (este domingo). As submiss&otilde;es s&atilde;o avaliadas por membros da comunidade. As&nbsp;<a href="http://www.agilebrazil.com/2013/pt/inscricao/">inscri&ccedil;&otilde;es</a> j&aacute; est&atilde;o abertas e com descontos de &quot;early bird&quot;.</p> 
<p><strong>Novidades e depoimentos</strong></p> 
<p>Desde 2010, as principais abordagens &aacute;geis estiveram presentes no Agile Brazil, incluindo Lean, Kanban, XP e Scrum. Nos &uacute;ltimos anos, a confer&ecirc;ncia tem incorporado outras tend&ecirc;ncias relacionadas ao Agile. Claudia Melo, uma da organizadoras, conta um pouco sobre as novidades do evento:</p> 
<blockquote> 
 <p>Este ano teremos novas trilhas, como a de Coaching e Facilita&ccedil;&atilde;o, Neg&oacute;cios e Produtos, Design e Experi&ecirc;ncia do Usu&aacute;rio, al&eacute;m da trilha de Pesquisa. Teremos duas extens&otilde;es diferenciadas para debater assuntos ainda pol&ecirc;micos: Agilidade no Governo e Agile PMI.</p> 
</blockquote> 
<p>Conhe&ccedil;a a seguir depoimentos de alguns profissionais que palestraram em edi&ccedil;&otilde;es passadas.</p> 
<p>Paulo Igor Godinho disse sobre a experi&ecirc;ncia em palestrar:</p> 
<blockquote> 
 <p>Ser palestrante no Agile Brazil foi uma experi&ecirc;ncia sensacional, n&atilde;o s&oacute; no aspecto profissional como no aspecto pessoal. ... Na empresa em que eu estava atuando na &eacute;poca foi percept&iacute;vel o reconhecimento do trabalho e do que foi abordado na palestra.</p> 
</blockquote> 
<p>&nbsp;Rafael Barbosa Camargo tamb&eacute;m apresentou palestra:</p> 
<blockquote> 
 <p>A oportunidade de compartilhar minha experi&ecirc;ncia e receber feedback me auxiliou muito para evoluir em qualidade e satisfa&ccedil;&atilde;o no trabalho. Foi um marco na minha passagem de maturidade profissional. O networking que se faz em um grande evento como o Agile Brazil traz oportunidades de conhecer profissionais de v&aacute;rios lugares e v&aacute;rias aspira&ccedil;&otilde;es, abrindo novas possibilidades de trabalho. Meu atual emprego nasceu na edi&ccedil;&atilde;o de 2010!</p> 
</blockquote> 
<p>A confer&ecirc;ncia abre espa&ccedil;o para a intera&ccedil;&atilde;o entre os participantes. H&aacute; sempre um local para happy hour ou jantar onde os conferencistas podem se reencontrar &agrave; noite. E, segundo os organizadores, mesmo nesse ambiente mais informal costumam acontecer contrata&ccedil;&otilde;es, fechamento de parcerias, e at&eacute; a produ&ccedil;&atilde;o de c&oacute;digo.</p> 
<p>O Agile Brazil acontecer&aacute; em&nbsp;<a href="http://www.agilebrazil.com/2013/pt/brasilia/">Bras&iacute;lia-DF</a> nos dias 26, 27 e 28 de Junho de 2013, no Royal Tulip Bras&iacute;lia Alvorada. O&nbsp;<a href="http://www.agilebrazil.com/2013/">site</a> do evento &eacute; a maior fonte de informa&ccedil;&otilde;es sobre a atual edi&ccedil;&atilde;o e todas as edi&ccedil;&otilde;es anteriores do evento, al&eacute;m de incluir informa&ccedil;oes sobre v&aacute;rios aspectos da agilidade. O InfoQ Brasil filmou v&aacute;rias tracks da edi&ccedil;&atilde;o de 2012; confira as <a href="http://www.infoq.com/br/agilebrasil/;jsessionid=1FBE46CA1F8A61CD94C79E004522D237">apresenta&ccedil;&otilde;es publicadas</a> at&eacute; agora.</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>