<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Padrões de Código Java do Google</h3><p>O Google liberou recentemente sua lista completa de defini&ccedil;&otilde;es de <a href="http://google-styleguide.googlecode.com/svn/trunk/javaguide.html">padr&otilde;es de c&oacute;digo para c&oacute;digo-fonte Java</a>. S&atilde;o regras definitivas sobre c&oacute;digo Java que devem ser seguidas universalmente dentro do Google. Esta lista contempla formata&ccedil;&atilde;o de c&oacute;digo assim como outros tipos de conven&ccedil;&otilde;es e padr&otilde;es de c&oacute;digo.</p>
<p>O documento &eacute; divido em seis se&ccedil;&otilde;es principais: Fundamentos de Arquivos Fonte, Estrutura de Arquivo Fonte, Nomenclatura, Pr&aacute;ticas de Programa&ccedil;&atilde;o e Javadoc. A se&ccedil;&atilde;o de Fundamentos de Arquivos Fonte fala sobre nomes e codifica&ccedil;&atilde;o de arquivos, caracteres de espa&ccedil;o e caracteres especiais. A se&ccedil;&atilde;o sobre Estrutura de Arquivos Fonte fala sobre informa&ccedil;&atilde;o de licen&ccedil;a, declara&ccedil;&otilde;es de pacotes e import e ordem de membros de uma classe. A se&ccedil;&atilde;o de Formata&ccedil;&atilde;o discute sobre chaves, indenta&ccedil;&atilde;o, tamanho da linha, espa&ccedil;os em branco, par&ecirc;nteses, enums, vetores, declara&ccedil;&otilde;es de switch, anota&ccedil;&otilde;es, coment&aacute;rios e modificadores. A se&ccedil;&atilde;o sobre Nomenclatura fala sobre identificadores (pacote, classe, m&eacute;todo, constante, campo, vari&aacute;veis locais, tipos de vari&aacute;vel) e CamelCase. A se&ccedil;&atilde;o sobre Pr&aacute;ticas de Programa&ccedil;&atilde;o fala sobre @Override, exce&ccedil;&otilde;es, membros est&aacute;ticos e finalizers. A se&ccedil;&atilde;o sobre Javadoc fala sobre como formatar o Javadoc e onde ele &eacute; necess&aacute;rio.</p>
<p>Abaixo segue alguns itens presentes no guia:</p>
<ul> 
 <li>Nenhuma declarac&atilde;o de importa&ccedil;&atilde;o com coringas;</li> 
 <li>Sobrecargas aparecem em sequ&ecirc;ncia;</li> 
 <li>Chaves s&atilde;o usadas mesmo quando o corpo do c&oacute;digo &eacute; vazio ou cont&eacute;m somente uma declara&ccedil;&atilde;o;</li> 
 <li>Indenta&ccedil;&atilde;o com dois espa&ccedil;os;</li> 
 <li>O limite de colunas s&atilde;o de 80 &agrave; 100 caracteres;</li> 
 <li>Sem declara&ccedil;&otilde;es de vetores no estilo C;</li> 
 <li>A declara&ccedil;&atilde;o <em>default</em> no switch &eacute; obrigat&oacute;ria;</li> 
 <li>Modificadores aparecem na ordem recomendada pela Especifica&ccedil;&atilde;o da Linguagem Java;</li> 
 <li>Constantes usam LETRAS_MAI&Uacute;SCULAS. Note que toda constante &eacute; um campo final e est&aacute;tico, por&eacute;m nem todos os campos finais e est&aacute;ticos s&atilde;o constantes.</li> 
</ul>
<p>Para uma leitura completa, leia o <a href="http://google-styleguide.googlecode.com/svn/trunk/javaguide.html">Google Java Style</a>. Tamb&eacute;m existe o guia oficial <a href="http://www.oracle.com/technetwork/java/javase/documentation/codeconvtoc-136057.html">Conven&ccedil;&otilde;es de C&oacute;digo para a Linguagem de Programa&ccedil;&atilde;o Java</a> da Oracle. O Google tamb&eacute;m possui <a href="https://code.google.com/p/google-styleguide/">guias de estilo</a> para outras linguagens como C++, Objective-C, Python, Sheel, HTML/CSS, JavaScript e Lisp.</p><br><br><br><br><br><br></body></html>