<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>QCon New York Update: 60/100 Speakers; Gilad Bracha, Netflix Keynotes Confirmed (Jun 11-13, 2014)</h3><p>Gilad Bracha, Co-Author of the Java Spec, and Dianne Marsh, Director of Engineering at Netflix have been confirmed as <a href="https://www.qconnewyork.com/keynotes?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=04112014news">keynote speakers</a> for the third annual QCon New York (Jun 11-13, 2014).&nbsp; The tutorials schedule has been <a href="https://www.qconnewyork.com/tutorials?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=04112014news">finalized</a> and new speakers are being added daily to the conference website, with more than 60/100 speakers already confirmed. <a href="https://qconnewyork.com/registration?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=04112014news">Register</a>&nbsp;<strong>before Apr 19th</strong>&nbsp;and save $400.</p>
<p>QCon New York is a practitioner-driven conference designed for people influencing innovation in their software development teams: team leads, architects, project managers, engineering directors. &nbsp;There will be two days of full &amp; half day&nbsp;<strong>tutorials from&nbsp;June 9-10</strong>&nbsp;(Mon-Tues) and a full&nbsp;<strong>3-day conference from June 11-13</strong>&nbsp;(Wed-Fri).</p>
<p>This year’s sessions include:</p>
<ul> 
 <li><a href="https://qconnewyork.com/presentation/structure-personalization-scale-deep-dive-linkedin-search/?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=04112014news"><strong>Data Science @ LinkedIn</strong></a>, by <strong>Daniel Tunkelang</strong>, Head of Query Understanding at LinkedIn</li> 
 <li><a href="https://www.qconnewyork.com/presentation/functional-programming-concepts-facebooks-mobile-apps?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=04112014news"><strong>The Functional Programming Concepts in Facebook's Mobile Apps</strong></a>, by <strong>Adam Ernst</strong>, iOS Engineer at Facebook</li> 
 <li><a href="https://www.qconnewyork.com/presentation/big-data-capital-markets?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=04112014news"><strong>Big Data in Capital Markets</strong></a>, by <strong>Clive Saha</strong>, Lead Consultant at Risk Focus, Distributed Computing</li> 
 <li><a href="https://www.qconnewyork.com/presentation/migrating-microservices?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=04112014news"><strong>Migrating to Microservices</strong></a>, by <strong>Adrian Cockcroft</strong>, Lead Netflix's migration to a large scale</li> 
 <li><a href="https://www.qconnewyork.com/presentation/advanced-data-visualization-html5-and-risk-analysis?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=04112014news"><strong>Advanced Data Visualization: HTML5 and Risk Analysis</strong></a>, by Fabrice Aresu, Product Manager for Risk Solutions at Luxoft</li> 
 <li><a href="https://www.qconnewyork.com/presentation/devops-culture-and-practices-create-flow?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=04112014news"><strong>DevOps Culture And Practices To Create Flow</strong></a>, by Jez Humble, Co-Author of “Continuous Delivery”</li> 
 <li><a href="https://www.qconnewyork.com/presentation/data-science-mount-sinai/?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=04112014news"><strong>Data Science @ Mount Sinai</strong></a>, by <strong>Jeff Hammerbacher</strong>, Founder, Cloudera; Creator of Facebook's Data Science Practice</li> 
 <li><a href="https://www.qconnewyork.com/presentation/typescript-%E2%80%93-scaling-javascript?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=04112014news"><strong>TypeScript – Scaling up JavaScript</strong></a>, by Jonathan Turner, Co-Designer of the TypeScript Language</li> 
 <li><a href="https://www.qconnewyork.com/presentation/github-communications-culture-and-tools?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=04112014news"><strong>GitHub Communications Culture and Tools</strong></a>, by Matthew McCullough, Trainer at GitHub</li> 
 <li><a href="https://www.qconnewyork.com/presentation/evolving-rest-iot-world?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=04112014news"><strong>Evolving REST for an IoT World</strong></a>, by <strong>Todd Montgomery</strong>, Ex-NASA Researcher, Chief Architect, Kaazing</li> 
 <li><a href="https://www.qconnewyork.com/presentation/functional-programming-frontend-facebook-react?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=04112014news"><strong>Functional programming on the frontend with Facebook React</strong></a>, by Dustin Getz, React Pioneer</li> 
 <li><u>Big Data at Facebook</u>, by <strong>Justin Moore</strong>, Engineer, Facebook</li> 
</ul>
<p>Other confirmed speakers include:</p>
<ul> 
 <li><strong>Eric Evans</strong>, Creator of Domain Driven Design</li> 
 <li><strong>Brian Goetz</strong>, Java Language Architect at Oracle</li> 
 <li><strong>Rob Witoff</strong>, Data Scientist, CTO’s Office, NASA</li> 
 <li><strong>Asif Makhani</strong>, Director of Engineering at LinkedIn</li> 
 <li><strong>Nell Thomas</strong>, Data Analyst, Etsy</li> 
 <li><strong>John Musser</strong>, Founder, ProgrammableWeb</li> 
 <li><strong>Jon Hoffman</strong>, Foursquare Engineer</li> 
 <li><strong>Kirk Pepperdine</strong>, Java Performance Expert</li> 
 <li><strong>Nicolas Bevacqua</strong>, Author of JavaScript Application Design</li> 
</ul>
<p>See the complete list of <a href="https://www.qconnewyork.com/speakers?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=04112014news">confirmed speakers here</a>.</p>
<p>QCon New York is a conference designed to meet the unique needs of senior software practitioners – technical team leads, architects, and software engineers - such as yourself.&nbsp; With a high speaker-to-attendee ratio, facilitated peer learning, and numerous networking opportunities, QCon has inspired thousands of technical leaders, helping them drive change and innovation in their software development projects.</p>
<p>Registration for QCon New York is $1,895 ($400 off) for the 3-day conference (including OSGi DevCon).&nbsp;<a href="https://qconnewyork.com/registration?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=04112014news"><strong>Register</strong></a>&nbsp;before April 19th to receive the best rate available.</p>
<p>Corporate and group discounts are also available. Please email&nbsp;<a href="mailto:info@qconnewyork.com">info@qconnewyork.com</a>&nbsp;for details.</p><br><br><br><br><br><br></body></html>