<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Quinto LinguÁgil acontece em março</h3><p>As inscri&ccedil;&otilde;es est&atilde;o abertas para a 5a. edi&ccedil;&atilde;o do <a href="http://linguagil.com.br/">Lingu&Aacute;gil</a>, evento que acontece em Salvador, entre os dias 13 e 15 de mar&ccedil;o, evento que promove a divulga&ccedil;&atilde;o, o debate e a troca de experi&ecirc;ncias entre especialistas nacionais e a comunidade baiana de profissionais e estudantes. O local ser&aacute; a <a href="http://www.unifacs.br/">Universidade Salvador</a> (UNIFACS).</p>
<p>De acordo com a proposta do evento, o mesmo &eacute; motivado pelo cen&aacute;rio abaixo:</p>
<blockquote> 
 <p>O incremento na complexidade dos sistemas atuais tem gerado uma tend&ecirc;ncia na uni&atilde;o de diversas tecnologias para o desenvolvimento de solu&ccedil;&otilde;es. Java, PHP, Ruby e Python representam algumas das mais utilizadas linguagens de programa&ccedil;&atilde;o que, isoladamente, apresentam vantagens espec&iacute;ficas para determinados contextos. Por&eacute;m, quando integradas, possibilitam resultados mais robustos e eficientes. O problema &eacute; que, para se obter os melhores resultados com esta abordagem, &eacute; necess&aacute;rio o conhecimento das diversas op&ccedil;&otilde;es oferecidas.</p> 
</blockquote>
<p>Atrav&eacute;s de cursos pr&aacute;ticos e palestras, as tend&ecirc;ncias de mercado e novidades das linguagens de programa&ccedil;&atilde;o Java, PHP, Ruby e Python, al&eacute;m das pr&aacute;ticas inovadoras das metodologias &aacute;geis, como Scrum e XP, ser&atilde;o amplamente expostas e discutidas. Em 2014 o evento amplia o espa&ccedil;o para o tema do empreendedorismo tecnol&oacute;gico, trazendo um conjunto composto de curso e palestra dedicados ao tema.</p>
<p>Dentre as palestras e minicursos confirmados, est&atilde;o entre outros, <a href="http://www.infoq.com/br/author/Edson-Yanaga">Edson Yanaga</a>, L&iacute;der T&eacute;cnico da Produtec Inform&aacute;tica, professor de p&oacute;s-gradua&ccedil;&atilde;o de diversas institui&ccedil;&otilde;es, e instrutor-l&iacute;der da Globalcode no Paran&aacute;, com a palestra Transformando Desenvolvedores numa Equipe 10x; e Mariana Bravo, desenvolvedora e consultora pela ThoughtWorks, com a palestra O Desenvolvedor Completo.</p>
<p>Cloud Computing ter&aacute; seu espa&ccedil;o com <a href="http://www.infoq.com/br/author/Bruno-Souza">Bruno Souza</a>, evangelista de Java e open source, al&eacute;m de consultor nas empresas Summa Technologies e ToolsCloud, apresentando a palestra Estrat&eacute;gias Open Source para Automa&ccedil;&atilde;o na Nuvem e Luiz Cl&aacute;udio Silva, Assessor de TI do IEL/BA, ministrando o minicurso Desenvolvendo Aplica&ccedil;&otilde;es Python para a Nuvem.</p>
<p>Bruno Souza tamb&eacute;m ministra um minicurso introdut&oacute;rio sobre Application Lifecycle Management Open Source. E Maur&iacute;cio Purifica&ccedil;&atilde;o e Adewale Andrade D'Alcantara ministram sobre Open Source BI com Pentaho.</p>
<p>A mobilidade est&aacute; presente nos minicursos confirmados. Leandro Santos, que trabalha desde 2008 no desenvolvimento de aplicativos m&oacute;veis, ministra o minicurso Introdu&ccedil;&atilde;o Pr&aacute;tica &agrave; Plataforma Android. Uma Breve Introdu&ccedil;&atilde;o ao PhoneGap ser&aacute; ministrado por M&aacute;rcio Albuquerque, que trabalha como DevOps no SERPRO.</p>
<p><a href="http://www.infoq.com/br/author/Otavio-Santana">Ot&aacute;vio Santana</a>, desenvolvedor entusiasta do mundo open source, ministra o minicurso NoSQL com Java, onde apresenta o hist&oacute;rico, os principais conceitos e os tipos de reposit&oacute;rios NoSQL.</p>
<p>Informa&ccedil;&otilde;es mais detalhadas, como chegar e tamb&eacute;m a p&aacute;gina de inscri&ccedil;&atilde;o est&atilde;o no <a href="http://linguagil.com.br/">site</a> do evento.</p><br><br><br><br><br><br></body></html>