<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>A Few Highlights from QConSF2013- Part 2 of 2</h3><p class="MsoNormal">The 2013 <a href="http://www.infoq.com/articles/qcon-san-francisco-2013#_Toc374443466">QCon San Francisco</a> software conference at the Hyatt Regency is already a distant memory. However that doesn't lessen the importance of the body of knowledge gained there by its attendees and the after-the-fact viewers of the <a href="http://www.infoq.com/conferences/qconsf2013/">online presentations</a> available at the InfoQ web site.</p>
<p class="MsoNormal">The technology that supports the infrastructure of modern civilization is controlled by software. The QCon conferences perform a vital service to the tech community by providing the missing link between competition, best practices, education and more. Something indefinable happens at QCon that only attendees can fully appreciate.</p>
<p class="MsoNormal">QConSF attendees and speakers alike were temporarily freed from their usual day-to-day corporate settings. Hundreds of enterprise software professionals, placed in the comfortably plush environment of the Hyatt Regency Hotel in San Francisco, were exposed to three days of new ideas like code tooling and the techniques of tomorrow, concepts like scalability, availability and performance and methods such as <a href="http://www.infoq.com/presentations/adopting-continuous-delivery">designing for the Cloud</a>.&nbsp;</p>
<p class="MsoNormal">Via talks ranging from &quot;Hybrid Mobile Development using Java and HTML5 for iOS and Android&quot; given by Oracle's <a href="http://www.oracle.com/technetwork/articles/huang-iphone-097081.html">Joe Huang</a> and presentations from some of the most prominent figures in the software community like <a href="http://www.infoq.com/author/Brendan-Eich">Brendan Eich</a>. Attendees and presenters received instruction and valuable insights to assist them in refining their techniques, approach and execution in their own coding challenges ahead.</p>
<p class="MsoNormal">After three full days of getting up to date with enterprise software trends like <a href="http://qconlondon.com/london-2014/tracks/show_track.jsp?trackOID=914&amp;utm_source=infoq&amp;utm_medium=VCR&amp;utm_campaign=HadoopBigDatatrack">big data</a>, <a href="https://github.com/explore">GitHub,</a> the newest <a href="http://www.infoq.com/research/java-relational-data?utm_source=infoqresearch&amp;utm_campaign=lr-homepage">Java innovations</a> and as many exciting nights of being wined and dined while adding valuable new contacts to their networks. The throngs of QCon attendees filed out the Hyatt Regency's staircases, escalators, elevators, doors and then poured out into the <a href="http://www.youtube.com/watch?v=hY2mEEzeQo8">streets of San Francisco</a> with a greater understanding of some of the diverse software trends and methods that are shaping technology.</p>
<p class="MsoNormal">The conference portion of QCon was officially over but the thirst for software programming knowledge continued with two more <a href="http://www.infoq.com/conferences/qconsf2013/">full days of tutorials</a>. It's one thing having an in-house training program. But there is a certain deeper insight that can be gained from <a href="http://qconlondon.com/?utm_source=infoq&amp;utm_medium=header&amp;utm_campaign=infoqheader">attending a Q-Con</a> conference and the associated two days of software tutorials in person. Which may be one reason why attendance at the <a href="http://c4media.com/qcon.html">globe-hopping event</a> continues to grow.&nbsp;</p>
<p class="MsoNormal">Though the tutorials were most informative, one six-hour day for each subject is simply not enough time to create a good bug-free mobile app. So mastering <a href="http://i5.nyu.edu/~mm64/qcon/ios/">app creation in iOS</a> on Thursday or in the <a href="http://i5.nyu.edu/~mm64/qcon/android/">Android operating system</a> on Friday wasn't in the cards. The depth of study that can be achieved in one six-hour session precluded that.&nbsp;</p>
<p class="MsoNormal"><img src="http://www.infoq.com/resource/news/2013/12/Highlights-QConSF-2013/en/resources/2pic for part 2 infoq post qconsf.jpg" alt="" _href="img://2pic for part 2 infoq post qconsf.jpg" _p="true" /></p>
<p class="MsoNormal">Nevertheless that was the task --condensing the salient points of the two 30-hour courses down to the available six hours-- that <a href="http://qconsf.com/user/mark-meretzky">instructor Mark Meretzky</a> was faced with on each of his two days of tutorials closing out QConSF 2013. Luckily Mr. Meretzky was a <a href="http://www.infoq.com/interviews/meretzky-mobile">veteran of the last QCon</a> New York so he was well qualified to deliver useful and informative cliff notes versions. The tutorials were about building blocks of Xcode iOS design patterns and Eclipse screen layouts, controls, buttons and slider programming methods and ideas.</p>
<p class="MsoNormal">Got any QCon stories to share? Post them in the comments section below!</p>
<p class="MsoNormal">
 <!--[if !supportEmptyParas]--><img src="http://www.infoq.com/resource/news/2013/12/Highlights-QConSF-2013/en/resources/free lunch.jpg" alt="" _href="img://free lunch.jpg" _p="true" />&nbsp;
 <!--[endif]-->
 <o:p></o:p></p>
<p class="MsoNormal"><i>The food was great too!
  <o:p></o:p></i></p>
<p>&nbsp;</p><br><br><br><br><br><br></body></html>