<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>HadoopジョブをGPU上で実行するParallelX</h3><p><a target="_blank" href="http://www.infoq.com/news/2013/12/hadoop-gpu-parallelx"><em>原文(投稿日：2013/12/26)へのリンク</em></a></p>
<div class="article_page_left news_container text_content_container"> 
 <div class="text_info"> 
  <p><a href="http://en.wikipedia.org/wiki/MapReduce">MapReduce</a>パラダイムは，大規模な計算集約的アルゴリズムを扱う場合には，必ずしも理想的ではない。ある企業家の小さなチームが，これを解決するために<a href="http://www.parallelx.com/">ParallelX</a>という製品を開発している。GPUのパワーを活用して<a href="http://hadoop.apache.org/">Hadoop</a>ジョブを強力に加速することで，ボトルネックを解消しようというものだ。</p> 
  <p>ParalleXは &quot;Javaで記述されたコードをOpenCLに変換して，それを当社のAWS GPUクラウド上で実行するGPUコンパイラです&quot; と，創設者のひとりである<a href="https://twitter.com/tonydiepenbrock">Tony Diepenbrock</a>氏は説明する。最終的な製品は，<a href="http://aws.amazon.com/ec2/instance-types">EC2 GPUインスタンス</a>を使用するという違いを除けば，Amazonの<a href="http://aws.amazon.com/elasticmapreduce/">Elastic MapReduce</a>と同じようなサービスになる。</p> 
  <p>GPUサーバを提供しているクラウドプロバイダは，もちろんAmazonだけではない。<a href="http://www.softlayer.com/dedicated-servers/high-performance-computing">IBM/Softlayer</a>や<a href="http://www.nimbix.net/nvidia/">Nimbix</a>などの会社でも，NVidia GPUを使用したサーバを提供している。ParallelXでAmazon以外のプロバイダをサポートする予定があるかという質問に，Tonyは次のように答えている &quot;直近ではありませんが，ユーザがインハウスのHadoopクラスタで使用できるようにSDKを提供する予定です。GPUクラウドプロバイダのほとんどはHPCクラウド上でGPUを提供していますが，私たちとしては，もっと安価なGPUをクラウドで利用したいのです。何といっても，安価な市販ハードウェアで動作することを目標として，Hadoopは設計されているのですから。&quot;</p> 
  <p>ParallelXコンパイラの動作についてもう少し理解するためには，GPUタイプの違いに加えて，並列コンピューティングのプラットフォームにも<a href="http://www.nvidia.com/object/cuda_home_new.html">CUDA</a>や<a href="http://en.wikipedia.org/wiki/OpenCL">OpenCL</a>といった違いがあることに注意する必要がある。その中でParallelXが対応するものは何か，Tonyの説明によれば，&quot;コンパイラはJVMバイトコードをOpenCL 1.2のコードに変換します。それがOpenCLコンパイラを通じて，GPU上で実行するシェーダアセンブリにコンパイルされるのです。現在はOpenCLコードも実行可能なFPGAハードウェアを用意していますが，将来は一般的な並列ハードウェアをサポートする予定です。&quot; リフレクションやネイティブコールを行うJavaコードはサポートされないとしても，MapReduceジョブに必要なコード変更を最小限に留めることがParallelXの目標だ。</p> 
  <p>ParallelXチームは現在，I/Oバウンドジョブのスループット向上を検討すると同時に，&quot;リアルタイムプロセッシング，PigとHiveのコードで表記されたクエリ，それからI/Oバウンドジョブ用に大規模なデータセットのストリーミングをサポートする作業をしています&quot; とTonyは話している。&quot;当社のパイプラインフレームワークを使用することで，社内テストではGPUのスループットと同等のI/Oスループットを実現しています。&quot;</p> 
  <p>現時点での開発は<a href="http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/emr-plan-hadoop-differences.html">Amazon Hadoopディストリビューション</a>が中心だが，チームは<a href="http://www.cloudera.com/content/cloudera/en/products-and-services/cdh.html">ClouderaのCHD</a>など，その他のHadoopディストリビューションをターゲットにする計画を持っている。このような商用ディストリビューションで提供されている<a href="http://hive.apache.org/">Hive</a>や<a href="http://pig.apache.org/">Pig</a>にある多数の改良点をParallelXのコンテキストで利用できるならば，それは間違いなく有効だろう。</p> 
  <p>ParallelXの生い立ちは実にユニークだ。Tonyは<a href="https://medium.com/game-changing-ideas/c3c516146599">ある記事</a>で，このプロジェクトにまつわる２年半の冒険旅行について語っている。それはフラタニティ(学生を対象とする社交クラブ)用のソーシャルネットワークに始まり，Facebookのウィジェットを経て，盗用コードの識別ツールに達する旅路だ。これらのプロジェクトには，グラフ分析やアルゴリズムをGPU上で実行するという共通点があった。ParallelXのアイデアはそこから自然発生的に生み出されたのだ。</p> 
  <p>ParalellXに適したワークロードにはさまざまなものが存在するが，中心となるのは，機械学習やグラフ処理のような多量の解析に代表されるハイパフォーマンスコンピューティングである。その方面の能力を示すためにParallelXでは，大規模なフラタニティのネットワークをひとつのCPUで，１秒以内にクラスタ化することに成功している。他の手段ならば，６台のコンピュータで並列化しても１時間は必要な処理だ。ただし実用上の目的に制約がある訳ではなく，MapReduce用に書かれたものであれば何であれ，ParallelXを使ってGPUで動作するようにコンパイルすることができる。</p> 
  <p>ParallelXの開発チームでは，現実のワークロードにおける彼らのHadoop-to-GPUコンパイラのパフォーマンスを立証するために，将来的にデータやホワイトペーパの公開を予定している。この話題に対するコミュニティの反応は分かれている。このニュースが<a href="https://news.ycombinator.com/">Hacker News</a>に掲載されたときの &quot;特別な主張には特別な証拠が必要だ&quot; というコメントに見られるように，ギアを切り替える前のホワイトペーパ公開を<a href="https://news.ycombinator.com/item?id=6762653">期待する声もある</a>。</p> 
  <p>GPUのパワーをHadoop上で味わうことならば，<a href="https://code.google.com/p/aparapi/">Aparapi</a>を使えば現在でも可能だ。Aparapiは，JavaバイトコードをOpenCLに変換することで，指定されたコードフラグメントをGPU上で実行可能にするJava APIで，Javaで記述されたMapReduceジョブに組み込むことができる。</p> 
  <p>ParallelXは，複雑なアルゴリズムをますます必要とする研究志向のユーザに対して，Hadoopを普及させる上で重要なステップになるかも知れない。例えばグラフ解析アルゴリズムについては，<a href="http://hama.apache.org/">Apache Hama</a>が一般化した<a href="http://en.wikipedia.org/wiki/Bulk_synchronous_parallel">バルク同期並列(BSP)</a>モデルを用いることで，今日では非常に良好なパフォーマンスが得られている。グラフアルゴリズムをMapReduceジョブとして実行する<a href="http://giraph.apache.org/">Apache Giraph</a>のようなプロジェクトをParallelXに組み込むことができれば，データ科学者のグラフ解析用ツールに大きな付加価値を提供することになるだろう。</p> 
  <p><a href="http://www.parallelx.com/">オンラインベータにサインアップする</a>には，メールアドレスを入力すればよい。 ParallelXでは，限定的なストレージでパワフルなGPUにアクセス可能なフリーミアムプランをサポートする予定だ。</p> 
 </div> 
</div><br><br><br><br><br><br></body></html>