<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>O que deve e o que não deve ser feito em uma API Web</h3><p>H&aacute; uma s&eacute;rie de discuss&otilde;es em torno do <a href="http://pt.wikipedia.org/wiki/REST">REST</a> e das <a href="http://en.wikipedia.org/wiki/Web_api">APIs web</a> nas listas e f&oacute;runs de discuss&atilde;o, e na opini&atilde;o de <a href="http://gotocon.com/berlin-2013/speaker/Oliver+Wolf">Oliver Wolf</a>, consultor s&ecirc;nior na InnoQ, n&atilde;o h&aacute; uma verdade absoluta. Foi assim que Wolf iniciou a sua <a href="http://gotocon.com/berlin-2013/presentation/Web%20API%20DOs%20and%20DON'Ts">palestra</a> <a href="http://www.google.com/url?q=http%3A%2F%2Fgotocon.com%2Fberlin-2013%2Fpresentation%2FWeb%2520API%2520DOs%2520and%2520DON'Ts&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNFwOLLI5aJuA5Khi6knAveDvZR1Og">&quot;</a><a href="http://gotocon.com/berlin-2013/presentation/Web%20API%20DOs%20and%20DON'Ts">O que deve e o que n&atilde;o deve ser feito em uma API Web</a>&quot;, na confer&ecirc;ncia <a href="http://gotocon.com/berlin-2013/speaker/Oliver+Wolf">GOTO Berlin</a>.</p>
<p><strong>N&atilde;o pense em termos de endpoints.</strong> A <a href="http://pt.wikipedia.org/wiki/SOAP">especifica&ccedil;&atilde;o SOAP</a> possui uma fachada com um ponto de entrada &uacute;nico. Em contraste com a web, que possui v&aacute;rios pontos de entrada que s&atilde;o constru&iacute;dos a partir de relacionamentos e interconex&otilde;es, tendo a hiperm&iacute;dia como um elemento cr&iacute;tico. Em vez de fazer com que a sua API se torne um buraco negro com apenas uma via de entrada, deve-se utilizar controles de hiperm&iacute;dia para vincular as suas representa&ccedil;&otilde;es de recursos, de modo que tenham significado para o seu p&uacute;blico.</p>
<p><strong>N&atilde;o exponha o seu modelo de dom&iacute;nio em sua API.</strong> Um problema presente em v&aacute;rios modelos &eacute; que estes cont&ecirc;m somente dados, sendo carentes de todos os tipos de comportamento (chamados de <a href="http://www.martinfowler.com/bliki/AnemicDomainModel.html">modelos an&ecirc;micos</a>). A exposi&ccedil;&atilde;o de um modelo como este acaba gerando recursos <a href="http://en.wikipedia.org/wiki/CRUD">CRUD</a> (Create, Read, Update, Delete). Isto n&atilde;o &eacute; necessariamente um ponto negativo, pois &agrave;s vezes tudo o que se precisa &eacute; de uma API CRUD pura. Entretanto, um problema em se expor somente um modelo CRUD &eacute; que um cliente usando uma API precisa de muito conhecimento: quais a&ccedil;&otilde;es podem ser executadas em quais recursos; em qual ordem fazer as coisas etc. Muita l&oacute;gica est&aacute; presente no cliente, gerando um acoplamento forte entre o cliente e o servidor.</p>
<p><strong>Projete sua API al&eacute;m da inten&ccedil;&atilde;o.</strong> Pense sobre o que o seu cliente quer e o que far&aacute;. Ocasionalmente isto requer um equil&iacute;brio entre clareza e flexibilidade, o qu&atilde;o limpa e simples a sua API deve ser versus qual flexibilidade &eacute; necess&aacute;ria. Um modo flex&iacute;vel, por&eacute;m mais imperativo de consultar quais s&atilde;o os clientes mais rent&aacute;veis, poderia ser assim:</p>
<pre>
GET /customers?sortBy=grossmargin&amp;order=descending
</pre>
<p>Em contrapartida, um estilo mais declarativo que exp&otilde;e a inten&ccedil;&atilde;o, por&eacute;m menos flex&iacute;vel, poderia ser assim:</p>
<pre>
GET /most_profitable_customers
</pre>
<p>A ideia central de Oliver aqui &eacute; pensar sobre o que um cliente precisa para usar a sua API, qual seria o seu objetivo e tentar adat&aacute;-la para este fim.</p>
<p><strong>N&atilde;o abuse dos verbos GET e POST.</strong> Basicamente significa que n&atilde;o se deve utiliz&aacute;-los da forma errada e que violem a especifica&ccedil;&atilde;o HTTP. Deve-se, por exemplo, n&atilde;o utilizar os verbos GET e POST para deletar um recurso. Os verbos HTTP s&atilde;o definidos por uma raz&atilde;o, eles possuem qualidades complementares e ganha-se muito ao seguir a especifica&ccedil;&atilde;o. Utilizar os verbos transmite inten&ccedil;&atilde;o, o que o cliente espera fazer e qual o comportamento o cliente pode esperar do servidor.</p>
<p><strong>N&atilde;o limite as suas op&ccedil;&otilde;es de c&oacute;digos de erro em 200 e 500.</strong> Utilize todo o espectro de c&oacute;digos de erro, h&aacute; 160 c&oacute;digos de erro para se escolher e h&aacute; um para quase todos os tipos de erro conceb&iacute;veis. Utilizar o c&oacute;digo de erro correto &eacute; chave para o tratamento adequado do erro no cliente.</p>
<p>Um problema comum &eacute; os servidores retornarem 200 (OK), embora tenha ocorrido um erro. Fingir que est&aacute; tudo bem quando na verdade n&atilde;o est&aacute;, nem sempre &eacute; uma boa ideia.</p>
<p><strong>N&atilde;o ignore o cache.</strong> Haver&aacute; caches envolvidos, sejam quais forem, e estes s&atilde;o uma parte muito importante da web. Auxilie os caches adicionando cabe&ccedil;alhos de cache apropriados. Se, por exemplo, n&atilde;o quiser que o cache seja realizado, seja explicito e o desligue.</p>
<p>Uma das melhores formas de se controlar o caching &eacute; utilizar validadores, de prefer&ecirc;ncia Etags, que permitem ao lado do servidor agir sobre dados arbitr&aacute;rios. Uma ETag &eacute; apenas um valor que o servidor gera e passa para o cache, e &eacute; posteriormente devolvido ao servidor pelo cache, que questiona o servidor sobre a recentidade do recurso.</p>
<p><strong>N&atilde;o obrigue versionamento.</strong> O que &eacute; considerado como uma altera&ccedil;&atilde;o de um recurso, na maioria das vezes &eacute; de fato uma altera&ccedil;&atilde;o na representa&ccedil;&atilde;o. O recurso continua sendo o mesmo e mant&eacute;m a mesma URL, sendo assim evite versionar a URL. Em vez disso deve haver uma nova vers&atilde;o do tipo de media, adicionando-se v2, por exemplo:</p>
<pre>
Content-Type=application/vnd.company.v2+xml
</pre>
<p><strong>N&atilde;o utilize extens&otilde;es na</strong> <strong>negocia&ccedil;&atilde;o</strong><strong> de conte&uacute;do.</strong> A forma adequada de se negociar sobre um formato de representa&ccedil;&atilde;o &eacute; atrav&eacute;s do uso do Accept e Content-Type no cabe&ccedil;alho.</p>
<p>A <a href="http://gotocon.com/berlin-2013/">GOTO Berling Conference 2013</a> foi a primeira confer&ecirc;ncia GOTO em Berlin, e reuniu 420 participantes e 80 palestrantes.</p><br><br><br><br><br><br></body></html>