<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Is Android Moving to a Closed Source Model?</h3><p>In an <a href="http://arstechnica.com/gadgets/2013/10/googles-iron-grip-on-android-controlling-open-source-by-any-means-necessary/">interesting analysis appeared on Ars Technica</a>, Ron Amadeo argues that Google is progressively shifting Android towards a closed source model. Google's strategy would aim at making Android suitable to be freely customised and used &quot;for little hobbies&quot;, while hampering the choices of &quot;anyone trying to use Android without Google’s blessing&quot;.</p>
<p>According to Amadeo, Google's strategy about Android has changed from its initial stage. At first, indeed, Google aimed at providing a full open source mobile platform, complete with all the necessary apps and services to make it usable and a thorough competitor in the mobile market. This approach had its goal in having as many manufacturers as possible engage with the Android Open Source Platform (AOSP).</p>
<p>In a second phase, continues Amadeo, after Android became dominant, Google stopped actively developing a few parts of AOSP, including apps like Search, Music, and Calendar. The Ars Technica piece goes into details describing how those open source apps came to a development standstill after Google rebranded them, enhanced them, and made them available as closed source apps in Play Store. “While you can't kill an open source app, you can turn it into abandonware by moving all continuing development to a closed source model&quot;, according to Amadeo. It can be also noted that, after the Ars Technica piece was written, <a href="http://www.unwiredview.com/2013/11/21/android-4-4-kitkat-ships-without-browser-app-oems-have-to-license-chrome-or-build-their-own/">Chrome was removed from Android 4.4</a> as well.</p>
<p>Another pillar of Google's Android strategy aims at locking-in manufacturers through the Open Handset Alliance (OHA), whose members &quot;are contractually prohibited from building <a href="http://source.android.com/compatibility/overview.html">non-Google approved devices</a>&quot;. What this means is that any OEM trying to build a mobile phone based on an incompatible fork of Android, will lose its rights within the OHA, namely the possibility to use Google Apps in any other product they develop. This contractual obligation has been leveraged by Google against Acer when it tried to ship a mobile phone based on <a href="http://en.wikipedia.org/wiki/Aliyun_OS">Aliyun OS</a>, a cloud-based Chinese Android fork. More famously, as Amadeo remarks, “no major OEM is allowed to produce the Kindle Fire for Amazon” if it wants to remain in the Android family.</p>
<p>The third pillar of Google's strategy as described in the Ars Technica article is locking-in third party apps through proprietary cloud APIs for Google maps, push notifications, location, in-app purchases, games. Such APIs are not part of AOSP and are not available on non-Google approved devices. In short, according to Amadeo:</p>
<blockquote> 
 <p>Google's strategy with Google Play Services is to turn the 'Android App Ecosystem' into the 'Google Play Ecosystem' by making a developer's life as easy as possible on a Google-approved device—and as difficult as possible on a non-Google-approved device.</p> 
</blockquote>
<p>A few of the comments to the article pointed out that:</p>
<ul> 
 <li>Google's strategy &quot;is defragging Android [...] Google is doing this because they have to.” (<a href="http://arstechnica.com/gadgets/2013/10/googles-iron-grip-on-android-controlling-open-source-by-any-means-necessary/?comments=1&amp;post=25517069">idealego</a>)</li> 
 <li>“From the standpoint of the individual user, Google is what brings value to Android devices and makes them useful...” (<a href="http://arstechnica.com/gadgets/2013/10/googles-iron-grip-on-android-controlling-open-source-by-any-means-necessary/?comments=1&amp;post=25516865">batmanuel</a>), “Google is entirely justified in keeping a tight lid on those things.” (<a href="http://arstechnica.com/gadgets/2013/10/googles-iron-grip-on-android-controlling-open-source-by-any-means-necessary/?comments=1&amp;post=25517107">karlsvec</a>)</li> 
 <li>“Even with all these tie-ins turning closed-source, Android as a base is still open-source.”(<a href="http://arstechnica.com/gadgets/2013/10/googles-iron-grip-on-android-controlling-open-source-by-any-means-necessary/?comments=1&amp;post=25517153">walkop</a>)</li> 
</ul>
<p>On the other hand, commenters also stressed that:</p>
<ul> 
 <li>“Google's PR face of 'open source android' is, essentially, a lie.” (db<a href="http://arstechnica.com/gadgets/2013/10/googles-iron-grip-on-android-controlling-open-source-by-any-means-necessary/?comments=1&amp;post=25517261">right</a>)</li> 
 <li>this strategy, specifically OHA obligations, could hamper innovation from mobile startups. (<a href="http://arstechnica.com/gadgets/2013/10/googles-iron-grip-on-android-controlling-open-source-by-any-means-necessary/?comments=1&amp;post=25517125">ChrisSD</a>)</li> 
</ul>
<p>At the time of this writing, <a href="http://arstechnica.com/gadgets/2013/10/googles-iron-grip-on-android-controlling-open-source-by-any-means-necessary/?comments=1&amp;post=25516889#comment-25516889">the most upvoted comment</a> is one likening Google's strategy to Microsoft's “Embrace, Extend, Extinguish”. (<a href="http://arstechnica.com/gadgets/2013/10/googles-iron-grip-on-android-controlling-open-source-by-any-means-necessary/?comments=1&amp;post=25516889#comment-25516889">Paul Rodgers</a>)</p>
<p>The discussion has extended beyond Ars Technica. In a <a href="http://www.androidauthority.com/google-control-friday-debate-286504/">debate hosted on Android Authority</a>, Robert Triggs states that Google “necessitates the production of some proprietary software and services. It’s impossible for Google to open up all of its software to the open-source crowd”. Adam Koueider observes that Google gaining more control over Android is ultimately a good thing for users, since “you can’t have one pie being pulled in 14 completely different directions”. A <a href="http://www.androidauthority.com/google-control-friday-debate-286504/#ViewPollResults">poll held on Android Authority website</a> shows that 72% of respondents believe that Google's increased control is good for users, while 13% believe it will be eventually bad.</p>
<p>Stijn Schuermans in the post <a href="http://www.visionmobile.com/blog/2013/11/the-naked-android/?1">'The Naked Android'</a> summarizes Google's strategy about its proprietary APIs:</p>
<blockquote> 
 <p>The operating system had been forked by Amazon and too many Asian handset makers. Worse, it had become too easy to replace Google Play with a proprietary app store yet leverage existing Android apps; too easy to replace Google’s services (Maps) with 3rd party alternatives (Nokia’s HERE). Even the Android brand wasn’t the king of the hill anymore, being eclipsed by Samsung’s Galaxy.</p> 
</blockquote>
<p>According to Schuermans, Google's response to this has been stripping down Android to its essentials, so that it could let go of it, while consolidating its proprietary Google Play Services and Google Apps.</p>
<p>Another dimension of this issue is represented by OEMs, their relationship with Google, and how they will react to Google's increasing control over Android.</p>
<p>In the context of an investigation about a patent infringement case, The Verge's Nilay Patel <a href="http://www.theverge.com/2011/05/12/google-android-skyhook-lawsuit-motorola-samsung/#2">reported about Google's practices towards OEMs</a>, stating that there was evidence of Google &quot;using compatibility as a club to make [OEMs] do what we want&quot; and the OEMs were aware of it; furthermore Google would have “a major role in Android device development, to the point where Andy Rubin himself approves and denies requests from OEMs”.</p>
<p>With Samsung selling about 63% of all mobile handsets and with five Samsung models among the ten most successful handsets (<a href="http://www.localytics.com/blog/2013/fonblets-and-phablets-samsung-has-share-of-android-mobile-devices/">Localytics data</a>), it becomes understandable why not controlling its own software is becoming a limit to break for Samsung and why the South Korean company is trying to give more and more relevance to its Tizen OS to move beyond Android, according to an <a href="http://www.firstpost.com/tech/why-samsung-is-planning-to-ditch-android-for-its-new-tizen-os-1225473.html">Associated Press story</a>.</p>
<p>Parmy Olson, <a href="http://www.forbes.com/sites/parmyolson/2013/10/28/samsung-kicks-off-its-first-developers-conference-as-it-seeks-an-edge-in-software/">writing for Forbes</a>, also establishes a relation between the latest efforts done by Samsung in order to get the developer community more engaged with its growing software platform and Google's increasing control over Android and remarks that “future growth depends on keeping customers loyal through unique software services.”</p><br><br><br><br><br><br></body></html>