<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Microsoft Ditches the Stack Ranking System. Yahoo! Lays off 600 because of It</h3><p>Yahoo! has recently laid off about 600 employees based on a ranking system introduced last year, while Microsoft is ditching their system to relieve some of the pressure from their staff.</p>
<p>Under its new CEO Marissa Mayer, Yahoo! introduced last year an employee evaluation system resulting in <a href="http://allthingsd.com/20131108/because-marissa-said-so-yahoos-bristle-at-mayers-new-qpr-ranking-system-and-silent-layoffs/">the layoff of some 600 people</a> during the last several weeks, according to AllThingsD. Not only that, but the system has upset many inside Yahoo! including managers who are forced to label certain team members as underperformers in order comply with the bell-curve-based evaluation system:</p>
<blockquote> 
 <p>I was forced to give an employee an occasionally misses, was very uncomfortable with it. Now, I have to have a discussion about it when I have my QPR meetings. I feel so uncomfortable because in order to meet the bell curve, I have to tell the employee that they missed when I truly don’t believe it to be the case. I understand we want to weed out mishires/people not meeting their goals, but this practice is concerning. I don’t want to lose the person mentally. How do we justify?</p> 
</blockquote>
<p>Using an internal anonymous message board, one Yahoo! employee argued that the ranking system should be applied to managers also:</p>
<blockquote> 
 <p>Will the ‘occasionally misses’ classification apply to L2 and L3 execs also? At every goals meeting, we find senior staff who missed even the 70% goals. Thus, by definition, they should be classified as ‘occasionally misses.’ Two such classifications, and that person should be let go, amiright? How about we set an example for the rest of the company and can a few of the top execs who miss (or who sandbag their goals to make sure they ‘meet’)?</p> 
</blockquote>
<p>In the meantime, Microsoft’s departing CEO Steve Ballmer has decided to eliminate the stack ranking system used for many years, a system considered by many inside and outside the company as Microsoft’s most destructive process:</p>
<blockquote> 
 <p><a href="http://www.theverge.com/2013/11/12/5094864/microsoft-kills-stack-ranking-internal-structure">The Verge</a>: <em>Vanity Fair </em>contributing editor Kurt Eichenwald blamed a combination of Microsoft’s obsessive focus on Windows and Office and the company’s internal stack ranking-system <a href="http://www.theverge.com/2012/7/3/3134719/microsoft-windows-office-loyalty-lost-decade">for a &quot;lost decade&quot; and cannibalistic culture</a>. Eichenwald interviewed a number of current and former Microsoft employees who all cited stack ranking as the most destructive process inside the software giant.</p> 
 <p><a href="http://www.businessweek.com/articles/2013-11-13/microsoft-kills-its-hated-stack-rankings-dot-does-anyone-do-employee-reviews-right">Bloomberg Businessweek</a>: David Auerbach, a former Microsoft employee, recently told <em>Bloomberg Businessweek </em>that the practice had employees feeling helpless and “<a href="http://www.businessweek.com/articles/2013-11-07/the-annual-performance-review-worthless-corporate-ritual">encouraged people to backstab their co-workers</a>.”</p> 
 <p><a href="http://www.forbes.com/sites/petercohan/2013/11/13/marissas-second-epic-fail-microsoft-abolishes-stack-ranking-as-yahoo-ramps-it-up/">Forbes</a>: Stack Ranking – forcing managers to rank their employees and get rid of the bottom ones — is a horrible idea that Microsoft’s Steve Ballmer imported from GE. As I wrote in <a href="http://www.forbes.com/sites/petercohan/2012/07/13/why-stack-ranking-worked-better-at-ge-than-microsoft/">July 2012</a>, stack ranking at Microsoft was a mess.</p> 
 <p><a href="http://online.wsj.com/news/articles/SB10001424052702303460004579193951987616572">The Wall Street Journal</a>: The rankings were a key factor in promotions and in allocating bonuses and equity awards under Chief Executive <a href="http://topics.wsj.com/person/B/Steve-Ballmer/599">Steve Ballmer</a>, who in August said he plans to retire within a year. But many current and former Microsoft employees complained the system resulted in capricious rankings, power struggles among managers, and unhealthy competition among colleagues.</p> 
</blockquote>
<p>According to an <a href="http://www.theverge.com/2013/11/12/5094864/microsoft-kills-stack-ranking-internal-structure">internal memo</a> sent to the employees by Microsoft HR Chief Lisa Brummel, there will be “No more curve”, “No more ratings”, the emphasis being on employee growth and team collaboration in the future:</p>
<blockquote> 
 <ul> 
  <li><b>More emphasis on teamwork and collaboration</b>.&nbsp; We’re getting more specific about how we think about successful performance and are focusing on three elements – not just the work you do on your own, but also how you leverage input and ideas from others, and what you contribute to others’ success – and how they add up to greater business impact.</li> 
  <li><b>More emphasis on employee growth and development</b>. Through a process called “Connects” we are optimizing for more timely feedback and meaningful discussions to help employees learn in the moment, grow and drive great results.&nbsp; These will be timed based on the rhythm of each part of our business, introducing more flexibility in how and when we discuss performance and development rather than following one timeline for the whole company.&nbsp; Our business cycles have accelerated and our teams operate on different schedules, and the new approach will accommodate that.</li> 
 </ul> 
</blockquote>
<p>The bell-curve ranking system was popularized by GE Chief Executive Jack Welch back in the 1980s being used by many companies, but <a href="http://www.businessweek.com/articles/2013-11-13/microsoft-kills-its-hated-stack-rankings-dot-does-anyone-do-employee-reviews-right">some of them have dropped it in the last years</a>, including Adobe and Expedia. The main idea of the system is that a company’s employees performance follows a bell-curve, having a small percentage of high performers, a large number of average performers and, at the lower end, another small percentage of underperformers. The system would be used to find and get rid of underperformers in order to improve the overall performance of the workforce and resulting in a smaller standard deviation which corresponds to a more homogeneous company, as show in the following chart (from <a href="http://web.mit.edu/chintanv/www/Publications/Chintan%20Vaishnav%20Punishing%20by%20Rewards%20for%20Publication%20Final.pdf">Punishing by Rewards: When the Performance Bell-curve Stops Working For You</a><em> - PDF)</em>:</p>
<blockquote> 
 <p><a href="/resource/news/2013/11/stack-ranking-microsoft-yahoo/en/resources/bell-curve-1.png" target="_blank"><img title="image" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" alt="image" src="http://www.infoq.com/resource/news/2013/11/stack-ranking-microsoft-yahoo/en/resources/bell-curve-1.png" border="0" _href="img://bell-curve-1.png" _p="true" /></a></p> 
</blockquote>
<p>But several studies performed in the last years indicate that the bell-curve ranking system has a number of flaws. <a href="http://www.bchrma.org/wp-content/uploads/2012/11/rb-the-best-and-the-rest.pdf"><em>The Best and the Rest: Revisiting the Norm of Normality of Individual Performance</em></a><em> (PDF)</em> indicates that instead of a Gaussian distribution the picture of performance if better represented by a Paretian distribution, as shown in the following chart:</p>
<blockquote> 
 <p><a href="/resource/news/2013/11/stack-ranking-microsoft-yahoo/en/resources/bell-curve-2.png" target="_blank"><img title="image" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" alt="image" src="http://www.infoq.com/resource/news/2013/11/stack-ranking-microsoft-yahoo/en/resources/bell-curve-2.png" border="0" _href="img://bell-curve-2.png" _p="true" /></a></p> 
</blockquote>
<p>According to this research, the majority of workers are underperformers (left) with a few of them being high performers (right). The recommendation of the research is not to keep the top performers and lay off the rest, but to “selectively source superstars for key positions where they will make the most impact to the bottom line.”</p>
<p>Another study, <a href="http://web.mit.edu/chintanv/www/Publications/Chintan%20Vaishnav%20Punishing%20by%20Rewards%20for%20Publication%20Final.pdf">Punishing by Rewards: When the Performance Bell-curve Stops Working For You</a><em> – PDF, </em>outlined a series of other problems with the bell-curve ranking system including the pressure put on employees when the system is applied:</p>
<blockquote> 
 <p>We observe that pressure, if maintained below a certain level, can lead to higher performance. However, as the lay-offs take place, constant pressure demoralizes employees, leading to drop in performance. As the bottom performers depart, the rigid distribution of the bell-curve forces managers to categorize a high performer (when compared to the rest of the labor market) as a mediocre. A high performer, unmotivated by such artificial demotion, behaves like a mediocre. Further, in a shrinking company, managers find it difficult to differentiate employees. As a result, they begin to reward visible performance over the actual. Beyond a certain point, the erosion of social capital has the potential to cripple the company.</p> 
</blockquote>
<p>The recommendations of this study are to maintain a balance between pressure and morale, and to decouple performance evaluation from lay-offs:</p>
<blockquote> 
 <p>We recommend the use of a semi-bell-curve that does not follow the rigid percentage distribution, and where someone who performers like a top performer is rewarded as one. Further, we recommend balancing pressure and morale. We recognize that this balance is very difficult to strike, especially in a company that is constantly shrinking. The only way we see of keeping the pressure at the optimum level and the morale high in such an organization <br /> is to decouple to some extent the performance evaluation process from the issue of lay-offs.</p> 
</blockquote><br><br><br><br><br><br></body></html>