<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>IBM Launches Contest for Cognitive Mobile Apps using Watson</h3><p>At the <a href="http://www.mobileworldcongress.com/">Mobile World Congress</a>, IBM has announced a developer contest for developers to create mobile consumer and business apps powered by <a href="http://www-03.ibm.com/innovation/us/watson/">IBM Watson cognitive computing platform</a>.</p>
<p>The winners of the <a href="http://www-03.ibm.com/press/us/en/pressrelease/43309.wss">IBM Watson Mobile Developer Challenge</a> will receive design consulting and support from IBM to gain access to the market.</p>
<p>IBM Watson is a computer system capable of answering questions posed in natural language. <a href="https://blogs.discovermagazine.com/sciencenotfiction/2010/06/28/watson-fails-the-turing-test-but-just-might-pass-the-jeopardy-test/">Watson is not yet able to pass the Turing Test</a> but it could <a href="http://www.cio.com/article/665677/IBM_Watson_Vanquishes_Human_Jeopardy_Foes">win the TV game show Jeopardy</a> against <a href="http://www.youtube.com/watch?v=WFR3lOm_xhE">former winners Brad Rutter and Ken Jennings</a>. Rutter and Jennings are not two randomly chosen human opponents: Rutter holds the record for Jeopardy! winnings while Jennings holds the record for longest Jeopardy! winning streak with 74 straight wins.</p>
<p><a href="http://en.wikipedia.org/wiki/Watson_(computer)#Software">Watson's software</a> was written in various languages, including Java, C++, and Prolog. Watson is based on Apache Hadoop framework for distributed computing, Apache UIMA (Unstructured Information Management Architecture) framework, IBM’s DeepQA software and SUSE Linux Enterprise Server 11 operating system. <a href="ftp://public.dhe.ibm.com/common/ssi/ecm/en/pow03061usen/POW03061USEN.PDF">According to IBM</a>, &quot;more than 100 different techniques are used to analyze natural language, identify sources, find and generate hypotheses, find and score evidence, and merge and rank hypotheses.&quot;</p>
<p><a href="http://en.wikipedia.org/wiki/Watson_(computer)#Processing">Watson's basic working principle</a> is to parse keywords in a clue while searching for related terms as responses. Watson's main strength is its <a href="http://wayback.archive.org/web/20110414214425/http://www.pbs.org/wgbh/nova/tech/will-watson-win-jeopardy.html">ability to quickly execute thousands of proven language analysis algorithms simultaneously</a> to find the correct answer. The more algorithms find the same answer independently, the more likely Watson is to be correct. Once Watson has a small number of potential solutions, it is able to check against its database to ascertain whether the solution makes sense.</p>
<p>In IBM's vision, <a href="http://www.cio.com/article/746296/IBM_Looks_to_Outsmart_Big_Data_Competition_With_Watson">cognitive computing comes down to three abilities</a>, each paired to a specific service IBM is offering:</p>
<ul> 
 <li> <p>Watson Discovery Advisor is intended to help find the right questions in data through natural language processing and to provide human-style communication.</p> </li> 
 <li> <p>Watson Analytics allows users to explore big data insights through visual representations, without the need for advanced analytics training.</p> </li> 
 <li> <p>Watson Explorer is intended to help users uncover and share data-driven insights through a unified view.</p> </li> 
</ul>
<p>The new step that <a href="http://www-03.ibm.com/press/us/en/pressrelease/42867.wss">IBM has taken with the creation of the Watson Group</a> has led to opening up Watson's technology through the <a href="http://www-03.ibm.com/innovation/us/watson/watson_ecosystem.shtml">Watson Development Cloud</a>, which aims at offering <a href="http://blog.programmableweb.com/2013/11/19/ibm-uses-restful-apis-to-turn-watson-into-a-cloud-service/">Watson functionality through a RESTful API</a> to enable third parties to design, develop, and deploy cognitive applications.</p>
<p>Other companies are playing in the cognitive computation field. <a href="http://www.expectlabs.com">Expect Labs</a>, makers of the <a href="http://www.expectlabs.com/mindmeld/">MindMeld app</a> for dynamically suggesting content in response to the topics in a spoken conversation, have recently launched their own <a href="http://blog.programmableweb.com/2014/02/19/today-in-apis-expect-labs-launches-mindmeld-api-and-5-new-apis/">cognitive platform as a service</a>, which could <a href="http://gigaom.com/2014/02/19/more-ai-for-developers-as-expect-labs-releases-the-mindmeld-api/">help build something similar to Google Now</a>. Wolfram released in 2009 its <a href="https://www.wolframalpha.com">Wolfram Alpha</a> computational knowledge engine <a href="http://en.wikipedia.org/wiki/Wolfram_Alpha">able to respond to natural language questions and generate a human-readable answer</a>. Finally, Google is also there. <a href="http://www.theguardian.com/technology/2014/feb/22/robots-google-ray-kurzweil-terminator-singularity-artificial-intelligence?">In a recent interview with The Guardian</a>, Google engineering director Ray Kurzweil explained how important natural language processing is to Google: “IBM’s Watson is a pretty weak reader on each page, but it read the 200m pages of Wikipedia. And basically what I’m doing at Google is to try to go beyond what Watson could do. To do it at Google scale.”</p><br><br><br><br><br><br></body></html>