<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Cresce competição entre implementações do Hadoop para consultas em tempo real</h3><p>Desde o an&uacute;ncio da tecnologia <a href="http://research.google.com/pubs/pub36632.html">Google Dremel</a>, a comunidade Hadoop vem tentando construir funcionalidade similar no Hadoop. O primeiro projeto nessa linha foi o <a href="https://code.google.com/p/dremel/">OpenDremel</a>, que atualmente &eacute; parte do <a href="http://www.infoq.com/news/2012/09/drill;jsessionid=2C33932E819FA62793C22B75CFE09974">Apache Drill</a>, e que por sua vez tornou-se um projeto na Apache Incubator no ano passado. Tamb&eacute;m no ano passado, a Cloudera apresentou o <a href="http://www.infoq.com/news/2012/10/HadoopWorld;jsessionid=2C33932E819FA62793C22B75CFE09974">Impala</a>, que atualmente est&aacute; em beta e &eacute; parte da distribui&ccedil;&atilde;o Hadoop da Cloudera: CDH 4.1.</p> 
<p>The new contender in this space is the <a href="http://hortonworks.com/blog/100x-faster-hive/">Stinger Initiative</a>, introduced by Hortonworks last week into Apache's incubation process, being aimed to:</p> 
<p>O novo competidor nesse espa&ccedil;o &eacute; o <a href="http://hortonworks.com/blog/100x-faster-hive/">Stinger Initative</a>, inclu&iacute;do pela Hortonworks no processo de incuba&ccedil;&atilde;o da Apache. O Stinger tem por objetivo:</p> 
<blockquote> 
 <p>Possibilitar que o tempo de resposta do Hive seja adequado para casos de uso com interatividade humana (exemplo: consultas que demoram entre 5 a 30 segundos), como explora&ccedil;&atilde;o de <a href="http://en.wikipedia.org/wiki/Big_data">Big Data</a>, visualiza&ccedil;&atilde;o e relat&oacute;rios parametrizados. Isso sem a necessidade de recorrer a mais uma ferramenta para instalar, manter e aprender a utilizar. Isso pode ser de grande valia para a comunidade de usu&aacute;rios com habilidades e investimentos no Hive.</p> 
</blockquote> 
<p>A Hortonworks pretende alcan&ccedil;ar esse objetivo, atrav&eacute;s das seguintes iniciativas:</p> 
<ul> 
 <li>Melhorando a compatibilidade do Hive com SQL, incluindo suporte aos tipos SQL que est&atilde;o faltando no Hive, e suporte a subconsultas na cl&aacute;usula &quot;where&quot;;</li> 
 <li>Otimizando o plano de execu&ccedil;&atilde;o do Hive;</li> 
 <li>Suportando o novo formato colunar do Hadoop chamado ORCFile (similar ao Dremel Drill e ao Trevini da Cloudera);</li> 
 <li>Introdu&ccedil;&atilde;o do novo framework de execu&ccedil;&atilde;o <a href="http://hortonworks.com/blog/introducing-tez-faster-hadoop-processing/">Tez</a>, baseado no <a href="http://www.infoq.com/articles/ApacheYARN;jsessionid=2C33932E819FA62793C22B75CFE09974">YARN</a>.</li> 
</ul> 
<p>O framework Tez (palavra hindi que significa &quot;velocidade&quot;) atualmente em processo de vota&ccedil;&atilde;o para incuba&ccedil;&atilde;o na Apache:</p> 
<blockquote> 
 <p>[&Eacute; um] framework altamente customiz&aacute;vel, de prop&oacute;sito geral e que simplifica a cria&ccedil;&atilde;o de tarefas de processamento de dados atrav&eacute;s de cargas de trabalho no Hadoop que sejam tanto de pequena escala (baixa lat&ecirc;ncia) quanto de grande escala (alta vaz&atilde;o). O Tez generaliza o paradigma <a href="http://en.wikipedia.org/wiki/MapReduce">MapReduce</a> para um framework mais poderoso, ao fornecer a habilidade de executar um <a href="http://pt.wikipedia.org/wiki/Grafos_ac%C3%ADclicos_dirigidos">DAG (gr&aacute;fico ac&iacute;clico dirigido)</a> complexo de tarefas para um &uacute;nico job. Dessa forma, projetos do ecossistema Apache Hadoop, como Apache Hive, Apache Pig e Cascading, podem atender aos requisitos de tempo de resposta para interatividade humana e de alt&iacute;ssima vaz&atilde;o, na escala de petabytes (claramente, o MapReduce foi fundamental para atingir esse objetivo).</p> 
</blockquote> 
<p>As tr&ecirc;s implementa&ccedil;&otilde;es do Hadoop para consultas em tempo real (Drill, Impala e agora o Stinger) j&aacute; s&atilde;o open source, ou ter&atilde;o seu c&oacute;digo aberto em breve. Poder&atilde;o, assim, contar com o apoio e feedback da comunidade, para resolver problemas importantes na &aacute;rea de consultas em tempo real com Hadoop.</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>