<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Ensino de programação para todos: oportunidade para suprir as demandas de mercado</h3><p>Foi lan&ccedil;ado recentemente o site <a href="http://www.code.org/">Code.org</a>, com o objetivo principal de disseminar conhecimento em programa&ccedil;&atilde;o e tentar suprir a grande demanda de programadores prevista para os pr&oacute;ximos anos, principalmente nos Estados Unidos.</p> 
<p>O site tem o apoio de grandes nomes da ind&uacute;stria norte-americana que corroboram com a ideia, tais como: Bill Gates (Microsoft), Mark Zuckerberg (Facebook), Eric Schmidt (Google), al&eacute;m de alguns nomes da pol&iacute;tica, esporte e m&uacute;sica: <a href="http://pt.wikipedia.org/wiki/Bill_Clinton">Bill Clinton</a> (ex-presidente norte-americano), <a href="http://pt.wikipedia.org/wiki/Chris_Bosh">Chris Bosh</a> (Miami Heat) e <a href="http://pt.wikipedia.org/wiki/Will.i.am">will.i.am</a> (Black Eyed Peas).</p> 
<p>Um <a href="http://www.youtube.com/watch?v=dU1xS07N-FA">v&iacute;deo institucional</a> de divulga&ccedil;&atilde;o do site, em que s&atilde;o apresentadas as raz&otilde;es da iniciativa Code.org, est&aacute; invadindo as redes sociais e tem se propagado rapidamente. No v&iacute;deo, uma frase c&eacute;lebre de Steve Jobs ganhou destaque:</p> 
<blockquote> 
 <p>Todos deste pa&iacute;s deveriam aprender como programar um computador... pois isso ensina voc&ecirc; a pensar.</p> 
</blockquote> 
<p>Depois, Bill Gates conta a sua hist&oacute;ria:</p> 
<blockquote> 
 <p>Eu tinha apenas 13 anos de idade quando tive acesso ao primeiro computador. Codifiquei um programa de Jogo da Velha.</p> 
</blockquote> 
<p>Mark Zuckerberg incentiva o aprendizado de programa&ccedil;&atilde;o dizendo:</p> 
<blockquote> 
 <p>Acredito que voc&ecirc; pode come&ccedil;ar programando pequenas coisas. E um dos maiores equ&iacute;vocos sobre a Ci&ecirc;ncia da Computa&ccedil;&atilde;o e programa&ccedil;&atilde;o, em geral, &eacute; o fato de que voc&ecirc; precisa aprender um grande conjunto de informa&ccedil;&otilde;es antes de come&ccedil;ar a construir algo.</p> 
</blockquote> 
<p>Segundo a <a href="http://www.code.org/stats">estat&iacute;stica exibida no pr&oacute;prio site</a>, h&aacute; um crescimento acentuado da demanda de programadores nos Estados Unidos, mostrando que o pa&iacute;s n&atilde;o ter&aacute; condi&ccedil;&otilde;es de suprir a demanda at&eacute; 2020, pelo menos. <a href="http://www.infoq.com/news/2013/02/agile-developers-needed;jsessionid=05E033851BDF39817BA8A2DE0A38FD81">Outra not&iacute;cia</a>, publicada no InfoQ, refor&ccedil;a a procura por desenvolvedores e demonstra como est&aacute; a demanda por contrata&ccedil;&atilde;o de profissionais que seguem a filosofia &aacute;gil.</p> 
<p>Na mesma linha do Code.org, v&aacute;rios cursos online e gratuitos est&atilde;o dispon&iacute;veis na Internet, e oferecem conte&uacute;do, material e carga hor&aacute;ria adequados, como: <a href="https://www.coursera.org/category/cs-programming">Coursera</a>, <a href="https://www.udacity.com/">Udacity</a>, <a href="https://www.edx.org/courses/">Edx</a>, <a href="http://www.teachingtree.co/">Teaching Tree</a> e <a href="http://www.veduca.com.br/index.php">Veduca</a> (em portugu&ecirc;s).</p> 
<p>E quanto ao Brasil? Como est&aacute; o mercado de desenvolvimento de software? N&atilde;o seria uma brilhante ideia disseminarmos o ensino de forma gratuita por aqui? O aprendizado de programa&ccedil;&atilde;o n&atilde;o somente alavanca a economia do pa&iacute;s como ensina algo muito mais importante &agrave; popula&ccedil;&atilde;o: pensar logicamente e de forma estruturada.</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>