<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Google's BigQuery Gaining Momentum</h3><p>Google's BigQuery, a <a href="https://developers.google.com/bigquery/what-is-bigquery">SaaS query offering by Google</a>, seems to gain more and more momentum. It allows to query <a href="https://cloud.google.com/developers/articles/bigquery-in-practice">large-scale columnar data structures</a>&nbsp;in the cloud. Developers can load data into BigQuery via upload to <a href="https://developers.google.com/storage/">Google Cloud Storage</a> (the equivalent of Amazon's S3) or <a href="https://developers.google.com/bigquery/streaming-data-into-bigquery">stream data into the platform</a>, and then perform OLAP-style queries using a SQL-like query language.</p>
<p>Practitioners now increasingly share their hands-on experience with BigQuery. For example,&nbsp;Graham Polley of Shine Technologies&nbsp;<a href="http://blog.shinetech.com/2014/01/18/reeling-in-big-data-using-googles-bigquery/">reported</a>:</p>
<blockquote>
 We decided to run our own tests, laying down the gauntlet to BQ and using a data set with 1.5 billion rows. Things were about to get very interesting – could Google’s sales pitch of &quot;being able to interactively analyse massive data sets with billions of rows&quot; really do what it said it could? It could and we were impressed. In fact, very impressed. Even when not using cached results (cached results can be toggled on and off) we experienced consistent results in the 20-25 second range for grinding through our massive data set of 1.5 billion rows using relatively complex queries to aggregate the data.
</blockquote>
<p>BigQuery can be used stand-alone, but also provides integration with other services, such as <a href="https://developers.google.com/apps-script/articles/bigquery_tutorial">Google Apps Script</a> or Google Analytics. Concerning the latter, Jonathan Weber (Data Evangelist at LunaMetrics) wrote an <a href="http://www.lunametrics.com/blog/2014/01/27/google-analytics-bigquery-whys-hows/">informative piece</a>&nbsp;where he states:</p>
<blockquote>
  First, BigQuery export is available only for Google Analytics Premium customers. You can have the BigQuery export turned on through your Premium account manager. Note that there are costs for both data storage and processing in BigQuery, but GA Premium users get a $500/month credit to use toward those charges. In many cases, that $500 will take you a long way. For reference, I took a look at one of our Premium customers using BigQuery. Their site has about 6M visits and 50M pageviews per month. Data has been exporting since September, and this month their storage charges will be about $12.86.
 <br /> 
</blockquote>
<p>While BigQuery is only available as a cloud-based solution, the underlying technology that powers BigQuery (<a href="http://research.google.com/pubs/pub36632.html">Dremel</a>) is the core of many <a href="http://www.infoq.com/news/2013/12/open-source-sql-hadoop-solutions">Open Source SQL-in-Hadoop solutions</a> such as Apache Drill or Impala.</p><br><br><br><br><br><br></body></html>