<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>QCon London 2014 Tutorials: Reactive Extensions, Mobile Dev, Agile, Continuous Delivery (March 3-7)</h3><p>Language pioneers, project leads, and seasoned practitioners will provide two days of hands-on tutorials at the eighth annual <a href="http://qconlondon.com/?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">QCon London (Mar 3-7, 2014)</a>. &nbsp;Three to six hours in length, each QCon tutorial delves into a new technology, tool, or methodology driving innovation in enterprise software development. &nbsp;For the three day conference that follows, you can get in early by reserving your seat now&nbsp;<strong>saving &nbsp;&pound;236</strong> by&nbsp;<strong>Jan 8th.</strong></p>
<p>Some of this year's 15 tutorials, taking place March 3rd and 4th, include:</p>
<ul> 
 <li><a href="http://qconlondon.com/london-2014/presentation/Principles%20of%20Reactive%20Programming/?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">Principles of Reactive Programming</a>, by <strong>Erik Meijer,</strong> Creator, LINQ</li> 
 <li><a href="http://qconlondon.com/london-2014/presentations/show_presentation.jsp?oid=5897&amp;utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">Continuous Delivery</a>, by <strong>Dave Farley</strong>, Co-Author, &quot;Continuous Delivery&quot;</li> 
 <li><a href="http://qconlondon.com/london-2014/presentations/show_presentation.jsp?oid=5899&amp;utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">Creating Android Apps with Xtend</a>, by <strong>Sven Efftinge</strong>, Founder Xtext Framework</li> 
 <li><a href="http://qconlondon.com/london-2014/presentations/show_presentation.jsp?oid=5907&amp;utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">Fast and Beautiful Mobile Apps with Phone Gap</a>, by <strong>Brian LeRoux</strong>, PhoneGap Project Lead, Adobe</li> 
 <li><a href="http://qconlondon.com/london-2014/presentations/show_presentation.jsp?oid=5904&amp;utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">Problem-solving and Decision-making in Software Development</a>, by <strong>Linda Rising</strong>, Queen of Patterns</li> 
 <li><a href="http://qconlondon.com/london-2014/presentations/show_presentation.jsp?oid=5901&amp;utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">A Fluent API for Java and MongoDB</a>, by <strong>Trisha Gee,</strong> Software Engineer, MongoDB</li> 
 <li><a href="http://qconlondon.com/london-2014/presentations/show_presentation.jsp?oid=5893&amp;utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">Getting the Most out of Your Distributed Team</a>, by <strong>Shane Hastie</strong>, InfoQ Agile Lead Editor, Agile Coach</li> 
 <li><a href="http://qconlondon.com/london-2014/presentations/show_presentation.jsp?oid=5896&amp;utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">Systems Thinking and Methods</a>, by <strong>Michael T. Nygard</strong>, Author of &quot;Release IT!&quot;</li> 
 <li><a href="http://qconlondon.com/london-2014/presentations/show_presentation.jsp?oid=5900&amp;utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">Embracing Change: Building Adaptable Software with Events</a>, by <strong>Russell Miles</strong>, Co-Author of &quot;Head First Software Development&quot;</li> 
 <li><a href="http://qconlondon.com/london-2014/presentations/show_presentation.jsp?oid=5898&amp;utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">The Psychological and Cognitive Mechanisms behind Good User Experience</a>, by <strong>Janne Jul Jensen</strong>, Senior Interaction Designer and Usability Specialist</li> 
</ul>
<p>See the complete list of tutorials <a href="http://qconlondon.com/london-2014/training/?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">here</a>.</p>
<p>The three full conference days (Mar 5-7) that follow will feature over 100 speakers presenting across 15 different tracks covering topics like Java, Big Data, Agile, Cloud, HTML5, Mobile, Architecture, and more.</p>
<p>Don't forget about our <a href="http://qconlondon.com/london-2014/upcomingevents/?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">QCon Nights</a>. These are free evening community events, driven by involvement from both speakers and participants. Come along and learn something new! Join <strong>Mark Harwood, Software Engineer at Elasticsearch Inc,</strong> on <strong>January 15</strong>, and listen his talk on <a href="http://qconlondon.com/london-2014/upcomingevents/?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news">What's New in Elasticsearch 1.0</a>.</p>
<p><b>Attending with your colleagues?</b>&nbsp;QCon London offers special savings when you register a group of five or more people from your company.&nbsp;<a href="https://secure.trifork.com/london-2014/registration/?utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=12042013news">Click here for more details</a>. &nbsp;</p>
<p>QCon London 2013 drew over 1,100 attendees last year and elicited thousands of tweets and hundreds of blogs all of which are summarized in the&nbsp;<a href="http://www.infoq.com/articles/QCon-London-2013">Key Takeaway Points and Lessons Learned from QCon London 2013</a>.&nbsp;&nbsp;We hope you can join us for QCon London 2014.&nbsp;<a href="https://secure.trifork.com/london-2014/registration/&amp;utm_source=infoq&amp;utm_medium=news&amp;utm_campaign=01062014news"><strong>Register before January 8th and save &pound;236.</strong></a>&nbsp;</p>
<p>QCon is co-produced by InfoQ.com and Trifork, producer of the Danish GOTO conference.</p><br><br><br><br><br><br></body></html>