<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>REST e a Internet das Coisas</h3><p>J&aacute; faz mais de uma d&eacute;cada desde que as pessoas come&ccedil;aram a falar sobre <a href="http://www.ubiq.com/hypertext/weiser/UbiHome.html">Computa&ccedil;&atilde;o Ub&iacute;qua</a> ou <a href="http://www.rfidjournal.com/articles/view?4986">Internet das Coisas</a> (quase tr&ecirc;s d&eacute;cadas para a primeira), e naquela &eacute;poca era considerado um sonho. Atualmente &eacute; uma realidade, estamos rodeados &agrave; todo momento por <a href="http://www.hpts.ws/papers/2013/gongshow/WayneDuquaine.pdf">diversos dispositivos habilitados</a> para a Internet. Recentemente, muito trabalho tem sido realizado por alguns grupos de padroniza&ccedil;&atilde;o (como o <a href="http://www.ietf.org/">IETF</a>, por exemplo) em diversos aspectos relacionados com a Internet das Coisas (IoT), incluindo o protocolo <a href="http://tools.ietf.org/html/draft-bormann-cbor-00">Concise Binary Object Represantation</a> (CBOR), que visa preencher mensagens pequenas com o m&aacute;ximo poss&iacute;vel de informa&ccedil;&atilde;o.</p>
<blockquote> 
 <p>O Concise Binary Object Representation (CBOR) &eacute; um formato de dados em que os objetivos de design incluem a possibilidade de tamanho de c&oacute;digo extremamente reduzido, tamanho de mensagem relativamente pequeno, e extensibilidade sem a necessidade de negocia&ccedil;&atilde;o de vers&atilde;o. Estes objetivos de design o diferenciam de protocolos mais antigos de serializa&ccedil;&atilde;o bin&aacute;ria, como o ASN.1 e MessagePack.</p> 
</blockquote>
<p>Mas foi s&oacute; uma quest&atilde;o de tempo, at&eacute; que o REST fosse utilizado nesta &aacute;rea. O grupo de trabalho <a href="https://datatracker.ietf.org/wg/core/charter/">Constrained RESTful Environments</a> (CoRE) &eacute; financiado pelo IETF para fornecer:</p>
<blockquote> 
 <p>[...] um framework para aplica&ccedil;&otilde;es orientadas a recursos, direcionado a execu&ccedil;&atilde;o em redes IP restritas. Uma rede IP restrita possui pacotes de tamanhos limitados, pode exibir um alto &iacute;ndice de perda de pacotes, e ter um n&uacute;mero substancial de dispositivos que podem ser desligados a qualquer momento, mas que s&atilde;o periodicamente &quot;acordados&quot; por curtos intervalos de tempo.</p> 
</blockquote>
<p>Como parte desse framework de constru&ccedil;&atilde;o de aplica&ccedil;&otilde;es para dispositivos restritos, o grupo de trabalho tamb&eacute;m definir&aacute; o Constrained Application Protocol (CoAP) para manipula&ccedil;&atilde;o de recursos nestes dispositivos:</p>
<blockquote> 
 <p>O Grupo de Trabalho definir&aacute; um mapeamento entre o CoAP e uma API HTTP REST; este mapeamento n&atilde;o ser&aacute; dependente de uma aplica&ccedil;&atilde;o espec&iacute;fica. Vale a pena notar que n&atilde;o &eacute; necess&aacute;rio haver proxy na fronteira entre a rede restrita e a rede geral, mas pode ser implantado em v&aacute;rios pontos da rede irrestrita.</p> 
</blockquote>
<p>O grupo j&aacute; definiu uma s&eacute;rie de requisitos que o protocolo deve atender, incluindo:</p>
<ul class="c7 lst-kix_v1exfu6tfg7g-0 start"> 
 <li>A capacidade de criar, ler, atualizar e remover um recurso em um dispositivo;</li> 
 <li>Suportar o envio de mensagens multicast n&atilde;o confi&aacute;veis a um grupo de dispositivos;</li> 
 <li>Deve operar sobre UDP, com algum suporte opcional (e limitado) ao TCP;</li> 
 <li>Especifica&ccedil;&atilde;o da API baseada em HTTP REST e a <a href="http://tools.ietf.org/html/draft-castellani-core-http-mapping-02">sua tradu&ccedil;&atilde;o entre CoAP e o HTTP</a> para comunica&ccedil;&atilde;o de dispositivos.</li> 
</ul>
<p>Visto que o grupo apenas iniciou seus trabalhos recentemente, ainda h&aacute; uma s&eacute;rie de indefini&ccedil;&otilde;es, como seguran&ccedil;a, por exemplo. Contudo, j&aacute; existe um projeto que suporta CoAP em Java com <a href="https://code.google.com/p/jcoap/">jCoAP</a>.</p><br><br><br><br><br><br></body></html>