<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Oracle lança o Java 8</h3><p>No dia 18/03, durante o evento <a href="http://www.eclipsecon.org/na2014/">EclipseCon</a>, a Oracle anunciou a <a href="http://mreinhold.org/blog/jdk8-ga">vers&atilde;o completa e est&aacute;vel (GA)</a> do <a href="http://www.oracle.com/technetwork/java/javase/downloads/index.html">Java 8</a>, a primeira grande atualiza&ccedil;&atilde;o dos &uacute;ltimos 2 anos. O <a href="http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html">download est&aacute; dispon&iacute;vel</a> para Linux e Windows no formato 32 ou 64 bits, e tamb&eacute;m para Mac OS X e Solaris 64 bits. H&aacute; tamb&eacute;m um vers&atilde;o para ARM (compilador para o Hard Float ABI) que pode ser usado no Raspbian e em outras plataformas do Raspberry Pi.</p>
<p>O Java 8 traz muitas <a href="http://www.oracle.com/technetwork/java/javase/8-whats-new-2157071.html">melhorias e novas funcionalidades</a>. Dentre as quais podemos destacar:</p>
<ul> 
 <li><strong>Lambdas</strong> fornecem uma maneira de passar fun&ccedil;&otilde;es como dados. Com a convers&atilde;o impl&iacute;cita para tipos de Single Abstract Method (M&eacute;todo Abstrato Simples, tal como o Runnable) simplificar&aacute; muito o c&oacute;digo necess&aacute;rio para passar filtros ou atributos como dados. (Note que a raz&atilde;o pela qual isso &eacute; chamado de lambdas &eacute; que o Java possui closures na forma de classes internas desde a vers&atilde;o 1.1; o que alguns chamam de forma incorreta de closures, na verdade est&atilde;o falando de lambdas.) Um exemplo de lambda &eacute; x -&gt; x + 1;</li> 
 <li><strong>Refer&ecirc;ncias de m&eacute;todos</strong> permitem que m&eacute;todos est&aacute;ticos possam ser referenciados como fun&ccedil;&otilde;es que podem ser passadas para outras fun&ccedil;&otilde;es. Um exemplo pode ser o Integer::parseInt, que pode ser mapeado para uma cole&ccedil;&atilde;o de Strings para produzir uma cole&ccedil;&atilde;o de Integers;</li> 
 <li><strong>Streams</strong> que fornecem um itera&ccedil;&atilde;o no estilo <i>lazy</i> dos valores, tanto a partir de uma cole&ccedil;&atilde;o, como de uma s&eacute;rie infinita (tal como a ThreadLocalRandom) ou de um intervalo fixo (tal com os produzidos pelo byIntStream); bem como a itera&ccedil;&atilde;o sobre os dados, sendo permitido processar em paralelo e realizar redu&ccedil;&otilde;es, filtragens e mapeamentos que permitem que a combina&ccedil;&atilde;o com lambdas forne&ccedil;a constru&ccedil;&otilde;es de programa&ccedil;&atilde;o funcional em Java;</li> 
 <li><strong>Os m&eacute;todos de extens&atilde;o</strong> permitem uma maneira de adicionar novos m&eacute;todos para interfaces que j&aacute; existem no Java sem a necessidade recompilar as classes que utilizam essas interfaces. Isso &eacute; usado em uma grande quantidade de classes de cole&ccedil;&otilde;es para fornecer interfaces para a implementa&ccedil;&atilde;o de streams e outras refer&ecirc;ncias &uacute;teis que de outra forma deveriam estar na classe utilit&aacute;ria Collections;</li> 
 <li><strong>JSR310</strong> adicionou o novo processamento de data e hora no Java, para evitar os problemas excessivos da classe java.util.Date e dos pacotes relacionados;</li> 
 <li><strong>PermGen</strong> nunca mais; os desenvolvedores n&atilde;o precisar&atilde;o mais adicionar a flag -XX:PermGen para adivinhar antes da hora qual a quantidade de strings ser&atilde;o criadas internamente pela aplica&ccedil;&atilde;o;</li> 
 <li><strong>Nashorn</strong> adicionou suporte nativo para JavaScript na JVM, permitindo que o Java e outras linguagens baseadas na JVM possam utilizar as vantagens do JavaScript nas suas aplica&ccedil;&otilde;es;</li> 
 <li><strong>OpenJFX</strong> trouxe o JavaFX para o OpenJDK, preparando o terreno para que as IDEs futuras possam utilizar esse sistema de interface gr&aacute;fica de usu&aacute;rio.</li> 
</ul>
<p>Assim como o Java 8, todos os grandes fabricantes de IDEs anunciaram o suporte ao Java 8 no mesmo dia, como o <a href="https://wiki.eclipse.org/JDT/Eclipse_Java_8_Support_For_Kepler">patch dispon&iacute;vel para o Eclipse 4.3.2</a>, uma pequena vers&atilde;o do <a href="http://www.jetbrains.com/idea/">IntelliJ 13.1</a> e a nova vers&atilde;o do <a href="https://netbeans.org/community/releases/80/">NetBeans 8.0</a>.</p><br><br><br><br><br><br></body></html>