<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>JavaScript Memory Analyzer in Visual Studio 2012 Identifies Leaks in Windows Store Apps</h3><p><a href="http://blogs.msdn.com/b/somasegar/archive/2012/11/26/visual-studio-2012-update-1-now-available.aspx">Visual Studio 2012 Update 1</a> includes a <a href="http://blogs.msdn.com/b/visualstudio/archive/2013/01/28/javascript-memory-analysis-for-windows-store-apps-in-visual-  studio-2012.aspx">JavaScript memory analysis tool</a> for Windows 8 that enables developers to identify how much memory is being consumed by a JavaScript based <a href="http://www.windowsstore.com/">Windows Store</a> app and is available for Visual Studio 2012 Express, Professional, Premium and Ultimate on Windows 8.</p> 
<p><img src="http://www.infoq.com/resource/news/2013/04/javascript-memory-analyzer/en/resources/4Figure_1.png;jsessionid=43DB6F92D9BD88F680B8950F6E7F323C" alt="" _href="img://4Figure_1.png" _p="true" /></p> 
<p>The <em>Launch startup project </em>option in JavaScript memory tool enables developers to analyze the startup project in the current Visual Studio instance. The <em>Launch installed App </em>Package option launches the Windows Store app which enables Visual Studio 2012 to start the diagnostic session. The last option, <em>Attach to running app</em> prompts you to attach to the already running apps to enable Visual Studio to start the diagnostic session.</p> 
<p><img src="http://www.infoq.com/resource/news/2013/04/javascript-memory-analyzer/en/resources/1Figure_2.png;jsessionid=43DB6F92D9BD88F680B8950F6E7F323C" alt="" _href="img://1Figure_2.png" _p="true" /></p> 
<p>A process memory graph will be displayed when you launch the JavaScript memory tool that allows you to observe the amount of memory consumed by the app over time. The graph gives you an indication of the memory trend for the app which enables you to judge when it is appropriate to take a heap snapshot.</p> 
<p>In order to inspect JavaScript memory, you have to make use of <em>Take a Snapshot </em>option, which generates a summary tile that indicates the size of the JavaScript heap at the time the snapshot was taken along with the number of objects allocated in addition to a screenshot of the application.</p> 
<p>You can continue to capture snapshots at regular intervals and you can use the generated additional tiles for future comparison. Moreover, built-ins and objects IDs can be shown in the details table by using the drop down at the top right corner of the details view.</p> 
<p><a href="/resource/news/2013/04/javascript-memory-analyzer/en/resources/Figure_3_Original.png;jsessionid=43DB6F92D9BD88F680B8950F6E7F323C" target="_blank"><img src="http://www.infoq.com/resource/news/2013/04/javascript-memory-analyzer/en/resources/Figure_3.png;jsessionid=43DB6F92D9BD88F680B8950F6E7F323C" alt="" _href="img://Figure_3.png" _p="true" /></a></p> 
<p>It is also possible to capture snapshots programmatically using console.takeHeapSnapshot, which takes a snapshot that appears on the tool and console.profileMark, which displays a profile mark in the memory graph while the diagnostic session is running including the ability to annotate the graph with custom marks.</p> 
<p>Sometimes, you will be required to check for existence of the commands before usage, since they are only available in the context of the memory analyzer:</p> 
<p><code>if (console &amp;&amp; console.takeHeapSnapshot) <br /> {<br /> console.takeHeapSnapshot();<br /> } </code></p> 
<p>By default, the snapshots collection is saved to disk under a diagnostic sessions folder, which contains .diagsession files. It can then be renamed, shared across teams and can also be reopened in compatible versions of <a href="http://www.microsoft.com/visualstudio/eng/downloads">Visual Studio 2012</a>. The snapshot tiles and the details views can be inspected upon opening the file.</p> 
<p><strong>Image Source</strong> - <a href="http://blogs.msdn.com/b/visualstudio/archive/2013/01/28/javascript-memory-analysis-for-windows-store-apps-in-visual-studio-2012.aspx">MSDN</a> &amp; <a href="http://www.drdobbs.com/windows/visual-studio-2012-update-1-arrives/240142941">Dr. Dobbs</a></p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>