<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>AWS se junta a concorrência dos provedores de Cloud e oferece suporte ao Node.js</h3><p>O time da Amazon Web Services (AWS) recentemente adicionou suporte ao Node.js para seu servi&ccedil;o <a href="http://www.google.com/url?q=http%3A%2F%2Faws.amazon.com%2Felasticbeanstalk%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNFA4nVzgzWNosTVz0peuGz_TaXvQQ">Elastic Beanstalk</a>, dando a Amazon a lideran&ccedil;a de mercado em n&uacute;mero de plataformas suportadas. Al&eacute;m do Node.js, a AWS Elastic Beanstalk d&aacute; ao desenvolvedor a habilidade de empacotar, instalar, e gerenciar aplica&ccedil;&otilde;es escritas em Java, PHP, .NET, Ruby e Python. A AWS tem se juntado ao repleto time de provedores de Clouds com suporte ao Node.js e tentar&aacute; se diferenciar dos concorrentes atrav&eacute;s da integra&ccedil;&atilde;o com os principais servi&ccedil;os da AWS.</p> 
<p>Em um <a href="http://www.google.com/url?q=http%3A%2F%2Fwww.allthingsdistributed.com%2F2013%2F03%2Fbeanstalk-a-la-node.html&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNE16Ve8DIohCEPC7YL-iQ3uti3S3g">post no blog do CTO da AWS, Werner Vogels, sobre a adi&ccedil;&atilde;o do Node.js</a>, Werner descreve algumas das raz&otilde;es para incluir esta plataforma que &eacute; cada vez mais popular.</p> 
<blockquote> 
 <p>Gastei muito tempo conversando com os desenvolvedores da AWS, sendo que muitos deles trabalham nas &aacute;reas de jogos e mobile, e a maioria destes desenvolvedores t&ecirc;m achado o Node.js bastante adequado para suas aplica&ccedil;&otilde;es web. Com o modelo de programa&ccedil;&atilde;o ass&iacute;ncrona, orientada a eventos, o Node.js permite que estes desenvolvedores tratem um grande n&uacute;mero de conex&otilde;es concorrentes com baixa lat&ecirc;ncia. Estes desenvolvedores normalmente usam inst&acirc;ncias EC2 combinadas com um de nossos servi&ccedil;os de banco de dados para criar servi&ccedil;os web usados na recupera&ccedil;&atilde;o de dados ou criar interfaces mobile din&acirc;micas.</p> 
</blockquote> 
<p>Jeff Barr, do time da AWS, <a href="http://www.google.com/url?q=http%3A%2F%2Faws.typepad.com%2Faws%2F2013%2F03%2Faws-elastic-beanstalk-for-nodejs.html&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNHIjc5lNDvXu77ElZh0KnIb_Pc-0g">apontou algumas de suas funcionalidades favoritas</a> do Node.js na Elastic Beanstalk:</p> 
<ul> 
 <li>Escolha entre <a href="http://www.google.com/url?q=http%3A%2F%2Fnginx.org%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNGk0NmnZchH6_c41cdhsqcSO1z3uA">Nginx</a> ou <a href="http://www.google.com/url?q=http%3A%2F%2Fhttpd.apache.org%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNEnE18Zqwca67qcEKHyyk34gCmIlQ">Apache</a> como proxy reverso para sua aplica&ccedil;&atilde;o Node.js. Voc&ecirc; pode inclusive escolher n&atilde;o utilizar proxy caso sua aplica&ccedil;&atilde;o exija que o cliente estabele&ccedil;a uma conex&atilde;o direta.</li> 
 <li>Configure o balanceamento de carga baseado em HTTP e TCP dependendo de qual sua aplica&ccedil;&atilde;o necessita. Caso sua aplica&ccedil;&atilde;o utilize WebSockets, o balanceamento de carga baseado em TCP pode ser mais apropriado para sua carga de trabalho.</li> 
 <li>Configure a pilha do Node.js usando a vers&atilde;o espec&iacute;fica do Node.js que sua aplica&ccedil;&atilde;o precisa, ou fornecendo o comando usado para iniciar sua aplica&ccedil;&atilde;o Node.js. Voc&ecirc; pode tamb&eacute;m gerenciar depend&ecirc;ncias usando o <a href="http://www.google.com/url?q=https%3A%2F%2Fnpmjs.org%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNEVz_xVDA0Xn26b_cHRL63S7_pXjQ">npm</a>.</li> 
 <li>Ajude a melhorar a performance configurando a compress&atilde;o gzip e arquivos est&aacute;ticos usando o Nginx ou o Apache. Com a compress&atilde;o gzip, voc&ecirc; pode reduzir o tamanho da resposta ao cliente, ajudando a criar uma alta taxa de transfer&ecirc;ncia. Com arquivos est&aacute;ticos, voc&ecirc; pode permitir que o Nginx ou o Apache rapidamente sirva seu conte&uacute;do est&aacute;tico (como imagens ou CSS) sem ter esse tipo de requisi&ccedil;&atilde;o roubando tempo de processamento intensivo de dados que sua aplica&ccedil;&atilde;o Node.js possa estar fazendo.</li> 
 <li>Integre sua aplica&ccedil;&atilde;o de forma transparente com o <a href="http://www.google.com/url?q=http%3A%2F%2Faws.amazon.com%2Frds%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNEMR8J7R9xMgLUcee5nH4a8-mHV5w">Amazon RDS</a> para armazenar e recuperar dados de uma base de dados relacional.</li> 
 <li>Customize suas inst&acirc;ncias EC2 ou conecte sua aplica&ccedil;&atilde;o nos recursos da AWS usando os arquivos de configura&ccedil;&atilde;o do Elastic Beanstalk (visite o <a href="http://www.google.com/url?q=http%3A%2F%2Fdocs.aws.amazon.com%2Felasticbeanstalk%2Flatest%2Fdg%2Fcreate_deploy_nodejs_custom_container.html&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNGn6qYBUSK9SuC7XhvB63aoCmMCxQ">Guia de desenvolvimento do AWS Elastic Beanstalk</a> para aprender mais sobre arquivos de configura&ccedil;&atilde;o).</li> 
 <li>Execute sua aplica&ccedil;&atilde;o Node.js dentro de um <a href="http://www.google.com/url?q=http%3A%2F%2Faws.amazon.com%2Fvpc%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNEmi1nZzBzuHToJhYTCMIcM1GCcGg">Amazon Virtual Private Cloud</a> para ter um controle de rede adicional.</li> 
</ul> 
<p>Al&eacute;m das funcionalidades listadas, o Elastic Beanstalk tamb&eacute;m suporta <a href="http://www.google.com/url?q=http%3A%2F%2Fdocs.aws.amazon.com%2Felasticbeanstalk%2Flatest%2Fdg%2Fcreate_deploy_nodejs.sdlc.html&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNHAvv4fLvUApNXPZEk3nsUtOqaKkQ">integra&ccedil;&atilde;o com Git</a>, <a href="http://www.google.com/url?q=http%3A%2F%2Fdocs.aws.amazon.com%2Felasticbeanstalk%2Flatest%2Fdg%2Fcreate_deploy_nodejs_express_elasticache.html&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNHAzj8IFiaYMICiQW57iAGpcsRCnQ">clusteriza&ccedil;&atilde;o para alta disponibilidade</a> e uso de <a href="http://www.google.com/url?q=http%3A%2F%2Fdocs.aws.amazon.com%2Felasticbeanstalk%2Flatest%2Fdg%2Fcreate_deploy_nodejs_custom_container.html&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNGn6qYBUSK9SuC7XhvB63aoCmMCxQ">vari&aacute;veis por ambiente espec&iacute;fico</a> . A AWS fez sua primeira incurs&atilde;o no mundo Node.js em Dezembro de 2012 quando <a href="http://www.google.com/url?q=http%3A%2F%2Faws.amazon.com%2Fabout-aws%2Fwhats-new%2F2012%2F12%2F04%2Fintroducing-the-aws-sdk-for-node-js%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNH1gEL2IVxiC2T_jw0Go5gAR4f9Fw">lan&ccedil;ou um SDK</a> para desenvolvedores Node.js. Esse SDK prov&ecirc; acesso a uma vasta gama de servi&ccedil;os dispon&iacute;veis na AWS incluindo Amazon DynamoDB, Amazon Simple Storage Service (S3), Amazon Relational Database Service (RDS), Amazon Simple Queue Service (SQS), Amazon Elastic Compute Cloud (EC2) e outros mais.</p> 
<p>Com esta iniciativa, a AWS junta-se as muitas outros provedores de Cloud que oferecem servi&ccedil;os para aplica&ccedil;&otilde;es Node.js. Com exce&ccedil;&atilde;o do Google App Engine. Atualmente, quase todos os fornecedores de Plataforma como Servi&ccedil;o disponibilizam estrutura para Node.js, incluindo <a href="http://www.google.com/url?q=https%3A%2F%2Fdevcenter.heroku.com%2Farticles%2Fnodejs&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNE_dRT2Fc_9smBLFmJJpniJvmnXZA">Heroku</a>, <a href="http://www.google.com/url?q=http%3A%2F%2Fwww.windowsazure.com%2Fen-us%2Fdevelop%2Fnodejs%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNHTimJ4Nyczt99LSXmVaLzyEAIRDA">Windows Azure</a>, <a href="http://www.google.com/url?q=https%3A%2F%2Fwww.openshift.com%2Fpaas&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNHX6rcjx7ZVFCPO_mOk9160skGJ6g">Open Shift</a>, <a href="http://www.google.com/url?q=https%3A%2F%2Fwww.engineyard.com%2Fproducts%2Fcloud%2Ffeatures&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNGD9v2JrN7M3NVe3cwbLD_jDby1Bw">Engine Yard</a> e os muitos provedores do <a href="http://www.google.com/url?q=http%3A%2F%2Fdocs.cloudfoundry.com%2Fframeworks%2Fnodejs%2Fnodejs.html&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNHCXHCx0hi5PfEs0cUYY_gI2tRO1A">Cloud Foundry</a>. Todos estes provedores tamb&eacute;m competem com o <a href="http://www.google.com/url?q=https%3A%2F%2Fwww.nodejitsu.com%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNHdK2SqcJ9BcTpENneYtZmX0lVeEA">lider de ideias e provedor de plataforma dedicada para Node.js, o Nodejitsu</a>. Ent&atilde;o qual o diferencial entre estes servi&ccedil;os? Uma maneira &eacute; atrav&eacute;s da disponibiliza&ccedil;&atilde;o de ferramentas. Werner Vogels aponta como o Elastic Beanstalk &eacute; fortemente integrado com ferramentas de desenvolvimento para muitas plataformas top de linha.</p> 
<blockquote> 
 <p>Voc&ecirc; pode instalar e gerenciar suas aplica&ccedil;&otilde;es em qualquer regi&atilde;o da AWS (exceto para GovCloud). Muitas ferramentas est&atilde;o dispon&iacute;veis para voc&ecirc; instalar e gerenciar sua aplica&ccedil;&atilde;o, &eacute; s&oacute; escolher sua op&ccedil;&atilde;o favorita. Se voc&ecirc; est&aacute; construindo uma aplica&ccedil;&atilde;o Java, pode utilizar o Toolkit AWS para Eclipse. Se est&aacute; construindo aplica&ccedil;&otilde;es .NET, pode utilizar o Toolkit AWS para Visual Studio. Se voc&ecirc; prefere trabalhar no terminal, pode utilizar uma ferramenta de linha de comando chamada 'eb' em conjunto com o Git. Parceiros como eXoCloud IDE tamb&eacute;m oferecem integra&ccedil;&atilde;o com o Elastic Beanstalk.</p> 
</blockquote> 
<p>O exoCloud, agora dividido e com o nome de <a href="http://www.google.com/url?q=https%3A%2F%2Fcodenvy.com%2Ffeatures&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNGFXvKFZGQ8EBQ9WBBsK7HLKNZsoQ">Codenvy</a>, prov&ecirc; aos desenvolvedores um ambiente para desenvolvimento baseado em Cloud podendo ser direcionado &agrave; implementa&ccedil;&otilde;es que utilizam o Node.js no Elastic Beanstalk. Al&eacute;m disso, para fornecer aos desenvolvedores ferramentas de deploy e instala&ccedil;&atilde;o de aplica&ccedil;&otilde;es Node.js, os provedores de Cloud est&atilde;o se diferenciando atrav&eacute;s da integra&ccedil;&atilde;o com servi&ccedil;os complementares, e oferecendo solu&ccedil;&otilde;es para o dif&iacute;cil problema do gerenciamento de aplica&ccedil;&otilde;es. Um aspecto atraente da execu&ccedil;&atilde;o do Node.js no Elastic Beanstalk &eacute; a habilidade de facilitar a integra&ccedil;&atilde;o com os muitos servi&ccedil;os de aplica&ccedil;&otilde;es fornecido pela AWS. As aplica&ccedil;&otilde;es Node.js que rodam no ambiente da AWS t&ecirc;m acesso de baixa lat&ecirc;ncia ao banco de dados, storage, computa&ccedil;&atilde;o, filas, cache e muito mais. Clouds como o Windows Azure tem uma proposta de valor diferente onde os <a href="http://www.google.com/url?q=http%3A%2F%2Fwww.windowsazure.com%2Fen-us%2Fdevelop%2Fnodejs%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNHTimJ4Nyczt99LSXmVaLzyEAIRDA">desenvolvedores que instalam as aplica&ccedil;&otilde;es Node.js</a> tamb&eacute;m t&ecirc;m acesso ao diverso conjunto de servi&ccedil;os nativos para banco de dados, storage e mensageria. Provedores como <a href="http://www.google.com/url?q=https%3A%2F%2Faddons.heroku.com%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNE73mNM5hxo3BU6QbvSpoNyT5kdUg">Heroku</a> e <a href="http://www.google.com/url?q=https%3A%2F%2Fwww.nodejitsu.com%2Fpaas%2Faddons%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNEHcicg6nXlcQunKpyREQwuzOM-3Q">Nodejitsu</a> n&atilde;o possuem os pr&oacute;prios conjuntos de servi&ccedil;os complementares, mas mant&ecirc;m um refinado cat&aacute;logo de servi&ccedil;os que pod&ecirc;m ser integrados com as aplica&ccedil;&otilde;es que rodam nas plataformas de cada um.</p> 
<p>Al&eacute;m de prover servi&ccedil;os complementares como uma maneira de se destacar, os provedores de Cloud tamb&eacute;m demonstram suas habilidades para tornar a instala&ccedil;&atilde;o e o gerenciamento de aplica&ccedil;&otilde;es mais f&aacute;ceis. Isso significa suportar reposit&oacute;rios de controle de fonte baseados na web - assim como AWS, Windows Azure e o Nodejitsu - e oferecer servi&ccedil;os de deploy cont&iacute;nuo, como o Nodejitsu faz atrav&eacute;s de suporte ao TravisCI. Um monitoramento de alta qualidade e sistema de resposta podem tornar o gerenciamento de demanda muito mais simples para desenvolvedores e administradores de cloud. A AWS tem produtos para o monitoramento de uso e redimensionamento autom&aacute;tico dos ambientes da sua aplica&ccedil;&atilde;o e <a href="http://www.google.com/url?q=http%3A%2F%2Fwww.allthingsdistributed.com%2F2013%2F03%2Fbeanstalk-a-la-node.html&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNE16Ve8DIohCEPC7YL-iQ3uti3S3g">Werner Vogels</a> explicou como o Elastic Beanstalk ajuda a provisionar aplica&ccedil;&otilde;es com todos os recursos de gerenciamento inclu&iacute;dos.</p> 
<blockquote> 
 <p>O Elastic Beanstalk automatiza o provisionamento, monitora&ccedil;&atilde;o e a configura&ccedil;&atilde;o de muitos recursos subjacentes da AWS como o Balanceamento de Carga El&aacute;stico, Auto Scaling e EC2. O Elastic Beanstalk tamb&eacute;m fornece automa&ccedil;&atilde;o para instalar sua aplica&ccedil;&atilde;o, rotacionar seus logs e customizar suas inst&acirc;ncias EC2.</p> 
</blockquote> 
<p>Esteja atento nesta &aacute;rea, pois os provedores de Cloud cada vez mais aperfei&ccedil;oam os recursos de gerenciamento de aplica&ccedil;&otilde;es e oferecem servi&ccedil;os nativos ou integrados que melhoram a utilidade das aplica&ccedil;&otilde;es rodando em suas plataformas de Cloud Computing.</p> 
<p>Veja o post <a href="http://www.infoq.com/news/2013/03/aws-node-elastic-beanstalk;jsessionid=88603C4B78F9880E123084A838D49F91">original</a>.</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>