<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>EclipseCon 2013総まとめ</h3><p><a target="_blank" href="http://www.infoq.com/news/2013/03/eclipsecon-2013;jsessionid=26746CE6D61643C6726E577245AD4172"><em>原文(投稿日：2013/03/28)へのリンク</em></a></p> 
<div class="clearer-space"></div> 
<div id="newsContent"> 
 <p><a href="http://www.eclipsecon.org/2013" target="_blank">EclipseCon 2013</a>は北アメリカで開催された<a href="http://www.eclipsecon.org/2013/past-conferences" target="_blank">10回目</a>のEclipseのカンファレンスであり、今年はボストンで開催された。過去数年と同様に今年も<a href="http://www.osgi.org/DevCon2013/HomePage" target="_blank">OSGi DevCon</a>と<a href="http://www.eclipsecon.org/2013/almconnect" target="_blank">ALM Connect</a>が同時に開催された。OSGiがEclipseの基盤技術であることはよく知られているが、アプリケーションライフサイクルマネジメントのカンファレンスは<a href="http://www.eclipsecon.org/2012/agilealm" target="_blank">2012年</a>に始まった。ソフトウエア開発の実践とそれを支えるツールについてより広い視点から眺められる催しとなった。</p> 
 <p>開催基調講演はRedMonkの<a href="https://www.eclipsecon.org/2013/users/1387" target="_blank">Stephen O'Grady氏</a>が<a href="http://thenewkingmakers.com" target="_blank">開発者が新たなるキングメーカー</a>であることについて語り、第二基調講演では<a href="http://www.eclipsecon.org/2013/users/1386" target="_blank">Jeffrey Hammond氏</a>が<a href="http://www.eclipsecon.org/2013/sessions/moving-towards-alm-30" target="_blank">ALM 3.0への移行</a>について語った。従来の技術的選択肢はソフトウエアを購入する顧客が決定していたが、今やどのソフトウエアスタックを利用するかは暗黙に(そして積極的に)開発者自身が決定している、というのがStephen O'Grady氏の基調講演の前提だった。オープンな標準がプロプライエタリに勝りつつあり、その証拠に、この困難な時代にRedHatのような企業がオープンソースのサポートで収益を上げ、成長を続けている。それだけでなく、指先でスイッチをオン/オフするだけで巨大なコンピュータスケジューリングシステムが利用できるようになったことは資金のないスタートアップ企業に大きな力を与えた。今や時間当たり10ドルで、10台のマシンと50ギガバイトの共有ストレージを持つクラウドネットワークを作ることができる。</p> 
 <p>火曜日の基調講演では<a href="http://www.eclipsecon.org/2013/users/1390" target="_blank">Zach Holman氏</a>が<a href="http://www.eclipsecon.org/2013/sessions/how-github-works" target="_blank">GitHubの運営について</a>語ったが、オープンソースに貢献することについてや好きなことをすることについてなど話題は広がった(氏は<a href="http://www.infoq.com/presentations/How-GitHub-Works;jsessionid=A0490F2C73E73C6B5A302571B36ABFAC;jsessionid=26746CE6D61643C6726E577245AD4172" target="_blank">以前InfoQ</a>にGitHubの運営についてのプレゼンを提供している)。水曜は<a href="http://www.eclipsecon.org/2013/sessions/nashorn-javascript-jvm" target="_blank">Nashorn(JVM向けJavaScript)</a>についてOracleの<a href="https://www.eclipsecon.org/2013/users/1388" target="_blank">Jim Laskey氏</a>が語った。本来はTim Fox氏が<a href="http://vertx.io" target="_blank">Vert.X</a>について語る予定だったが実現できなかった。しかし、Jim Laskey氏はOracleがNashornを使って&quot;node.jar&quot;と呼ばれるものを開発していることを明らかにした。</p> 
 <p>EclipseConでのそのほかの特筆すべき出来事は、</p> 
 <p><b>Xtend</b> 今年のEclipseConでXtendのバージョン2.4のリリースが発表された(<a href="http://www.infoq.com/news/2013/03/xtend-24;jsessionid=A0490F2C73E73C6B5A302571B36ABFAC;jsessionid=26746CE6D61643C6726E577245AD4172" target="_blank">以前InfoQで取り上げている</a>)。今年はこの言語のテキストベースモデリングとフレームワークについてのセッションやチュートリアルがあった。Xtendの構文はScalaと同程度にコンパクトでありながら、Javaの型システムが使えるので、必要以上に複雑にならない。さらに、静的型推論や関数型プログラミングが利用できるので、普通のJavaよりも魅力的だ。また、既存のJavaコンパイラでコンパイルされたJavaコードを翻訳することもできる。後方互換性があり、リリース間の互換性の問題も最小限に抑えられている。</p> 
 <p><b>M2M</b> M2Mという頭字語は<a href="http://m2m.eclipse.org" target="_blank">Machine to Machine</a>という意味だ。最近Eclipse財団はM2Mワーキンググループを立ち上げ、<a href="http://en.wikipedia.org/wiki/Internet_of_things" target="_blank">モノのインターネット</a>の相互運用性を実現するための独立したエコシステムの構築に興味がある関係者が参加している。手始めに、Eclipseは<a href="http://arduino.cc" target="_blank">Arduino</a>と<a href="http://raspberrypi.org" target="_blank">Rasberry Pi</a>デバイスの開発のチュートリアルを提供している。これには組み込みLuaランタイム(<a href="http://eclipse.org/mihini/" target="_blank">Mihini</a>)とLuaの開発環境(<a href="http://www.eclipse.org/koneki/ldt/" target="_blank">Koneki</a>)のセットアップ方法も含まれている。これらのデバイスは<a href="http://mqtt.org" target="_blank">MQTT</a>(Message Queue Telemetry Transport)という低いレベルのマシン間コミュニケーションレイヤで通信を行う。MQTTは<a href="https://www.oasis-open.org/news/announcements/call-for-participation-message-queuing-telemetry-transport-mqtt-tc" target="_blank">OASIS標準</a>として提案されている。Java、C、Lua向けのライブラリは<a href="http://www.eclipse.org/paho/" target="_blank">Paho</a>プロジェクトで提供されている。一部はJustin Ribeiro氏の<a href="http://justinribeiro.com/chronicle/2012/09/05/getting-makerbot-status-on-the-web-with-mqtt-pywebsocket-eclipse-paho-and-html-5-web-sockets/" target="_blank">リモートの3Dプリンタを監視する</a>試みで利用されている。この試みではWebSocketsとArduino/Rasberry Piインターフェイスが利用されている。</p> 
 <p><b>CloudとOSGi</b> 近年、クラウドと分散配置モデルとして利用することに対する興味が高まっている。OSGiのEnterprise Expert Groupはこの分野に注力している。いくつかのセッションがOSGiに加えられるServiceScopes、CDI、RestInterfaceのような新しい仕様(<a href="http://www.osgi.org/Download/File?url=/download/osgi-early-draft-2013-03.pdf" target="_blank">OSGi Early Access Draft</a>にみられる)を取り上げていた。また、BlueprintやHttpServiceのような新しい仕様やOSGiのサブシステムを実現するフックの改善もある。</p> 
 <p><b>宇宙のEclipse</b> もっとも申し込みが多かったのは<a href="https://www.eclipsecon.org/2013/users/1030" target="_blank">Tamar Cohen氏</a>による<a href="http://www.eclipsecon.org/2013/sessions/nasa-uses-eclipse-rcp-applications-experiments-international-space-station" target="_blank">NASAでのEclipse RCPの利用</a>についてのセッションだ。国際宇宙ステーションには<a href="http://www.nasa.gov/mission_pages/tdm/telerobotics/spheres.html" target="_blank">SPHERES</a> (Synchronized Position Hold, Engage, Reorient, Experimental Satellites)という<a href="http://ti.arc.nasa.gov/tech/asr/intelligent-robotics/" target="_blank">知能ロボット</a>が乗船している。このロボットは<a href="http://www.nasa.gov/multimedia/videogallery/index.html?media_id=147267281" target="_blank">NASAの動画</a>で見れる。Eclipse RCPアプリケーションは計画とエンジンのリモート監視に利用されている。氏の説明によれば、このような厳密にスタイルが決まっているUIのアプリケーションが必要なのは、'無重力状態ではドラッグアンドドロップがうまく動作しないから'であり、アプリケーション間の一貫性を保持するためだ。 as well as consistency between applications. 現時点ではEclipseのワークベンチは地上で動いているが、国際宇宙ステーションのWindows XPマシンへのアップロードは今年の後半に行われる予定だ。SPHERE自体は<a href="http://www.nasa.gov/multimedia/videogallery/index.html?media_id=147267281" target="_blank">10年前に作れらており</a>(Eclipse財団とほぼ同い年)国際宇宙ステーションに搭載されたのは2006年だ。近頃行われた作業では、ジャイロスコープとカメラセンサーを搭載した強力でポータブルなコンピュータとしてNexus S Android携帯が取り付けられ(2011年、NASAによればこの携帯は&quot;宇宙での利用が保証された唯一の携帯&quot;だそうだ)た。リチウムイオンのバッテリが国際宇宙ステーションで火事を起こしてしまうリスクがあるので、AAバッテリと交換されている。壁に取り付けられていないものはすべてAAバッテリで動作している。その結果、地球からの積荷には多くのAAバッテリがついている。</p> 
 <p>最後に<a href="http://www.eclipse.org/org/press-release/20130326_winnerawards.php" target="_blank">Eclipse Community Awards</a>が発表された。このアワードは年次で<a href="http://www.infoq.com/news/2012/03/eclipsecon-awards;jsessionid=A0490F2C73E73C6B5A302571B36ABFAC;jsessionid=26746CE6D61643C6726E577245AD4172" target="_blank">発表</a>されており、今年は、</p> 
 <ul> 
  <li><b>トップコミッタ</b>: Markus Knauer氏 (Ed D. Wilink氏とJohn Arthorne氏がファイナリスト)</li> 
  <li><b>トップニューカマーエバンジェリスト</b>: Jonas Helming氏(Benjamin Cab&eacute;氏とRussell Bateman氏がファイナリスト)</li> 
  <li><b>最優秀オーププロジェクト</b>: <a href="http://www.eclipse.org/egit/" target="_blank">EGit</a> (<a href="http://www.eclipse.org/cdt/" target="_blank">CDT</a>と<a href="http://www.eclipse.org/orion/" target="_blank">Orion</a>がファイナリスト)</li> 
  <li><b>最優秀イノべーティブ新機能/Eclipseプロジェクト</b>: <a href="http://www.eclipse.org/diffmerge/" target="_blank">EMF Diff/Merge</a> (<a href="http://www.eclipse.org/paho/" target="_blank">Paho</a>、<a href="http://www.eclipse.org/intent/" target="_blank">Mylyn Intent</a>、<a href="http://www.eclipse.org/vjet/" target="_blank">VJet</a>がファイナリスト)</li> 
  <li><b>最優秀開発者ツール</b>: <a href="http://wireframesketcher.com/" target="_blank">Wireframe Sketcher</a> (<a href="http://www.klocwork.com/products/insight/index.php" target="_blank">Klockwork Insight</a>、<a href="http://www.sonarsource.org/" target="_blank">Sonar</a>がファイナリスト)</li> 
  <li><b>最優秀開発者プラグイン</b>: <a href="http://findbugs.sourceforge.net/index.htm" target="_blank">FindBugs</a> (<a href="http://www.efxclipse.org/" target="_blank">e(fx)clipse</a>、<a href="http://www.junitloop.org/" target="_blank">JUnitLoop</a>がファイナリスト)</li> 
  <li><b>最優秀モデリング製品</b>: <a href="http://www.obeodesigner.com/" target="_blank">Obeo Designer</a> (<a href="http://www.umlet.com/" target="_blank">UMLet</a>がファイナリスト)</li> 
  <li><b>最優秀アプリケーション</b>: <a href="http://chrononsystems.com/chronon4" target="_blank">Chronon 4 ‘Ops’</a> (<a href="http://www.bonitasoft.com/" target="_blank">Bonita Open Solutions</a>と<a href="http://www.talend.com/products/talend-open-studio" target="_blank">Talend Open Studio</a>がファイナリスト)</li> 
 </ul> 
 <p>上述のアワードに加え、Eclipse財団は、コミュニティのメンバによる投票でLifetime Contribution Awardを<a href="http://www.eclipse.org/org/elections/candidate.php?year=2013&amp;id=aniszczyk" target="_blank">Chris Aniszczyk氏</a>に授与した。氏は長年、Eclipseのエコシステムに貢献しており、初期段階のプロジェクトにはメンターとして参加し、多くのプロジェクトにコミットし貢献している。Eclipse財団のJGitへの移行と、プロジェクトのバージョン管理システムのGitヘの移行を推進したのも氏だ(現時点では財団の<a href="http://www.eclipse.org/projects/scmcountdown.php" target="_blank">80%</a>以上がGitであり、<a href="http://git.eclipse.org/" target="_blank">500</a>のgitリポジトリが<a href="https://eclipse.googlesource.com" target="_blank">https://eclipse.googlesource.com</a>にミラーされている)。</p> 
 <p>6月には、EclipseConは初めてフランスで開催される予定。場所は<a href="http://www.eclipsecon.org/france2013/" target="_blank">トゥールーズ</a>。さらに10月にはルートヴィヒスブルクでEclipseCon Europe 2013が開催される予定だ。</p> 
 <p id="lastElm"></p> 
</div> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>