<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>VMware vCenterを管理するAWS Management Portal</h3><p><a target="_blank" href="http://www.infoq.com/news/2014/06/aws-vcenter-plugin"><em>原文(投稿日：2014/06/03)へのリンク</em></a></p>
<div class="article_page_left news_container text_content_container"> 
 <div class="text_info"> 
  <p>Amazon Web Services (AWS)が<a href="https://aws.amazon.com/blogs/aws/aws-management-portal-for-vcenter/">VMware vCenter用のManagement Portalプラグイン</a>を発表した。パブリッククラウドであるEC2インスタンスとプライベートクラウドのVMwareインスタンスを，同一の管理コンソールから管理できる。VMwareユーザのプライベート環境をAmazonのパブリックサービスに拡張して，ハイブリッドクラウドを容易に構築可能にすることを目的としたプラグインだ。</p> 
  <p>AWSプラグインによるハイブリッドクラウドの構築は，VMware自身が2013年8月にローンチした<a href="http://www.vmware.com/products/vcloud-hybrid-service">vCHS(vCloud Hybrid Service)</a>と競合する。現在のvCHSは，利用する処理能力分の前払いが必要な，リザーブドインスタンス価格モデルでのみ使用可能だ。先日の<a href="http://www.reddit.com/r/IAmA/comments/25ys3b/we_are_the_hybrid_cloud_team_at_vmware_and_are/">vCHSチームによるReddit AMA(Ask Me Anything)</a>でも，オンデマンド料金に関する話題がもっとも多かった。2014年第２四半期には従量制サービスの提供が予定されている。</p> 
  <p>VMwareは自身のクラウドオーケストレーションを以前から用意している。2012年のDynamicOpsの買収以降は，Amazonのサービスとの相互運用機能も含まれている。その後，ブランド名がvCAC(vCloud Automation Center)に変更され，さまざまなタイプの仮想インフラストラクチャやプライベートクラウド，パブリッククラウドに対応した。VMware米国CTOのChris Wolf氏は，攻撃的なブログ記事 &quot;<a href="http://cto.vmware.com/dont-be-fooled/">Don’t Be Fooled By Import Tools Disguised as Hybrid Cloud Management</a>&quot; の中で，vCenterのAWSプラグインよりvCACのようなスイートの方が，より多くの抽象化効果を得ることができると主張している。しかしながら，vCenterとvCACという２製品の間にある階層の差は，VMwareのカスタマベースに技術レベルの異なる層が存在することを示している。Amazonはそのローエンドを攻撃対象に選択したのだ。</p> 
  <p>プラグインの機能のひとつであるイメージインポートは，Amazonにある<a href="http://aws.amazon.com/ec2/vm-import/">VMインポート</a>機能の上位機能として，VMwareなど一般的な仮想インフラストラクチャのファイル形式をサポートする。vCenterが統合されれば，企業レベルのオペレーティングシステムのイメージを，ポイント＆クリック操作でAWSにインポート可能になるはずだ。インスタンスの基本的なライフサイクル管理 - 開始，停止，再起動にも対応する。</p> 
  <p>このプラグインは，AmazonのVPC(Virtual Private Cloud)インスタンスのみで動作する。EC2クラッシクはサポート対象外である。これはVPCをデフォルトとする最近の施策に従ったものだ。AmazonがIPsecあるいは<a href="http://aws.amazon.com/ec2/vm-import/">Direct Connect</a>接続を提供している方法を考えれば，企業がVPCを選択するという前提に立つのは合理的だと言える。VPCやサブネット，関連するセキュリティグループのコンフィギュレーションも，プラグインによって容易になる。ただしIPsec接続(あるいはDirect Connect)の設定機能は提供されていない。そのため，EC2にデプロイされたインスタンスがVMあるいは企業内の他のサービスに接続する必要のある場合には，帯域外のアクティビティが発生する可能性がある。</p> 
  <p>ロールベースのアクセス管理も提供されるので，AWS内で誰が何をすることができるのかという管理や制御もvCenterから可能になる。プラグインは現在，利用企業毎にひとつのIDプロバイダ(ディレクトリ)，単一のAWSアカウントでの利用に制限されている。IDはプラグインを<a href="http://docs.aws.amazon.com/amp/latest/userguide/setting-up.html">インストールする過程</a>で，エンタープライズディレクトリとAWS <a href="http://aws.amazon.com/iam/">IAM(Identity and Access Management)</a>内に作成しておく必要がある。SSHキーのペアもプラグイン内で管理可能だ。ただしAWSメタデータ内のキーペアと，それを使用するインポートしたイメージとの関連性について，プラグインの資料には説明がない(VMインポートの資料で<a href="http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/PreparingYourVirtualMachine.html">部分的にふれている</a>のみだ)。</p> 
  <p>Amazonはプラグインそのものを無償で配布して，AWSの使用料を通常のレートで課金している。市場で提供されている，より洗練されたクラウドオーケストレーションツールの一部が備えているような，課金管理や予測機能などはまったく提供されない。</p> 
 </div> 
</div><br><br><br><br><br><br></body></html>