<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Akka Toolkit 2.3 com Java 8 e suporte a persistência</h3><p>A &uacute;ltima vers&atilde;o do kit de ferramentas do <a href="http://www.google.com/url?q=http%3A%2F%2Fakka.io%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNGVVEWf1BCR5ebqKaCnmQ7gY_2s-g">Akka</a> possui como novidades a persist&ecirc;ncia, permitindo salvar o estado interno dos atores. O recente lan&ccedil;amento da <a href="http://www.google.com/url?q=http%3A%2F%2Fakka.io%2Fnews%2F2014%2F03%2F05%2Fakka-2.3.0-released.html&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNEISQUyyByh3AtwB1UQ_A_qYWtrLA">vers&atilde;o 2.3.0</a> tamb&eacute;m est&aacute; preparado para suportar express&otilde;es lambda do Java 8.</p>
<p>Na <a href="http://www.google.com/url?q=http%3A%2F%2Fdoc.akka.io%2Fdocs%2Fakka%2F2.3.0%2Fscala%2Fpersistence.html&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNGkiyVWNVwdHqpP_svlKkrqmotpkg">persist&ecirc;ncia Akka</a>, em vez do estado atual, cada mudan&ccedil;a de estado de um ator s&atilde;o persistidas. As mudan&ccedil;as s&atilde;o anexadas a um journal e o estado dos atores pode ser reconstru&iacute;do repetindo as altera&ccedil;&otilde;es armazenadas. Tamb&eacute;m &eacute; fornecido suporte para event sourcing e mensagens com garantia de pelo menos uma entrega.</p>
<p>Usando Java 8 e express&otilde;es lambda, ambos <a href="http://www.google.com/url?q=http%3A%2F%2Fdoc.akka.io%2Fdocs%2Fakka%2F2.3.0%2Fjava%2Flambda-actors.html&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNFVOpOSP_jXSCr9T0GwOlE4XQIKMA">Atores</a> e <a href="http://www.google.com/url?q=http%3A%2F%2Fdoc.akka.io%2Fdocs%2Fakka%2F2.3.0%2Fjava%2Flambda-fsm.html&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNEnAGnmxcir1wK55ZXk0kH8jpsYiw">Finite State Machines</a> (<a href="http://www.google.com/url?q=http%3A%2F%2Fen.wikipedia.org%2Fwiki%2FFinite-state_machine&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNFN77KgMkHjLIdvRjSr5PvmBkVvtg">FSM</a>) podem agora ser implementados usando sintaxe lambda, removendo assim a necessidade de declarar classes internas an&ocirc;nimas.</p>
<p>Ambos os m&oacute;dulos de persist&ecirc;ncia e suporte ao lambda est&atilde;o marcados como <em>experimentais</em>, com a plano de melhorar a API atrav&eacute;s do feedback dos usu&aacute;rios.</p>
<p><a href="http://www.google.com/url?q=http%3A%2F%2Fakka.io%2Fnews%2F2014%2F03%2F05%2Fakka-2.3.0-released.html&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNEISQUyyByh3AtwB1UQ_A_qYWtrLA">Outras melhorias</a> incluem:</p>
<ul class="c9 lst-kix_5zr9mnhwk2es-0 start"> 
 <li>Um cluster que pode estar parcialmente inacess&iacute;vel agora pode voltar a funcionar normalmente sem nenhuma condi&ccedil;&atilde;o de falha quando os n&oacute;s afetados tornam-se responsivos;</li> 
 <li>A fragmenta&ccedil;&atilde;o de cluster pode ser usada para distribuir o estado dos atores sobre v&aacute;rios n&oacute;s quando os atores consomem mais recursos que uma m&aacute;quina pode suportar;</li> 
 <li>A remo&ccedil;&atilde;o do r&oacute;tulo experimental do pacote Akka IO, mas com a infraestrutura do pipeline descontinuado;</li> 
 <li>O suporte <a href="http://www.google.com/url?q=http%3A%2F%2Fen.wikipedia.org%2Fwiki%2FOSGi&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNH7x5hg-mfg4eIT6dcaWY3AYzclxQ">OSGi</a> foi reformulado para tornar o akka-actor um pacote OSGI.</li> 
</ul>
<p>A <a href="http://www.google.com/url?q=http%3A%2F%2Fakka.io%2Fdocs%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNH9Zv9wfVBmOMIvC4NJ3Ivyqj068Q">documenta&ccedil;&atilde;o</a> junto com o<a href="http://www.google.com/url?q=http%3A%2F%2Fdoc.akka.io%2Fdocs%2Fakka%2F2.3.0%2Fintro%2Fgetting-started.html&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNF2dlixAKxy0KsV0izS-LYqyrpT3w">guia de inicia&ccedil;&atilde;o</a> foi atualizada para refletir as mudan&ccedil;as no framework. O Akka tamb&eacute;m &eacute; parte do amplo exemplo de <a href="http://www.google.com/url?q=http%3A%2F%2Ftypesafe.com%2Fplatform%2Fgetstarted&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNE61IBTmpl6KDqDmDTrPJ9pM4035g">plataforma reativa</a>.</p>
<p>O novo lan&ccedil;amento cont&eacute;m algumas mudan&ccedil;as estruturais que requerem mudan&ccedil;as no c&oacute;digo quando atualizando da vers&atilde;o 2.2.*. A atualiza&ccedil;&atilde;o a partir de vers&otilde;es anteriores pode necessitar de algumas etapas extras.</p>
<p>O kit de ferramentas do Akka &eacute; uma implementa&ccedil;&atilde;o do <a href="http://www.google.com/url?q=http%3A%2F%2Fen.wikipedia.org%2Fwiki%2FActor_model&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNGmp2Kt4yycsEyl3-FwH77SiNOpKw">Actor Model</a>, dispon&iacute;vel tanto nas APIs do Java como do Scala. A vers&atilde;o 2.3 &eacute; a primeira etapa de um grande <a href="https://docs.google.com/document/d/18W9-fKs55wiFNjXL9q50PYOnR7-nnsImzJqHOPPbM4E/pub">marco</a> planejado para o segundo semestre de 2014.</p>
<p>O Akka &eacute; um produto de c&oacute;digo fonte aberto, licenciado sobre a licen&ccedil;a do Apache 2.</p>
<p><a href="http://www.google.com/url?q=http%3A%2F%2Fvaughnvernon.co%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNFbAgl6vRcFzVOm8N9NEv6L7TjGNQ">Vaughn Vernon</a>, autor de <a href="http://www.google.com/url?q=http%3A%2F%2Fwww.informit.com%2Fstore%2Fimplementing-domain-driven-design-9780321834577&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNHjh0EtDj8gxrrq2-zGhGKUfrgiMA">Implementing Domain-Driven Design</a>, <a href="http://www.google.com/url?q=http%3A%2F%2Fwww.infoq.com%2Fbr%2Fnews%2F2013%2F12%2Fvernon-reactive-ddd&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNHGgsfobPZyNWc7EhGnuwRnBM39Gw">falou</a> no ano passado sobre o actor model no Domain Driven Design reativo e em uma <a href="http://www.google.com/url?q=http%3A%2F%2Fwww.infoq.com%2Fnews%2F2013%2F06%2Factor-model-ddd&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNFgj8CcZY33D_6N7HqOuZ2KASdi7A">not&iacute;cia</a> anterior sobre a base para o actor model junto com o DDD.</p>
<p>Um <a href="https://groups.google.com/forum/#%21forum/akka-user">f&oacute;rum</a> para usu&aacute;rios do Akka est&aacute; dispon&iacute;vel com mais de 3000 membros.</p><br><br><br><br><br><br></body></html>