<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Reduza o desperdício através da mudança do método cascata para método ágil</h3><p>Um dos motivos das empresas migraram para m&eacute;todos &aacute;geis &eacute; para se tornarem aptas a gerenciar mudan&ccedil;as. As necessidades de clientes geralmente mudam ao longo do caminho, o que exige da equipe de desenvolvimento adaptabilidade para gerenciar o produto. M&eacute;todos &aacute;geis ajudam as equipes a entregar produtos que satisfa&ccedil;am as necessidades dos clientes; produtos que n&atilde;o contenham funcionalidades desnecess&aacute;rias (e que n&atilde;o ser&atilde;o utilizadas). O processo de desenvolvimento de software enxuto utiliza o termo desperd&iacute;cio: tudo que n&atilde;o cria valor para o cliente &eacute; considerado desperd&iacute;cio. Como a transi&ccedil;&atilde;o do m&eacute;todo cascata para um processo de desenvolvimento &aacute;gil ajuda as empresas a reduzir o desperd&iacute;cio?</p>
<p>Ron Lichty escreveu um post sobre as <a href="http://ronlichty.blogspot.co.nz/2013/07/the-most-convincing-reason-to-change.html">mais convincentes raz&otilde;es para as empresas mudarem do m&eacute;todo cascata para um m&eacute;todo &aacute;gil</a>. O principal motivo, segundo Ron Lichty, &eacute; o desperd&iacute;cio:</p>
<blockquote> 
 <p>Mas o que realmente me conquistou − o que me converteu a um entusiasta de m&eacute;todos &aacute;geis e totalmente desencantando do m&eacute;todo cascata − &eacute; o desperd&iacute;cio. Desperd&iacute;cio de recursos, de tempo de desenvolvimento e de esfor&ccedil;o.</p> 
</blockquote>
<p>Lichty descreve como questiona os desenvolvedores e seus gerentes de qual o percentual de uma especifica&ccedil;&atilde;o de requisitos de 400 p&aacute;ginas que eles trabalharam e que realmente foi entregue. A resposta que ele recebe &eacute; a seguinte:</p>
<blockquote> 
 <p>(...) a resposta raramente excede 45% − geralmente est&aacute; entre 15 e 25% − chegando at&eacute; mesmo a 10% dos requisitos funcionais entregues.</p> 
</blockquote>
<p>Lichty fala sobre a maior diferen&ccedil;a entre os m&eacute;todos &aacute;geis e cascata &eacute; como as decis&otilde;es s&atilde;o tomadas do que ser&aacute; entregue, o que possui impacto no valor do que &eacute; entregue:</p>
<blockquote> 
 <p>Um das coisas que eu adoro nos m&eacute;todos &aacute;geis &eacute; que o topo do backlog &eacute; ordenado a cada sprint pelos donos do produto colaborando com os l&iacute;deres de desenvolvimento para garantir que as equipes sempre trabalhem nos itens de maior valor.</p> 
 <p>A resposta em um cen&aacute;rio utilizando o m&eacute;todo cascata, por outro lado, quase nunca &eacute; valor. As respostas que recebo incluem, &quot;a coisa mais simples para codificar&quot;, &quot;o que era mais interessante para n&oacute;s&quot; (o que era mais brilhante!), &quot;o se destacou na nossa cabe&ccedil;a da leitura dos requisitos&quot; ou &quot;o que era mais legal&quot;. Prioriza&ccedil;&atilde;o em uma especifica&ccedil;&atilde;o de 400 p&aacute;ginas &eacute; quase que universalmente feita por desenvolvedores e n&atilde;o por donos de produtos.</p> 
</blockquote>
<p>No site <a href="http://www.google.com/url?q=http%3A%2F%2Fwww.poppendieck.com%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNEyHT99nJEVkUdyOVh7-m52ODvYUQ">a mentalidade enxuta</a>, Mary e Tom Poppendieck descrevem os princ&iacute;pios do desenvolvimento de software enxuto. Um dos princ&iacute;pios &eacute; &quot;eliminar o desperd&iacute;cio&quot;:</p>
<blockquote> 
 <p>Os tr&ecirc;s maiores desperd&iacute;cios no desenvolvimento de software s&atilde;o:</p> 
 <p>Construindo a coisa errada</p> 
 <p>&quot;N&atilde;o existe nada t&atilde;o in&uacute;til quanto fazer eficientemente aquilo que n&atilde;o deve ser feito.&quot; − Peter Drucker</p> 
 <p>Construindo a coisa de maneira errada</p> 
 <p>Parece que n&atilde;o h&aacute; tempo suficiente para construir a coisa da maneira correta, ent&atilde;o certamente n&atilde;o existe tempo para N&Atilde;O constru&iacute;-la da maneira certa.</p> 
 <p>Uma mentalidade de pacotes e filas</p> 
 <p>Trabalho com progresso esconde defeito, se torna obsoleto, causa altern&acirc;ncia entre tarefas e atrasa a realiza&ccedil;&atilde;o de valor.</p> 
</blockquote>
<p>Mike Cudemo escreveu um post sobre <a href="http://www.google.com/url?q=http%3A%2F%2Fproductmanagementtips.com%2F2013%2F01%2F24%2Fagile-vs-waterfall-differences%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNF3yug59NbGCGmTbdOK2uTT2eryeg">agilidade vs cascata - qual o grande neg&oacute;cio?</a> Ele come&ccedil;a explicando a diferen&ccedil;a de como os m&eacute;todos cascata e &aacute;gil controlam requisitos:</p>
<blockquote> 
 <p>O processo cascata tenta &quot;congelar os requisitos&quot; depois que os diagramas s&atilde;o desenhados. Como &eacute; poss&iacute;vel imaginar esta n&atilde;o &eacute; a realidade. Quanto mais tarde um problema no levantamento de requisitos for detectado (...), mais caro custa a corre&ccedil;&atilde;o. Em alguns casos chega a ser imposs&iacute;vel de corrigir. (...) O m&eacute;todo &aacute;gil n&atilde;o tenta &quot;pregar e congelar os requisitos&quot; tudo de uma &uacute;nica vez. Ele assume que os requisitos v&atilde;o evoluir e mudar assim que o cliente come&ccedil;ar a visualizar os pr&oacute;prios requisitos.</p> 
</blockquote>
<p>Mike Cudemo fornece a sua vis&atilde;o de como as itera&ccedil;&otilde;es no desenvolvimento de software &aacute;gil oferecem possibilidades de guiar os resultados:</p>
<blockquote> 
 <p>O m&eacute;todo &aacute;gil tenta focar no levantamento de requisitos, desenho, codifica&ccedil;&atilde;o e testes de maneira iterativa e em pequenas fases de desenvolvimento. Essencialmente, o m&eacute;todo &aacute;gil &eacute; uma s&eacute;rie de pequenos m&eacute;todos em cascata. Usu&aacute;rios finais e pessoas de neg&oacute;cio conseguem visualizar e experimentar o sistema durante seu desenvolvimento. Corre&ccedil;&otilde;es durante o desenvolvimento se tornam mais aparentes e f&aacute;ceis de serem trabalhadas.</p> 
</blockquote>
<p>Projetos cascata est&atilde;o gastando o or&ccedil;amento de TI, como Mike conclui:</p>
<blockquote> 
 <p>Diversos <a href="http://pt.wikipedia.org/wiki/Diretor_financeiro">CFOs</a> se encontram em um complexo ato de julgamento de corte de custos operacionais e investimentos em tecnologia. Os CFOs est&atilde;o for&ccedil;ando os CIOs a apresentarem planos para alavancar os investimento existentes, mas tamb&eacute;m desenvolver a capacidade de rapidamente responder ao crescimento econ&ocirc;mico e mudan&ccedil;as competitivas. Falhas em projetos n&atilde;o e uma op&ccedil;&atilde;o, mas de acordo com as estat&iacute;sticas, iniciativas em cascata gastam 60% do or&ccedil;amento de TI das empresas.</p> 
</blockquote>
<p>No artigo <a href="http://www.google.com/url?q=http%3A%2F%2Fwww.agileconnection.com%2Farticle%2Fagile-cheaper-right&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNHfDqZT7A6kNsJZfN3gTZDaA0q0gg">agilidade &eacute; mais barato certo</a>? Kenny Grant descreve como a iniciativa &aacute;gil pode ajudar as equipes a identificarem o desperd&iacute;cio e lidar com isso. O desenvolvimento de software &aacute;gil por si s&oacute; n&atilde;o &eacute; mais barato que o desenvolvimento de software em cascata, como Kenny Grant explica. O que faz o m&eacute;todo &aacute;gil mais barato &eacute; a maneira com que ele lida com mudan&ccedil;as de escopo e ajustes no projeto:</p>
<blockquote> 
 <p>Comparar o m&eacute;todo cascata com o m&eacute;todo &aacute;gil &eacute; como comparar ma&ccedil;as com laranjas. Isso porque seguir os princ&iacute;pios e processos &aacute;geis iriam, em minha opini&atilde;o, quase sempre gerar um produto diferente do que se a mesma necessidade de neg&oacute;cio fosse abordada com um projeto utilizando a metodologia em cascata. (...) quase sempre existem algumas partes do escopo e que podem ser considerados desperd&iacute;cio ou seu valor n&atilde;o vale o custo da entrega. O m&eacute;todo &aacute;gil foca implacavelmente no valor de neg&oacute;cio e a ideia de somente o trabalho necess&aacute;rio identifica o desperd&iacute;cio − ou requisitos com pequeno retorno sobre o investimento (ROI) − e d&aacute; a equipe a oportunidade de mudar ou deixar o percurso.</p> 
</blockquote>
<p>Levando em considera&ccedil;&atilde;o que as necessidades de neg&oacute;cio e requisitos v&atilde;o mudar durante o projeto, Kenny Grant refor&ccedil;a a pergunta &quot;Agilidade &eacute; mais barato?&quot;:</p>
<blockquote> 
 <p>&quot;Para uma necessidade de neg&oacute;cio espec&iacute;fica, seguir os princ&iacute;pios e processos &aacute;geis permite desenvolver produtos que atendem as necessidades de neg&oacute;cio (nada mais, nada menos) de maneira mais barata do que seguindo a metodologia cascata?&quot; Nesse caso a resposta &eacute; &quot;Sim, absolutamente&quot;.</p> 
</blockquote><br><br><br><br><br><br></body></html>