<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Melhorando a Cultura DevOps com Informações Consolidadas</h3><p>A plataforma <a href="https://www.appsecute.com/features.html">Appsecute</a> visa melhorar a colabora&ccedil;&atilde;o e aumentar a produtividade por meio da consolida&ccedil;&atilde;o da informa&ccedil;&atilde;o associada ao ciclo de vida de uma aplica&ccedil;&atilde;o. A plataforma de software como servi&ccedil;o (SaaS) aceita mensagens diretamente de pessoas e de outras plataformas de tecnologicas integradas, desta maneira ela agrega os eventos de forma online para que possam ser visualizados por todos em uma organiza&ccedil;&atilde;o.</p> 
<p>A plataforma trata dos problemas de rastreamento de informa&ccedil;&otilde;es diferentes e tem como objetivo a preven&ccedil;&atilde;o de pap&eacute;is mantidos como silos em equipes de projetos. Tyler Power, CTO e co-fundador do Appsecute, comenta que:</p> 
<blockquote> 
 <p>O problema que n&oacute;s vemos &eacute; que existem muitas ferramentas envolvidas no ciclo de vida de uma aplica&ccedil;&atilde;o. Isto torna dif&iacute;cil um indiv&iacute;duo estar atualizado com o trabalho que esta sendo feito por meio destas ferramentas, assim tamb&eacute;m como estar ciente e pronto para responder as quest&otilde;es urgentes resultantes das mesmas. Isso gera uma cultura de isolamento entre pessoas onde elas limitam suas preocupa&ccedil;&otilde;es com pequenas partes do ciclo de vida de uma aplica&ccedil;&atilde;o, ignorando efetivamente o valor das outras ferramentas que a empresa tem investido.</p> 
</blockquote> 
<p>Al&eacute;m disso, os fundadores do Appsecute acreditam que o produto ir&aacute; reduzir o impacto do tempo indispon&iacute;vel. Tyler comentou o seguinte:</p> 
<blockquote> 
 <p>Significa, tamb&eacute;m, que durante uma crise, todos estar&atilde;o olhando para a mesma informa&ccedil;&atilde;o agregada, de todos os diferentes tipos de sistemas utilizados, n&oacute;s descobrimos que isto pode reduzir significativamente o tempo indispon&iacute;vel em uma crise, uma vez que torna muito mais f&aacute;cil reconhecer e resolver problemas.</p> 
</blockquote> 
<p>A plataforma prove aos usu&aacute;rios a habilidade de moldar a forma como a informa&ccedil;&atilde;o &eacute; apresentada em 'forma de um simples plano de fundo transparente' uma linha do tempo por gerenciamento de usu&aacute;rios, organiza&ccedil;&otilde;es, aplica&ccedil;&otilde;es e conectores de fluxo de eventos externos. O Appsecute da suporte a tecnologia de disparos de fluxo de eventos da fonte de controle, integra&ccedil;&atilde;o cont&iacute;nua, sistema de registro de chamados, e platorma como servi&ccedil;o (ou PaaS). Estes sistemas se alinham com multiplos pap&eacute;is na cultura DevOps. At&eacute; o momento o produto &eacute; livre e prov&ecirc; uma documenta&ccedil;&atilde;o com passo a passo de como construir conectores para se integrarem a fonte de fluxo de eventos com o Appsecute. Al&eacute;m disso ele prov&ecirc; o c&oacute;digo de diversos outros conectores no GitHub.</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>