<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Windows Management Framework 5 Preview Introduces Package Manager And Network Switches Cmdlets</h3><p>Microsoft <a href="http://blogs.technet.com/b/windowsserver/archive/2014/04/03/windows-management-framework-v5-preview.aspx?pi138548=1">announced</a> the availability of the <a href="http://www.microsoft.com/en-us/download/details.aspx?id=42316">Windows Management Framework V5 Preview</a>&nbsp;(WMF), which includes Windows PowerShell OneGet, a package manager in the spirit of yum and apt-get; a set of cmdlets to manage network switches; and some polishing on Windows PowerShell Desired State Configuration (DSC).</p>
<p>Windows PowerShell OneGet fills a hole on the Windows platform: a package management solution. It fulfills the same purpose of yum, apt-get and others on the Linux platform. OneGet will support different package repositories, but right now it only supports <a href="http://chocolatey.org/">Chocolatey</a> repositories. Chocolatey is a community-based package management system, built on <a href="http://www.nuget.org/">NuGet</a>&nbsp;infrastructure. It has thousands of available packages, such as&nbsp;<a href="http://chocolatey.org/packages/git">Git</a>,&nbsp;<a href="https://chocolatey.org/packages/nodejs.install">NodeJS</a>,&nbsp;<a href="http://chocolatey.org/packages/7zip">7-Zip</a> and other popular software. Boe Prox <a href="http://learn-powershell.net/2014/04/03/checking-out-oneget-in-powershell-v5/">authored</a> a detailed how-to describing most of the available OneGet cmdlets.</p>
<p>The new cmdlets for network switches management help with the creation of <a href="http://en.wikipedia.org/wiki/Software-defined_networking">software defined networks</a>, a growing area of interest in the operations community. There are cmdlets for automating VLANs, ethernet ports, port modes and other <a href="http://en.wikipedia.org/wiki/Network_switch#Layer_2">L2 layer</a>&nbsp;features. They build upon already available PowerShell&nbsp;<a href="http://blogs.msdn.com/b/powershell/archive/2013/07/31/dal-in-action-managing-network-switches-using-powershell-and-cim.aspx">CIM cmdlets</a>. The PowerShell-based network switch management is part of a&nbsp;<a href="http://blogs.technet.com/b/windowsserver/archive/2012/08/22/software-defined-networking-enabled-in-windows-server-2012-and-system-center-2012-sp1-virtual-machine-manager.aspx">concerted effort</a>&nbsp;to support software defined networks on the Windows platform. This effort is framed by the Microsoft's&nbsp;<a href="http://technet.microsoft.com/en-us/cloud/dal.aspx">Datacenter Abstraction Layer (DAL)</a>&nbsp;initiative, which aims to provide a &quot;a common management abstraction for all the resources of a data center&quot;, including the definition of standards within the context of the&nbsp;<a href="http://www.dmtf.org/">Distributed Management Task Force (DMTF)</a>. On pratical terms, this means that only network switches that pass the Certified for Windows program, and follow these standards, can be automated through the network switches cmdlets. Microsoft is collaborating in this process with network switches providers like Arista, Cisco and Huawei.</p>
<p>PowerShell DSC received stability and performance improvements. These improvements complement the release&nbsp;of more than <a href="http://blogs.msdn.com/b/powershell/archive/2014/03/28/dsc-resource-kit-wave-3.aspx">50 DSC resources</a>&nbsp;since December. According to Jeffrey Snove, who wrote the WMF preview announcement: &quot;If you are considering purchasing a Configuration Management tool, make sure that tool supports DSC or you won’t be aligned with the Windows Server strategy&quot;.</p>
<p>Daniel Davidson voiced security concerns, as others did, on the announcement of OneGet and the use of Chocolatey repositories:</p>
<blockquote> 
 <p>I think what bothers me about it is that it asserts a false sense of trust - &quot;the oneget module is core to Powershell, the things I can download must be vetted and safe&quot;. Few people feel nervous pulling software from microsoft.com for that reason... Chocolatey isn't Microsoft.com (...)</p> 
</blockquote>
<p>Jeffrey Snover, from the Windows Server team, replied:</p>
<blockquote> 
 <p>You are correct to be concerned about security of downloading and installing community bits. The reality is that you don't know who is vouching for the bits in the community repository and thus whether they can be trusted or not. That is why when you do a Get-PackageSource, you'll see that we let you declare whether a source is TRUSTED or not. By default, the community repository is not trusted and therefore we will ask you about this when you download software from it.</p> 
</blockquote>
<p>Jeffrey added that:</p>
<blockquote> 
 <p>So yes - it is a concern and you'll see us doing a lot of work in this space but I have nothing to announce today.</p> 
</blockquote>
<p>and:</p>
<blockquote> 
 <p>Right now, it [Chocolatey] is very popular but also very informal. What you'll see is that we'll work [with the Chocolatey team] to provide a sliding scale of formality (e.g. opt-in formality) where you'll have a choice between getting very informal software (where there are very few steps required for anyone to publish software) to much more formal software.</p> 
</blockquote><br><br><br><br><br><br></body></html>