<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Docker、Mac OS XとBTRFSをサポート</h3><p><a target="_blank" href="http://www.infoq.com/news/2014/02/docker_0_8"><em>原文(投稿日：2014/02/17)へのリンク</em></a></p>
<div class="article_page_left news_container text_content_container"> 
 <div class="text_info"> 
  <p><a href="http://blog.docker.io/2014/02/docker-0-8-quality-new-builder-features-btrfs-storage-osx-support/">Docker 0.8のリリース</a>の一部として、Docker.ioチームは<a href="http://docs.docker.io/en/latest/installation/mac/">Mac OS Xへのインストールサポート</a>と<a href="http://en.wikipedia.org/wiki/Aufs">AUFS</a>の代替として<a href="http://en.wikipedia.org/wiki/Btrfs">BTRFS</a>が使えるようになったことを発表した。</p> 
  <p>Macサポートは、<a href="http://get.docker.io/builds/Darwin/x86_64/docker-latest">ネイティブのDocker OS Xクライアント</a>と<a href="http://en.wikipedia.org/wiki/Virtualbox">VirtualBox</a>で動かすのに必要な軽量な<a href="https://github.com/steeve/boot2docker">Boot2Docker</a>仮想マシン (VM) から構成される（OS XはDockerに必要なLinuxコンテナをサポートしていないため）。このリリース以前は、MacユーザはLinux仮想マシン上でDockerクライアントとデーモンの両方を動かす必要があった。</p> 
  <p>DockerチームはLinuxコンテナ (<a href="http://en.wikipedia.org/wiki/Lxc">LXC</a>) 関連をOS Xに移植することを望んでいたが、今のところ、デーモンはVMで起動する必要がある。Boot2Dockerは最小限のLinux環境とVirtualBoxで動くコマンドラインスクリプト一式を提供する。Boot2Dockerはライフサイクル管理とともに、VMで動作するSSHとDockerデーモンのポートマッピングの面倒を見る。DOCKER_HOST環境変数を使うことで、クライアントはデフォルトのネイティブUnixソケットではなく、TCPでDockerデーモンに接続することができる。残念ながら、Boot2DockerはまだDocker自身のポートマッピングメカニズムと統合されておらず、ホストであるMacからコンテナ内で動いているサービスに接続するためには、<a href="https://github.com/dotcloud/docker/issues/4007">VirtualBoxとDocker両方のポートをマップする</a>必要がある。</p> 
  <p>BTRFSドライバはまだ実験的なものとされており、既存のBTRFSパーティションを用意する必要がある。Dockerの動作には、基本となる<a href="http://en.wikipedia.org/wiki/Copy_on_write">コピーオンライト</a>ファイルシステムの利用が不可欠だ。イメージとイメージから生成したコンテナはファイルシステムブランチにマッピングされたレイヤにより構成される。<a href="http://en.wikipedia.org/wiki/Zfs">ZFS</a>ドライバの作業も進行中だ。</p> 
  <p>また、Docker.ioチームは特定の機能とは関係なしに、月1回リリースすると発表した。これは元VMware VPでGreylock Partnersの<a href="http://www.greylock.com/teams/50-Jerry-Chen">Jerry Chen</a>氏による<a href="http://blog.docker.io/2014/01/docker-closes-15-m-series-b-funding/">$15mの投資ラウンド</a>に沿ったもので、Dockerを製品レベルにし、コミュニティプラットフォームを築き、商用化に向けた道筋をつけていく予定だ。Dockerチームは<a href="https://github.com/dotcloud/docker">githubのmasterブランチ</a>を安定させ、これを最新版を求めている人へのリファレンスポイントにすると約束している。なお、最新の投資ラウンドに先立ち、<a href="http://www.infoq.com/news/2013/10/dotcloud-renamed-docker">dotCloudは社名をDocker Incに変更した</a>。</p> 
  <p>Dockerの背景と使われ方について、詳しくはZef Hemel氏の「<a href="http://www.infoq.com/jp/articles/docker-containers/">Docker: Linuxコンテナを使ってアプリケーションの配置を支援する</a>」を参照。</p> 
 </div> 
</div><br><br><br><br><br><br></body></html>