<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Práticas para escalar o Agile nas Empresas</h3><p>Empresas que est&atilde;o adotando uma reorganiza&ccedil;&atilde;o &aacute;gil abrangendo toda a empresa em algum momento ter&atilde;o que escalar suas pr&aacute;ticas &aacute;geis. Essas empresas geralmente t&ecirc;m v&aacute;rias equipes interdependentes. Isso requer que as pr&aacute;ticas &aacute;geis funcionem atrav&eacute;s da empresa de forma semelhante, para permitir a colabora&ccedil;&atilde;o entre equipes distintas.</p>
<p>Frank Langeveld promoveu uma sess&atilde;o de meia hora na confer&ecirc;ncia <a href="http://www.conferences.unicom.co.uk/agileincomplexenvironments/">M&eacute;todos &aacute;geis no setor financeiro e em ambientes complexos</a> para compartilhar experi&ecirc;ncias entre os participantes sobre como escalar Agile nas empresas. Come&ccedil;ou pedindo para as pessoas ficarem em p&eacute; caso conhecessem alguma pr&aacute;tica para escalar Agile que gostariam de falar a respeito. Apenas quatro pessoas levantaram, e Frank pediu a cada uma delas para que falasse 30 segundos sobre a pr&aacute;tica, que foi registrada em um quadro. J&aacute; que eram apenas quatro pr&aacute;ticas, Frank decidiu que cada apresentador teria 5 minutos para explic&aacute;-las em mais detalhes e responder as d&uacute;vidas dos participantes. Dado o curto espa&ccedil;o de tempo, somente perguntas que ajudariam a esclarecer a pr&aacute;tica foram permitidas; discuss&otilde;es sobre se uma pr&aacute;tica poderia ou n&atilde;o funcionar foram interrompidas pelo l&iacute;der da sess&atilde;o.</p>
<p>As quatro pr&aacute;ticas que surgiram foram:</p>
<ul> 
 <li>Ciclo de vida risco/valor</li> 
 <li>Modelagem de casos de uso</li> 
 <li>Estrutura de projetos em dua camadas</li> 
 <li>Combina&ccedil;&atilde;o das melhores pr&aacute;ticas</li> 
</ul>
<p>Veja os resumos das pr&aacute;ticas apresentadas:</p>
<blockquote> 
 <p><strong>Ciclo de de vida r</strong><strong>isco/valor</strong></p> 
 <p>Essa &eacute; uma pr&aacute;tica do RUP (<a href="http://pt.wikipedia.org/wiki/IBM_Rational_Unified_Process">Rational Unified Process</a>) e dispon&iacute;vel como uma <a href="http://epf.eclipse.org/wikis/epfpractices/practice.mgmt.risk_value_lifecycle.base/guidances/practices/risk_value_lifecycle_847D8B7D.html">pr&aacute;tica do Eclipse Process Framework</a>. &Eacute; uma estrat&eacute;gia de mitiga&ccedil;&atilde;o de riscos que pode ser usada em projetos &aacute;geis. Os maiores riscos de iniciar um projeto est&atilde;o frequentemente ligados ao grau de envolvimento dos interessado nos projeto. Por esse motivo, o foco das primeiras itera&ccedil;&otilde;es (durante a fase de inicial) deve ser em conseguir que todos os interessados concordem quanto ao problema a ser resolvido. Se n&atilde;o estiverem envolvidos suficientemente, n&atilde;o ser&aacute; poss&iacute;vel entregar uma solu&ccedil;&atilde;o que resolver&aacute; os problemas em quest&atilde;o.</p> 
 <p>Itera&ccedil;&otilde;es na fase de Elabora&ccedil;&atilde;o devem se concentrar em provar que se pode fazer o produto. Na fase de constru&ccedil;&atilde;o, o foco deve ser em assegurar que a funcionalidade requerida pode ser realizada no produto. Na fase de transi&ccedil;&atilde;o a gest&atilde;o de riscos se concentra em assegurar que os usu&aacute;rios podem realmente usar o produto. Resumindo, o Ciclo de Vida Risco/Valor ajuda a gerenciar diferentes riscos durante o ciclo de vida do projeto para entregar valor.</p> 
</blockquote>
<blockquote> 
 <p><strong>Modelagem de Casos de Uso</strong></p> 
 <p>Essa pr&aacute;tica pode ser usada com uma pr&aacute;tica para escalar o Agile no gerenciamento de requisitos em projetos &aacute;geis. <a href="http://en.wikipedia.org/wiki/User_story">User Stories</a> s&atilde;o boas para especifica&ccedil;&atilde;o, mas n&atilde;o ajudam a documentar o contexto de um sistema e lidar com abstra&ccedil;&otilde;es. Nessa situa&ccedil;&atilde;o os Casos de Uso t&ecirc;m valor sendo poss&iacute;vel capturar as hist&oacute;rias de usu&aacute;rio para mostrar como se relacionam. Modelagem de Caso de Uso tamb&eacute;m pode ajudar a combinar as User Stories do usu&aacute;rio em processos e regras de neg&oacute;cios a n&iacute;vel empresarial.</p> 
</blockquote>
<blockquote> 
 <p><strong>A estrutura de projetos de duas camadas</strong></p> 
 <p>A estrutura de projetos de duas camadas torna poss&iacute;vel gerenciar projetos em cascata (Waterfall), Agile, al&eacute;m de outros modelos e em um escrit&oacute;rio de projetos. Essa estrutura consiste de uma camada de gerenciamento de projeto e uma camada de execu&ccedil;&atilde;o. A camada de gerenciamento de projeto &eacute; a mesma para diferentes tipos de projetos, e assegura que todos os projetos ir&atilde;o reportar no mesmo formato para seus stakeholders. Um gerente de projeto tem a flexibilidade de definir a camada de execu&ccedil;&atilde;o de tal maneira que isso o ajuda a gerenciar o projeto. A estrutura de projetos de duas camadas pode consistir de itera&ccedil;&otilde;es &aacute;geis, v&aacute;rias trilhas para o gerenciamento de v&aacute;rios produtos ou partes grandes de um produto em um projeto, ou fases do modelo em cascata. A camada de gerenciamento do projeto tem as fases &quot;definir&quot;, &quot;executar&quot; e &quot;encerrar&quot;. Um projeto no modelo em cascata pode, por exemplo, ter uma camada de execu&ccedil;&atilde;o com design, implementa&ccedil;&atilde;o e constru&ccedil;&atilde;o que se encaixa na fase de execu&ccedil;&atilde;o da camada de gerenciamento de projetos, no qual um projeto usando Scrum teria sprints na fase de execu&ccedil;&atilde;o. Tamb&eacute;m &eacute; poss&iacute;vel ter projetos com equipes que tem diferentes camadas de execu&ccedil;&atilde;o como, por exemplo, uma equipe de interface com o usu&aacute;rio que est&aacute; usando itera&ccedil;&otilde;es &aacute;geis e na constru&ccedil;&atilde;o da camada de neg&oacute;cios uma equipe com fases do modelo em cascata.</p> 
</blockquote>
<blockquote> 
 <p><strong>Combina&ccedil;&atilde;o das melhores pr&aacute;ticas</strong></p> 
 <p>Ao escalar Agile na empresa, ser&aacute; muito &uacute;til se a organiza&ccedil;&atilde;o for capaz de combinar pr&aacute;ticas de diferentes m&eacute;todos para construir sua pr&oacute;pria abordagem Agile de grande escala. Isso pode ser chamado de &quot;um pouco de tudo&quot;, no qual basicamente usa-se o que est&aacute; dispon&iacute;vel na empresa e reusa e combina as melhores pr&aacute;ticas para escalar Agile.</p> 
</blockquote>
<p>Quais pr&aacute;ticas sua empresa utiliza para escalar Agile?</p><br><br><br><br><br><br></body></html>