<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Domino: Datascience-as-a-Service</h3><p>O <a href="http://www.google.com/url?q=http%3A%2F%2Fwww.dominoup.com%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNHVHGcmvPUnu4QxY0KD5-pByp4L_A">Domino</a>, uma plataforma para a ci&ecirc;ncia anal&iacute;tica de dados, permite que qualquer pessoa realize um trabalho anal&iacute;tico usando linguagens como Python ou <a href="http://www.google.com/url?q=http%3A%2F%2Fpt.wikipedia.org%2Fwiki%2FR_%2528linguagem_de_programa%25C3%25A7%25C3%25A3o%2529&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNEC2jtuFiWz9DqnMkn9SXvRZvHU6g">R</a>.</p>
<p>De acordo com Nick Elprin (co-fundador da Domino), a plataforma permite que os cientistas possam se concentrar em suas an&aacute;lises, sem perder tempo com a infra-estrutura:</p>
<blockquote> 
 <p>Ao passo que os volumes de dados v&ecirc;m aumentando e as t&eacute;cnicas de an&aacute;lise v&ecirc;m se tornando mais sofisticadas, acreditamos que as ferramentas mais modernas para realizar a an&aacute;lise de dados devem ser de f&aacute;cil uso e n&atilde;o limitem o trabalho no campo da ci&ecirc;ncia de dados.</p> 
</blockquote>
<p>A plataforma Domino tem como pilares tr&ecirc;s funcionalidades:</p>
<ol class="c8 lst-kix_4m5n96ope8f9-0 start" start="1"> 
 <li><strong>Implanta&ccedil;&atilde;o e execu&ccedil;&atilde;o na nuvem:</strong> O Domino executa um c&oacute;digo existente (Python, R, Matlab, Julia, shell scripts, entre outros) no EC2, a fim de executar tarefas de longa dura&ccedil;&atilde;o e uso intensivo de recursos. O sistema disponibiliza toda a estrutura para que isso aconte&ccedil;a: gest&atilde;o AMI, gest&atilde;o do ciclo de vida das m&aacute;quinas, transfer&ecirc;ncia segura de dados entre m&aacute;quinas e transfer&ecirc;ncia segura dos resultados.</li> 
 <li><strong>Controle de Vers&atilde;o:</strong> A equipe do Domino percebeu que ferramentas de controle de vers&atilde;o, como git, s&atilde;o insuficientes para fluxos de trabalho de an&aacute;lise, pois n&atilde;o conseguem lidar com grandes conjuntos de dados e n&atilde;o fazem um relacionamento entre as entradas e os resultados (por exemplo: tabelas e figuras). O Domino faz o controle de vers&atilde;o de todo o projeto automaticamente, atualmente at&eacute; 40 GB, tornando mais f&aacute;cil manter a mem&oacute;ria de todo o projeto, incluindo c&oacute;digos, os dados e os resultados.</li> 
 <li><strong>Colabora&ccedil;&atilde;o:</strong> Como um projeto do Github, projetos Domino podem ter colaboradores que podem ver, editar e executar um projeto. O Domino detecta conflitos, envia notifica&ccedil;&otilde;es atualizadas sobre os resultados das execu&ccedil;&otilde;es e tem um bloco de notas interno para facilitar a discuss&atilde;o da equipe sobre o andamento do projeto.</li> 
</ol>
<p>Com a abordagem <a href="http://www.google.com/url?q=http%3A%2F%2Finside-bigdata.com%2F2014%2F02%2F21%2Fdata-science-cloud-domino%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNGAnikmfERO1Abc3FQVNumlP7eYng">pague e use</a>, os pre&ccedil;os do Domino variam de contas gratuitas at&eacute; assinaturas mensais. Como o InfoQ apurou com Nick Elprin, apesar de a plataforma ser bem recente, j&aacute; vem sendo utilizada por todo o espectro de <a href="http://www.google.com/url?q=http%3A%2F%2Fbickson.blogspot.com%2F2014%2F03%2Fdomino-data-labs-run-data-analytics-in.html&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNFkZQQvpK_yzDru9d4a5AtU6XWo2A">profissionais da ci&ecirc;ncia de</a> <a href="http://www.google.com/url?q=http%3A%2F%2Fbickson.blogspot.com%2F2014%2F03%2Fdomino-data-labs-run-data-analytics-in.html&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNFkZQQvpK_yzDru9d4a5AtU6XWo2A">dados</a>: desde acad&ecirc;micos, como por exemplo um ecologista que analisa milhares de imagens para sua pesquisa, at&eacute; empresas de marketing que ajudam seus clientes a atingirem seus objetivos.</p><br><br><br><br><br><br></body></html>