<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Build 2014 Retrospective</h3><p class="Standard">The first week of April Microsoft held their annual Build developer conference in San Francisco, California.&nbsp; Microsoft uses this conference to communicate and evangelize developers for the various platforms (Windows, Windows Phone, and Xbox).&nbsp; The result is that provides a useful insight to what Microsoft feels is important and where these platforms are headed next.
 <o:p></o:p>
 <o:p>
  &nbsp;
 </o:p></p>
<p class="Standard">My comments are based on my third attendance and how the presentations compare to the previous years.&nbsp; The overall theme I would take away from Build 2014 is that Microsoft has a renewed focus on appealing to developers and increased commitment to open source licensed technologies.&nbsp; Sure some Microsoft platforms are locked down (Windows Phone / Xbox ) but that is an inherent characteristic of their nature.&nbsp; Even so libraries like WinJS and Portable Class Libraries are available to run in those environments.&nbsp; <a href="http://typescript.codeplex.com/">TypeScript</a> has been open source since the beginning.&nbsp; The Roslyn project has produced a complete rewrite of the C# and VB.NET compilers and released them under an open source license.&nbsp; Combining Roslyn with Mono and Xamarin tools opens the door to non-Microsoft platforms Android, Linux, and iOS.&nbsp; 
 <o:p></o:p></p>
<p class="Standard">The atmosphere from the Microsoft personnel seemed livelier as they spoke with a renewed energy when compared to previous Build events.&nbsp; For example, last year the keynote focused on Windows 8.1 Update and the new devices being released to support touch-based computing.&nbsp; Developer-centric content was there, but it was secondary to the message of new devices.&nbsp; 
 <o:p></o:p></p>
<p class="Standard">The choice of presenters helps to illustrate the difference.&nbsp; The spotlight for Build 2014 was given to various teams and department heads that focused on developer content rather than just purely highlighting new devices.&nbsp; Joe Belfiore, David Treadwell, and Kevin Gallo (among several others) discussed migrating legacy Win32 applications, building Universal Apps, and the improvements to the Windows Phone platform.&nbsp; By comparison last year highlighted Windows 8.1 improvements and described the Bing platform—all interesting in their own way but by no means developer-centric.
 <o:p></o:p></p>
<p class="Standard">Many of these technologies have been in development before Nadella took office, and so Steve Ballmer certainly deserves credit for putting them in motion while CEO.&nbsp; Nadella’s full role and direction for Microsoft is still under observation given his recent promotion.&nbsp; Yet perhaps it took his elevation to CEO to give some of the messages a fresh vote of support.
 <o:p></o:p></p>
<p class="Standard">This is not to say that the picture is entirely rosy.&nbsp; Critics could argue that the Windows app convergence is long overdue, that Windows Phone cannot unseat iPhone and Android, and that Visual Studio is overpriced.&nbsp; Rather than see the rapid releases of Visual Studio as a positive, some see it as a chance for Microsoft to charge another upgrade fee.&nbsp; (Especially since comments indicate the next wave of C++ language features <a href="http://blogs.msdn.com/b/vcblog/archive/2013/11/18/announcing-the-visual-c-compiler-november-2013-ctp.aspx">will require V.Next</a> to use in formal production environments/Go-Live.) 
 <o:p></o:p></p>
<p class="Standard">In final summary, while Microsoft still has many challenges ahead, it would seem that the company is successfully pivoting to face its competitors head on.&nbsp; Reinvigorating support for the Windows platforms should only improve the opportunities for customers to get better products.
 <o:p></o:p></p><br><br><br><br><br><br></body></html>