<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Desenvolvedor Java é o mais procurado e bem pago pelo mercado</h3><p>Os desenvolvedores Java foram os mais procurados pelos recrutadores em 2013 e, n&atilde;o por acaso, s&atilde;o os mais bem pagos no mercado. &Eacute; a conclus&atilde;o de <a href="http://jaxenter.com/why-java-skills-are-still-golden-for-developers.1-49296.html">um editorial do site JAXenter</a>, publicado em janeiro, a partir de alguns levantamentos nos EUA realizados sobre o tema.</p>
<p>O editorial tomou como base <a href="http://readwrite.com/2014/01/08/in-demand-tech-skills-of-2013-java#awesm=~oxidvFWg5PnKKY">os n&uacute;meros compilados</a> por <a href="http://readwrite.com/author/lauren-orsini#awesm=~oxiND0YteZRPeY">Lauren Orsini</a>, do site de not&iacute;cias de tecnologia <a href="http://readwrite.com/page/about#awesm=~oxil2BynDlrTDT">ReadWrite</a>. Na compila&ccedil;&atilde;o, feita a partir de um conjunto de 14.000 consultas por profissionais no site <a href="http://careers.stackoverflow.com/">Careers 2.0</a> realizadas no ano passado, foi apurado que 22,26% eram com a palavra-chave Java - quase o dobro do segundo colocado, PHP. O Android, outra tecnologia baseada em Java, ficou em quarto com 9,94% acima de JavaScript e Python respectivamente com 9,23% e 8,30%.</p>
<p><img src="http://www.infoq.com/resource/news/2014/04/dev-java-mais-procurado/pt/resources/image00.png" alt="Os 10 mais procurados conhecimentos em programa&ccedil;&atilde;o de 2013" _href="img://image00.png" _p="true" /></p>
<p>Figura: Os 10 mais procurados conhecimentos em programa&ccedil;&atilde;o de 2013.</p>
<p>Fonte: <a href="http://readwrite.com/2014/01/08/in-demand-tech-skills-of-2013-java#awesm=~oxidvFWg5PnKKY">readwrite.com</a></p>
<p>Entretanto, tal fato n&atilde;o era nenhuma novidade. Ainda em janeiro de 2013, o mesmo JAXenter publicou <a href="http://jaxenter.com/java-tops-desired-software-skills-list-survey-reveals-40135.html">o resultado de um question&aacute;rio</a> apontando a tecnologia Java/J2EE como o conhecimento mais desejado pelos gerente e recrutadores. Contudo, o que surpreende &eacute; o fato do Java n&atilde;o ser a linguagem mais popular entre os desenvolvedores, apesar de ser uma das tr&ecirc;s tecnologias que mais bem pagam os profissionais.</p>
<p>Um <a href="http://jaxenter.com/java-devs-among-best-paid-in-industry-47961.html">levantamento</a> feito por <a href="http://www.linkedin.com/pub/ben-podgursky/7/5aa/593">Ben Podgursky</a>, engenheiro de software da <a href="https://liveramp.com/about/">LiveRamp</a>, calculou a renda m&eacute;dia por desenvolvedor de cada linguagem dos 100.000 projetos mais populares no GitHub e concluiu que o Java &eacute; terceira linguagem mais rent&aacute;vel acima de linguagens como C, Perl e Ruby. Tal resultado contrasta com o atual <a href="http://en.wikipedia.org/wiki/TIOBE_index">&iacute;ndice TIOBE</a>, que mede a popularidade das linguagens de programa&ccedil;&atilde;o, e <a href="http://www.tiobe.com/index.php/content/paperinfo/tpci/index.html">traz o Java em segundo lugar</a>, atr&aacute;s da campe&atilde; de popularidade C.</p>
<p><img src="http://www.infoq.com/resource/news/2014/04/dev-java-mais-procurado/pt/resources/image01.png" alt="Receita m&eacute;dia por programador de cada linguagem." _href="img://image01.png" _p="true" /></p>
<p>Figura: Receita m&eacute;dia por programador de cada linguagem.</p>
<p>Fonte: <a href="http://jaxenter.com/java-devs-among-best-paid-in-industry-47961.html">JAXenter.com</a> (adaptado de <a href="http://bpodgursky.files.wordpress.com/2013/08/chart_2.png">bpodgursky.com</a>)</p>
<p><a href="http://careers.stackoverflow.com/willcole">Will Cole</a>, gerente de produto do Careers 2.0 do Stack Overflow, sentencia:</p>
<blockquote> 
 <p>&quot;Ame ou odeie, muita gente conhece Java e muitas empresas querem estes desenvolvedores.&quot;</p> 
</blockquote>
<p>Por fim, o editorial destaca o dom&iacute;nio das linguagens estabelecidas h&aacute; mais tempo no mercado e a aus&ecirc;ncia de qualquer nova tecnologia da moda nas listas de habilidades mais procuradas como parte da tend&ecirc;ncia de estabilidade no setor em 2013. Como evid&ecirc;ncia desta tend&ecirc;ncia, tem-se a entrega do <a href="http://jaxenter.com/top-programming-languages-list-of-2013-throws-up-surprise-winner-49247.html">pr&ecirc;mio de linguagem do ano</a> do &iacute;ndice TIOBE ao Transact-SQL, uma linguagem de extens&atilde;o para SQL propriet&aacute;ria da Microsoft e Sybase.</p><br><br><br><br><br><br></body></html>