<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>AWS se junta à concorrência dos provedores de Cloud e oferece suporte ao Node.js</h3><p>O time da Amazon Web Services (AWS) recentemente adicionou suporte ao Node.js para seu servi&ccedil;o <a href="http://aws.amazon.com/pt/elasticbeanstalk/">Elastic Beanstalk</a>, dando a Amazon a lideran&ccedil;a de mercado em n&uacute;mero de plataformas suportadas. Al&eacute;m do Node.js, a AWS Elastic Beanstalk d&aacute; ao desenvolvedor a habilidade de empacotar, instalar, e gerenciar aplica&ccedil;&otilde;es escritas em Java, PHP, .NET, Ruby e Python. A AWS tem se juntado ao repleto time de provedores de Clouds com suporte ao Node.js e tentar&aacute; se diferenciar dos concorrentes atrav&eacute;s da integra&ccedil;&atilde;o com os principais servi&ccedil;os da AWS.</p> 
<p>Em um<a href="http://www.allthingsdistributed.com/2013/03/beanstalk-a-la-node.html"> post no blog do CTO da AWS, Werner Vogels, sobre a adi&ccedil;&atilde;o do Node.js</a>, Werner descreve algumas das raz&otilde;es para incluir esta plataforma que &eacute; cada vez mais popular.</p> 
<blockquote> 
 <p>Gastei muito tempo conversando com os desenvolvedores da AWS, sendo que muitos deles trabalham nas &aacute;reas de jogos e mobile, e a maioria destes desenvolvedores t&ecirc;m achado o Node.js bastante adequado para suas aplica&ccedil;&otilde;es web. Com o modelo de programa&ccedil;&atilde;o ass&iacute;ncrona, orientada a eventos, o Node.js permite que estes desenvolvedores tratem um grande n&uacute;mero de conex&otilde;es concorrentes com baixa lat&ecirc;ncia. Estes desenvolvedores normalmente usam inst&acirc;ncias EC2 combinadas com um de nossos servi&ccedil;os de banco de dados para criar servi&ccedil;os web usados na recupera&ccedil;&atilde;o de dados ou criar interfaces mobile din&acirc;micas.</p> 
</blockquote> 
<p>Jeff Barr, do time da AWS, <a href="http://aws.typepad.com/aws/2013/03/aws-elastic-beanstalk-for-nodejs.html">apontou algumas de suas funcionalidades favoritas</a> do Node.js na Elastic Beanstalk:</p> 
<ul> 
 <li>Escolha entre <a href="http://nginx.org/">Nginx</a> ou <a href="http://httpd.apache.org/">Apache</a> como proxy reverso para sua aplica&ccedil;&atilde;o Node.js. Voc&ecirc; pode inclusive escolher n&atilde;o utilizar proxy caso sua aplica&ccedil;&atilde;o exija que o cliente estabele&ccedil;a uma conex&atilde;o direta.</li> 
 <li>Configure o balanceamento de carga baseado em HTTP e TCP dependendo de qual sua aplica&ccedil;&atilde;o necessita. Caso sua aplica&ccedil;&atilde;o utilize WebSockets, o balanceamento de carga baseado em TCP pode ser mais apropriado para sua carga de trabalho.</li> 
 <li>Configure a pilha do Node.js usando a vers&atilde;o espec&iacute;fica do Node.js que sua aplica&ccedil;&atilde;o precisa, ou fornecendo o comando usado para iniciar sua aplica&ccedil;&atilde;o Node.js. Voc&ecirc; pode tamb&eacute;m gerenciar depend&ecirc;ncias usando o <a href="https://npmjs.org/">npm</a>.</li> 
 <li>Ajude a melhorar a performance configurando a compress&atilde;o gzip e arquivos est&aacute;ticos usando o Nginx ou o Apache. Com a compress&atilde;o gzip, voc&ecirc; pode reduzir o tamanho da resposta ao cliente, ajudando a criar uma alta taxa de transfer&ecirc;ncia. Com arquivos est&aacute;ticos, voc&ecirc; pode permitir que o Nginx ou o Apache rapidamente sirva seu conte&uacute;do est&aacute;tico (como imagens ou CSS) sem ter esse tipo de requisi&ccedil;&atilde;o roubando tempo de processamento intensivo de dados que sua aplica&ccedil;&atilde;o Node.js possa estar fazendo.</li> 
 <li>Integre sua aplica&ccedil;&atilde;o de forma transparente com o <a href="http://aws.amazon.com/pt/rds/">Amazon RDS</a> para armazenar e recuperar dados de uma base de dados relacional.</li> 
 <li>Customize suas inst&acirc;ncias EC2 ou conecte sua aplica&ccedil;&atilde;o nos recursos da AWS usando os arquivos de configura&ccedil;&atilde;o do Elastic Beanstalk (visite o <a href="http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_nodejs_custom_container.html">Guia de desenvolvimento do AWS Elastic Beanstalk</a> para aprender mais sobre arquivos de configura&ccedil;&atilde;o).</li> 
 <li>Execute sua aplica&ccedil;&atilde;o Node.js dentro de um <a href="http://aws.amazon.com/pt/vpc/">Amazon Virtual Private Cloud</a> para ter um controle de rede adicional.</li> 
</ul> 
<p>Al&eacute;m das funcionalidades listadas, o Elastic Beanstalk tamb&eacute;m suporta <a href="http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_nodejs.sdlc.html">integra&ccedil;&atilde;o com Git</a>, <a href="http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_nodejs_express_elasticache.html">clusteriza&ccedil;&atilde;o para alta disponibilidade</a> e uso de <a href="http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_nodejs_custom_container.html">vari&aacute;veis por ambiente espec&iacute;fico</a> . A AWS fez sua primeira incurs&atilde;o no mundo Node.js em Dezembro de 2012 quando <a href="http://aws.amazon.com/about-aws/whats-new/2012/12/04/introducing-the-aws-sdk-for-node-js/">lan&ccedil;ou um SDK</a> para desenvolvedores Node.js. Esse SDK prov&ecirc; acesso a uma vasta gama de servi&ccedil;os dispon&iacute;veis na AWS incluindo Amazon DynamoDB, Amazon Simple Storage Service (S3), Amazon Relational Database Service (RDS), Amazon Simple Queue Service (SQS), Amazon Elastic Compute Cloud (EC2) e outros mais.</p> 
<p>Com esta iniciativa, a AWS junta-se as muitas outros provedores de Cloud que oferecem servi&ccedil;os para aplica&ccedil;&otilde;es Node.js. Com exce&ccedil;&atilde;o do Google App Engine. Atualmente, quase todos os fornecedores de Plataforma como Servi&ccedil;o disponibilizam estrutura para Node.js, incluindo <a href="http://devcenter.heroku.com">Heroku</a>, <a href="http://www.windowsazure.com/en-us/develop/nodejs/">Windows Azure</a>, <a href="https://www.openshift.com/paas">Open Shift</a>, <a href="https://www.engineyard.com/products/cloud/features">Engine Yard</a> e os muitos provedores do <a href="http://docs.cloudfoundry.com/frameworks/nodejs/nodejs.html">Cloud Foundry</a>. Todos estes provedores tamb&eacute;m competem com o <a href="https://www.nodejitsu.com/">lider de ideias e provedor de plataforma dedicada para Node.js, o Nodejitsu</a>. Ent&atilde;o qual o diferencial entre estes servi&ccedil;os? Uma maneira &eacute; atrav&eacute;s da disponibiliza&ccedil;&atilde;o de ferramentas. Werner Vogels aponta como o Elastic Beanstalk &eacute; fortemente integrado com ferramentas de desenvolvimento para muitas plataformas top de linha.</p> 
<blockquote> 
 <p>Voc&ecirc; pode instalar e gerenciar suas aplica&ccedil;&otilde;es em qualquer regi&atilde;o da AWS (exceto para GovCloud). Muitas ferramentas est&atilde;o dispon&iacute;veis para voc&ecirc; instalar e gerenciar sua aplica&ccedil;&atilde;o, &eacute; s&oacute; escolher sua op&ccedil;&atilde;o favorita. Se voc&ecirc; est&aacute; construindo uma aplica&ccedil;&atilde;o Java, pode utilizar o Toolkit AWS para Eclipse. Se est&aacute; construindo aplica&ccedil;&otilde;es .NET, pode utilizar o Toolkit AWS para Visual Studio. Se voc&ecirc; prefere trabalhar no terminal, pode utilizar uma ferramenta de linha de comando chamada 'eb' em conjunto com o Git. Parceiros como eXoCloud IDE tamb&eacute;m oferecem integra&ccedil;&atilde;o com o Elastic Beanstalk.</p> 
</blockquote> 
<p>O exoCloud, agora dividido e com o nome de <a href="https://codenvy.com/features">Codenvy</a>, prov&ecirc; aos desenvolvedores um ambiente para desenvolvimento baseado em Cloud podendo ser direcionado &agrave; implementa&ccedil;&otilde;es que utilizam o Node.js no Elastic Beanstalk. Al&eacute;m disso, para fornecer aos desenvolvedores ferramentas de deploy e instala&ccedil;&atilde;o de aplica&ccedil;&otilde;es Node.js, os provedores de Cloud est&atilde;o se diferenciando atrav&eacute;s da integra&ccedil;&atilde;o com servi&ccedil;os complementares, e oferecendo solu&ccedil;&otilde;es para o dif&iacute;cil problema do gerenciamento de aplica&ccedil;&otilde;es. Um aspecto atraente da execu&ccedil;&atilde;o do Node.js no Elastic Beanstalk &eacute; a habilidade de facilitar a integra&ccedil;&atilde;o com os muitos servi&ccedil;os de aplica&ccedil;&otilde;es fornecido pela AWS. As aplica&ccedil;&otilde;es Node.js que rodam no ambiente da AWS t&ecirc;m acesso de baixa lat&ecirc;ncia ao banco de dados, storage, computa&ccedil;&atilde;o, filas, cache e muito mais. Clouds como o Windows Azure tem uma proposta de valor diferente onde os <a href="http://www.windowsazure.com/en-us/develop/nodejs/">desenvolvedores que instalam as aplica&ccedil;&otilde;es Node.js</a> tamb&eacute;m t&ecirc;m acesso ao diverso conjunto de servi&ccedil;os nativos para banco de dados, storage e mensageria. Provedores como Heroku e Nodejitsu n&atilde;o possuem os pr&oacute;prios conjuntos de servi&ccedil;os complementares, mas mant&ecirc;m um refinado cat&aacute;logo de servi&ccedil;os que pod&ecirc;m ser integrados com as aplica&ccedil;&otilde;es que rodam nas plataformas de cada um.</p> 
<p>Al&eacute;m de prover servi&ccedil;os complementares como uma maneira de se destacar, os provedores de Cloud tamb&eacute;m demonstram suas habilidades para tornar a instala&ccedil;&atilde;o e o gerenciamento de aplica&ccedil;&otilde;es mais f&aacute;ceis. Isso significa suportar reposit&oacute;rios de controle de fonte baseados na web - assim como AWS, Windows Azure e o Nodejitsu - e oferecer servi&ccedil;os de deploy cont&iacute;nuo, como o Nodejitsu faz atrav&eacute;s de suporte ao TravisCI. Um monitoramento de alta qualidade e sistema de resposta podem tornar o gerenciamento de demanda muito mais simples para desenvolvedores e administradores de cloud. A AWS tem produtos para o monitoramento de uso e redimensionamento autom&aacute;tico dos ambientes da sua aplica&ccedil;&atilde;o e <a href="http://www.allthingsdistributed.com/2013/03/beanstalk-a-la-node.html">Werner Vogels</a> explicou como o Elastic Beanstalk ajuda a provisionar aplica&ccedil;&otilde;es com todos os recursos de gerenciamento inclu&iacute;dos.</p> 
<blockquote> 
 <p>O Elastic Beanstalk automatiza o provisionamento, monitora&ccedil;&atilde;o e a configura&ccedil;&atilde;o de muitos recursos subjacentes da AWS como o Balanceamento de Carga El&aacute;stico, Auto Scaling e EC2. O Elastic Beanstalk tamb&eacute;m fornece automa&ccedil;&atilde;o para instalar sua aplica&ccedil;&atilde;o, rotacionar seus logs e customizar suas inst&acirc;ncias EC2.</p> 
</blockquote> 
<p>Esteja atento nesta &aacute;rea, pois os provedores de Cloud cada vez mais aperfei&ccedil;oam os recursos de gerenciamento de aplica&ccedil;&otilde;es e oferecem servi&ccedil;os nativos ou integrados que melhoram a utilidade das aplica&ccedil;&otilde;es rodando em suas plataformas de Cloud Computing.</p> 
<p>Veja o post <a href="http://www.infoq.com/news/2013/03/aws-node-elastic-beanstalk;jsessionid=D542569F30B9EDF701702A797F82CD1D">original</a>.</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>