<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Deploying Chrome Apps on Android&iOS with Cordova 3.3.0</h3><p>Developer can now deploy Chrome apps on Android and iOS with Apache Cordova 3.3.0.</p>
<p>Six weeks after <a href="http://www.infoq.com/news/2013/12/PhoneGap-3.3">Adobe made available PhoneGap 3.3</a>, Cordova 3.3.0 was made available on <a href="https://build.phonegap.com/">PhoneGap Build</a>. Beside supporting Android KitKat, Cordova 3.3.0 adds support for <a href="https://developers.google.com/chrome-developer-tools/docs/remote-debugging">remote webview debugging from Chrome</a> on Android, &nbsp;and <a href="http://moduscreate.com/enable-remote-web-inspector-in-ios-6/">remote debugging with Safari</a>&nbsp;on iOS. The release notes contain details for each operating system supported: <a href="https://github.com/apache/cordova-ios/blob/master/RELEASENOTES.md">iOS</a>, <a href="https://github.com/apache/cordova-android/blob/master/RELEASENOTES.md">Android</a>, <a href="http://cordova.apache.org/announcements/2013/12/16/cordova-330.html#whats_new_in_windows_phone_7__8">Windows</a>. Cordova 2.5.0 and 2.7.0 will be deprecated in the near future, Blackberry, WebOS, or Symbian developer being invited to use version 2.9.0.</p>
<p>Back in September, Google announced the possibility to create <a href="http://chrome.blogspot.ro/2013/09/a-new-breed-of-chrome-apps.html">Chrome applications that can be deployed to the desktop</a> (samples of such apps can be found <a href="https://chrome.google.com/webstore/category/collection/for_your_desktop">here</a>). These apps can run on Windows, Mac or Linux either in online or offline mode. Recently, <a href="http://blog.chromium.org/2014/01/run-chrome-apps-on-mobile-using-apache.html">Google has expanded Chrome apps’ reach to mobile platforms</a>, Android and iOS, via Cordova 3.3.0.</p>
<p>To create their Chrome app for mobile, developers need to use a tool-chain based on Node.js, JDK 7, Android SDK 4.4.2, and Apache Ant for Android, or Xcode 5, ios-deploy, ios-sim for iOS, and use Cordova to wrap the application in a native shell, then publish it on Google Play or Apple App Store.</p>
<p>The following Chrome APIs have been made available for mobile apps:</p>
<blockquote> 
 <ul> 
  <li><a href="http://developer.chrome.com/apps/identity.html">identity</a> - sign-in users using OAuth2 without prompting for passwords</li> 
  <li><a href="http://developer.chrome.com/apps/google_wallet.html">payments</a> (currently Android only) - sell virtual goods within your mobile app</li> 
  <li><a href="http://developer.chrome.com/apps/pushMessaging.html">pushMessaging</a> - push messages to your app from your server</li> 
  <li><a href="http://developer.chrome.com/apps/socket.html">sockets</a> - send and receive data over the network using TCP and UDP</li> 
  <li><a href="http://developer.chrome.com/apps/notifications.html">notifications</a> (currently Android only) - send rich notifications from your mobile app</li> 
  <li><a href="https://developer.chrome.com/apps/storage.html">storage</a> - store and retrieve key-value data locally</li> 
  <li><a href="https://developer.chrome.com/apps/syncFileSystem.html">syncFileSystem</a> - store and retrieve files backed by Google Drive</li> 
  <li><a href="http://developer.chrome.com/apps/alarms.html">alarms</a> - run tasks periodically</li> 
 </ul> 
</blockquote>
<p>Beside those, developers can make use of a <a href="http://plugins.cordova.io/#/_browse/all">large number of Cordova APIs</a>&nbsp;providing wide access to native functionality.</p><br><br><br><br><br><br></body></html>