<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Puppet Enterprise 3.2 Brings Fully Supported Modules</h3><p><a href="http://puppetlabs.com/">Puppet Labs</a> has just released <a href="http://puppetlabs.com/blog/puppet-enterprise-3.2-extending-automation">Puppet Enterprise 3.2</a>, the commercially supported Puppet release. This release includes improvements such as fully supported modules, automation of tasks by non-root users and a <a href="http://puppetlabs.com/services/tech-preview">tech preview</a> of <a href="http://docs.puppetlabs.com/pe/3.2/razor_intro.html">Razor</a>, an application that discovers and provisions new servers.</p>
<p>Starting with this release, Puppet Labs provides full support for <a href="http://forge.puppetlabs.com/supported">twelve modules</a>. Puppet Labs bundles seven modules with Puppet Enterprise, which are critical to build an infrastructure. These modules configure the <a href="http://forge.puppetlabs.com/puppetlabs/apt">APT package management application</a>, <a href="http://forge.puppetlabs.com/puppetlabs/firewall">firewalls</a>, <a href="http://forge.puppetlabs.com/puppetlabs/java_ks">key stores</a>, <a href="http://forge.puppetlabs.com/puppetlabs/reboot">Windows machines reboots</a> and <a href="http://forge.puppetlabs.com/puppetlabs/stdlib">basic</a> <a href="http://forge.puppetlabs.com/puppetlabs/concat">building</a> <a href="http://forge.puppetlabs.com/puppetlabs/inifile">blocks</a> required by the remaining resources. The remaining five modules are available for <a href="http://forge.puppetlabs.com/supported">download</a> from <a href="http://forge.puppetlabs.com/">Puppet Forge</a>. They enable the installation and configuration of <a href="http://forge.puppetlabs.com/puppetlabs/apache">Apache</a>, <a href="http://forge.puppetlabs.com/puppetlabs/mysql">MySQL</a>, <a href="http://forge.puppetlabs.com/puppetlabs/postgresql">PostgreSQL</a>, <a href="http://forge.puppetlabs.com/puppetlabs/ntp">ntp</a> and the <a href="http://forge.puppetlabs.com/puppetlabs/registry">Windows registry</a>.</p>
<p>The 3.2 release also includes a tech preview, so it's not intended to use in a production environment, of <a href="https://github.com/puppetlabs/razor-server">Razor</a>. Razor is a tool that automatically discovers and provisions bare metal machines, as <a href="http://www.infoq.com/news/2012/06/razor">reported</a> by InfoQ. This tech preview is a rewrite of that initial version, as explained at Razor's <a href="https://github.com/puppetlabs/razor">initial GitHub repository</a>:</p>
<blockquote>
  Over the last year, we've also learned a lot about the community's needs and how Razor should evolve, and about the limitations of Razor that make evolution harder than it needs to be. This knowledge has brought us to the conclusion that Razor's community and future development are best served by a rewrite of the current code base. 
</blockquote>
<p>Non-root users, like database administrators and developers, can now automate tasks. So if a non-root user can perform an installation or configuration task by hand, then it can automate it with Puppet as well. This capability can also be useful in an outsourced infrastructure scenario. It gives the internal teams the autonomy to use Puppet within well-defined boundaries.</p>
<p>Puppet's agent technology also received some enhancements. Agent's installation is simplified by leveraging package management systems such as yum and apt. The supported platforms' range now includes Solaris 11. Future releases will support additional platforms.</p>
<p>Puppet Labs <a href="http://forge.puppetlabs.com/supported#testing-section">tests</a> the supported modules with <a href="http://puppet-lint.com/">puppet-lint</a>, <a href="http://rspec-puppet.com/">rspec-puppet</a> and <a href="https://github.com/puppetlabs/beaker">Beaker</a>. Beaker is a new acceptance test framework built by Puppet Labs.</p>
<p>Puppet Labs is studying the possibility of supporting community modules. Although the testing process is certain to require the use of the above mentioned tools, the whole vetting process is not yet defined.</p><br><br><br><br><br><br></body></html>