<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>DevOps CafeポッドキャストがQCon London 2014 DevOpsトラックを紹介</h3><p><a target="_blank" href="http://www.infoq.com/news/2014/02/devopscafe-on-qcon-london-track"><em>原文(投稿日：2014/02/09)へのリンク</em></a></p>
<div class="article_page_left news_container text_content_container"> 
 <div class="text_info"> 
  <p>前回のDevOps Cafe Podcats(<a href="http://devopscafe.org/show/2014/2/5/devops-cafe-episode-47.html">エピソード47</a>)は，<a href="http://qconlondon.com/london-2014/">QCon London 2014</a> <a href="http://qconlondon.com/london-2014/tracks/show_track.jsp?trackOID=911">DevOpsトラック</a>のプレビューだった。トラックのホストと講演者のほとんどが参加して，DevOps Cafeのホストである<a href="https://twitter.com/damonedwards">Damon Edwards</a>氏, <a href="https://twitter.com/botchagalupe">John Wills</a>氏と議論していた。トラックのホストである<a href="https://twitter.com/manupaisable">Manuel Pais</a>, <a href="https://twitter.com/shanehastie">Shane Hasite</a>両氏による各セッションの選択理由の説明に続いて，それぞれの講演者が自身の講演について紹介した。その後は科学的手法の重要性について，あるいはアジャイルの&quot;Done&quot;の定義をDevOpsにどのように適応すべきかなど，さまざまな話題が議論された。</p> 
  <p>Manuelによると，QConはどちらかといえば開発者指向のカンファレンスなので，DevOpsが何を意味するのか，どのような違いを生み出すのかといった説明を通じて，開発指向の人々との橋渡しを支援するようなトラックにしたいというのが講演者たちの考えだ。セッションがさまざまな視点 – 文化的側面からビジネス視点まで – からDevOpsを捉える一方で，いくつかのケーススタディがトピックそのものに具体性を与える。</p> 
  <p><a href="http://qconlondon.com/london-2014/speaker/Daniel+Schauenberg">Daniel Schauenberg</a>氏の講演<a href="http://qconlondon.com/london-2014/presentation/Development,%20Deployment%20&amp;%20Collaboration%20at%20Etsy">&quot;Development, Deployment &amp; Collaboration at Etsy&quot;</a>では，本物のDevOps文化が根付いて継続的デリバリと組み合わされたとき，そこにどれほどの効果が期待できるか，という話題を取り上げる。講演ではEtsyのスタック構築方法 – 予想に反しているかも知れないが，クラウドではなく，モノシリックなアプリケーション形式を採用している – について紹介する予定だ。講演の中心はEtsyにおけるアプローチ開発やデプロイメント，インシデント対応，目標を共有するコラボレーション，といったものになる。</p> 
  <p><a href="http://qconlondon.com/london-2014/speaker/Damon+Edwards">Damon Edwards</a>氏の<a href="http://qconlondon.com/london-2014/presentation/Dev%20%22Programming%22%20Ops%20For%20DevOps%20Success">&quot;Dev 'Programming' Ops For DevOps Success&quot;&quot;</a>という講演では，DevOpsの文化面に注目する。ゼロからDevOps文化を構築することのできる組織もあるが，そのような幸運に恵まれない場合の方が多い。氏の言うように，&quot;企業とは成功の結果&quot;なのだ。多くの企業には多数のアプリケーション遺産があり，長年に渡って独自の文化が築き上げられている。講演では，この状況を打開するための二面アプローチを取り上げる。第１のアプローチでは，変化を引き起こし，開発(Dev)と運用(Ops)のギャップを埋めるためのヒントやトリックに注目する。第２の方法では，運用チームがどのように行動すべきか，というモデル構築の必要性に着目する。DevOpsのアプローチを説明する上で，オペレーション・アズ・ア・サービスということばが使われることがある。運用活動をチケットや要求/対応キューを通じて管理される対象としてではなく，もっと計画的な方法で，自己完結的に実施されるサービスとして捉えるアプローチだ。</p> 
  <p><a href="http://qconlondon.com/london-2014/speaker/Dave+Farley">Dave Farley</a>氏が講演する<a href="http://qconlondon.com/london-2014/presentation/The%20process,%20Technology%20&amp;%20Practice%20of%20Continuous%20Delivery">&quot;The process, Technology &amp; Practice of Continuous Delivery&quot;</a>では，継続的デリバリとDevOpsに共通する特徴やツーリング，コラボレーションの必要性，フィードバックループの短縮といった話題を取り上げる予定だ。アジャイルの有用性はフィードバックループの短さにあると氏は考える。それによって促進される迅速かつ継続的な学習ループは，DevOpsの提唱するものと同じだ。DevOps Cafeでの氏は，DevOpsと継続的デリバリの関連性を描きあげている。氏はこれを&quot;人類史上最高の&quot;科学的手法と呼ぶ。講演では実際のプロジェクトを例として，彼らが継続的デリバリを達成するために用いてきた方法や，それがなぜ，どのように有効であるのか，ということを説明したいと考えている。</p> 
  <p><a href="http://qconlondon.com/london-2014/speaker/Robert+Benefield">Robert Benefield</a>氏の<a href="http://qconlondon.com/london-2014/presentation/Instrumenting%20Your%20Business%20For%20Success%20with%20DevOps">&quot;Instrumenting Your Business For Success with DevOps&quot;</a>では，DevOpsにビジネス面での価値を見出すために運用チームが行うべきことについて取り上げる。経営側が現実の世界で起きていることを理解し，その状況認識をいかに差別化要因とすることができるためには，優れたインストルメンテーションが鍵である，と氏は考える。 さらに氏は，ビジネス的な表現方法の重要性についても言及している。&quot;1日100デプロイメント&quot;は意味がない，経営側が知りたいのは，ビジネス上のイベントに対する応答がどれほど早いか，という点なのだ。</p> 
  <p><a href="http://qconlondon.com/london-2014/speaker/Ola+Ellnestam">Ola Ellnestam</a>氏はポッドキャストには出席できなかったので，代わりにShaneが氏の講演<a href="http://qconlondon.com/london-2014/presentation/DevOps%20at%20a%20small%20International%20Bank%20-%20Contiguous%20Improvement%20over%20Continuous%20Delivery">&quot;DevOps at a small International Bank - Contiguous Improvement over Continuous Delivery&quot;</a>について説明した。この講演は銀行という，法規が厳密かつ複雑でコンプライアンスが重要な状況において，DevOpsがどのように適用できるかのケーススタディとなる予定だ。氏が従事するスウェーデン銀行では，物事に取り組む場合において，付加価値の向上と同時にその実行安全性が重要視される。そのプロセスにおいて生み出された&quot;継続的改善 (Contiguous Improvement)&quot;ということばには，&quot;改善の必要なものだけを改善する&quot;という意図が含まれている。講演では数多くのストーリを取り上げて，その基本的な原則と価値，背景にあるビジネス，実施された技術的選択といった点に注目する予定だ。</p> 
  <p>ポッドキャストの最後の３分の１は，フィードバックループやアジャイルにおけるDoneの定義など，より一般的な話題に触れていた。</p> 
  <p>DevOpsプラクティス成功の鍵が迅速なフィードバックとそれに伴う検証可能性にあるというのは，誰もが同意するところだ。それはまた科学的手法のプロセス – 仮説の立案，実験の実施, 仮説の証明あるいは反証 – とも関連する。このサイクルの速度を限界まで速めると同時に，それを継続することが必要だ。</p> 
  <p>アジャイルの&quot;Done&quot;の定義についても議論された。 この定義には誤解があるのではないか，開発が完了して経営側に承認されれば作業終了と開発チームが考えているのではないか，運用面が忘れられているのではないか，という懸念がある。特にサービスの世界においては，完全に終了(Done)というのはあり得ないことだ。 Damonはさらに， “WaterScrumFall&quot;についても言及した。これは開発チームがアジャイルであるにも関わらず，その上流と下流，つまり経営陣と運用側が従来の業務スタイルを踏襲している状況を表すことばだ。DevOpsはこの思考ラインを打破し，参画者すべてが同じ価値の流れに身を置くために生まれたものなのだ。</p> 
 </div> 
</div><br><br><br><br><br><br></body></html>