<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Entrega Contínua aumenta a velocidade de inovação</h3><p>A Thoughtworks publicou recentemente um documento, <a href="http://www.thoughtworks-studios.com/register?destination=node/10946">incluindo um modelo de maturidade para a entrega cont&iacute;nua</a> como uma resposta &agrave; pesquisa que indica que a maioria das empresas entendem a import&acirc;ncia da inova&ccedil;&atilde;o, mas n&atilde;o s&atilde;o capazes de entregar software de forma r&aacute;pida o suficiente para atender as necessidades de seus l&iacute;deres empresariais.</p> 
<p>Com este documento, a Thoughtworks pretende que as empresas <a href="http://consultantsmind.com/2012/07/01/maturity-model/">utilizem este modelo de maturidade para identificar lacunas</a> em seus processos assim como identificar ferramentas para que possam se concentrar em melhorar essas &aacute;reas. Eles acreditam que a entrega cont&iacute;nua &eacute; a solu&ccedil;&atilde;o para melhorar a produtividade do desenvolvimento de software, a ponto de exceder as expectativas e, por sua vez criar compet&ecirc;ncias dentro dos departamentos de tecnologia, para que possam desempenhar um papel cr&iacute;tico na dire&ccedil;&atilde;o estrat&eacute;gica de suas empresas. Os seguintes n&iacute;veis e os resultados s&atilde;o explicados em detalhe no documento:</p> 
<ul> 
 <li>5: Otimizando - a capacidade de <a href="http://www.startuplessonslearned.com/2009/06/why-continuous-deployment.html">entregar continuamente</a> possibilita a inova&ccedil;&atilde;o e a experimenta&ccedil;&atilde;o de novos neg&oacute;cios</li> 
 <li>4: quantitativamente gerenciado - O software est&aacute; sempre dispon&iacute;vel para libera&ccedil;&atilde;o de vers&atilde;o. O timebox de determinada vers&atilde;o do software (tempo necess&aacute;rio para entregar uma vers&atilde;o do software) &eacute; bem definido e igual ou inferior a necessidade do neg&oacute;cio.</li> 
 <li>3: definido - O timebox de determinada vers&atilde;o do software &eacute; bem definido, mas a dura&ccedil;&atilde;o desde o in&iacute;cio da ideia at&eacute; alcan&ccedil;ar a vers&atilde;o de produ&ccedil;&atilde;o &eacute; maior do que a necessidade do neg&oacute;cio.</li> 
 <li>2: gerenciado - O timebox de determinada vers&atilde;o do software &eacute; bem definido, mas a dura&ccedil;&atilde;o desde o in&iacute;cio da ideia at&eacute; alcan&ccedil;ar a vers&atilde;o de produ&ccedil;&atilde;o &eacute; maior do que a necessidade do neg&oacute;cio.</li> 
 <li>1: inicial - Implementa&ccedil;&otilde;es Ad hoc, ou seja, constru&iacute;das para uma finalidade espec&iacute;fica do neg&oacute;cio</li> 
</ul> 
<p>O modelo de maturidade &eacute; dividido em cinco n&iacute;veis. As empresas que n&atilde;o conseguem ultrapassar o n&iacute;vel 4 ser&atilde;o fortemente pressionadas a entregar inova&ccedil;&atilde;o em um ritmo aceit&aacute;vel. Muitas empresas que operam no n&iacute;vel 3 ou abaixo dele nunca conseguir&atilde;o acompanhar as demandas almejadas pelos l&iacute;deres empresariais e do mercado.</p> 
<p>A Thoughtworks fez uso da orienta&ccedil;&atilde;o da consultoria Forrester para realizar pesquisas para o seu documento t&eacute;cnico, e isto incluiu a avalia&ccedil;&atilde;o de 325 profissionais das &aacute;reas de neg&oacute;cio e TI.</p> 
<p>Informa&ccedil;&otilde;es adicionais para ajudar a preencher as lacunas identificadas atrav&eacute;s do uso deste modelo de entrega cont&iacute;nua podem ser encontradas no InfoQ. Um modelo para auxiliar na <a href="http://www.infoq.com/articles/Continuous-Delivery-Maturity-Model;jsessionid=CFA606E841ECCD1B4CC126FCB5FF00FC">ado&ccedil;&atilde;o de entrega cont&iacute;nua</a> foi publicado no in&iacute;cio deste ano. Jez Humble, um dos principais consultores da ThoughtWorks, recentemente falou sobre os <a href="http://www.infoq.com/presentations/Adopting-Continuous-Delivery;jsessionid=CFA606E841ECCD1B4CC126FCB5FF00FC">fatores mais importantes na implementa&ccedil;&atilde;o da entrega cont&iacute;nua</a>.</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>