<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Microsoft prevê um sistema operacional único para dispositivos móveis e sensores</h3><p>Durante a confer&ecirc;ncia <a href="http://www.ubs.com/global/en/investment-bank/key-investor-conferences/global/_jcr_content/par/accordionbox_12/linklist_4/link.1319112588.file/bGluay9wYXRoPS9jb250ZW50L2RhbS9JbnZlc3RtZW50QmFuay9kb2N1bWVudHMvY29uZmVyZW5jZXMvR1RDLUZpbmFsLUFnZW5kYS0xMS0xOC0xMy5wZGY=/GTC-Final-Agenda-11-18-13.pdf">UBS Global Technology</a> que ocorreu em novembro, Julie Larson-Green, vice-presidente executiva da divis&atilde;o Devices and Studios da Microsoft, discutiu a abordagem que a empresa est&aacute; levando para o mercado de software, expondo a vis&atilde;o interna da empresa, especialmente sobre o espa&ccedil;o ocupado por sistemas operacionais de dispositivos m&oacute;veis. Foram selecionados os fragmentos mais interessantes da transcri&ccedil;&atilde;o desta palestra (<a href="http://view.officeapps.live.com/op/view.aspx?src=http://www.microsoft.com/investor/downloads/events/UBS_LarsonGreen.docx">HTML</a>, <a href="http://www.microsoft.com/investor/downloads/events/UBS_LarsonGreen.docx">DOCX</a>).</p>
<p>Ao responder questionamentos sobre a Microsoft estar &quot;muitos passos atr&aacute;s&quot; no mercado m&oacute;vel, Larson-Green reconheceu que a <a href="http://www.infoq.com/news/2013/07/microsoft-reorganization">&uacute;ltima grande reorganiza&ccedil;&atilde;o da empresa</a> que come&ccedil;ou em Julho deste ano foi motivada justamente pelo atraso da companhia em rela&ccedil;&atilde;o aos seus concorrentes. A Microsoft est&aacute; determinada a estar fortemente presente e ativa no mercado m&oacute;vel por consider&aacute;-lo &quot;algo que afeta uma parte enorme do modo como as pessoas vivem, trabalham e interagem hoje em dia&quot;.</p>
<p>Ao falar sobre a eminente aposentadoria de Steve Ballmer, Larson-Green tentou minimizar a impress&atilde;o de que a empresa n&atilde;o possu&iacute; um direcionamento claro:</p>
<blockquote> 
 <p>Trabalhamos como uma equipe gerencial, ent&atilde;o n&atilde;o somos dependentes de um &uacute;nico tomador de decis&otilde;es, posso dizer que h&aacute; um esfor&ccedil;o em nosso grupo para que trabalhemos juntos no planejamento e direcionamento do roadmap dos produtos que desejamos fornecer aos nossos clientes em seus dispositivos que, acreditamos, as pessoas precisam e querem. Ent&atilde;o, isso (a sa&iacute;da de Ballmer) n&atilde;o nos atrapalhou de modo algum.</p> 
</blockquote>
<p>Enquanto a Microsoft parece estar a todo vapor buscando alcan&ccedil;ar a concorr&ecirc;ncia no mercado m&oacute;vel, Larson-Green ainda v&ecirc; futuro no seu sistema operacional para desktops:</p>
<blockquote> 
 <p>Acredito que ainda existir&aacute; por um longo tempo, pelo menos durante minha vida, computadores desktop nos quais as pessoas executam movimentos precisos com o mouse e teclado e que s&atilde;o moldados pensando em alta produtividade.</p> 
</blockquote>
<p>apesar desta declara&ccedil;&atilde;o, parece que o foco est&aacute; de fato nos dispositivos em que o Windows &eacute; executado:</p>
<blockquote> 
 <p>algo no seu pulso, ou em sua cabe&ccedil;a, ou em seu bolso que permite a intera&ccedil;&atilde;o para ler seus e-mails, receber notifica&ccedil;&otilde;es, acessar dados corporativos que s&atilde;o necess&aacute;rios para o seu trabalho, al&eacute;m de tamb&eacute;m interagir com seus amigos e fam&iacute;lia.</p> 
</blockquote>
<p>Referenciando inova&ccedil;&otilde;es passadas como o primeiro iPhone da Apple e sua interface de toque, Larson-Green acredita que o Kinect ir&aacute; desempenhar papel similar em um futuro pr&oacute;ximo:</p>
<blockquote> 
 <p>Haver&aacute; outro ponto de inflex&atilde;o que ser&aacute; fruto do modelo de entrada (input) de hardware. &Eacute; por esta raz&atilde;o que criamos produtos como o Kinect, baseado em gestos. &Eacute; poss&iacute;vel fazer coisas com a voz. J&aacute; h&aacute; algo vindo nesta dire&ccedil;&atilde;o unindo diversos tipos de intera&ccedil;&atilde;o. Quero dizer: fomos os primeiros a vir com a ideia de tablets, mas a tecnologia ainda n&atilde;o estava dispon&iacute;vel que os pudesse tornar realmente m&oacute;veis ao ponto de poder carreg&aacute;-los por a&iacute; com facilidade. A ideia do tablet permite fazer anota&ccedil;&otilde;es e estar sempre dispon&iacute;vel sem estar preso em um dispositivo de quase tr&ecirc;s quilos, mas que gra&ccedil;as &agrave; evolu&ccedil;&atilde;o hoje &eacute; uma pe&ccedil;a leve e fina. Ent&atilde;o todos estes elementos est&atilde;o se juntando e acreditamos que a cola seja o modelo de intera&ccedil;&atilde;o/experi&ecirc;ncia do usu&aacute;rio, este ponto de inflex&atilde;o vir&aacute; pelo hardware, que &eacute; a raz&atilde;o pela qual estamos investindo em dispositivos.</p> 
</blockquote>
<p>N&atilde;o apenas smartphones e tablets estar&atilde;o envolvidos neste processo, mas um mundo de sensores:</p>
<blockquote> 
 <p>Ent&atilde;o os sensores se tornar&atilde;o uma grande parte do modo como se pensa sobre as coisas. Algumas das coisas sobre as quais estamos falando a respeito − como estes aparelhos de gin&aacute;stica que as pessoas usam em seus pulsos que fazem algumas coisas bem interessantes. Qual a extens&atilde;o daquilo? Quais s&atilde;o os sensores e as coisas que poder&atilde;o construir e nos ajudar em nossa vida di&aacute;ria, desde nos informar que as flex&otilde;es de bra&ccedil;o n&atilde;o est&atilde;o t&atilde;o boas quanto imaginavamos at&eacute; informar que o batimento card&iacute;aco est&aacute; alto demais e precisa relaxar, respirar fundo, at&eacute; mesmo informar que seu &ocirc;nibus est&aacute; atrasado.</p> 
 <p>Ent&atilde;o h&aacute; um monte de coisas que podemos fazer mudando a maneira como pensamos no modo como as pessoas interagem com a tecnologia. Assim como o mouse foi uma inven&ccedil;&atilde;o, o toque foi uma inven&ccedil;&atilde;o, haver&aacute; novos modos que usaremos para interagir com nossos dispositivos e &eacute; por esta raz&atilde;o que temos focado tanto em interfaces de usu&aacute;rio mais naturais.</p> 
</blockquote>
<p>E para isto ser&aacute; necess&aacute;rio um novo n&iacute;vel de intera&ccedil;&atilde;o com os aplicativos:</p>
<blockquote> 
 <p>Acredito que conectando aplicativos entre si, porque muitas coisas possuem prop&oacute;sitos especiais, ser&aacute; poss&iacute;vel ver novas maneiras de integrar aplica&ccedil;&otilde;es. Acredito que h&aacute; muito o que vir desta rede de informa&ccedil;&atilde;o inteligente sobre a pessoa e sua localiza&ccedil;&atilde;o.</p> 
</blockquote>
<p>N&atilde;o podemos deixar de imaginar como os m&uacute;ltiplos sistemas operacionais da Microsoft − Windows, Windows RT, Windows Phone − se encaixar&atilde;o neste mundo insinuado por Larson-Green. Sem entrar em detalhes, ela tornou bastante claro que:</p>
<blockquote> 
 <p>N&atilde;o teremos tr&ecirc;s sistemas operacionais. Acreditamos em um mundo no qual exista um sistema operacional mais m&oacute;vel que consiga superar as limita&ccedil;&otilde;es da vida da bateria e dos problemas de seguran&ccedil;a. O custo desta supera&ccedil;&atilde;o ser&aacute; a diminui&ccedil;&atilde;o da flexibilidade. Ent&atilde;o acreditamos nesta vis&atilde;o e continuaremos trilhando por este caminho.</p> 
</blockquote>
<p>As preocupa&ccedil;&otilde;es como a dura&ccedil;&atilde;o de bateria, seguran&ccedil;a e a perda da flexibilidade sugerem que a Microsoft escolheu o Windows RT como o futuro a ser seguido por seus sistemas operacionais voltados para computadores desktop e dispositivos. (Claro, tamb&eacute;m existir&aacute; o Windows Server para o back-end e nuvem, mas esta &eacute; outra hist&oacute;ria.) Informa&ccedil;&otilde;es sobre esta <a href="http://www.infoq.com/news/2011/01/Will-Microsoft-Unify-OSes">unifica&ccedil;&atilde;o de sistemas operacionais</a> come&ccedil;ou a aparecer em 2011, inicialmente negadas pela Microsoft, mas <a href="http://www.infoq.com/news/2012/06/Windows-Phone-8">reiteradas um ano depois</a>, e refor&ccedil;adas pela recente <a href="http://www.infoq.com/news/2013/11/Store-Unification">consolida&ccedil;&atilde;o das lojas de aplicativos para Windows e Windows Phone</a>.</p><br><br><br><br><br><br></body></html>