<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>BizTalk Servicesのリリースが告げる，Mirosoft統合プラットフォームの"クラウドファースト”転向</h3><p><a target="_blank" href="http://www.infoq.com/news/2013/11/biztalk-services-released"><em>原文(投稿日：2013/11/26)へのリンク</em></a></p>
<div class="article_page_left news_container text_content_container"> 
 <div class="text_info"> 
  <p>長く続いたインキュベーション期間を経て，Microsoftは，Windows Azure BizTalk Servicesと名付けたクラウドベースの統合ツールをリリースした。オンプレミスの統合ツールへの取り組みについて繰り返し強調している同社は，しかしながらイノベーションの推進においてはクラウドプラットフォームを優先する，と述べている。</p> 
  <p>Microsoft副社長のScott Guthrie氏は，<a href="http://weblogs.asp.net/scottgu/archive/2013/11/21/windows-azure-general-availability-release-of-biztalk-services-traffic-manager-azure-ad-app-access-xamarin-support-for-mobile-services.aspx" target="_blank">先週のブログ記事</a>で，Windows Azure BizTalk ServicesのGA(General Availability)について発表した。その中核となるEAIとB2Bのユースケースとして氏が挙げたのは，クラウドにホストされたメッセージングエンジンを必要とする企業だ。</p> 
  <blockquote> 
   <p>Windows Azure BizTalk Servicesは，サプライチェーンやクラウドベースのEDI，あるいは企業アプリケーション統合といった強力なビジネスシナリオを，すべて慣れ親しんだツールセットとエンタープライズレベルの信頼性をもって実現します。パートナ間でのEDI接続の管理に加えて，オンプレミス設備とのEAIブリッジ設定 – オンプレミスのSAP, SQL Server, Oracle, Siebelシステムとの統合サポートを含みます – も，組み込みでサポートしています。また必要に応じて，Windows Azure BizTalk ServicesをオンプレミスのBizTals Server環境と統合することも可能です。これによって，強力なハイブリッドエンタープライズソリューションが実現します。</p> 
  </blockquote> 
  <p>リリースされた製品には一連の入出力アダプタ，&quot;ブリッジ&quot;と呼ばれる実行可能なメッセージングモデル，取引先管理用ポータル，統合アプリケーションをスケーリングするためのインフラストラクチャが含まれている。開発者はMicrosoft Visual Studio上でメッセージングソリューションを構築して，実行時にコンポーネントをWindows Azureにデプロイする。サブスクリプションサービスにはDevelopers, Basic, Standard, Premiumという<a href="http://www.windowsazure.com/en-us/manage/services/biztalk-services/editions-chart/" target="_blank">４つのエディション</a>がある。Developer Edition – MSDN購入者への特典と連携している – では，スケールおよびバックアップソリューションを除く，サービスのコア機能をすべて利用可能である。それ以外のエディションでは，さらに &quot;スケールユニットV，オンプレミス接続の拡張，バックアップおよびリストア機能，データアーカイブなどの機能がサポートされる。価格はDeveloper Editionの時間あたり0.13ドルから，Premium Editionの時間あたり(１ユニット)8.06ドルまでとなっている。</p> 
  <p>当初<a href="http://www.infoq.com/news/2012/01/azure-eai" target="_blank">Windows Azure Service Bus EAI Labsという名称で，2011年にプレビューが発表された</a> BizTalk Serviceは，従来からのオンプレミス統合製品であるMicrosoft <a href="http://www.microsoft.com/en-us/biztalk/default.aspx" target="_blank">BizTalk Server</a>とはあまり関連性を持っていない。名前こそ同じだが，クラウドサービスに含まれるのはBizTalk Server機能の小規模なサブセットのみであり，一方で構築されたソリューションは他方では実行できない。それでもシアトルで<a href="http://blogs.biztalk360.com/whats-the-story-from-biztalk-integration-summit-2013-seattle/" target="_blank">先週開催されたBizTalk Summit</a>でMicrosoftは，オンプレミス製品と同等の機能をBizTalk Seviceでも段階的に提供していくという，積極的なプランを打ち出した。当面については，新たなアダプタを導入することでギャップを埋められるという期待から，サードパーティによるアダプタ開発を容易にするため，B2BシナリオにEDIFACTサポートを追加している。将来的にはもっと大がかりな機能として，永続的ワークフローコンポーネント，ビジネスプロセスデザイナ，ルールデザイナ，ビジネスアクティビティ監視，管理機能の強化などが考えられている。</p> 
  <p>MicrosoftはBiziTalk Servicesについて，少なくとも３ヶ月に１回のアップデートを予定している。BizTalk Serverのメジャーバージョンが２年に１度のペースで更新されているのとは対照的だ。同社では新しいテクノロジについて，まずクラウドサービスにプッシュされた上で，その後段階的にオンプレミス製品に展開していく，と述べている。BizTalk Servicesに関する詳細は<a href="http://www.windowsazure.com/en-us/documentation/services/biztalk-services/" target="_blank">製品紹介ページ</a>で見ることができる。サービスの体験には<a href="http://www.microsoft.com/en-us/download/details.aspx?id=39087" target="_blank">開発用SDKをダウンロード</a>してほしい。</p> 
 </div> 
</div><br><br><br><br><br><br></body></html>