<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>EC2でMesosによるクラスタの自動デプロイを実現するElastic Mesos</h3><p><a target="_blank" href="http://www.infoq.com/news/2013/12/elastic-mesos"><em>原文(投稿日：2013/12/17)へのリンク</em></a></p>
<div class="article_page_left news_container text_content_container"> 
 <div class="text_info"> 
  <p>EC2上でApache Mesosの自動デプロイが可能になった。Apache Mesosはクラスタのリソース全体を，複数のデータ処理フレームワークで共有するオープンソースツールである。使用されているのは，ビッグデータの新興企業<a href="http://mesosphere.io/">Mesosphere</a>が提供する<a href="http://mesosphere.io/2013/11/13/elastic-mesos/">Elastic Mesos</a>という，新しいWebサービスだ。</p> 
  <p>このサービスは，ZookeeperやHDFSなどといったMesosが扱うものを，すべてAmazon EC2インスタンスに対してインストールして，即時運用可能なクラスタを提供してくれる。その意味では，<a href="http://aws.amazon.com/elasticmapreduce/">AmazonのElastic MapReduce</a>と本質的には類似している。しかもその上，Elastic Mesosに関する費用はまったく必要ない。ユーザはEC2の使用料のみ負担すればよいのだ。Elastic Mesosでは現在，提供リージョンをus-east-1に限定した上で，提供クラスタのサイズを<a href="https://aws.amazon.com/ec2/pricing/#onDemandTabs">オンデマンドインスタンス価格</a>別に，6ないし18の m1.largeインスタンスからなる構成のみとしている。</p> 
  <p>Mesosクラスタのデプロイは<a href="https://elastic.mesosphere.io/">Elastic Mesos UI</a>を通じて行うことができる。必要なクラスタサイズの指定，EC2認証の設定，通知用Eメールアドレスの設定，という３つのステップを実行するだけで，その他には何も必要ない。所要時間はEC2インスタンスのプロビジョニング時間によってまちまちだが，Meosphereでは目安として，クラスタ設定完了まで20分程度という時間を公表している。</p> 
  <p>Mesosは当初，カリフォルニア大学バークレー校で<a href="http://www.cs.berkeley.edu/~matei/papers/2011/nsdi_mesos.pdf">研究プロジェクトとして</a>開発された。その後Twitterの手で，同社の爆発的な拡大に対処するための機能を完備したプラットフォームへと変化した。Twitterの技術担当副社長であるChristopher Fry氏が “<a href="http://www.wired.co.uk/news/archive/2013-11/26/qa-with-chris-fry">Twitter版のEC2</a>” とも表するMesosは現在，<a href="http://mesos.apache.org/">Apacheのトップレベルプロジェクト</a>でもある。Mesosphereの創設者であるFlo Leibert氏とTobi Knaup氏は以前，TwitterとAriBnbで働いていた。両社がMesosの最大ユーザであることを考えれば，MesosphereがMesos関連製品を開発することは理にかなった選択だ。毎月拡大する<a href="http://mesos.apache.org/documentation/latest/powered-by-mesos/">Mesosユーザのリスト</a>を見れば，両社以外にもVimeoやOpenTableなどのビッグネームに加えて，バークレー校でも現在はMesosを採用していることが分かる。</p> 
  <p>Elastic Mesosは<a href="http://whirr.apache.org/">Apache Whirr</a>と類似している。Apache Whirrはクラウド上のサービスの実行と管理を行うオープンソースライブラリであるが，<a href="https://issues.apache.org/jira/browse/WHIRR-121">Mesosをサポートしていない</a>。さらにはElastic Mesosが自己完結型サービスであるのに対して，Whirrはクラスタのライフサイクル全般において，システム管理者による関与をより重要視しているという違いがある。</p> 
  <p>今回の動きは，これまでHadoopの<a href="http://hadoop.apache.org/docs/current/hadoop-yarn/hadoop-yarn-site/YARN.html">YARN</a>と混同されることの多かったMesosにとって，採用の主流へと向かう上での貴重な一歩になる。クラスタを効果的かつシームレスに共有するという目標は共通だが，Hadoop 2のスケジューラのデファクトとなったYARNの方が，普及率でははるかに先行する形となっている。</p> 
  <p>Twitterでのコミュニティの反応は概ね良好ではあるが，採用が進むかどうかは今後を見なければならない。すでに<a href="http://spark-summit.org/talk/nathan-spark-on-elastic-mesos-for-enterprise-use-cases/">2013年12月のSpark Summit</a>では，Elastic MesosでSparkを実行するためのチュートリアルが実施されて，Sparkコミュニティから好評を得ている。</p> 
 </div> 
</div><br><br><br><br><br><br></body></html>