<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Chef Sugar ajuda a melhorar a experiência de autoria de receitas do Chef</h3><p>O Chef Sugar fornece m&eacute;todos DSL em diversas &aacute;reas, tais como computa&ccedil;&atilde;o em nuvem (ex., cloud, ec2) ou plataforma (ex., ubuntu, centos). Existem discuss&otilde;es em andamento para incluir m&eacute;todos auxiliares. No seu artigo, Seth mostra um exemplo que contrasta uma receita que faz uso do Chef Sugar com outra que n&atilde;o. Essa receita:</p>
<blockquote> 
 <p><span>include_recipe 'cookbook::_windows_setup' if platform_family?('windows') <br /> include_recipe 'cookbook::_ec2_setup' if node['ec2'] || node['eucalyptus'] <br /> <br /> package 'foo' do <br /> action :nothing <br /> end.run_action(:install) <br /> <br /> execute 'untar package' do <br /> if node['kernel']['machine'] == 'x86_64' <br /> command 'ARCH_FLAGS=x64 make' <br /> else <br /> command 'ARCH_FLAGS=i386 make' <br /> end <br /> not_if do <br /> ::File.exists?('/bin/tool') &amp;&amp; <br /> ::File.executable?('/bin/tool') &amp;&amp; <br /> shell_out!('/bin/tool --version').stdout.strip == node['tool']['version'] <br /> end <br /> end <br /> <br /> credentials = Chef::EncryptedDataBagItem.load('accounts', 'passwords')</span></p> 
</blockquote>
<p>pode ser transformada na seguinte receita:</p>
<blockquote> 
 <p><span>include_recipe 'cookbook::_windows_setup' if windows? <br /> include_recipe 'cookbook::_ec2_setup' if ec2? || eucalyptus? <br /> <br /> compile_time do <br /> package 'apache2' <br /> end <br /> <br /> execute 'untar package' do <br /> if _64_bit? <br /> command 'ARCH_FLAGS=x64 make' <br /> else <br /> command 'ARCH_FLAGS=i386 make' <br /> end <br /> not_if { installed_at_version?('/bin/tool', node['tool']['version']) } <br /> end <br /> <br /> credentials = encrypted_data_bag_item('accounts', 'passwords') </span></p> 
</blockquote>
<p>O Chef Sugar foi escrito intencionalmente para ser acessado de dentro de uma receita, mas tamb&eacute;m como uma <a href="http://www.google.com/url?q=http%3A%2F%2Fdocs.opscode.com%2Fessentials_cookbook_libraries.html&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNFvRMdUE694MRj2tZskhIuBoKPGng">biblioteca do Chef</a>, o conceito que permite a inclus&atilde;o de um c&oacute;digo Ruby em um cookbook. A &uacute;nica diferen&ccedil;a significante &eacute; que quando usado como uma biblioteca, os m&eacute;todos do Chef Sugar recebem um objeto node como par&acirc;metro:</p>
<p><span># cookbook/libraries/default.rb <br /> def only_on_windows(&amp;block) <br /> yield if Chef::Sugar::PlatformFamily.windows?(@node) <br /> end</span></p>
<p><strong>InfoQ.com: O a&ccedil;&uacute;car sint&aacute;tico &eacute; visto as vezes como algo sup&eacute;rfluo e menos importante.</strong> <strong>Uma vez que</strong> <strong>voc&ecirc; criou um projeto chamado Chef Sugar, voc&ecirc; claramente n&atilde;o pensa que esse &eacute; sempre o caso. Quando voc&ecirc; acha que um pouco de a&ccedil;&uacute;car sint&aacute;tico &eacute; bom e quando &eacute; demais?</strong></p>
<blockquote> 
 <p><strong>Vargo</strong>: Eu acho que a&ccedil;&uacute;car sint&aacute;tico &eacute; uma das principais raz&otilde;es do Ruby (e Rails) ter se tornado um sucesso entre os desenvolvedores. Por exemplo, ActiveSupport &eacute; um a&ccedil;&uacute;car para a classe Integer que permite chamar m&eacute;todos como 5.days.ago. A&ccedil;&uacute;car sint&aacute;tico &eacute; inacreditavelmente usado para reduzir a complexidade e a repeti&ccedil;&atilde;o. Muitos cookbooks compartilham idiomas ou padr&otilde;es comuns - como verificar se o peda&ccedil;o de um software est&aacute; instalado em uma vers&atilde;o em particular. Quando eu vejo esse tipo de padr&atilde;o aparecendo, eu sei que &eacute; hora de aplicar um pouco de a&ccedil;&uacute;car.</p> 
 <p>Por outro lado, eu n&atilde;o buscava, e n&atilde;o busco, ativamente &aacute;reas para &quot;a&ccedil;ucarar&quot;. Eu acho que isso &eacute; um equ&iacute;voco feito com frequ&ecirc;ncia. Na minha opini&atilde;o, o a&ccedil;&uacute;car foi muito longe quando existem mais que dois ramos de l&oacute;gica ou componentes. Por exemplo, algu&eacute;m pode facilmente escrever um a&ccedil;&uacute;car sint&aacute;tico que encapsula um grupo de l&oacute;gica e recursos, mas isso serve melhor como uma biblioteca ou <a href="http://www.google.com/url?q=http%3A%2F%2Fdocs.opscode.com%2Flwrp.html&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNFQuKKav0p8MwkUOMOXhTODA2D1iA">LWRP</a>. A&ccedil;&uacute;cares devem ser facilmente test&aacute;veis e manuten&iacute;veis, e desenvolvedores iniciantes devem ser capazes de dissecar o m&eacute;todo que define o a&ccedil;&uacute;car sint&aacute;tico.</p> 
</blockquote>
<p><strong>InfoQ.com: Voc&ecirc; acredita que, em geral, esse tipo de funcionalidade deve estar dispon&iacute;vel no n&uacute;cleo da aplica&ccedil;&atilde;o ou &eacute; melhor t&ecirc;-las como extens&otilde;es? Por que?</strong></p>
<blockquote> 
 <p><strong>Vargo</strong>: Eu acredito fortemente no padr&atilde;o de arquitetura plug&aacute;vel. Eu poderia facilmente ter inclu&iacute;do Chef Suger no n&uacute;cleo do Chef, mas tomei a decis&atilde;o consciente de mant&ecirc;-lo isolado. Assim como um desenvolvedor n&atilde;o deve ser obrigado a usar o ActiveSupport, um desenvolvedor Chef n&atilde;o deve ser obrigado a usar Chef Sugar.</p> 
 <p>Do ponto de vista de manutenibilidade, tendo o Chef Sugar como uma gem separada me permite trabalhar e iterar de forma independente do ciclo de versionamento do Chef. O Ruby mesmo est&aacute; usando esse formato plug&aacute;vel, migrando classes principais do para gems com mantenedores individuais. Rubinius 2.0 &eacute; inteiro composto de gems. Assim como existem vantagens em ter um sistema distribu&iacute;do ao inv&eacute;s de uma aplica&ccedil;&atilde;o monol&iacute;tica, essas vantagens est&atilde;o presentes quando usando um componente plug&aacute;vel ao inv&eacute;s de construir o componente no n&uacute;cleo do framework. Esse padr&atilde;o tamb&eacute;m est&aacute; presente em ferramentas como Vagrant Knife (a interface de linha de comando do Chef) ou RubyGems.</p> 
 <p><span>ERROR: While executing gem ... (Gem::InstallError) <br /> gem &quot;bigdecimal&quot; cannot be uninstalled because it is a default gem <br /> </span></p> 
 <p>Existe, por&eacute;m, um meio termo no qual o componente plug&aacute;vel &eacute; empacotado junto de uma vers&atilde;o espec&iacute;fica do n&uacute;cleo (como uma depend&ecirc;ncia), mas continua a existir fora do framework como um recurso isolado. Os usu&aacute;rio podem atualiz&aacute;-los para a &uacute;ltima vers&atilde;o a qualquer momento ou esperar para atualizar o pacote inteiro. Ruby 2.0 segue esse padr&atilde;o. Tente desinstalar o bigdecimal e voc&ecirc; receber&aacute; o seguinte erro:</p> 
 <p><span>ERROR: While executing gem ... (Gem::InstallError) <br /> gem &quot;bigdecimal&quot; cannot be uninstalled because it is a default gem</span></p> 
 <p>Mas os desenvolvedores podem optar por atualizar o pacote para a &uacute;ltima vers&atilde;o a qualquer hora.</p> 
 <p>Um &uacute;ltimo ponto a considerar, e que &eacute; sempre esquecido, est&aacute; relacionado &agrave;s implica&ccedil;&otilde;es de licenciamento. No caso do Chef Sugar, assim como o Chef, usa a licen&ccedil;a Apache 2.0, ent&atilde;o isso n&atilde;o &eacute; um problema. Mas em certos casos n&atilde;o &eacute; poss&iacute;vel incluir algum componente no n&uacute;cleo do aplicativo porque ele poderia impedir de revender, patentear (devido &agrave; restri&ccedil;&atilde;o imposta por algumas licen&ccedil;as), etc.</p> 
</blockquote>
<p><strong>InfoQ.com: Existe alguma outra parte do Chef que pode ser beneficiar dos m&eacute;todos adicionais do Chef Sugar?</strong></p>
<blockquote> 
 <p><strong>Vargo</strong>: Como eu disse antes, eu n&atilde;o procuro partes para &quot;a&ccedil;ucarar&quot;. Quando a primeira vers&atilde;o do Chef Sugar foi lan&ccedil;ada, havia uma imensa popularidade. Dentro de 20 minutos, um membro da comunidade a disponibilizou no FreeBSD. O projeto viveu ent&atilde;o por dois meses sem qualquer manuten&ccedil;&atilde;o (ele simplesmente funcionava). H&aacute; alguns meses atr&aacute;s algu&eacute;m adicionou o suporte no Cloudstack.</p> 
 <p>Eu tenho a tend&ecirc;ncia de me orgulhar pelo r&aacute;pido reconhecimento e fazer os merges solicitados, ent&atilde;o eu sempre encorajo as pessoas a submet&ecirc;-los. Eu tamb&eacute;m n&atilde;o tenho medo de dizer n&atilde;o quando um patch avan&ccedil;a al&eacute;m dos objetivos do projeto. Se um membro da comunidade v&ecirc; algo que pode ser &quot;a&ccedil;ucarado&quot;, eu fico contente em dar uma olhada.</p> 
</blockquote>
<p><strong>InfoQ.com: Quais s&atilde;o as partes mais importantes no Chef que podem ser beneficiar de um maior envolvimento da comunidade?</strong></p>
<blockquote> 
 <p><strong>Vargo</strong>: Todas as mudan&ccedil;as relacionadas ao Chef s&atilde;o controladas no <a href="https://www.google.com/url?q=https%3A%2F%2Ftickets.opscode.com%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNGDQbFk4wcaK8alcV9kBjlfz9PdGQ">Sistema de Gerenciamento de Mudan&ccedil;as do Chef</a>. A maioria das solicita&ccedil;&otilde;es est&atilde;o ordenadas por prioridade. Para novos membros, as solicita&ccedil;&otilde;es marcadas como &quot;trivial&quot; ou &quot;menor&quot; envolvem pequenas mudan&ccedil;as e s&atilde;o uma boa forma de mergulhar no n&uacute;cleo do Chef. E, por &uacute;ltimo, nunca subestime o poder das corre&ccedil;&otilde;es tipogr&aacute;ficas ou gramaticais. Como o Chef est&aacute; cada vez mais aumentando a sua popularidade, usu&aacute;rios de l&iacute;ngua n&atilde;o inglesa tamb&eacute;m devem ser capazes de ler a documenta&ccedil;&atilde;o.</p> 
 <p>Adicionalmente, h&aacute; um projeto aberto no GitHub para <a href="https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fopscode%2Fchef-rfc&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNHFViu3yf98_lh5dH_7RqxVZS2AJA">as RFCs do Chef</a>. Elas s&atilde;o propostas da comunidade para funcionalidades alto n&iacute;vel ou mudan&ccedil;as no roadmap. As solicita&ccedil;&otilde;es de mudan&ccedil;a de c&oacute;digo (pull request) naquele reposit&oacute;rio se beneficiam significativamente do envolvimento da comunidade (mesmo que seja algo extremamente pequeno).</p> 
 <p>Al&eacute;m do projeto central do Chef, foi anunciado no Chef Community Summit, em Novembro, algumas importantes mudan&ccedil;as no <a href="https://www.google.com/url?q=https%3A%2F%2Ftickets.opscode.com%2Fbrowse%2FCOOK&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNEmpFJLHB5fx2cU7YVCwYFqMteWZA">Projeto de Livro de Receitas</a> (receitas da comunidade que o Chef mant&eacute;m). O Chef est&aacute; em um processo de compartilhar as responsabilidades das <a href="http://www.google.com/url?q=http%3A%2F%2Fcommunity.opscode.com%2Fcookbooks&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNECKO5KuVQbC1SPkkWc5JWGOsqEfg">receitas</a> com os membros da comunidade.</p> 
 <blockquote> 
 </blockquote>
</blockquote><br><br><br><br><br><br></body></html>