<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Rocket to Mars: A Sprint Planning Game</h3><p>“Many team and their product owners believe that the team's unique job is to deliver more and more story points,&nbsp;but we&nbsp;consider this to be a complete misunderstanding of the relation between the team and the&nbsp;product owner”&nbsp;said Damien Thouvenin and Pierrick Revol. At the <a href="http://www.xpday.net/">XP Days Benelux 2013 conference</a>, Damien and Pierrick facilitated a sprint planning game for teams and product owners to learn about deciding to invest their sprint time&nbsp;to produce stories, investigate issues, reduce technical debt, or&nbsp;do&nbsp;training.&nbsp;</p>
<p>Rocket to Mars (v2) is a collaborative role playing game for Scrum product owners, their managers and the teams they work with to learn agile and lean planning practices. It is a board game played by teams who choose and adapt their strategy to build a rocket for the next mission to Mars. In the game they take decisions&nbsp;to do in-depth analysis or to start coding, develop expertise or generalist skills, and to refactor or finish user stories to burn down more story points. The aim of the game is to score the most points in 8 iterations, where team score points by finishing user stories but points are deducted when they have accumulated technical debt. The game is a successor of the <a href="http://www.agileplayground.org/gameorama/mission-to-mars-(en).aspx">Mission to Mars</a> game.</p>
<p>Initially team members are only skilled to do one activity, by doing training they can develop new skills. When team members have these skills they are able to do different activities and the team will become more&nbsp;multidisciplined and&nbsp;capable to do more work in an iteration.</p>
<p>This game is influenced by a talk by Prof Philippe Kruchten,&nbsp;covered on InfoQ in <a href="http://www.infoq.com/news/2010/05/what-color-backlog">what color is your backlog</a>, where he talks about key decisions that need to be made early that will set the scene for ongoing work. This talk explains that every sprint the team has to decide if they will work on delivering new functionality, solving bugs, or invest time in training. Damien and Pierrick&nbsp;showed how these decisions fall into 4 quadrants covering short-term vs. long-term effects (or visible&nbsp;and invisible effects) and producing up vs. preventing risks:</p>
<p><img src="http://www.infoq.com/resource/news/2013/12/rocket-to-mars-sprint-planning/en/resources/Rocket-toMars-4-quadrants.jpg" alt="" _href="img://Rocket-toMars-4-quadrants.jpg" _p="true" />Damian and Pierrick asked the teams what they have learned from playing the game. One team explained how they were hampered by illness, which caused their velocity to go down. There was not much that they&nbsp;felt that they could do to address that. Another team explained how&nbsp;investing early in training helped them to become faster in the next sprints. Other feedback received was that playing the game “showed the true value on investing in training and analysis”, “the game show the real life issues during sprints”, “gives a good view on the difference between sprint backlog and product backlog at sprint planning”, and “the game is a lot of fun, learned a lot”. &nbsp;</p>
<p>During the debriefing Damien explained how a strategy&nbsp;can look to deal with functionality, technical debt and training in the planning game:</p>
<blockquote> 
 <p>What people learn through the game is that the sprint planning should not be concerned only with how many user stories we can stack in the sprint backlog. The concern of the team and the PO should be to enable long running sustainability. Since there are no &quot;inter-sprint&quot; spaces, that means all those activities must take place during the sprint: reducing technical debt before it explodes and blocks you, investigating future stories or epics, grooming you backlog, exploring technical options for the next sprints, training people on technical or business subjects.</p> 
</blockquote>
<p>The conclusion from playing the game, as Damien stated, is&nbsp;that&nbsp;“the team and their product owners should have discussions about how they want the team to invest her sprint time: producing story points, investigating the next issues, killing debt, or&nbsp;do&nbsp;training”.</p><br><br><br><br><br><br></body></html>