<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Pair Coaching with Agile Teams</h3><p>Agile coaches can&nbsp;coach in pairs instead of coaching individually. Two coaches can&nbsp;collaboratively help individuals or teams to learn and improve when adopting agile.</p>
<p>Stephan Schwab wrote a&nbsp;blog post about the <a href="http://www.stephan-schwab.com/coaching/2013/09/12/risks-and-side-effects-of-agile-coaching.html">risk and side effects of agile coaching</a>. He described why people might feel threatened when a coach starts working with them:</p>
<blockquote> 
 <p>Going along with the way things are will most likely not help the client much. Something is about to be challenged the moment the coach shows up. It is inevitable that some change will happen. Were that not the case, nobody would call in a coach. Help cannot be provided by not touching anything at all.</p> 
 <p>So the coach will look around, turn over the proverbial stones, ask questions and highlight facts that are probably hiding in plain sight. People may have been talking in the hallway for some time already. That activity might be seen by some as sneaking around, as putting his nose into someone else’s business. Others may even perceive that activity as a threat.</p> 
</blockquote>
<p>He mentioned two sides that coaching should address. The combination of them can be challenging:</p>
<blockquote> 
 <p>In the case of an Agile Coach there is a technical and a psychological side. On the technical side, amongst other activities, new techniques are introduced, things are getting measured and made visible. On the psychological side, again amongst other activities, help to deal with the changes is offered. If the same person tries to introduce change and tries to help those affected by it to deal with it, it is highly likely that they will blame the coach instead of developing a trust relationship with him.</p> 
</blockquote>
<p>Stephen suggestion is to pair with two coaches:</p>
<blockquote> 
 <p>Pair coaching with a partner who never introduces any changes whatsoever might be a good solution to that problem. It is that person who has access to those feeling threatened. He can build up a trust relationship by being the only who always has an open ear, shows deep empathy and understands their concerns. But as he also understands the reasoning behind the changes being introduced by the other he can help <em>from the other side</em> to make the transition to a different mindset and to a different way of working successful.</p> 
</blockquote>
<p>In pair coaching two coaches work together when coaching individuals or teams. Each coach will focus on different aspects of coaching. As every coach has specific experience and skills they can complement each other. Pair coaching aims to increase the quality and value of the coaching delivered to the coachee.</p>
<p>Earlier InfoQ interviewed <a href="http://www.infoq.com/interviews/whelan-agile-coaching-lean-startup">Declan Whelan on agile coaching, lean startup and the agile alliance</a>. Declan explained in the interview why he prefers to do pair coaching:</p>
<blockquote> 
 <p>One thing that we stress is, if we are facilitating a session and one person can be really focused on facilitating that we are starting on time, we are ending on time, people are engaged and the other person can be making sure that the room is being well served - so one person focusing on content, another person more on the dynamics of the room.</p> 
</blockquote>
<p>Declan talked about how working in pairs helped him:</p>
<blockquote> 
 <p>(…) I found that other people are actually much better at reading people than I am, or I am focused on something else and they are noticing things that I am not noticing so the ‘aha’ moment has been really kind of having somebody really focused on trying to see the body language and who looks at who and all of that - subtle interactions that you might not notice as an individual because you are so just focused on, perhaps, some technical aspect or view - what’s a story point or something. I think as an individual, I have been really challenged with my own assumptions and my own weaknesses if you will, so having other coaches come up and say “Declan, let’s debrief that. Here’s some things I’ve noticed, did you think about this?” Its really raised the bar on my game having someone else, because a client won’t do that for you, or most won’t, right? But if you are paired up with another coach and you can have that safety then you can have those conversations, so I feel like it’s really improved my game.</p> 
</blockquote>
<p>Yves Hanoulle explained in the <a href="http://www.infoq.com/articles/agile-lean-mindset">InfoQ interview on the agile and lean mindset</a> how he pairs with employees of the companies that he works with:</p>
<blockquote> 
 <p>(…) I say that I want to coach with an internal person. I tell them: “I will coach that person, and I will teach that person a lot about scrum and agile and XP, and that person will teach me about your corporate culture and how things are done in your company”. In that sense we fill two different kinds of roles. (...) For me it’s important that I make sure that my knowledge stays in the company and pairing with somebody internally in the company makes sure that he grasps not just what I’m doing but also my intentions behind it.</p> 
</blockquote>
<p>Have you done pair coaching? Did it help you to adopt agile?</p><br><br><br><br><br><br></body></html>