<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>AppleのSwift言語を学ぶためのオンラインリソース</h3><p><a target="_blank" href="http://www.infoq.com/news/2014/06/apple-swift-learning-resources"><em>原文(投稿日：2014/06/05)へのリンク</em></a></p>
<div class="article_page_left news_container text_content_container"> 
 <div class="text_info"> 
  <p>AppleがOS XとiOSプラットフォームに向けての新言語Swiftを導入したことで、開発者コミュニティからの関心に火がついている。たった数日間で、<a href="http://stackoverflow.com/questions/tagged/swift-language">Stack Overflowではすでにほぼ500の質問があがっており</a>、<a href="https://github.com/search?q=language%3Aswift&amp;ref=cmdform">GitHubクエリ</a>によれば約350のSwiftで書かれたリポジトリができている。</p> 
  <p>この言語の学習に興味を持つ人向けに、インターネットにはスタート地点となる有用なリソースが提供されている:</p> 
  <ul> 
   <li> <p><strong>プログラミング言語Swift（The Swift Programming Language）</strong></p> <p>AppleはiTunes上で<a href="https://itunes.apple.com/us/book/swift-programming-language/id881256329?mt=11">電子書籍&quot;The Swift Language Reference&quot;</a>を無料で利用可能にした。iTunesにアクセスするためにはAppleデバイスが必要だが、他の人にもその言語を学ぶチャンスはある。実際、同じ内容がAppleウェブサイト上で<a href="https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/Swift_Programming_Language/">HTML形式</a>で利用可能である。この言語の新規性を考えれば、この電子書籍は確実に基本となるリソースであり、言語のすべての側面を、C/Objective-Cとの相互運用性も含めてカバーしている。</p> </li> 
   <li> <p><strong><a href="http://www.raywenderlich.com/73997/swift-language-highlights">Swift言語ハイライト（Swift Language Highlights）</a></strong></p> <p>RayWenderlich.comから出ているもので、Objective-C開発者の視点からSwiftで導入された新機能のいくつかについて紹介した短いプレゼンテーションである: <a href="http://ja.wikipedia.org/wiki/%E5%9E%8B%E6%8E%A8%E8%AB%96">型推論</a>、<a href="http://ja.wikipedia.org/wiki/%E3%82%B8%E3%82%A7%E3%83%8D%E3%83%AA%E3%83%83%E3%82%AF%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0">ジェネリクス</a>、switch文、定数性が紹介されている。</p> </li> 
   <li> <p><strong><a href="http://ios-blog.co.uk/tutorials/ios8-how-to-use-objective-c-classes-in-swift/">Swiftで Objective-Cクラスを使う方法（How to use Objective-C Classes in Swift）</a></strong></p> <p>Mark Petherbridge氏によるステップバイステップガイド。SwiftからObjective-Cを使えるようにするための<em>橋渡しヘッダ（bridging header）</em>の作るために、どう取り組むかについて記述したもの。</p> </li> 
   <li> <p><strong><a href="http://jamesonquave.com/blog/developing-ios-apps-using-swift-tutorial/">Swiftを使ってiOSアプリを開発する（Developing iOS Apps Using Swift）</a></strong></p> <p>Jameson Quave氏による、SwiftでゼロからiOSアプリを開発し始めるための5部シリーズのチュートリアル。このチュートリアルは次のトピックをカバーしている: &quot;hello world&quot;アプリの作成、ウェブAPIリクエストとそれによって得られるJSONのパース、プロトコルとデリゲートを使うベストプラクティス、インタラクティブテーブルビュー、非同期イメージロードとキャッシング。</p> </li> 
   <li> <p><strong><a href="http://www.learnswift.tips">Swift学習のコツ（LearnSwift.tips）</a></strong></p> <p>見る側のレベル（初心者、中級者、上級者）ごとにまとめられたSwift言語についての学習リソースのコレクション。GitHubの興味深いプロジェクトセレクションも含んでいる。</p> </li> 
   <li> <p><strong><a href="http://cdn2.raywenderlich.com/wp-content/uploads/2014/06/RW-Swift-Cheatsheet-0_3.pdf">Swift言語チートシート（Swift language cheat sheet）</a></strong></p> <p>RayWenderlich.comからのもう一つのリソースで、最も重要なSwiftの文法を1ページにまとめたもの。次をカバーしている: クラス実装、メソッド宣言、オブジェクトのインスタンス化と利用、変数宣言、制御フロー、文字列/配列/ディクショナリの簡単な例。</p> </li> 
   <li> <p><strong><a href="http://http://www.sososwift.com/">So So Swift</a></strong></p> <p>チュートリアル、動画、リポジトリを登場順に並べた巨大なコレクション。</p> </li> 
   <li> <p><strong><a href="https://raw.githubusercontent.com/densh/talks/master/swift-vs-scala-211-2014-06-03/Swift%20vs%20Scala%202.11.pdf">SwiftとScalaの比較表（Swift vs. Scala Comparison Sheet）</a></strong></p> <p>SwiftとScalaの文法を比較したもの。制御フロー構造、表現、宣言、パターン、型を含む。</p> </li> 
   <li> <p><strong><a href="https://raw.githubusercontent.com/densh/talks/master/swift-vs-scala-211-2014-06-03/Swift%20vs%20Scala%202.11.pdf">SwiftLang.eu</a></strong></p> <p>Swiftリソースを集めたもう1つのサイト。Appleの&quot;The Swift Programming Language Book&quot;をMOBI、PDF、ePub形式で提供している。さらに、開発者が考えやソースコードを共有するためのコミュニティセクションも提供している。</p> </li> 
  </ul> 
  <p>この言語を導入した背景やLLVMとの関係については<a href="http://www.infoq.com/jp/news/2014/06/apple-swift">InfoQ上のこのAlex Blewitt氏の投稿</a>も参照のこと。</p> 
  <p>Swiftは現在、すべての<a href="https://developer.apple.com/devcenter/ios/index.action">Appleデベロッパプログラムに登録した開発者</a>に向けてAppleが公開したXcode 6 developer preview内のみで利用可能である。</p> 
 </div> 
</div><br><br><br><br><br><br></body></html>