<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Apple oferece microsite para design de interface do usuário para iOS7</h3><p>A Apple est&aacute; oferecendo aos desenvolvedores iOS registrados um <a href="https://developer.apple.com/design/">novo microsite</a> com uma cole&ccedil;&atilde;o de v&iacute;deos, documentos e artigos t&eacute;cnicos sobre design de interface de usu&aacute;rio para iOS 7. O novo site visa oferecer ao desenvolvedor a informa&ccedil;&atilde;o necess&aacute;ria &quot;para criar aplicativos refinados, envolventes e intuitivos para iOS 7.&quot;</p>
<p>O site re&uacute;ne alguns documentos fundamentais para o desenvolvimento iOS, incluindo:</p>
<ul> 
 <li><a href="https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/">Guia de Interface Humana do iOS</a>, que foi completamente reformulado para levar em conta o novo paradigma de interface de usu&aacute;rio do iOS7;</li> 
 <li><a href="https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/TransitionGuide/">Guia de transi&ccedil;&atilde;o de interface de usu&aacute;rio do iOS 7</a>, resumindo todas as mudan&ccedil;as visuais introduzidas no iOS 7, como por exemplo, bot&otilde;es sem bordas, barras transl&uacute;cidas, e layouts em tela cheia para views;</li> 
 <li><a href="https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/UIKitUICatalog/">Cat&aacute;logo de interface de usu&aacute;rio UIKit</a>, um cat&aacute;logo com os elementos de interface de usu&aacute;rio utilizados em aplicativos iOS e um guia de como configur&aacute;-los;</li> 
 <li><a href="https://developer.apple.com/design/tips/">Recomenda&ccedil;&otilde;es no design de interface dos usu&aacute;rios</a>, uma cole&ccedil;&atilde;o de dicas organizadas em quatro categorias: interatividade, legibilidade, gr&aacute;ficos e clareza.</li> 
</ul>
<p>Al&eacute;m disso, o site lista uma sele&ccedil;&atilde;o de v&iacute;deos da <a href="https://developer.apple.com/wwdc/">Confer&ecirc;ncia Apple World Wide Developer de 2013</a> ou <a href="https://developer.apple.com/tech-talks/">palestras t&eacute;cnicas</a> que s&atilde;o consideradas particularmente relevantes no contexto do design da interface de usu&aacute;rio para o iOS 7:</p>
<ul> 
 <li><a href="https://developer.apple.com/wwdc/videos/?id=208">O que h&aacute; de novo no design de interface de usu&aacute;rio no iOS</a>, um passeio pelo iOS 7 ilustrando seus princ&iacute;pios de design atrav&eacute;s de uma revis&atilde;o de apps que a Apple redesenhou para isso;</li> 
 <li><a href="https://developer.apple.com/wwdc/videos/?id=225">Melhores pr&aacute;ticas para &oacute;timos design de interface de usu&aacute;rio no iOS</a>, com o objetivo de evitar armadilhas comuns e fornecer perspectivas sobre o que torna um aplicativo intuitivo e bonito na vis&atilde;o da Apple;</li> 
 <li><a href="https://developer.apple.com/tech-talks/videos/?id=2">Design de Interface de Usu&aacute;rio de apps para o iOS7,</a> descrevendo novas funcionalidades no iOS 7 como por exemplo: camadas, tingimento, tipografia, efeitos de movimento, din&acirc;mica e anima&ccedil;&atilde;o.</li> 
</ul>
<p>O material acima &eacute; somente uma sele&ccedil;&atilde;o de materiais que o o site de desenvolvedores da Apple oferece. Em particular, o site de desenvolvedores Apple disponibiliza para desenvolvedores registrados todos os v&iacute;deos das sess&otilde;es de <a href="https://developer.apple.com/wwdc/videos/">WWDC 2013</a> (evento em que o iOS 7 foi apresentado). Al&eacute;m disto, podem tamb&eacute;m ser encontrados v&iacute;deos exclusivos relacionados a interface do usu&aacute;rio como:</p>
<ul> 
 <li><a href="https://developer.apple.com/wwdc/videos/?id=206">Introdu&ccedil;&atilde;o ao UIKit Dynamics</a>, focando anima&ccedil;&otilde;es e transi&ccedil;&otilde;es movidos pelo novo motor de f&iacute;sica do iOS 7;</li> 
 <li><a href="https://developer.apple.com/wwdc/videos/?id=226">Implementa&ccedil;&atilde;o de interface de usu&aacute;rio atraente no iOS</a>, ensinando como conseguir anima&ccedil;&atilde;o e transi&ccedil;&otilde;es responsivas;</li> 
 <li><a href="https://developer.apple.com/wwdc/videos/?id=210">Introduzindo o Text Kit</a>, o novo mecanismo de texto no iOS 7, fornecendo capacidades de manipula&ccedil;&atilde;o de texto e diagrama&ccedil;&atilde;o sofisticados;</li> 
 <li><a href="https://developer.apple.com/wwdc/videos/?id=221">T&eacute;cnicas avan&ccedil;adas com o UIKit Dynamics</a>, indo al&eacute;m do b&aacute;sico aplicando o dynamics em views e view controllers;</li> 
 <li><a href="https://developer.apple.com/wwdc/videos/?id=220">Layouts de texto avan&ccedil;ado e efeitos com o Text Kit</a>, entrando em detalhes sobre a manipula&ccedil;&atilde;o de texto avan&ccedil;ado;</li> 
 <li><a href="https://developer.apple.com/wwdc/videos/?id=218">Transi&ccedil;&otilde;es customizadas usando View Controllers</a>, ensinando como definir transi&ccedil;&otilde;es customizadas entre view controllers;</li> 
 <li><a href="https://developer.apple.com/wwdc/videos/?id=214">Customizando a apar&ecirc;ncia da app para o iOS7</a>, sobre a capacidade de customiza&ccedil;&atilde;o para views e controles para adotar a interface de usu&aacute;rio do iOS7.</li> 
</ul>
<p>De acordo com <a href="http://techcrunch.com/2014/02/28/apple-adds-new-designing-great-apps-micro-site-for-ios-7-developers/">Darrell Etherington escrevendo para o Tech Crunch</a>, o novo microsite da Apple, embora n&atilde;o ofere&ccedil;a nenhum material novo, pode ajudar os desenvolvedores a refinar seus produtos e prover a n&atilde;o desenvolvedores uma vista de como a Apple visualiza o design das apps e quais tratamentos de interface de usu&aacute;rio s&atilde;o especialmente relevantes para isso.</p><br><br><br><br><br><br></body></html>