<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Ora2Pg 11.1: Migrações de Oracle para PostgreSQL mais rápidas</h3><p>A <a href="http://www.dalibo.com/">Dalibo</a> anunciou no &uacute;ltimo 10 de abril o <a href="http://ora2pg.darold.net/news.html">lan&ccedil;amento</a> da vers&atilde;o 11.1 do Ora2Pg. Essa importante vers&atilde;o traz o t&atilde;o aguardado suporte para multiprocessamento, que possibilita exportar dados de forma paralela. A importa&ccedil;&atilde;o de dados a partir de um banco de dados Oracle passa a ser 10 vezes mais r&aacute;pida se comparada com as vers&otilde;es anteriores. Com esse novo recurso, o desempenho do Ora2Pg fica bem mais pr&oacute;ximo ao que se deseja obter com qualquer <a href="http://pt.wikipedia.org/wiki/Extract,_transform,_load">ETL</a> (opera&ccedil;&otilde;es de extra&ccedil;&atilde;o, transforma&ccedil;&atilde;o e carga de dados).</p> 
<p>O Ora2Pg &eacute; uma ferramenta de uso simplificado que permite migrar dados de um banco de dados Oracle para o PostgreSQL. Desenvolvido desde 2001 por Gilles Darold, o Ora2Pg permite exportar a maioria dos objetos de um banco de dados Oracle (tabelas, views, sequ&ecirc;ncias, &iacute;ndices, triggers, fun&ccedil;&otilde;es, procedures, pacotes, parti&ccedil;&otilde;es, dados, blobs e tabelas externas) para <a href="http://www.postgresql.org/">PostgreSQL</a>.</p> 
<p>Al&eacute;m do aumento no desempenho, a nova vers&atilde;o do Ora2Pg traz outras melhorias importantes como:</p> 
<ul> 
 <li>Agora &eacute; poss&iacute;vel gerar arquivos de transforma&ccedil;&atilde;o XML para o <a href="http://kettle.pentaho.com/">Kettle</a>;</li> 
 <li>Maior desempenho na leitura de bancos de dados Oracle contendo grande n&uacute;mero de objetos;</li> 
 <li>Tabelas com dados particionados passam a ser importados diretamente para as tabelas de destino, em vez de serem inseridas em uma tabela principal e enviadas ao seu destino final por uma trigger. Nesta vers&atilde;o, o Ora2Pg identifica automaticamente a tabela de parti&ccedil;&atilde;o de entrada ou sa&iacute;da, sem a necessidade de configura&ccedil;&atilde;o;</li> 
 <li>Corre&ccedil;&otilde;es de bugs na exporta&ccedil;&atilde;o de dados RAW e LONG RAW;</li> 
 <li>Reescrita de c&oacute;digo PL/SQL para PL/pgSQL.</li> 
</ul> 
<p><a href="http://www.darold.net/">Gilles Darold</a>, l&iacute;der do projeto e principal desenvolvedor do Ora2Pg, cita que:</p> 
<blockquote> 
 <p>O desenvolvimento de Ora2Pg est&aacute; muito r&aacute;pido porque mais e mais empresas est&atilde;o migrando do Oracle para o PostgreSQL. Essa nova vers&atilde;o traz melhorias de desempenho para migrar bases de dados multi-terabyte de forma mais r&aacute;pida.</p> 
 <p>Para a maioria dos usu&aacute;rios, a redu&ccedil;&atilde;o no tempo de migra&ccedil;&atilde;o &eacute; fundamental porque significa menos tempo de inatividade durante a troca do Oracle para PostgreSQL.</p> 
</blockquote> 
<p>&Eacute; importante destacar que as melhorias de desempenho alcan&ccedil;adas nessa vers&atilde;o foram desenvolvidas com a orienta&ccedil;&atilde;o da Dalibo em colabora&ccedil;&atilde;o com a <a href="http://www.photobox.com/">Photobox</a> e pela <a href="http://www.bouyguestelecom.fr/">Bouygues Telecom</a>, sem os quais os testes realizados em conjunto com essas empresas, n&atilde;o permitiriam alcan&ccedil;ar o desempenho destacado nessa nova vers&atilde;o.</p> 
<p>O Ora2Pg &eacute; um software de c&oacute;digo livre sob a <a href="http://en.wikipedia.org/wiki/GNU_General_Public_License">licen&ccedil;a GPL</a> e est&aacute; dispon&iacute;vel para <a href="https://github.com/darold/ora2pg">download</a> no GitHub. O projeto &eacute; mantido por Gilles Darold por meio de consultorias e parcerias com empresas como a Dalibo.</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>