<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Novidades da Microsoft e Amazon para o Android</h3><p>O Windows Azure agora possui um <a href="https://github.com/WindowsAzure/azure-mobile-services">Android SDK</a>, incluindo notifica&ccedil;&otilde;es push para dispositivos Android. A Amazon disponibilizou uma <a href="https://developer.amazon.com/sdk/mobileads.html">API de an&uacute;ncios mobile</a>, que pode ser utilizada para exibi&ccedil;&atilde;o de an&uacute;ncios da rede da Amazon em qualquer dispositivo Android, em paralelo com os an&uacute;ncios do Google AdMob.</p> 
<p><strong>SDK Android para o Windows Azure</strong></p> 
<p>A Microsoft <a href="http://www.google.com/url?q=http%3A%2F%2Fblogs.msdn.com%2Fb%2Finteroperability%2Farchive%2F2013%2F03%2F04%2Fms-open-tech-develops-the-open-source-android-sdk-for-windows-azure-mobile-services.aspx&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNFJOLBURVQ_wCnWHV0xS0ieAjax4g">anunciou</a> o Android SDK para <a href="http://www.google.com/url?q=http%3A%2F%2Fwww.windowsazure.com%2Fen-us%2Fdevelop%2Fmobile%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNGR9QkmfMoZ0kRYYySXmwAKIEnY-A">Windows Azure Mobile Services</a>. O Mobile Services ajuda os desenvolvedores a conectarem o Windows 8, Windows Phone 8 e aplica&ccedil;&otilde;es Android a diversos servi&ccedil;os executados na nuvem da Microsoft, em um ambiente escal&aacute;vel. Atualmente, a Microsoft suporta a cria&ccedil;&atilde;o e o gerenciamento de tabelas de dados, autentica&ccedil;&atilde;o de usu&aacute;rios e notifica&ccedil;&otilde;es push.</p> 
<p>Para adicionar os servi&ccedil;os mencionados em uma aplica&ccedil;&atilde;o Android, o desenvolvedor pode criar o esqueleto de uma aplica&ccedil;&atilde;o atrav&eacute;s do portal do Windows Azure, baixar o c&oacute;digo-fonte e ent&atilde;o carreg&aacute;-lo no Eclipse. Mais detalhes s&atilde;o fornecidos <a href="http://www.google.com/url?q=http%3A%2F%2Fwww.windowsazure.com%2Fen-us%2Fdevelop%2Fmobile%2Ftutorials%2Fget-started-android%2F&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNHzhHqAIWPDRrdKZI7ZYQWrjTUH6Q">nesse tutorial</a>.</p> 
<p>O SDK Android para o Windows Azure inclui tr&ecirc;s APIs:</p> 
<ul> 
 <li>Dados: conex&atilde;o com tabelas do Windows Azure utilizando &quot;uma API fluente para consultas e serializa&ccedil;&atilde;o/desserializa&ccedil;&atilde;o autom&aacute;tica&quot;;</li> 
 <li>Identifica&ccedil;&atilde;o/Autentica&ccedil;&atilde;o de usu&aacute;rios: para contas Microsoft, Facebook, Twitter ou Google;</li> 
 <li>Filtragem de Servi&ccedil;os, que cria uma fila para a entrega de solicita&ccedil;&otilde;es e respostas de servi&ccedil;os de forma ordenada.</li> 
</ul> 
<p>Outro novo recurso s&atilde;o as notifica&ccedil;&otilde;es push para dispositivos Android atrav&eacute;s do <a href="http://www.infoq.com/news/2012/08/GoogleCMReplacesC2Dm;jsessionid=8AE36C3AEACFEAC55332668ADC3DDC85">Google Cloud Messaging</a> (GCM). Um servidor executado no Windows Azure envia mensagens para o GCM que por sua vez envia as mensagens para o dispositivo Android.</p> 
<p>O Android SDK est&aacute; disponibilizado no GitHub assim como outros SDKs para Windows 8, Windows Phone 8 e iOS. O Android SDK suporta o Android 2.2 ou vers&atilde;o superior.</p> 
<p><strong>API de an&uacute;ncios mobile da Amazon</strong></p> 
<p>A Amazon lan&ccedil;ou sua API de an&uacute;ncios (Amazon Mobile Ads API), que habilita desenvolvedores a exibir an&uacute;ncios da Amazon e de seus parceiros. A API tem como principal alvo o Kindle Fire/HD mas tamb&eacute;m pode ser utilizada em outros telefones ou tablets com Android.</p> 
<p>A &uacute;nica condi&ccedil;&atilde;o exigida pela Amazon &eacute; que o aplicativo seja publicado primeiro no <a href="http://www.google.com/url?q=https%3A%2F%2Fdeveloper.amazon.com%2Fwelcome.html&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNFdpgxy4CWBHEZfVHRNDBx3WqbjIA">Mobile App Distribution Portal</a> antes de ser disponibilizado em outros canais como o Google Play. A aplica&ccedil;&atilde;o assim criada pode exibir tanto an&uacute;ncios da Amazon quanto os do <a href="http://www.google.com/ads/admob/">Google AdMob</a>.</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>