<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Soluções Hadoop Big Data, e o estado das coisas no Q1/2014 da Forrest</h3><p>De acordo com o novo <a href="http://www.google.com/url?q=http%3A%2F%2Finfo.mapr.com%2Frs%2Fmapr%2Fimages%2FThe_Forrester_Wave__Big_D%2520%25282%2529.pdf&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNFqCpDfGzW1fVBgfqBo_e6ORbWWSg">relat&oacute;rio da Forest</a>, muitas empresas est&atilde;o procurando ter um conhecimento mais profundo da massiva quantidade de dados estruturados, n&atilde;o estruturados, semi-estruturados e bin&aacute;rios que j&aacute; possuem. Uma das conclus&otilde;es do relat&oacute;rio &eacute; que</p>
<blockquote> 
 <p>&nbsp;</p> 
 <p>A maioria das empresas estimam que est&atilde;o somente analisando 12% de todos os dados que possuem, deixando 88% de seus dados sem uma an&aacute;lise mais elaborada. A falta de &aacute;reas de armazenamento e a falta de capacidade de an&aacute;lise s&atilde;o as principais raz&otilde;es disto. Adicionando-se a isto, muitas vezes &eacute; imposs&iacute;vel julgar quais s&atilde;o os dados que possuem valor ou n&atilde;o. Em rela&ccedil;&atilde;o ao tempo de armazenamento dos dados para o Big Data, devemos capturar e armazenar tudo. Dados que talvez possam parecer completamente irrelevantes para o neg&oacute;cio em um dado momento, como dados de mobile e GPS, podem ser uma mina de ouro no futuro.</p> 
</blockquote>
<p>Como resultado, muitas empresas est&atilde;o procurando o Hadoop para resolver os seguintes problemas:</p>
<ul class="c8 lst-kix_u8zwimio2l1w-0 start"> 
 <li>Capturar e armazenar todos os dados relevantes para o neg&oacute;cio da empresa</li> 
 <li>Suportar an&aacute;lises avan&ccedil;adas capacitando a inclus&atilde;o de intelig&ecirc;ncia de neg&oacute;cios, visualiza&ccedil;&atilde;o avan&ccedil;ada e an&aacute;lise preditiva para explora&ccedil;&atilde;o dos dados de novas maneiras.</li> 
 <li>Compartilhar os dados rapidamente com todos que os necessitem. A combina&ccedil;&atilde;o de dados de m&uacute;ltiplas fontes, pode ajudar uma empresa a encontrar respostas para quest&otilde;es complexas que foram anteriormente questionadas ou respostas que ainda n&atilde;o foram questionadas.</li> 
 <li>O cont&iacute;nuo acomodamento de grande volumes e dados e novas fontes de dados. O Hadoop permite solu&ccedil;&otilde;es r&aacute;pidas de escalabilidade com um baixo custo efetivo, habilitando o controle do aumento do volume, velocidade e variedade dos dados.</li> 
</ul>
<p>De acordo com o relat&oacute;rio, a procura por solu&ccedil;&otilde;es Hadoop est&aacute; em uma crescente ascens&atilde;o, surgindo assim mais e mais fornecedores nesta &aacute;rea. Embora o Hadoop seja um projeto Apache de c&oacute;digo fonte aberto onde todos podem fazer o download gratuitamente, a maioria das empresas preferem solu&ccedil;&otilde;es de fornecedores. Al&eacute;m do empacotamento de todos os componentes Hadoop os fornecedores garantem o funcionamento de todos os componentes juntos (vers&otilde;es compat&iacute;veis), tamb&eacute;m oferecendo suporte a n&iacute;vel empresarial e estendem, aumentando o Apache Hadoop (Commom, HDFS, MapReduce) fazendo implementa&ccedil;&otilde;es em seus componentes n&uacute;cleo adicionando recursos diferenciados tornando assim suas solu&ccedil;&otilde;es atraentes para as empresas.</p>
<p>O relat&oacute;rio da Forrest analisa de perto nove fornecedores: Amazon Web Services, Cloudera, Hortonworks, IBM, Intel, MapR Techonologies, Microsoft, Pivotal Software, e Teradata, avaliando-os com base nos seguintes crit&eacute;rios:</p>
<ul class="c8 lst-kix_twvveptehqke-0 start"> 
 <li>A oferta atual, incluindo a arquitetura da solu&ccedil;&atilde;o, dados e caracter&iacute;sticas de processamento, configura&ccedil;&atilde;o, gest&atilde;o e ferramentas de monitoramento e de compatibilidade e recursos comunit&aacute;rios.</li> 
 <li>Estrat&eacute;gia, incluindo o plano para atender &agrave;s atuais demandas dos clientes e preencher as lacunas existentes para implementa&ccedil;&otilde;es empresariais. Avalia&ccedil;&atilde;o de estrat&eacute;gias inclu&iacute;ndo op&ccedil;&otilde;es de aquisi&ccedil;&atilde;o, capacidade interna para executar a estrat&eacute;gia e roadmap de produtos e recursos de suporte ao cliente.</li> 
 <li>Presen&ccedil;a de mercado, incluindo as finan&ccedil;as da empresa, presen&ccedil;a global e base instalada e estrat&eacute;gias com parcerias com outros fornecedores de software, empresas de presta&ccedil;&atilde;o de servi&ccedil;os de software como servi&ccedil;o (SaaS) /nuvem/provedores de hospedagem.</li> 
</ul>
<p>As principais conclus&otilde;es do relat&oacute;rio s&atilde;o as seguintes:</p>
<ul class="c8 lst-kix_1s90r0nwbbeb-0 start"> 
 <li>Existem muitos l&iacute;deres, mas n&atilde;o existe um dominante.</li> 
</ul>
<blockquote> 
 <p>&nbsp;</p> 
 <p>Os l&iacute;deres em solu&ccedil;&otilde;es Hadoop para Big Data s&atilde;o Amazon Web Services, Cloudera, Hortonworks, IBM, MapR Technologies, Pivot Software e Teradata. Os fornecedores come&ccedil;am com o projeto Apache de c&oacute;digo aberto adicionando em seguida pacotes de componentes, suporte, integra&ccedil;&otilde;es, e inova&ccedil;&otilde;es que preenchem as lacunas do Hadoop para as empresas. Todos os fornecedores tem feito isso de formas diferentes - como um fornecedor individual a sua classifica&ccedil;&atilde;o e seu perfil pode tornar sua escolha clara.</p> 
</blockquote>
<p>&nbsp;</p>
<ul class="c8 lst-kix_dgi2j7y95r82-0 start"> 
 <li>Soluc&otilde;es mais jovens, casam muito bem com fornecedores renomados do mercado.</li> 
</ul>
<p>Intel e Microsoft, s&atilde;o novos fornecedores renomados de solu&ccedil;&otilde;es Hadoop para Big Data. A Microsoft tem um robusto roteiro para o HDInsight o que a tornar&aacute; t&atilde;o atraente quanto os outros l&iacute;deres. O <a href="http://www.google.com/url?q=http%3A%2F%2Fwww.microsoft.com%2Fen-us%2Fserver-cloud%2Fsolutions%2Fbig-data.aspx%23fbid%3DqzMjr37TLoR&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNE1ChNwdw-QmdzE6QLa4x7ABda2zw">Microsoft HDInsight</a> tamb&eacute;m foi projetado para o Azure, sendo a melhor solu&ccedil;&atilde;o para os clientes da Microsoft que desejam implementar o Hadoop no Azure. A Intel tem focado muito suas inova&ccedil;&otilde;es no n&iacute;vel de chip; a Intel ainda necessita refor&ccedil;ar a sua estrat&eacute;gia e ferramentas empresariais para fazer mais incurs&otilde;es como uma solu&ccedil;&atilde;o corporativa.</p>
<p>Embora, de acordo com o relat&oacute;rio, estas avalia&ccedil;&otilde;es do mercado de solu&ccedil;&otilde;es Big Data Hadoop sejam somente um ponto de partida inicial, ele fornece excelentes informa&ccedil;&otilde;es para qualquer empresa que esteja tentando explorar este complexo cen&aacute;rio de fornecedores Hadoop.</p><br><br><br><br><br><br></body></html>