<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Facebook adota o Chef para gerência da camada web</h3><h1>&nbsp;</h1> 
<p>O Facebook implantou o <a href="http://www.opscode.com/private-chef/">Private Chef</a>, um produto de automa&ccedil;&atilde;o de infraestrutura da <a href="http://www.opscode.com/">Opscode</a>, para gerenciamento da sua camada web. Para garantir que o Chef atenda aos requisitos de escalabilidade do Facebook, a empresa ajudou a projetar a &uacute;ltima vers&atilde;o do <a href="http://www.infoq.com/news/2013/02/Chef-11-Hyperscale-Ready;jsessionid=7406395A1707361FF640B2C1BA086426">Chef Server, que foi totalmente reescrito em Erlang</a>.</p> 
<p>A equipe do Facebook, at&eacute; o momento, afirma <a href="http://www.wired.com/wiredenterprise/2013/02/facebook-chef/">estar satisfeita com os resultados da utiliza&ccedil;&atilde;o do Chef</a> e divulgar&aacute; mais detalhes do projeto em abril, na confer&ecirc;ncia <a href="http://chefconf.opscode.com/">ChefConf</a>. Phil Dibowitz, engenheiro de produ&ccedil;&atilde;o do Facebook, <a href="http://www.theregister.co.uk/2013/02/04/opscode_chef_11_control_freak/">em entrevista ao The Register</a>, afirmou que o Chef &eacute; a &uacute;nica solu&ccedil;&atilde;o de automa&ccedil;&atilde;o com flexibilidade suficiente para atender &agrave; din&acirc;mica de escalabilidade do Facebook, sem que seja necess&aacute;rio mudan&ccedil;as no fluxo de trabalho da empresa.</p> 
<p>O Chef aparenta estar ganhando mercado para deploys em larga escala.</p> 
<ol start="1"> 
 <li>O <a href="http://www.dreamhost.com/">Dreamhost</a>, uma grande empresa de hospedagem web, est&aacute; utilizando o Private Chef em tr&ecirc;s datacenters;</li> 
 <li><a href="http://www.opscode.com/blog/2013/02/04/cycle-computing-puts-chef-11-through-its-paces-w10k-aws-servers/">A Cycle Computing administrou mais de 10 mil n&oacute;s da Amazon AWS</a>, utilizando uma &uacute;nica inst&acirc;ncia do Chef 11 server para identificar potenciais aplica&ccedil;&otilde;es para cura do c&acirc;ncer para uma grande empresa farmac&ecirc;utica;</li> 
 <li>A <a href="http://www.edmunds.com/">edmunds.com</a> automatizou toda sua <a href="http://www.youtube.com/watch?v=np5krbpPJiE&amp;feature=em-uploademail">infraestrutura</a> de 2.500 hosts Hadoop. Para a Edmunds, esse foi seu primeiro <em>case</em> de sucesso de automa&ccedil;&atilde;o de infraestrutura amplamente divulgado.</li> 
</ol> 
<p><a href="http://twitter.com/puppetmasterd">Luke Kanies</a> do <a href="https://puppetlabs.com/">Puppet Labs</a>, criadora do <a href="http://www.infoq.com/bycategory/newsbycategory.action;jsessionid=7406395A1707361FF640B2C1BA086426?idx=3&amp;alias=Puppet&amp;ct=4">Puppet</a> e que compete com a Opscode no mercado de automa&ccedil;&atilde;o de infraestrutura, <a href="http://www.wired.com/wiredenterprise/2013/02/facebook-chef/">disse</a>:</p> 
<blockquote> 
 <p>&Eacute; impressionante o resultado alcan&ccedil;ado pela Opscode em rela&ccedil;&atilde;o &agrave; escalabilidade, contudo nosso produto est&aacute; neste n&iacute;vel a tr&ecirc;s ou quatro anos.</p> 
</blockquote> 
<p>Para confirmar sua afirma&ccedil;&atilde;o, Kanies aponta como exemplo os 50 mil servidores da Zynga e o pr&oacute;ximo deploy do laborat&oacute;rio Su&iacute;&ccedil;o de pesquisa em f&iacute;sica nuclear CERN, que ser&aacute; composto por 30 mil servidores.</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>