<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>IDC Study: How Many Software Developers Are Out There?</h3><p><a href="http://www.idc.com/">IDC</a> has published the “<a href="http://www.idc.com/getdoc.jsp?containerId=244709">2014 Worldwide Software Developer and ICT-Skilled Worker Estimates</a>” document, a study estimating the number of professional software developers, hobbyist developers and Information and Communications Technology (ICT)-skilled workers in the world at the start of 2014. The 90 countries covered in the study represent 97% of the world’s GDP.</p>
<p>According to <a href="http://www.idc.com/getdoc.jsp?containerId=PRF003108">Al Hilwa</a>, Research Director at IDC and author of the above mentioned study, there are an estimated “29 million ICT-skilled workers in the world as we enter 2014, including 11 million professional developers.” Besides those, there are estimated to be another 7.5M hobbyist software developers around the globe, the actual numbers being depicted in the table below:</p>
<p><a href="/resource/news/2014/01/IDC-software-developers/en/resources/IDC 2014 ITC estimates.png" target="_blank"><img title="image" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" border="0" alt="image" src="http://www.infoq.com/resource/news/2014/01/IDC-software-developers/en/resources/IDC 2014 ITC estimates.png" _href="img://IDC 2014 ITC estimates.png" _p="true" /></a></p>
<p>The number of professional software developers by major economic regions is shown in the following chart:</p>
<p><a href="/resource/news/2014/01/IDC-software-developers/en/resources/IDC-pro-devs-region.png" target="_blank"><img title="image" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" border="0" alt="image" src="http://www.infoq.com/resource/news/2014/01/IDC-software-developers/en/resources/IDC-pro-devs-region.png" _href="img://IDC-pro-devs-region.png" _p="true" /></a></p>
<p>When it comes to countries, United States has the most software developers (professional + hobbyist) – 19.2%, followed by China with 10.1% and India with 9.8%. The document includes detailed statistics for all the countries covered by this study.</p>
<p>Definitions used, according to the IDC study:</p>
<blockquote> 
 <p><strong>Professional software developers</strong> are persons engaged in gainful employment where the primary activity is the construction of software or the direct supervision of such activity.</p> 
</blockquote>
<p>Pro developers include the following workers, based on the U.S. Bureau of Labor Statistics’ classification:</p>
<ul> 
 <li>Develop, create, and modify general computer applications software or specialized utility programs.</li> 
 <li>Analyze user needs and develop software solutions.</li> 
 <li>Design software or customize software for client use with the aim of optimizing operational efficiency.</li> 
 <li>May analyze and design databases within an application area, working individually or coordinating database development as part of a team.</li> 
 <li>May supervise computer programmers.</li> 
</ul>
<p>Hobbyists are a new category of persons involved with software and tracked by IDC in their studies. According to this document,</p>
<blockquote> 
 <p><strong>Hobbyist software developers </strong>range from persons engaged in software development to a much more limited degree so that it cannot be fairly classified as their primary occupation, even if they have formal occupations in the labor force. Hobbyist developers may also be students, who form a large chunk of this population. Hobbyist developers may also be unemployed or otherwise outside a country's labor force.</p> 
</blockquote>
<p>The ICT-skilled workers include the professional developers, a small number of hobbyist and ICT operations and management-skilled workers, the study defining the later as:</p>
<blockquote> 
 <p>Simplistically, everyone in the classic ICT occupation classifications and the expanded STEM classifications, who is involved in ICT but is not deemed a professional software developer as described above, was counted as an <strong>ICT operations and management skilled worker</strong>. The primary occupations contributing to this number are systems, database, and network managers.</p> 
</blockquote>
<p>The relationship between professional software developers, hobbyist and ICT workers is shown in the next graphic:</p>
<p><a href="/resource/news/2014/01/IDC-software-developers/en/resources/IDC-overlap.png" target="_blank"><img title="IDC-overlap" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" border="0" alt="IDC-overlap" src="http://www.infoq.com/resource/news/2014/01/IDC-software-developers/en/resources/IDC-overlap.png" _href="img://IDC-overlap.png" _p="true" /></a></p>
<p>Regarding the methodology used to estimate the number of ITC-skilled workers worldwide, IDC has relied on workforce statistical data (Eurostat, , ILO, country statistical organizations such as the US Department of Labor, Bureau of Labor Statistics, etc.) provided by 54 of the countries studied. For other countries, IDC used the analysis of “secondary and tertiary education enrollment and for tertiary education graduations in <a href="http://en.wikipedia.org/wiki/STEM_fields">STEM</a>-related fields available from the OECD.” For a small fraction of the countries for which there was no direct statistical data available, IDC relied on “macroeconomic data on labor force population sizes, GDP, education levels, human development indices, and IDC software spend data sets such as available from IDC's Software Tracker.”</p>
<p>To answer the question in the title, currently there are an estimated 11,005,000 professional software developers, with 554,483 (5.3%) more than in 2011, and some 7.5M additional hobbyist, a community which has not been estimated by IDC before.</p><br><br><br><br><br><br></body></html>