<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Novo Radar de Tecnologias da ThoughtWorks: Mobile e Big Data em destaque</h3><p>O mais recente relat&oacute;rio <a href="http://www.thoughtworks.com/articles/technology-radar-october-2012">Radar de Tecnologias</a> da ThoughtWorks concentra-se em plataformas m&oacute;veis, an&aacute;lises de Big Data, arquiteturas simples, ambientes reproduz&iacute;veis, e persist&ecirc;ncia de dados bem constru&iacute;da. Segundo o relat&oacute;rio, no futuro as intera&ccedil;&otilde;es com o consumidor ser&atilde;o principalmente por meio de <a href="http://bgr.com/2013/01/02/android-ios-activations-december-2012-279464/">plataformas m&oacute;veis</a>. Outra tend&ecirc;ncia reportada &eacute; a forma como <a href="https://www.youtube.com/watch?v=cEaQB6e7G0Q">plataformas de computa&ccedil;&atilde;o na nuvem</a> confi&aacute;veis ​​permitir&atilde;o que an&aacute;lises de Big Data se tornem mais acess&iacute;veis.</p> 
<p>Tamb&eacute;m &eacute; destacada a necessidade de arquitetos criarem arquiteturas simples por meio de tecnologias intercambi&aacute;veis e de alta qualidade, e sugere que se deve encorajar equipes a criar ambientes reprodut&iacute;veis para colher benef&iacute;cios em visibilidade, rastreabilidade, confiabilidade e escalabilidade resultantes. Al&eacute;m disso, engenheiros de software s&atilde;o incentivados a usar <a href="http://rebelic.nl/engineering/the-four-categories-of-nosql-databases/">bancos de dados NoSQL</a> para modelar dom&iacute;nios com facilidade.</p> 
<p>As tecnologias recomendadas para ado&ccedil;&atilde;o est&atilde;o alinhadas com a presen&ccedil;a crescente de plataformas m&oacute;veis nas m&atilde;os dos consumidores. Al&eacute;m disso, sistemas de retaguarda est&atilde;o adotando tecnologias de bancos de dados de grafos, que podem facilmente representar dom&iacute;nios complexos e distribu&iacute;dos:</p> 
<blockquote> 
 <p>Bancos de grafos armazenam informa&ccedil;&otilde;es na forma de n&oacute;s interconectados arbitrariamente, ligados por rela&ccedil;&otilde;es nomeadas, ao inv&eacute;s de tabelas e jun&ccedil;&otilde;es</p> 
</blockquote> 
<p>Segundo o relat&oacute;rio, os sistemas de retaguarda ser&atilde;o capazes de capturar o m&aacute;ximo poss&iacute;vel de dados, para realizar an&aacute;lises avan&ccedil;adas em larga escala, usando recursos de computa&ccedil;&atilde;o em nuvem de baixo custo:</p> 
<blockquote> 
 <p>Utilizando uma gama de novas tecnologias, por exemplo coletores de dados NoSQL, frameworks de MapReduce e clusters de servidores independentes e comoditizados, hoje temos o poder necess&aacute;rio para fazer uso eficaz de t&eacute;cnicas de intelig&ecirc;ncia artificial, an&aacute;lise sem&acirc;ntica, minera&ccedil;&atilde;o de textos e an&aacute;lise quantitativa.</p> 
</blockquote> 
<p>Por outro lado, o relat&oacute;rio da Thoughtworks marca certas tecnologias como &quot;em espera&quot;, por n&atilde;o funcionarem bem em ambientes de entrega cont&iacute;nua, criando fragilidades:</p> 
<blockquote> 
 <p>Ferramentas para automa&ccedil;&atilde;o de navegadores web, como o Selenium, t&ecirc;m incentivado o uso amplo de testes automatizados por meio de navegadores. Embora esses testes continuem tendo seu lugar em um portf&oacute;lio de testes, a maioria das equipes considera que executar muitos testes no navegador leva a testes lentos e fr&aacute;geis.</p> 
</blockquote> 
<p>Uma parte das recomenda&ccedil;&otilde;es refor&ccedil;a diretamente as melhores pr&aacute;ticas do movimento <a href="http://www.ibm.com/developerworks/br/library/a-devops1/index.html">DevOps</a>, entre elas a automatiza&ccedil;&atilde;o do deploy e da infraestrutura com c&oacute;digo em combina&ccedil;&atilde;o com ferramentas de gerenciamento de configura&ccedil;&atilde;o. Por exemplo, o <a href="http://www.infoq.com/br/news/2009/01/chef-management-tool-announced;jsessionid=2BE49C9352F1A9FEF0222D20BFF92B5C">Chef</a> ou <a href="http://puppetlabs.com/">Puppet</a>, permitem a gest&atilde;o eficiente de grandes quantidades de servidores. Servidores imut&aacute;veis ​​tornam-se especialmente importantes com grandes quantidades de servidores autodimension&aacute;veis (por exemplo <a href="http://aws.amazon.com/autoscaling/">servidores escal&aacute;veis AWS</a>).</p> 
<p>O relat&oacute;rio cita que o uso de integra&ccedil;&atilde;o cont&iacute;nua na nuvem j&aacute; est&aacute; pronto para uso, desde que os projetos que se sujeitarem a esse tipo de tecnologia sejam capazes de identificar seus potenciais benef&iacute;cios e que estejam preparados para gerenciar os riscos existentes nesta abordagem (por exemplo, seguran&ccedil;a, regras espec&iacute;ficas de cada fornecedor, disponibilidade de tipos de tecnologia no fornecedor). Como exemplo, o relat&oacute;rio da ThoughtWorks d&aacute; a empresa AtTask que <a href="http://www.youtube.com/watch?v=zPyb8v4fNVE&amp;list=UUKlF3GIFy9KVUefVbycx_vw&amp;index=1">tirou proveito</a> da nuvem para utilizar Integra&ccedil;&atilde;o Cont&iacute;nua, conseguindo com isso reduzir o tempo necess&aacute;rio de seus testes de aceita&ccedil;&atilde;o para apenas alguns minutos (antes eram necess&aacute;rios no m&iacute;nimo 3 dias para execut&aacute;-los).</p> 
<p>O relat&oacute;rio &quot;Radar de Tecnologias&quot; tem como objetivo influenciar a tomada de decis&otilde;es por meio de recomenda&ccedil;&otilde;es sobre o que deve ser adotado ou experimentado, assim como o que deve ser evitado. As recomenda&ccedil;&otilde;es do &uacute;ltimo relat&oacute;rio seguem o mesmo formato da <a href="http://www.google.com/url?q=http%3A%2F%2Fwww.infoq.com%2Fnews%2F2012%2F03%2Fthoughtworks-radar-0312&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNGTridEd2zryNwGE85VWRKWwTZa4w">edi&ccedil;&atilde;o anterior</a>, e s&atilde;o semelhantes &agrave;s recomenda&ccedil;&otilde;es produzidas pela pesquisa de tecnologias do Gartner, descritas no <a href="http://www.gartner.com/technology/research/methodologies/hype-cycle.jsp">Hype Cycle</a>.</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>