<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>jQuery Mobile 1.3.0: enfoque no web design responsivo</h3><p>A vers&atilde;o 1.3.0 do <a href="http://jquerymobile.com/">jQuery Mobile</a>, o framework open source JavaScript e HTML5/CSS para aplicativos m&oacute;veis, tem foco em web design responsivo e traz novos componentes gr&aacute;ficos.</p> 
<p>O web design responsivo, ou RWD na sigla em ingl&ecirc;s, tem como objetivo fornecer a melhor experi&ecirc;ncia visual poss&iacute;vel, independentemente de qual aparelho ou tipo de navegador est&aacute; sendo usado. Ao inv&eacute;s de determinar o agente do usu&aacute;rio (User Agent) no servidor e entregar p&aacute;ginas espec&iacute;ficas, o RWD usa consultas de m&iacute;dia (<a href="http://www.w3.org/TR/css3-mediaqueries/">media queries</a>) do CSS para adaptar o layout da p&aacute;gina dinamicamente ao navegador. Dessa forma, al&eacute;m de se poder renderizar p&aacute;ginas em diferentes tamanhos de tela, tamb&eacute;m se pode reagir a mudan&ccedil;as de orienta&ccedil;&atilde;o da tela de celulares, por exemplo.</p> 
<p>Tood Parker, l&iacute;der do projeto jQuery Mobile, detalha a mudan&ccedil;a em dire&ccedil;&atilde;o ao design responsivo:</p> 
<blockquote> 
 <p>O jQuery Mobile foi projetado e testado para trabalhar n&atilde;o apenas em telefones celulares, mas tamb&eacute;m em tablets, e at&eacute; mesmo em navegadores desktop. Pense nisso como &quot;mobile primeiro&quot; e n&atilde;o &quot;mobile apenas&quot;. No nosso pr&oacute;ximo lan&ccedil;amento iniciaremos o processo de integra&ccedil;&atilde;o mais pr&oacute;xima com o jQuery UI, com objetivo de ter ainda mais c&oacute;digos e conven&ccedil;&otilde;es compartilhadas. Nosso foco para a vers&atilde;o 1.3 foi educar a comunidade quanto ao web design responsivo, adicionando documenta&ccedil;&atilde;o e exemplos que explicam os conceitos principais. Tamb&eacute;m adicionamos novos componentes como tabelas responsivas, pain&eacute;is e grids, que facilitam a cria&ccedil;&atilde;o de aplica&ccedil;&otilde;es e sites responsivos.</p> 
</blockquote> 
<p>Al&eacute;m de se preparar para o web design responsivo com os novos componentes, a nova vers&atilde;o inclui uma gama de novos elementos e funcionalidades para design de interface com o usu&aacute;rio (UI):</p> 
<ul> 
 <li>Campos de entrada de texto ou pain&eacute;is de menus que podem ser abertos (com anima&ccedil;&atilde;o) em dispositivos menores ou permanecer abertos em telas maiores;</li> 
 <li><em>Sliders</em> com dois guias que permitem definir um limite superior e inferior com apenas um componente (widget);</li> 
 <li>Novos &iacute;cones e temas de &iacute;cones melhorados;</li> 
 <li>Eventos de navega&ccedil;&atilde;o e um m&eacute;todo de navega&ccedil;&atilde;o que possibilita o manuseio do hist&oacute;rico do navegador, detectando manipula&ccedil;&otilde;es de DOM via Ajax;</li> 
 <li>Manipula&ccedil;&atilde;o aprimorada do gesto &quot;swipe&quot; (veja um <a href="http://jquerymobile.com/demos/1.3.0-beta.1/docs/demos/swipe/swipe-page.html#">demo</a>), permitindo anexar l&oacute;gica personalizada de in&iacute;cio e final do gesto.</li> 
</ul> 
<p>A Funda&ccedil;&atilde;o jQuery oferece v&aacute;rias bibliotecas <a href="http://pt.wikipedia.org/wiki/Cross-browser">cross-browser</a> para simplificar o design de aplica&ccedil;&otilde;es baseadas em JavaScript e HTML5/CSS. Al&eacute;m do <a href="http://jquerymobile.com/">jQuery Mobile</a>, focado em interfaces m&oacute;veis, a Funda&ccedil;&atilde;o oferece tamb&eacute;m o <a href="http://jquery.com/">jQuery</a> para funcionalidades avan&ccedil;adas de JavaScript e Ajax; o <a href="http://jqueryui.com/">jQuery UI</a>, para interfaces com o usu&aacute;rio para aplica&ccedil;&otilde;es desktop; e o framework <a href="http://qunitjs.com/">QUnit</a> para testes de JavaScript.</p> 
<p id="lastElm"></p><br><br><br><br><br><br></body></html>