<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Behaviour-Driven Development Tool Jasmine 2.0 Released</h3><p>The latest version of <a href="https://github.com/pivotal/jasmine">Jasmine</a>, a <a href="http://en.wikipedia.org/wiki/Behavior-driven_development">Behaviour-Driven Development</a>, BDD, testing framework for <a href="http://en.wikipedia.org/wiki/JavaScript">JavaScript</a>, comes with improved support for <a href="http://nodejs.org/">Node.js</a> and work on increasing the internal quality. Changes in the recently released version 2.0 include:</p>
<ul> 
 <li>The quality of support for Node.js is enhanced by including all tests of Node as part of the <a href="http://en.wikipedia.org/wiki/Continuous_integration">continuous integration</a> testing of Jasmine. Integration tests also include tests against major web browsers, including Firefox, Chrome, Safari and Internet Explorer.</li> 
 <li>The dependency on Ruby has been dropped and replaced with Node.js and <a href="http://gruntjs.com/">Grunt.js</a>. This has decreased the amount of code and may simplify for the community to verify the function of contributions before they are added.</li> 
 <li>Work on increasing quality of Jasmine by using Jasmine for testing itself.</li> 
</ul>
<p>Some changes have broken the backwards compatibility with previous versions, among others:</p>
<ul> 
 <li>The syntax for asynchronous tests has changed, a call-back function can now be provided.</li> 
 <li>The interface for reporters has been replaced; this has resulted in changes in how call-backs are used and a decrease in coupling between custom implementations and Jasmine.</li> 
 <li>The code for equality checks has been replaced which may cause a different behaviour.</li> 
</ul>
<p>In addition to these changes, a number of issues and bugs have been fixed. The biggest set of changes though comes from <a href="https://github.com/pivotal/jasmine/blob/master/release_notes/20.md#massive-refactoring-and-better-testing">refactoring</a> in almost all objects in the code base, using a more consistent coding style with the goals of improving tests and simplifying development for the core team as well as for the community when extending Jasmine. <br /> The team have also updated the <a href="http://jasmine.github.io/2.0/introduction.html">introduction to Jasmine</a>, highlighting the changes for 2.0.</p>
<p>Jasmine is a framework for behaviour-driven development testing of JavaScript code, not depending on any other JavaScript frameworks or a <a href="http://en.wikipedia.org/wiki/Document_Object_Model">Document Object Model</a>, DOM.<br /> A <a href="https://groups.google.com/forum/#!forum/jasmine-js">mailing list</a> for Jasmine users is available with more than 800 members and so far almost 600 topics. A book about JavaScript testing using Jasmine was <a href="http://shop.oreilly.com/product/0636920028277.do">published</a> earlier this year.</p>
<p>Jasmine, founded by <a href="http://pivotallabs.com/author/dwfrank/">Davis W. Frank</a> and currently <a href="https://github.com/pivotal/jasmine#maintainers">maintained</a> by three developers, is an open source product, licensed under the MIT License.</p><br><br><br><br><br><br></body></html>