<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>Presto: O Sistema para consultas SQL distribuídas do Facebook</h3><p>No final de 2012, o Facebook deu in&iacute;cio ao projeto que se tornou o <a href="https://github.com/facebook/presto">Presto</a>. O objetivo desse projeto era criar uma maneira de realizar an&aacute;lises ad-hoc em centenas de petabytes de dados. Depois de rejeitar alguns projetos externos, o Facebook decidiu criar o seu pr&oacute;prio mecanismo de consulta distribu&iacute;do.</p>
<p>A interface do Presto &eacute; baseada no modelo SQL ANSI. A maioria dos sistemas de consultas distribu&iacute;das requerem que o usu&aacute;rio aprenda uma nova sintaxe. &Agrave;s vezes, a sintaxe &eacute; semelhante ao SQL, mas nenhum &eacute; t&atilde;o conhecido e documentado quanto o pr&oacute;prio SQL. A expectativa do Facebook &eacute; que essa decis&atilde;o torne o aprendizado de novos usu&aacute;rios mais f&aacute;cil e r&aacute;pido. O fato de se basear no SQL ANSI tamb&eacute;m deve permitir que o Presto funcione com ferramentas existentes de terceiros.</p>
<p>Internamente, o Presto &eacute; baseado em pipelines. Ap&oacute;s a consulta ser analisada e as tarefas atribu&iacute;das aos n&oacute;s apropriados, o &quot;cliente recebe os dados do est&aacute;gio de sa&iacute;da que, por sua vez, recebe de etapas subjacentes.&quot; Segundo <a href="https://www.facebook.com/notes/facebook-engineering/presto-interacting-with-petabytes-of-data-at-facebook/10151786197628920">Martin Traverso</a>:</p>
<blockquote> 
 <p>O modelo de execu&ccedil;&atilde;o do Presto &eacute; fundamentalmente diferente do <a href="http://hive.apache.org/">Hive</a>/MapReduce. O Hive traduz as consultas em v&aacute;rios est&aacute;gios de tarefas MapReduce que executam uma ap&oacute;s a outra. Cada tarefa l&ecirc; a entrada do disco e escreve imediatamente a sa&iacute;da de volta para o disco. Por sua vez, o mecanismo do Presto n&atilde;o usa o MapReduce. Ele emprega consultas customizadas e um mecanismo de execu&ccedil;&atilde;o com operadores destinados a suportar sem&acirc;nticas SQL. Al&eacute;m da otimiza&ccedil;&atilde;o no agendamento, todo o processamento &eacute; feito em mem&oacute;ria e trafegado atrav&eacute;s da rede entre os est&aacute;gios. Isso evita opera&ccedil;&otilde;es desnecess&aacute;rias de I/O e, consequentemente, a lat&ecirc;ncia associada a essas opera&ccedil;&otilde;es. O modelo de execu&ccedil;&atilde;o em pipeline executa v&aacute;rios est&aacute;gios de uma vez, e direciona os dados de um est&aacute;gio anterior para o pr&oacute;ximo conforme forem se tornando dispon&iacute;veis. Esse processo reduz significativamente a lat&ecirc;ncia final para v&aacute;rios tipos de consultas.</p> 
</blockquote>
<p>O Presto foi escrito em Java com um backend plug&aacute;vel. Para cada fonte de dados, como o Hive, HBase ou Scribe, um conector espec&iacute;fico &eacute; necess&aacute;rio. O conector fornece metadados ao Presto, informa&ccedil;&atilde;o na qual cada n&oacute; cont&eacute;m os dados e uma maneira para buscar os dados como uma stream.</p>
<p>De acordo com Martin, o Presto est&aacute; superando o Hive/MapReduce por um fator de 10 quando se trata de lat&ecirc;ncia e efici&ecirc;ncia de CPU para a maioria das consultas no Facebook. Mas eles ainda n&atilde;o terminaram e t&ecirc;m planos para melhorar ainda mais o desempenho. Um desses planos envolve a concep&ccedil;&atilde;o de um novo formato de dados que reduz a quantidade de transforma&ccedil;&otilde;es necess&aacute;rias conforme os dados se movem de um est&aacute;gio para outro.</p>
<p>O Facebook tamb&eacute;m est&aacute; trabalhando para remover algumas das limita&ccedil;&otilde;es do desenho atual.</p>
<blockquote> 
 <p>As principais restri&ccedil;&otilde;es do est&aacute;gio atual s&atilde;o relacionadas &agrave; limita&ccedil;&atilde;o de tamanho ao fazer joins com tabelas e cardinalidade de chaves/grupos &uacute;nicos. O sistema tamb&eacute;m n&atilde;o tem a capacidade de gravar dados de sa&iacute;da de volta para as tabelas (atualmente, os resultados das consultas s&atilde;o transferidos para o cliente).</p> 
</blockquote>
<p>O <a href="https://github.com/facebook/presto">Presto</a> est&aacute; dispon&iacute;vel no GitHub sob a licen&ccedil;a Apache 2.</p><br><br><br><br><br><br></body></html>