<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>PhoneGap 3.3: Suporte do BlackBerry aprimorado e API de carregamento de recursos no Android</h3><p>O <a href="https://issues.apache.org/jira/browse/CB-3384">PhoneGap 3.3</a> foi liberado com suporte ao <a href="http://developer.android.com/about/versions/kitkat.html">Android 4.4</a> e API Level 19. Tamb&eacute;m conhecido como KitKat, essa vers&atilde;o do Android foi liberada no final de Outubro, e o foco dela foi a corre&ccedil;&atilde;o de bugs e completar a API de carregamento de recursos do Android.</p>
<p>A <a href="https://issues.apache.org/jira/browse/CB-3384">API de carregamento de recursos do Android</a> teve duas grandes motiva&ccedil;&otilde;es:</p>
<blockquote> 
 <p>1. Muitos plugins n&atilde;o tratavam as URLs corretamente quando estavam no formato de conte&uacute;do: ou file:///android_asset;</p> 
 <p>2. Para o <a href="https://github.com/apache/cordova-app-harness">cordova-app-harness</a> era necess&aacute;rio ter uma forma para redirecionar as requisi&ccedil;&otilde;es de carregamento de recursos, dessa forma o harness poderia carregar os recursos das aplica&ccedil;&otilde;es e ao mesmo tempo respeitar a tag &lt;content&gt;.</p> 
</blockquote>
<p>A documenta&ccedil;&atilde;o ainda est&aacute; sendo escrita, mas a ideia b&aacute;sica &eacute; que para cada plugin ser&aacute; dada uma oportunidade para modificar a requisi&ccedil;&atilde;o de recursos. Se o plugin fizer isso, todos os outros plugins ter&atilde;o a chance de modificar ainda mais a requisi&ccedil;&atilde;o alterada.</p>
<p>Do lado do BlackBerry, as aplica&ccedil;&otilde;es PhoneGap agora podem acessar diretamente o PIN do dispositivo. Assim removendo &quot;a depend&ecirc;ncia do PIN que &eacute; especificado dentro do blackberry10.json.&quot;</p>
<p>Para facilitar o tratamento de eventos, o blackberry.event agora exp&otilde;e o objeto document. Isto &eacute; necess&aacute;rio para chamar as fun&ccedil;&otilde;es [add/remove] do EventListener.</p>
<p>As mensagens de erros dos scripts agora ser&atilde;o postados no std err, tornando mais f&aacute;cil para os usu&aacute;rios visualizarem o porqu&ecirc; do script ter falhado.</p>
<p>Finalmente, <a href="https://issues.apache.org/jira/browse/CB-4804">o depurador do iOS foi alterado</a>. Previamente era utilizado o gdb, mas devido a sua remo&ccedil;&atilde;o do Xcode 5, foi substitu&iacute;do pelo LLDB.</p><br><br><br><br><br><br></body></html>