<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>新しいDesired State Configurationリソースが登場</h3><p><a target="_blank" href="http://www.infoq.com/news/2014/01/powershell-dsc-resources-toolkit"><em>原文(投稿日：2014/01/06)へのリンク</em></a></p>
<div class="article_page_left news_container text_content_container"> 
 <div class="text_info"> 
  <p>PowerShellチームは<a href="http://blogs.msdn.com/b/powershell/archive/2013/12/26/holiday-gift-desired-state-configuration-dsc-resource-kit-wave-1.aspx">新しいDesired Configuration State (DSC)リソース</a>をリリースした。これはコンピュータの構成を実現する構成ブロックだ。リソースキットが公開されたのはPowerShellコミュニティが、より多くのDSCリソースを作成するのを促すために公開された。</p> 
  <p><a href="http://gallery.technet.microsoft.com/site/search?f%5B0%5D.Type=Tag&amp;f%5B0%5D.Value=DSC%20Resource%20Kit%20Wave-1&amp;f%5B0%5D.Text=DSC%20Resource%20Kit%20Wave-1">DSC Resource Kit Wave 1</a>には8つの新しいリソースが含まれており、5つのモジュールにパッケージ化されている。<a href="http://gallery.technet.microsoft.com/xWebAdministration-Module-3c8bb6be">xWebAdministration</a>、 <a href="http://gallery.technet.microsoft.com/xComputerManagement-Module-3ad911cc">xComputerManagement</a>、<a href="http://gallery.technet.microsoft.com/xPSDesiredStateConfiguratio-417dc71d">xPSDesiredStateConfiguration</a>、<a href="http://gallery.technet.microsoft.com/xNetworking-Module-818b3583">xNetworking</a>、<a href="http://gallery.technet.microsoft.com/xHyperV-Module-PowerShell-a646ad1a">xHyperV</a>だ。<a href="http://technet.microsoft.com/en-us/library/dn249921.aspx">組み込みのリソース</a>とともにこのリソースキットを使うとDSCでゼロからウェブサーバを構成できる。</p> 
  <p>xWebAdministrationモジュールにはxWebsiteリソースが含まれている。このリソースを使うとウェブサイトを構成できる。xComputerManagementモジュールには、xComputerリソースが含まれており、コンピュータをリネームしたり、ワークグループやドメインを変更できる。xPSDesiredStateConfigurationモジュールにはxDscWebServiceリソースが含まれており、<a href="http://www.infoq.com/news/2013/12/powershell-dsc-push-and-pull">プルサーバであるDSCサービス</a>を構成できる。xNetworkingモジュールはふたつのリソースを含んでいる。xIPAddressとxDnsServerAddressだ。ノード、つまりコンピュータのIPアドレス、DNSサーバのアドレスを構成する。xHyperVモジュールは仮想マシンを構成できる。つまり、<a href="http://technet.microsoft.com/library/cc816638(WS.10).aspx">Hyper-V</a>の<a href="http://msdn.microsoft.com/en-us/library/windows/desktop/dd323654(v=vs.85).aspx">仮想ハードディスクファイル(VHD)</a>と<a href="http://technet.microsoft.com/en-us/library/hh831823.aspx">仮想スイッチ</a>というWindowsの仮想サーバ環境だ。これらの機能はxVMHyperV、xVhd、xVMSwitchリソースでそれぞれ構成される。</p> 
  <p>このDSC Resource KitにはMicrosoftはサポートプログラムやサービスを提供していない。このことを示すために、モジュールとリソースにはプレフィックスとして&quot;x&quot;がついている。開発チームはフィードバックをもらえれば、フィックスを提供する<em>かもしれない</em>。</p> 
  <p>DSC Resource Kitに含まれるすべてのリソースは、コピー、修正ができる。リソースを修正する場合は、そのリソースやモジュールや関連する物をリネームすることが推奨されている。&quot;MSFT&quot;を置き換えて、自分の組織の名前にし、&quot;x&quot;を削除するのだ。例えば、MSFT_xWebsiteをContoso_Websiteにする。</p> 
  <p>DSC Resource KitはWindows Server 2012だけで検証されている。しかし、PowerShell 4.0がインストールされていればどこでも動くはずだ。</p> 
 </div> 
</div><br><br><br><br><br><br></body></html>