<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>São necessárias alternativas ao REST?</h3><p>Ole Lensmar, o criador do SoapUI, recentemente questionou se REST est&aacute; perdendo a atratividade e se s&atilde;o necess&aacute;rias alternativas. S&atilde;o discutidos diversos pontos em rela&ccedil;&atilde;o a aplica&ccedil;&atilde;o de REST.</p>
<hr />
<p>Ole Lensmar, o criador do SoapUI, recentemente questionou se <a href="http://blog.programmableweb.com/2013/12/19/is-rest-losing-its-flair-rest-api-alternatives-2/">REST est&aacute; perdendo a atratividade e se s&atilde;o necess&aacute;rias alternativas</a>:</p>
<blockquote> 
 <p>Nos &uacute;ltimos anos, a ado&ccedil;&atilde;o de REST como principal m&eacute;todo para constru&ccedil;&atilde;o de APIs ofuscou outras tecnologias e abordagens para constru&ccedil;&otilde;es de APIs. Embora diversas alternativas (principalmente SOAP) ainda sejam (muito) encontradas nas empresas, os precursores do movimento de APIs s&atilde;o definitivamente contra as demais alternativas e adotaram REST como padr&atilde;o e JSON como formato de mensagens.</p> 
</blockquote>
<p>Lensmar tamb&eacute;m aponta as raz&otilde;es que ele acredita que tornaram REST uma abordagem mais bem sucedida do que outras alternativas, como por exemplo SOAP e XML-RPC. Contudo, Ole acredita que exista uma s&eacute;rie de &aacute;reas onde o REST n&atilde;o funcione bem, abrindo espa&ccedil;o para outras abordagem. Entre elas:</p>
<ul class="c10 lst-kix_i7v2s1mktt2k-0 start"> 
 <li>APIs ass&iacute;ncronas: &quot;A necessidade de consultar dados de forma ass&iacute;ncrona em contraponto a abordagem tradicional de request/response nem sempre se encaixa em um design RESTful. Al&eacute;m disto, tecnologias como WebSockets, MQTT, AMQP, Stomp, pubsubhubbub/WebHooks s&atilde;o distintas ao HTTP e muitas vezes n&atilde;o se alinham aos princ&iacute;pios REST.&quot;</li> 
 <li>Orquestra&ccedil;&atilde;o de APIs: &quot;A granularidade oferecida por uma API REST tradicional nem sempre &eacute; uma vantagem; extrair recursos em um dashboard mobile ou em uma aplica&ccedil;&atilde;o web complexa pode exigir muitas requisi&ccedil;&otilde;es a API, fato que adiciona overhead a l&oacute;gica do cliente, aumenta o consumo de largura de banda e processamento do servidor&quot;.</li> 
 <li>SDKs vs APIs: &quot;Grande parte dos consumidores de uma API, fundamentalmente realizam este consumo atrav&eacute;s de uma linguagem de alto n&iacute;vel; javascript, python, ruby, java, etc. Este fato levou muitos provedores de API, como Google e Facebook, a disponibilizarem bibliotecas para estas linguagens. Uma vez que estas linguagens sejam em sua maioria orientadas a RPC, provavelmente as suas APIs expostas atrav&eacute;s de uma SDK tamb&eacute;m sejam fornecidas neste paradigma. Este fato, abre caminho para que a API de backend seja tamb&eacute;m RPC, ou pelo uso de protocolos bin&aacute;rios mais otimizados ou pelo uso do recursos HTTP de forma an&aacute;loga ao modelo RPC (como exemplo JSON-RPC). &quot;</li> 
 <li>Protocolos Bin&aacute;rios: &quot;[...] para transfer&ecirc;ncia de mensagens otimizadas, como exemplo as utilizadas por dispositivos IoT e SDKs, diversos protocolos bin&aacute;rios tem ganho mais aten&ccedil;&atilde;o e uso, como por exemplo Apache Thrift, Google Protocol Buffers e Apache Avro. &Eacute; importante notar que diversas tecnologias ass&iacute;ncronas mencionadas acima utilizam um formato bin&aacute;rio - devido as restri&ccedil;&otilde;es de largura de banda e processamento impostas por seus servi&ccedil;os e ambiente.&quot;</li> 
</ul>
<p>Ole usa como exemplo o Evernote, que utilizou o Thrift como protocolo devido as requisitos de tempo-real (cen&aacute;rio no qual Ole provavelmente acredita estar al&eacute;m da capacidade de REST). Como o autor menciona, referindo-se a um artigo escrito por Daniel Jacobson, <a href="http://blog.programmableweb.com/2013/10/03/is-evernotes-restless-api-approach-a-model-for-other-api-designs/">Evernote's RESTless design</a>:</p>
<blockquote> 
 <p>[...] Uma API REST &eacute; provavelmente uma boa alternativa quando o p&uacute;blico alvo &eacute; um amplo e diverso n&uacute;mero de desenvolvedores. Mas em cen&aacute;rios onde a API &eacute; projetada para usu&aacute;rios, mercados, ind&uacute;strias ou tecnologias restritas, o uso de uma solu&ccedil;&atilde;o mais espec&iacute;fica n&atilde;o se trata somente de uma alternativa, mas sim, pode levar a diversas vantagens competitivas relacionadas a performance, facilidade de uso e seguran&ccedil;a.</p> 
</blockquote>
<p>Ole conclui admitindo que n&atilde;o existe solu&ccedil;&atilde;o ideal para todos problemas, especialmente no design de APIs. &quot;Felizmente para os apaixonados por tecnologia, o que nos motiva &eacute; o aprendizado e a aplica&ccedil;&atilde;o de novas tecnologias para trazer o maior retorno aos stakeholders. Ent&atilde;o, eu n&atilde;o sou contra esta diversidade, ela at&eacute; &eacute; bem vinda&quot;. Contudo, embora alguns leitores concordaram com Ole, muitos outros discordaram desta opini&atilde;o. Como exemplo John Sheehan:</p>
<blockquote> 
 <p>N&atilde;o acredito que o Evernote tenha abandonado o REST. Desde o in&iacute;cio ele nunca foi utilizado e por raz&otilde;es compreens&iacute;veis. Al&eacute;m disto, webhooks podem ser 'REST' (ao menos no conceito popular de REST). As ressalvas listadas na se&ccedil;&atilde;o de APIs Ass&iacute;ncronas n&atilde;o s&atilde;o aplic&aacute;veis na maior parte das implementa&ccedil;&otilde;es.</p> 
</blockquote>
<p>E Darrel Miller tenta diferenciar entre REST e o &quot;pop REST&quot; (termo cunhado pelo autor)</p>
<blockquote> 
 <p>Pelo meu entendimento em rela&ccedil;&atilde;o a camada de orquestra&ccedil;&atilde;o descrita pelo Daniel Jacobson &eacute; an&aacute;loga a maneira que tenho trabalhado durante anos na constru&ccedil;&atilde;o de APIs RESTFUL (guiadas por hipermedia). S&oacute; porque recentemente temos visto muitas APIS &quot;pop REST&quot; n&atilde;o significa que algo tenha mudado em rela&ccedil;&atilde;o as propriedades do REST proposto por Fielding.</p> 
</blockquote>
<p>De fato, grande parte das pessoas que comentaram o texto de Ole, acreditam que o autor n&atilde;o diferenciou muito bem APIs que seguem os princ&iacute;pios RESTFul de implementa&ccedil;&otilde;es que se auto denominam REST mas n&atilde;o seguem os princ&iacute;pios de Fielding. O que voc&ecirc; acha? REST &eacute; realmente aplic&aacute;vel as &aacute;reas que Ole destacou? Se n&atilde;o, que alternativas voc&ecirc; recomenda?</p><br><br><br><br><br><br></body></html>