<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>NetBeans 8: Suporte ao Java 8, HTML5 e muito mais</h3><p>A Oracle <a href="http://www.oracle.com/us/corporate/press/2173412">liberou o NetBeans 8</a> em 25 de Mar&ccedil;o, o mesmo dia que foi <a href="http://eventreg.oracle.com/profile/web/index.cfm?PKWebId=0x637279c68&amp;source=InfoQ">formalmente liberada a vers&atilde;o final do Java 8</a>.</p>
<p>Na semana anterior ao lan&ccedil;amento, Mark Reinhold, arquiteto chefe do Grupo da Plataforma Java, havia <a href="http://mreinhold.org/blog/jdk8-ga">anunciado que o Java 8 tinha alcan&ccedil;ado o status de GA</a> (Generally Available). Foi uma temporada produtiva para a comunidade de desenvolvimento do Java.</p>
<p>O NetBeans 8 cont&ecirc;m uma s&eacute;rie de melhorias do Java 8, incluindo analizador de c&oacute;digo e aprimoramento do editor de perfil (profile), lambdas, stream e m&eacute;todos de refer&ecirc;ncia. Tamb&eacute;m inclui o suporte para publicar, executar e depurar aplica&ccedil;&otilde;es Java SE Embedded em dispositivos embarcados como Raspberry Pi. Tamb&eacute;m &eacute; fornecido suporte para a pr&oacute;xima especifica&ccedil;&atilde;o do Java ME 8.</p>
<p>O NetBeans 8 tamb&eacute;m cont&ecirc;m muitas novas funcionalidades do HTML5. Foi refor&ccedil;ado o a&ccedil;&atilde;o de completar o c&oacute;digo para o AngularJS, Knockout e outros frameworks JavaScript. Tem integra&ccedil;&atilde;o com o Karma e Grunt, bem como a pr&eacute;-visualiza&ccedil;&atilde;o da web e integra&ccedil;&atilde;o com o Chrome Developer Tools. H&aacute; diversos aprimoramentos no suporte ao Java EE, Editor Java, Editor PHP e sistema de versionamento.</p>
<p>A <a href="https://netbeans.org/community/releases/80/">p&aacute;gina com as novidades do NetBeans 8.0</a> tem mais detalhes sobre o que foi inclu&iacute;do nessa vers&atilde;o. Tamb&eacute;m &eacute; mencionado a gera&ccedil;&atilde;o de CRUD com PrimeFaces, gera&ccedil;&atilde;o de c&oacute;digo com Facelets, suporte ao Tomcat 8.0 / TomEE e melhorias no desempenho do Maven. N&atilde;o foi mencionado o <a href="https://blogs.oracle.com/geertjan/entry/python_in_netbeans_ide_8">suporte ao Python</a>. H&aacute; diversos screencasts que ensinam essas e outras funcionalidades do NetBeans 8, como:</p>
<ul> 
 <li><a href="https://netbeans.org/kb/docs/java/jdk8-migration-screencast.html">Migra&ccedil;&atilde;o inteligente para o JDK8</a>;</li> 
 <li><a href="https://netbeans.org/kb/docs/javaee/maven-primefaces-screencast.html">Desenvolvimento com PrimeFaces no NetBeans IDE 8</a>;</li> 
 <li><a href="https://netbeans.org/kb/docs/javame/nb_me8_screencast.html">Suporte ao Java ME 8 no NetBeans IDE</a>.</li> 
</ul>
<p><a href="http://nl.linkedin.com/in/geertjanwielenga">Geertjan Wielenga</a> recentemente escreveu um post em seu blog sobre o suporte ao AngularJS no NetBeans 8, entitulado &quot;<a href="https://blogs.oracle.com/geertjan/entry/integrated_angularjs_development">Desenvolvimento Integrado com AngularJS</a>&quot;. Os coment&aacute;rios no post s&atilde;o bem entusiasmados:</p>
<blockquote> 
 <ul> 
  <li><i>&quot;OK, isso &eacute; insanamente legal!&quot;</i></li> 
  <li><i>&quot;Isso &eacute; maravilhoso, eu finalmente posso usar minha IDE favorita para desenvolvimento web!&quot;</i></li> 
  <li><i>&quot;Isso &eacute; realmente impressionante. Eu posso voltar a usar o NetBeans no futuro - o suporte ao AngularJS &eacute; realmente legal. Incr&iacute;veis funcionalidades. &Oacute;timo trabalho!&quot;</i></li> 
 </ul> 
</blockquote>
<p><a href="http://www.infoq.com/author/Matt-Raible">Matt Raible</a>, autor original dessa not&iacute;cia, perguntou para usu&aacute;rios do NetBeans, <a href="https://twitter.com/mraible/statuses/458471688611450880">se h&aacute; alguma melhoria no NetBeans 8 que voc&ecirc; realmente gosta</a>? As respostas incluem desempenho, suporte ao WildFly, suporte ao AngularJS, desenvolvimento Android, suporte ao SCSS, CRUD com PrimeFaces e aprimoramento do suporte do Maven e Git.</p>
<p>O NetBeans 8 tem uma s&eacute;rie de novas funcionalidades com o objetivo de agradar os desenvolvedores Web Java modernos, bem como os desenvolvedores embarcado e mobile. Se voc&ecirc; n&atilde;o est&aacute; usando o NetBeans, essas caracter&iacute;sticas s&atilde;o o suficiente para voc&ecirc; mudar?</p><br><br><br><br><br><br></body></html>