<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8" /></head><body><h3>MVP = aprendizado inteligente</h3><p>Criar um produto m&iacute;nimo vi&aacute;vel (MVP) n&atilde;o se trata de criar uma vers&atilde;o menor ou mais barata do produto, mas sim de conseguir dar in&iacute;cio ao processo de aprendizado e testes do modelo de neg&oacute;cio. Em um recente <a href="http://steveblank.com/2013/07/22/an-mvp-is-not-a-cheaper-product-its-about-smart-learning/">artigo de</a> <a href="http://steveblank.com/2013/07/22/an-mvp-is-not-a-cheaper-product-its-about-smart-learning/">Steve Blank</a>, &eacute; dado um exemplo de uma pequena startup de Stanford que confundiu o objetivo do MVP com a necessidade de se construir um prot&oacute;tipo caro.</p>
<p>O plano era se tornar um provedor de dados em um mercado emergente, a <a href="http://en.wikipedia.org/wiki/Precision_agriculture%20">agricultura de precis&atilde;o</a>. Fazendas seriam visitadas semanalmente com rob&ocirc;s voadores que coletariam e processariam os dados, os quais depois seriam entregues aos fazendeiros em um formato de f&aacute;cil compreens&atilde;o.</p>
<p>A equipe realizou pesquisas e, com base no feedback obtido, confirmou que os fazendeiros viam, teoricamente, valor nas informa&ccedil;&otilde;es que o projeto poderia oferecer. A equipe ent&atilde;o partiu para o pr&oacute;ximo passo: levantar dinheiro para criar um MVP. Steve Blank explica:</p>
<blockquote> 
 <p>A ideia da equipe era<span> que o MVP precisaria: <br /> 1) Demonstrar um rob&ocirc; capaz de voar; <br /> 2) Garantir que o software poderia processar corretamente todas as imagens do campo; <br /> 3) Apresentar os dados para o fazendeiro de uma forma &uacute;til.</span></p> 
 <p>A equipe concluiu que a maneira de fazer isso seria comprando um rob&ocirc;, uma c&acirc;mera hiperespectral, e um software de processamento de imagens, al&eacute;m de gastar meses da equipe de engenharia integrando a c&acirc;mera, a plataforma e o software. O or&ccedil;amento era extremamente limitado para fazer tudo isso. Era l&oacute;gico - mas errado.</p> 
</blockquote>
<p>A equipe confundiu o objetivo do MVP (a descoberta do cliente), com o processo de construir um prot&oacute;tipo. Blank prop&ocirc;s uma alternativa mais barata para a equipe, que iria cumprir melhor o objetivo do MVP: encontrar usu&aacute;rios iniciais dispostos a pagar pelos dados.</p>
<blockquote> 
 <p>N&atilde;o seria mais barato alugar uma c&acirc;mera e um avi&atilde;o ou helic&oacute;ptero, voar sobre as planta&ccedil;&otilde;es das fazendas, processar manualmente os dados e verificar se os fazendeiros pagariam por esses dados? N&atilde;o seria poss&iacute;vel fazer isso em um dia ou dois, por uma fra&ccedil;&atilde;o do custo planejado?</p> 
</blockquote>
<p>A sugest&atilde;o de Blank fez a equipe rever sua abordagem e a repensar o que o MVP precisaria testar. Foi mudado o foco inicial. Em vez de construir um prot&oacute;tipo do produto, o objetivo seria entender o que era poss&iacute;vel aprender com o MVP. Como se posicionavam como companhia provedora de dados, precisavam de um MVP que provasse que as informa&ccedil;&otilde;es oferecidas tinham valor real antes de gastar tempo e dinheiro:</p>
<blockquote> 
 <p>Isso significava que todo o trabalho de comprar um rob&ocirc; voador, c&acirc;mera, software e o tempo gasto integrando tudo era desperd&iacute;cio naquele momento. N&atilde;o era necess&aacute;rio testar nada daquilo agora. Haviam definido o MVP errado.</p> 
</blockquote>
<p>Ao mostrar um exemplo de equipe fazendo o que a maioria das pessoas pressup&otilde;em ser um MVP, Blank demonstra um equ&iacute;voco que tem se tornado sin&ocirc;nimo desse conceito: a necessidade de construir uma vers&atilde;o barata do produto e entreg&aacute;-la para potenciais consumidores. Por exemplo, <a href="http://www.inc.com/author/jon-burgstone">John Burgstone</a> afirma num <a href="http://www.inc.com/jon-burgstone/flaws-in-the-lean-start-up.html">artigo</a>:</p>
<blockquote> 
 <p>Os princ&iacute;pios do Lean Startup encorajam empreendedores a introduzir seus produtos no mercado rapidamente e aprender com o feedback dos clientes. Aprender com os clientes &eacute; de import&acirc;ncia imensa, mas ir para o mercado com um produto med&iacute;ocre pode ser uma loucura.</p> 
</blockquote>
<p>No entanto, como <a href="http://www.startuplessonslearned.com/2008/10/about-author.html">Eric Ries</a> especificamente aponta nos princ&iacute;pios do Lean Startup, &quot;O primeiro passo &eacute; descobrir o problema que precisa ser resolvido e depois desenvolver um produto m&iacute;nimo vi&aacute;vel para come&ccedil;ar o processo de aprendizado o mais r&aacute;pido poss&iacute;vel&quot;.</p>
<p>&Eacute; um conceito em que muitas equipes erram, j&aacute; que focam em construir rapidamente um produto para receber feedback, o oposto de criar um MVP para come&ccedil;ar a aprender. Nos primeiros est&aacute;gios de aprendizado, pode nem mesmo ser necess&aacute;rio escrever uma &uacute;nica linha de c&oacute;digo, como explica Ries <a href="http://techcrunch.com/2011/10/19/dropbox-minimal-viable-product/">no seu artigo</a> na TechCrunch sobre como o DropBox usou um MVP para aprender:</p>
<blockquote> 
 <p>O desafio era a impossibilidade de se demonstrar o software funcionando na forma de um prot&oacute;tipo. O produto exigia que uma grande dificuldade t&eacute;cnica fosse superada. Tamb&eacute;m possu&iacute;a um componente online que demandava alta disponibilidade e confiabilidade. Para evitar o risco de, ap&oacute;s anos de desenvolvimento, aparecer com um produto que ningu&eacute;m queria, Drew fez uma coisa surpreendentemente simples: um v&iacute;deo.</p> 
</blockquote>
<p>O artigo de Blank conclui seu exemplo com a equipe repensando seu MVP com o objetivo de aprender se havia a possibilidade de se obter um produto vi&aacute;vel rapidamente e sem despender dinheiro desnecessariamente. Blank apresenta as principais li&ccedil;&otilde;es aprendidas com a equipe:</p>
<ul class="c12 lst-kix_r5k5sh14jye-0 start"> 
 <li>O m&iacute;nimo produto vi&aacute;vel nem sempre &eacute; uma vers&atilde;o menor ou mais barata do seu produto final;</li> 
 <li>Considere solu&ccedil;&otilde;es de baixo custo para testar o objetivo;</li> 
 <li>Grandes empreendedores n&atilde;o perdem o foco no resultado final.</li> 
</ul><br><br><br><br><br><br></body></html>